#!/usr/bin/env python3
"""Generate Lean enums from the pinned M1 disposition matrix."""

from __future__ import annotations

import argparse
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
MATRIX = ROOT / "pilot/shared/M1_CONSTRUCTOR_DISPOSITION.tsv"
OUTPUT = ROOT / "pilot/lean/SmusniPilot/Inventory.lean"

GROUPS = {
    "primitive-core": "Primitive",
    "defined-surface": "SurfaceHead",
    "type-index-data": "TypeName",
    "gap-prose-only": "GapHead",
    "tool-only": "ToolHead",
}

SYMBOL_NAMES = {
    "$application": "application",
    "$lexical-predication": "lexicalPredication",
    "$natural": "natural",
    "$variable": "variable",
    "+": "add",
    "−": "subtract",
    "×": "multiply",
    "÷": "divide",
    "<": "lessThan",
    "≤": "lessOrEqual",
    ">": "greaterThan",
    "=": "equal",
    "∈": "memberOf",
    "¬": "not",
    "∧": "and",
    "∨": "or",
    "↔": "iff",
    "⊕": "xor",
    "→": "implies",
    "∀": "forall",
    "∃": "exists",
    "λ": "lambda",
    "⊤": "top",
    "components_κ": "componentsKappa",
    "te'a": "teha",
    "na'i-objection-prose": "nahiObjectionProse",
}


def lower_camel(parts: list[str]) -> str:
    if not parts:
        return "unnamed"
    first = parts[0]
    return first[:1].lower() + first[1:] + "".join(
        part[:1].upper() + part[1:] for part in parts[1:]
    )


def lean_name(qualified: str) -> str:
    namespace, raw = qualified.split(":", 1)
    raw_name = SYMBOL_NAMES.get(raw)
    if raw_name is None:
        ascii_name = (
            raw.replace("κ", "Kappa")
            .replace("'", "")
            .replace("-", " ")
            .replace("_", " ")
        )
        parts = re.findall(r"[A-Za-z0-9]+", ascii_name)
        raw_name = lower_camel(parts)
    if namespace == "term":
        return raw_name
    prefix = {
        "sort": "sort",
        "type-form": "typeForm",
        "type": "type",
        "family": "family",
        "metatheory": "metatheory",
    }.get(namespace, namespace)
    return prefix + raw_name[:1].upper() + raw_name[1:]


def read_groups() -> dict[str, list[tuple[str, str]]]:
    result = {lean: [] for lean in GROUPS.values()}
    for line in MATRIX.read_text(encoding="utf-8").splitlines():
        if not line or line.startswith("#") or line.startswith("head\t"):
            continue
        qualified, disposition, *_ = line.split("\t")
        result[GROUPS[disposition]].append((lean_name(qualified), qualified))
    for kind, rows in result.items():
        names = [name for name, _ in rows]
        duplicates = sorted({name for name in names if names.count(name) > 1})
        if duplicates:
            raise ValueError(f"duplicate Lean names in {kind}: {duplicates}")
    return result


def render_enum(kind: str, rows: list[tuple[str, str]]) -> str:
    constructors = "\n".join(f"  | {name}" for name, _ in rows)
    name_cases = "\n".join(
        f'  | .{name} => "{qualified}"' for name, qualified in rows
    )
    of_name_cases = "\n".join(
        f'  | "{qualified}" => Option.some .{name}' for name, qualified in rows
    )
    return f"""inductive {kind} where
{constructors}
  deriving Repr, DecidableEq, BEq, Inhabited

def {kind}.name : {kind} → String
{name_cases}

def {kind}.ofName : String → Option {kind}
{of_name_cases}
  | _ => Option.none

def {kind}.all : List {kind} := [
{chr(10).join(f'  .{name},' for name, _ in rows)}
]

"""


def render() -> str:
    groups = read_groups()
    body = "".join(render_enum(kind, rows) for kind, rows in groups.items())
    return f"""-- Generated by build_m1_inventory.py from M1_CONSTRUCTOR_DISPOSITION.tsv.
-- Do not edit by hand.

namespace SmusniPilot

{body}inductive HeadDisposition where
  | primitiveCore
  | definedSurface
  | typeIndexData
  | gapProseOnly
  | toolOnly
  deriving Repr, DecidableEq, BEq

def classifyHead (name : String) : Option HeadDisposition :=
  if (Primitive.ofName name).isSome then Option.some .primitiveCore
  else if (SurfaceHead.ofName name).isSome then Option.some .definedSurface
  else if (TypeName.ofName name).isSome then Option.some .typeIndexData
  else if (GapHead.ofName name).isSome then Option.some .gapProseOnly
  else if (ToolHead.ofName name).isSome then Option.some .toolOnly
  else Option.none

end SmusniPilot
"""


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", action="store_true")
    args = parser.parse_args()
    generated = render()
    if args.write:
        OUTPUT.parent.mkdir(parents=True, exist_ok=True)
        OUTPUT.write_text(generated, encoding="utf-8")
        print(f"wrote {OUTPUT.relative_to(ROOT)}")
        return 0
    if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != generated:
        print(f"stale or missing {OUTPUT.relative_to(ROOT)}; run --write")
        return 1
    counts = {kind: len(rows) for kind, rows in read_groups().items()}
    print("Lean inventory: ok " + " ".join(
        f"{kind}={counts[kind]}" for kind in sorted(counts)
    ))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
