; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: samples.md:411 fence 30; kind: specimen; sha1: ccf06145795d50e7dcf840ba1ce7e339b0f8e600
; mi tavla le pendo goi ko'a — aliasing is shared binding
(Bind {$friend :: Referents Entity}
        (Refer (λ {$x :: Referents Entity}
          {(Close (skicu Speaker $x Audience
            (λ {$y :: Referents Entity} {(pendo $y)})))}))
  {(Assert (Close (tavla Speaker $friend)))})
; later ko'a occurrences consume the same binding.  [pin P16]
