; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: samples.md:550 fence 37; kind: specimen; sha1: 24abc60c0d5f18ca606ebc30034871dedede44ba
; ci jbopre cu simxu lo ka tavla — a reciprocal    [spec §12]
(Bind {$trio :: Referents Entity}
        (SelectExactly 3 (λ {$x :: Entity} {(jbopre $x)}))
  {(Assert
    (Reciprocate $trio
      (λ {$a $b :: Referents Entity}
        {(Close (tavla $a $b))})))})
; simxu's lexicon row consumes the library's Reciprocate schema:
; pairwise both ways among the witness.
