; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: samples.md:712 fence 46; kind: specimen; sha1: 299c04f7e6a84ab2b123aa88d1455ed0cf35cfd3
; .i mi klama .i ku'i do stali — a discourse relation
{Let [$a1 :: Act Assertion] (Assert (Close (klama Speaker)))
  {Bind [$o1 :: ActOccurrence Assertion] (Perform Host $a1)
    {Let [$a2 :: Act Assertion] (Assert (Close (stali Audience)))
      {Bind [$o2 :: ActOccurrence Assertion] (Perform Host $a2)
        (Do (Perform AttachedDisplay
          (Express (Close (Contrast $o2 $o1)))))}}}}
