; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: samples.md:346 fence 25; kind: specimen; sha1: 92558dc42df172e09b26b2713a8fae8f1283c68e
; origin: surface
; rules: L7.1 L7.4
; mi'o jmaji — one neutral plural predication; ≡ mi jo'u do jmaji [P40]
(Assert (Close (jmaji (Combine Speaker Audience))))
