; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: samples.md:524 fence 36; kind: specimen; sha1: a538ad51b84398c3174fca7a5cf8faef1c5b62e6
; ci gerku ce'e re prenu cu nelci    [pin P17]
(Bind {$dogs :: Referents Entity}
        (SelectExactly 3 (λ {$x :: Entity} {(gerku $x)}))
        {$people :: Referents Entity}
        (SelectExactly 2 (λ {$x :: Entity} {(prenu $x)}))
  {(Assert
    (Distrib (λ {$d :: Entity}
      {(Distrib (λ {$p :: Entity}
         {(Close (nelci $d $p))}) $people)}) $dogs))})
; co-selected plural witnesses (the selections commute — one joint
; locus, P25's referential discipline); the member-wise Distrib nest
; is the full product
