; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: samples.md:64 fence 3; kind: specimen; sha1: b419005b5f493365ef4b162575898d6ee9ebf238
; klama fe ti tu — labelled fills, x1 left contextual
(Assert (Close (klama :2 This Yonder)))
