; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: samples.md:1369 fence 74; kind: specimen; sha1: 61de1cdcc879bf59408a075914889e684113c681
; origin: surface
; rules: L5.30 L5.1 L5.2
; ro gerku cu tavla su'o mlatu — two quantifiers: surface order is scope
; order; the cats may vary with the dog                         [pin P41]
(Assert
  (IndividualEvery {λ [$x :: Entity] (gerku $x)}
         {λ [$dog :: Entity]
           (IndividualSome {λ [$y :: Entity] (mlatu $y)}
                 {λ [$cat :: Entity] (Close (tavla $dog $cat))})}))
