; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: samples.md:1008 fence 58; kind: specimen; sha1: 2100a19acd0ebd45be30b6df0213d91980a3e3ce
; lo ka se klama — direct function abstraction
(λ {$x :: Referents Entity}
  {(Close (klama :2 $x))})
