; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: samples.md:1348 fence 75; kind: specimen; sha1: e8d065dc136052444d446128d5d3978d68393e60
; origin: surface
; rules: L5.1 L5.2 L4.1
; ro prenu poi ponse su'o gerku ku'o cu blabi — pure resolved restriction
(Assert
  (IndividualEvery
    {λ [$person :: Entity]
      (∧ (prenu $person)
         (IndividualSome {λ [$dog :: Entity] (gerku $dog)}
           {λ [$dog :: Entity] (Close (ponse $person $dog))}))}
    {λ [$person :: Entity] (Close (blabi $person))}))
