; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: samples.md:1009 fence 58; kind: specimen; sha1: b680c5cf6698f14202dd1390bd5081016fd617df
; lo ka se klama — direct function abstraction
{λ [$x :: Referents Entity]
  (Close (klama :2 $x))}
