; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: samples.md:1015 fence 64; kind: specimen; sha1: 8c242085d258c1d6abe8d39bd2dc7e8b128d745e
; origin: surface
; rules: L9.1 L9.8 L1.4
; lo du'u mi klama cu se djuno do
{Bind [$p :: Referents Proposition]
        (Refer {λ [$q :: Referents Proposition]
          (CoRef $q (Reify (Close (klama Speaker))))})
  (Assert (Close (djuno Audience $p)))}
; CoRef (library) is plural co-reference — mutual Among — since typed =
; stays first-order; Reify is pure and lifts to a singleton reference.

; lo se du'u mi klama — the sentence expressing it (CLL 11.7 place 2)
{Let [$p :: Proposition] (Reify (Close (klama Speaker)))
  {Bind [$s :: Referents (Sign Sentence)]
          (Refer {λ [$x :: Referents (Sign Sentence)]
            ((DuhuRel (Close (klama Speaker))) $p :2 $x)})
    (Mention $s)}}
; place 1 is filled with the reified content itself — the relation
; identifies it; so leaving place 1 to contextual closure would add a
; retrieval the Lojban does not contain.

; lo ni mi klama — an abstraction relation; reference outside  [spec §9.2]
{Bind [$a :: Referents Amount]
        (Refer {λ [$x :: Referents Amount]
          (Close ((NiRel (Close (klama Speaker))) $x))})
  (Mention $a)}
; the omitted scale place 2 closed contextually — the same rule as any
; omitted place; le ni …; quantified ni; relative clauses on
; abstractions: all inherited from ordinary reference.

; lo su'u mi klama kei be lo fasnu — explicit categorizer (CLL 11.9)
{Bind [$kind :: Referents Eventuality]
        (Refer {λ [$k :: Referents Eventuality] (fasnu $k)})
  {Bind [$a :: Referents AbstractNature]
          (Refer {λ [$x :: Referents AbstractNature]
            (Close ((SuhuRel (Close (klama Speaker))) $x $kind))})
    (Mention $a)}}

; lo nu mi pu klama — event abstraction: Refer at the event sort
{Bind [$ev :: Referents Eventuality]
      (Refer
        (ActualClause
          {λ [$e :: Referents Eventuality]
            (∧ ((DirectClause (klama Speaker)) $e)
               (purci $e Now))}))
  (Mention $ev)}
; The omitted-place Context sites remain inside the event property with their
; ordinary site identity; Refer sequences them rather than pretending purity.
