; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: samples.md:98 fence 7; kind: specimen; sha1: 57ea22e1867e3c11766c3b8b9f0dd01264cac3f5
; origin: surface
; rules: L1.1 L1.2 L6.2 L6.6
; mi pu citka
(Assert
  (CloseClause
    (ActualClause
      {λ [$e :: Referents Eventuality]
        (∧ ((DirectClause (citka Speaker)) $e)
           (purci $e Now))})))
