; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: samples.md:1057 fence 66; kind: specimen; sha1: 203880927716ccc2198466970bc150b74bcb7c26
; lu mi klama li'u
(Mention (StructuredQuote
  (Utterance {$u :: UtteranceToken}
    {(Realizes $u (Assert (Close (klama Speaker))))})))

; lo'u mi klama le'u — text; uninterpreted
(Mention (OpaqueQuote "mi klama"))

; zo klama cu valsi
(Assert (Close (valsi (WordSign "klama"))))

; la'e lu mi klama li'u — a sign's content
(Mention
  (InterpretContent
    (StructuredQuote
      (Utterance {$u :: UtteranceToken}
        {(Realizes $u (Assert (Close (klama Speaker))))}))))
; defined because the realized act is an assertion: InterpretContent is
; the RAW ActContent projection on assertion-realizing entries (spec §7.5).
; quotation supplies no ActOccurrence and therefore no RealizedContent; but
; the represented token's own intended context still interprets its deictics.

; li re te'a ci du li bi — MEX with te'a (library)
(Assert (= (te'a 2 3) 8))
; contrast: me'o re te'a ci mentions the EXPRESSION sign; not 8:
; (Mention (Sign {$s :: SignToken MathExpression} {(TextOf $s "re te'a ci")}))

; li pa vu'u mo'e lo ni mi klama — the numeric crossing (CLL 11.5)
{Bind [$scale :: Referents Scale] (Context)      ; ONE scale; hoisted:
  {Bind [$amt :: Referents Amount]                 ; it fills NiRel's place 2
          (Refer {λ [$a :: Referents Amount]     ; AND reads the value
            ((NiRel (Close (klama Speaker))) $a $scale)})
    (Mention (− 1 (AmountValue $amt $scale)))}}
; mo'e = AmountValue: the amount's numeric value on the SAME scale that
; defined it (distinct Context sites would allow a mismatch — pin P15).

; lo jei mi klama — epistemology-relative truth-value object (P38)
{Bind [$ep :: Referents Epistemology] (Context)
  {Bind [$tv :: Referents TruthValue]
          (Refer {λ [$v :: Referents TruthValue]
            ((JeiRel (Close (klama Speaker))) $v $ep)})
    (Mention $tv)}}
; The proposed numeric [0;1] crossing is gap-registered; not silently
; available as an alternative reading of this same surface form.

; la .bab. goi by. cu klama .i by. prami — letteral-keyed binding
{Bind [$bob :: Referents Entity]
        (Refer {λ [$x :: Referents Entity] (Named "bab" $x)})
  (Do (Assert (Close (klama $bob)))
      (Assert (Close (prami $bob))))}
; the letteral by. is a binding KEY resolved at the mapping layer;
; both occurrences consume the one binding.
