; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: samples.md:294 fence 21; kind: specimen; sha1: 2876852d13a2e58a91e2a64a38a429d66119040d
; origin: surface
; rules: L3.1 L5.9
; lo mlatu na jbena — the referent scopes outside negation
{Bind [$cat :: Referents Entity]
        (Refer {λ [$x :: Referents Entity] (mlatu $x)})
  (Assert
    (CloseClause (ClauseNot (DirectClause (jbena $cat)))))}
