; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: samples.md:172 fence 13; kind: specimen; sha1: 4fab3b87ce230a3fcfb053b863b9c0ed70d4135c
; origin: surface
; rules: L3.1 L3.11 L12.7 L6.1 L6.2
; ta pu du lo mi zdani — tense on eventless identity [spec §4.6]
(Assert
  (CloseClause
    (ActualClause
      {λ [$s :: Referents Eventuality]
        (∧ ((StateClause
               {Bind [$home :: Referents Entity]
                     (Refer {λ [$x :: Referents Entity]
                       (zdani $x Speaker)})
                 (CoRef That $home)}) $s)
           (purci $s Now))})))
; The home description is inside StateClause; so its property is evaluated in
; $s: That may have been the home then without being it now. Hoisting $home
; outside gives the rigid de re reading. du/CoRef itself retains ordinary arity.
