; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: samples.md:163 fence 12; kind: specimen; sha1: 746a1f80760906d8284c2e0a83291c6a25f0af94
; origin: surface
; rules: L5.1 L5.7 L6.6
; ro datka cu flulimna — CLL 10.19's bare capability reading
(Assert
  (CloseClause
    (StateClause
      (Every {λ [$x :: Entity] (datka $x)}
        {λ [$duck :: Entity]
          (CloseClause
            (CapableClause (DirectClause (flulimna $duck))))}))))
; Every's nuclear scope is member-level (§12: Distrib over the maximal
; reference); each duck's capability clause closes locally; the outer State
; is the universal claim. No one event is shared by every duck.
