; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: samples.md:1381 fence 75; kind: specimen; sha1: 9f96043bd01fe3c20d5c5f8fc8ebf7bbb62c627b
; origin: surface
; rules: L5.1 L5.30 L3.1
; ro gerku cu tavla lo mlatu — declared dog-dependent lo [P41]
(Assert
  (IndividualEvery {λ [$x :: Entity] (gerku $x)}
    {λ [$dog :: Entity]
      {Bind [$cats :: Referents Entity]
            (Refer {λ [$r :: Referents Entity] (mlatu $r)})
        (Close (tavla $dog $cats))}}))
