; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: samples.md:716 fence 47; kind: specimen; sha1: 503d01b346d6bf0ccd691b3621ea1022326831e5
; origin: surface
; rules: L3.1 L9.7
; ci jbopre cu simxu lo ka tavla — a reciprocal    [spec §12]
{Bind [$trio :: Referents Entity]
        (SelectExactly 3 {λ [$x :: Entity] (jbopre $x)})
  (Assert
    (Reciprocate $trio
      {λ [$a $b :: Referents Entity]
        (Close (tavla $a $b))}))}
; simxu's lexicon row consumes the library's Reciprocate schema:
; pairwise both ways among the witness.
