; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: samples.md:722 fence 47; kind: specimen; sha1: 0a7b60e1f1c8cc017092224c0a562c631f96706b
; do klama .i na'i — metalinguistic objection         [spec §7.3]
(Let {$prior :: Act Assertion} (Assert (Close (klama Audience)))
  {(Bind {$prioro :: ActOccurrence Assertion} (Perform Host $prior)
    {(Bind {$defect :: DefectKind} (Context)
      {(Express
        (Close (MetalinguisticallyDefective $prioro $defect)))})})})
; the defect dimension is contextually recovered; nothing is negated,
; and the objection itself performs nothing beyond the display.
