; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: samples.md:74 fence 5; kind: specimen; sha1: bb3f45defaafb03d528961457a04e3c6f27cfd66
; ti se klama mi — conversion consumed by the mapping; no Se operator
(Assert (Close (klama Speaker This)))
