; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: samples.md:102 fence 8; kind: specimen; sha1: f5df1896475bda775ffbdd3508d7d02473b4cfe8
; mi pu pu citka — a tense path: past of a past reference point
(Assert
  (CloseClause
    (ActualClause
      (λ {$e :: Referents Eventuality}
        {(∃ (λ {$m :: Referents Eventuality}
          {(∧ ((DirectClause (citka Speaker)) $e)
             (purci $m Now)
             (purci $e $m))}))}))))
