; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: samples.md:773 fence 49; kind: specimen; sha1: 0cb89ee56a509f9f188dd4a55197dd375af94b03
; za'a do cadzu — evidential grounding the act        [spec §7.6]
{Let [$a :: Act Assertion] (Assert (Close (cadzu Audience)))
  {Bind [$o :: ActOccurrence Assertion] (Perform Host $a)
    (Do (Perform AttachedDisplay
      (Express (Close (EvidentialBasis Speaker $o Observation)))))}}
; act-level display: Perform returns the bound occurrence handle; the family
; force clause grounds THIS occurrence (a mode of commitment);
; a later Perform $a returns a different; ungrounded occurrence;
; na za'a do cadzu negates the walking; never the basis.

; mi jinvi lo du'u ti'e do klama — evidential on embedded content
(Assert
  (Close
    (jinvi Speaker
      (Reify
        {Let [$p :: Proposition] (Reify (Close (klama Audience)))
          (Supplement $p
            (Close (EvidentialBasis Speaker $p Hearsay))
            (Holds $p))}))))
; content-level display: the content occurs ONCE; under a pure Reify
; shared by Let; Holds evaluates that same proposition object; so the
; anchor; the displayed basis; and the evaluated body all carry one set
; of contextual sites. The hearsay rides the embedded claim projectively
; — the reason evidentials are targeted display; not an operand on
; assertion force. (ti'e placed after du'u; targeting the abstraction's
; content; per the CLL attachment rule.)
