; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: samples.md:43 fence 2; kind: specimen; sha1: bca29759cc129330ac981b96275383a25add318f
; mi klama — Close expanded
(Assert
  (Bind {$to :: Referents Entity} (Context)
         {$from :: Referents Entity} (Context)
         {$via :: Referents Entity} (Context)
         {$by :: Referents Entity} (Context)
    {(CloseClause
      (λ {$e :: Referents Eventuality}
        {(∧ (klama Speaker $to $from $via $by :Eventuality $e)
           (fasnu $e))}))}))
