; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: samples.md:482 fence 33; kind: specimen; sha1: b9f173b27ac4961fb1b1b8325c921a535e7a7266
; origin: surface
; rules: L3.12 L3.9 L3.15 L3.2 L12.7
; lei ci prenu du le kamni — fragment after resolving le kamni and κ
{λ [[$κ :: DecompositionBasis (Group Entity) Entity]
    [$committee :: Referents (Group Entity)]]
  {Bind [$people :: Referents Entity]
        (Local (SelectExactly 3 {λ [$x :: Entity]
          (SpeakerDescribes $x
            {λ [$y :: Referents Entity] (prenu $y)})}))
    {Bind [$described :: Referents (Group Entity)]
          (Refer {λ [$g :: Group Entity]
                   (CompleteGunmaAt $κ $g $people)})
      (Assert (CoRef $described $committee))}}}
