; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: samples.md:493 fence 34; kind: specimen; sha1: 3fb669c310769bfcc41ab0e61e89c0ad41147dd3
; origin: surface
; rules: L3.14 L3.2 L3.9 L3.15
; lu'o le ci prenu — canonical aggregate of the selected people
{Bind [$people :: Referents Entity]
      (Local (SelectExactly 3 {λ [$x :: Entity]
        (Close (skicu Speaker $x Audience
          {λ [$y :: Referents Entity] (prenu $y)}))}))
  {Bind [$κ :: DecompositionBasis (Group Entity) Entity]
        (Context (GroupBasisConstraint lu'o Entity) deps…)
    {Bind [$aggregate :: Referents (Group Entity)] (Massify $κ $people)
      (Mention $aggregate)}}}
