; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: samples.md:510 fence 36; kind: specimen; sha1: dcea1ed0a217abde9363445f09a21d766080cca6
; origin: surface
; rules: L3.4
; lo'e mlatu cu cinri            [pin P11]
(Assert
  (Generic Typical
    {λ [$x :: Entity] (mlatu $x)}
    {λ [$x :: Entity] (Close (cinri $x))}))
