; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: samples.md:764 fence 51; kind: specimen; sha1: 0974123a7549881ac866736e6b007c7ec545f6ad
; origin: core
; one reusable package; two performance occurrences
{Let [$a :: Act Assertion] (Assert (Close (klama Speaker)))
  (Do (Perform $a) (Perform $a))}
