; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: samples.md:887 fence 55; kind: specimen; sha1: 1f40b8c8212224b32beb553ad82d9bbc1f05b502
; lo nu ta du lo mi zdani — event abstraction over eventless identity
(Bind {$home :: Referents Entity}
      (Refer (λ {$x :: Referents Entity} {(zdani $x Speaker)}))
  {(Bind {$state :: Referents Eventuality}
        (Refer (StateClause (CoRef That $home)))
    {(Mention $state)})})
; StateClause is already the event property nu needs; no event place is
; added to CoRef/du and EventOfContent selects this same holding state.
