; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: samples.md:79 fence 6; kind: specimen; sha1: fbabbeb68faeb654d6109699223a1496ae2cdac5
; lo ka se klama — a converted relation escaping as a function
(Mention
  (λ {$x :: Referents Entity}
    {(Close (klama :2 $x))}))
