; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: samples.md:382 fence 29; kind: specimen; sha1: 29247d0e41f1bb65c00865d8a8adcf57cf6fbafb
; origin: surface
; rules: L7.1
; mi'a / do'o / ma'a — their complete reference values [P40]
(Do
  (Mention (Combine Speaker MiAOthers))
  (Mention (Combine Audience DoOOthers))
  (Mention (Combine (Combine Speaker Audience) MaAOthers)))
