; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: samples.md:519 fence 34; kind: specimen; sha1: 546483572c8b82d02c31422e9f757152ce89b82b
; ro gerku cu blabi — importing universal   [pin P2]
(Assert
  (Presuppose
    (∃ {λ [$x :: Entity] (gerku $x)})
    (∀ {λ [$x :: Entity] (→ (gerku $x) (Close (blabi $x)))})))
