; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: samples.md:903 fence 55; kind: specimen; sha1: c42363a76bfb78cfee411824ccee42f1b30d9855
; origin: surface
; rules: L11.2
; .ui do klama — pure emotion: host asserted; joy displayed
{Let [$a :: Act Assertion] (Assert (Close (klama Audience)))
  {Bind [$o :: ActOccurrence Assertion] (Perform Host $a)
    (Do (Perform AttachedDisplay
      (Express (Close (Happiness Speaker $o Moderate)))))}}

; .au mi sipna — propositional attitude: host subordinated  [spec §7.6]
(Express (Close (Desire Speaker (Reify (Close (sipna Speaker))) Moderate)))
; no assertion of sleeping occurs — the host-force profile of .au.

; .uinai cai do klama — paired emotion; then degree   [spec §7.6]
{Let [$a :: Act Assertion] (Assert (Close (klama Audience)))
  {Bind [$o :: ActOccurrence Assertion] (Perform Host $a)
    (Do (Perform AttachedDisplay
      (Express (Close (Unhappiness Speaker $o Intense)))))}}
