; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: samples.md:812 fence 51; kind: specimen; sha1: 4a9b373fab796c473bb9e876485273e89bb061d3
; do klama .i na'i — metalinguistic objection         [spec §7.3]
{Let [$prior :: Act Assertion] (Assert (Close (klama Audience)))
  {Bind [$prioro :: ActOccurrence Assertion] (Perform Host $prior)
    {Bind [$defect :: DefectKind] (Context)
      (Express
        (Close (MetalinguisticallyDefective $prioro $defect)))}}}
; the defect dimension is contextually recovered; nothing is negated;
; and the objection itself performs nothing beyond the display.
