; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: samples.md:69 fence 3; kind: specimen; sha1: 3db37afbd27c832ee661ef1fad0b621eb031fed6
; origin: surface
; rules: L1.4 L1.6
; klama fe ti tu — labelled fills; place 1 left contextual
(Assert (Close (klama :2 This Yonder)))
