; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: samples.md:712 fence 46; kind: specimen; sha1: a504a67888f7c8505cd700df43dc346e3f2d82da
; .i mi klama .i ku'i do stali — a discourse relation
(Let {$a1 :: Act Assertion} (Assert (Close (klama Speaker)))
  {(Bind {$o1 :: ActOccurrence Assertion} (Perform Host $a1)
    {(Let {$a2 :: Act Assertion} (Assert (Close (stali Audience)))
      {(Bind {$o2 :: ActOccurrence Assertion} (Perform Host $a2)
        {(Do (Perform AttachedDisplay
          (Express (Close (Contrast $o2 $o1)))))})})})})
