; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: samples.md:434 fence 32; kind: schema; sha1: be009658e693cb9135c1a2af639e731f0bda6b86
; classification-note: joi lowering schema with an explicit dependency-profile metavariable
; mi joi do bevri lo pipno — one constituted group carries
{Bind [$κ :: GroupBasis Entity]
      (Context (GroupBasisConstraint joi Entity) deps…)
  {Bind [$g :: Referents (Group Entity)]
         (JoiGroup $κ Speaker Audience)
    {Bind [$p :: Referents Entity]
           (Refer {λ [$r :: Referents Entity] (pipno $r)})
      (Close (bevri $g $p))}}}
