; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: samples.md:417 fence 29; kind: specimen; sha1: bf1bff37b3eff8fbcd7f2aea46b3fa08def64d3a
; lo gerku noi blabi cu na melbi     [pin P7]
{Bind [$dog :: Referents Entity]
        (Refer {λ [$x :: Referents Entity] (gerku $x)})
  (Assert
    (Supplement $dog (Close (blabi $dog))
      (CloseClause (ClauseNot (DirectClause (melbi $dog))))))}
