; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: samples.md:562 fence 38; kind: specimen; sha1: 51e9744262ab201426d4473f58b2bdc498338e6d
; so'i prenu cu klama — vague quantity    [spec §6.4]
(Bind {$n :: Natural}
        (Vague (AdmissibleThreshold ManyK (λ {$x :: Entity} {(prenu $x)})))
  {(Assert
    (AtLeast $n (λ {$x :: Entity} {(prenu $x)})
                (λ {$w :: Referents Entity} {(Close (klama $w))})))})
