; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: samples.md:735 fence 48; kind: specimen; sha1: 7f889434ac9d00fa880823dc44ccd499a2988cd5
; sutra klama — one intended link recovered at this occurrence [spec §6.2]
(Assert
  (Close ((Tanru sutra klama) Speaker)))
; ≗ (Bind {$link :: PredTerm ρ(klama)}
;         (Context (λ {$r :: PredTerm ρ(klama)}
;                    {(TanruAdmissible sutra klama $r)}))
;     {… (∧ (klama …) ($link …))})
; no governor dependencies in this reading. `na sutra klama` retrieves
; one intended admissible link at that occurrence's site and negates that claim;
; it does not quantify over every possible tanru link.
