; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: samples.md:141 fence 11; kind: specimen; sha1: e3785369d0dec808c5bf5acff3899d2304bfcff4
; rules: L6.4
; mi citka — the episodic reading: at the contextually relevant occasion
(Assert
  {Bind [$occ :: Time] (Context)
    (CloseClause
      {λ [$e :: Referents Eventuality]
        (∧ ((ActualClause (DirectClause (citka Speaker))) $e)
           (cabna $e $occ))})})
