; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: samples.md:684 fence 45; kind: specimen; sha1: 1a575b6f5bb94517627d63ad1a30f80d0a825446
; origin: surface
; rules: L10.2 L3.10
; lo xo prenu cu jmaji — ... no — inner-no answer      [pin P22]
; the answer "no" is elliptical lo no prenu cu jmaji (guskant);
; which lowers through the zero-count special case; never Refer:
(Assert
  (No {λ [$x :: Entity] (prenu $x)}
      {λ [$w :: Referents Entity] (Close (jmaji $w))}))
; the nuclear scope is reference-typed (spec §12): "no people-witness
; gathers" — the collective reading a distributive quantifier could not
; state at all.
; answer substitution into the question's frame works; anaphora to
; the form is inaccessible (No exports nothing — nothing to refer to).
