; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: samples.md:385 fence 28; kind: specimen; sha1: a825016831dbd975987f71881672c4bca9272d60
; origin: surface
; rules: L7.1 L1.6
; mi'o klama — one place-1 value and one omitted place-2 Context site [P40]
{Bind [$to :: Referents Entity] (Context)
  (Assert
    (Close (klama (Combine Speaker Audience) :2 $to)))}
