; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: samples.md:241 fence 18; kind: schema; sha1: c3482340961a9a7fe10aa18250bac3e9702385be
; classification-note: open JoiClause fragment parameterized by kappa
; κ :: DecompositionBasis<Eventuality,Eventuality>, recovered for this joi
(JoiClause $κ
  (DirectClause (sanga Speaker))
  (DirectClause (dansu Audience)))
