; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: samples.md:812 fence 49; kind: specimen; sha1: 98b4460c090487fddece7d5a0c388054af682e01
; classification-note: P43 and samples §5 explicitly mark this as a plural/library comparison or excluded historical extension; retained as a checked core term, not a surface lowering (#20).
; durable-issue: #20
; origin: core
; Reference-level vague-quantity comparison.              [spec §6.4]
; Standard so'i prenu cu klama needs the L5.28 count adaptation.
{Bind [$n :: Natural]
        (Vague (AdmissibleThreshold ManyK {λ [$x :: Entity] (prenu $x)}))
  (Assert
    (AtLeast $n {λ [$x :: Entity] (prenu $x)}
                {λ [$w :: Referents Entity] (Close (klama $w))}))}
