; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: samples.md:354 fence 26; kind: specimen; sha1: e4d262c467cd0932d234acf4642bc0120cbe4b77
; lo'e mlatu cu cinri            [pin P11]
(Assert
  (Generic Typical
    (λ {$x :: Entity} {(mlatu $x)})
    (λ {$x :: Entity} {(Close (cinri $x))})))
