; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: samples.md:318 fence 24; kind: schema; sha1: 5e039ba77ddd394a407bab625ac3a23b4a39a59f
; classification-note: descriptor lowering schema with an explicit dependency-profile metavariable
; loi gerku — κ is the occurrence's resolved group basis
{Bind [$base :: Referents Entity]
      (Local (Refer {λ [$x :: Entity] (gerku $x)}))
  {Bind [$κ :: GroupBasis Entity]
         (Context (GroupBasisConstraint loi Entity) deps…)
    {Bind [$groups :: Referents (Group Entity)]
           (Refer {λ [$g :: Group Entity]
             (CompleteGunmaAt $κ $g $base)})
      (Mention $groups)}}}
