; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: samples.md:594 fence 40; kind: specimen; sha1: 7512a558db7681c8217b38bf7aa9c3d5ef3fd257
; mi cusku lu mi klama li'u — reported, not performed
(Assert
  (Close
    (cusku Speaker
      (StructuredQuote
        (Utterance {$u :: UtteranceToken}
          {(∧ (SpeakerOf $u Speaker)
          (Realizes $u (Assert (Close (klama Speaker)))))})))))
