; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: samples.md:426 fence 31; kind: specimen; sha1: 3888293d5a741a45d3def0a58d88c3dadb859c30
; ci gerku cu bajra .i ri tatpi      [spec §5.6]
(Bind {$dogs :: Referents Entity}
        (SelectExactly 3 (λ {$x :: Entity} {(gerku $x)}))
  {(Do
    (Assert (Close (bajra $dogs)))
    (Assert (Close (tatpi $dogs))))})
; the selection introduces and BINDS the witness; the anaphor is an
; ordinary bound occurrence — no free names, no retrieval operator.
; the nuclear predication is NEUTRAL (P4): each-ran comes from bajra's
; lexicon row, not from the quantifier — contrast ci prenu cu jmaji,
; where the three gather TOGETHER, same shape.
