; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: samples.md:84 fence 6; kind: specimen; sha1: 167ba93649e02fe22885e038fa31606397fb364e
; origin: surface
; rules: L1.4 L9.7
; lo ka se klama — a converted relation escaping as a function
(Mention
  {λ [$x :: Referents Entity]
    (Close (klama :2 $x))})
