; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: samples.md:131 fence 10; kind: specimen; sha1: 1a5245b069fb678e5065b8bd54bee5192432c613
; rules: L6.6
; mi ca'a citka — actuality as a facet
(Assert
  (CloseClause
    (ActualClause (DirectClause (citka Speaker)))))
