; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: samples.md:206 fence 15; kind: specimen; sha1: 0d9bdfb9acc1311c014ab563a98f96ab4f8769cb
; origin: surface
; rules: L12.6 L12.7 L12.8 L6.6
; li re su'i re ca'a du li vo — CAhA on mathematical identity
(Assert
  (CloseClause
    (ActualClause
      (StateClause (= (+ 2 2) 4)))))
