; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: samples.md:505 fence 35; kind: specimen; sha1: 096965489fcedaa8d5f2785b3fb7bd0ab3f05100
; origin: surface
; rules: L3.14 L8.1
; lu'a ri — fragment: components of the previously selected single group
{λ [[$κ :: DecompositionBasis (Group Entity) Entity]
    [$group :: Group Entity]]
  (Mention (components_κ $κ $group))}
; components_κ takes one Group<T> object (§12); ri's projective singular
; condition is what supplies that sole group and is elided here.
