; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: samples.md:720 fence 46; kind: specimen; sha1: 3629d28112535eed341d6cdf5d9b616315a60849
; la'e do'i — proposition reading of a salient performed assertion
{Bind [$u :: Referents UtteranceToken] (Context)
  (Mention (Reify (RealizedContent $u)))}
