; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: samples.md:304 fence 23; kind: specimen; sha1: f2ce0c4bc6d4e6eb980000770a6ce46328c172df
; lo'i gerku — a set object via selcmi (xorxes' lujvo: x2 = members) [P5]
(Bind {$base :: Referents Entity}
        (Local (Refer (λ {$x :: Entity} {(gerku $x)}))) ; ordinary base,
                                                        ; but not a surface DR
  {(Bind {$sets :: Referents (Set Entity)}
          (Refer (λ {$s :: Set Entity}
            {(Close (selcmi $s $base))}))
    {(Mention $sets)})})
