; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: samples.md:371 fence 28; kind: specimen; sha1: 05606f4ef1c0a477054a350053c5a49eef190406
; mi'o klama — one place-1 value and one omitted place-2 Context site [P40]
{Bind [$to :: Referents Entity] (Context)
  (Assert
    (Close (klama (Combine Speaker Audience)
                  :2 $to :3 This :4 That :5 Yonder)))}
