; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: samples.md:914 fence 58; kind: specimen; sha1: 29a4047bce86b1331b60c73b6c86d3a1692b7f97
; origin: surface
; rules: L1.10
; mi sutra klama — one intended link recovered at this occurrence [spec §6.2]
(Assert
  (Close ((Tanru sutra klama) Speaker)))
; ≗ {Bind [$link :: PredTerm (RowOf klama)]
;         (Context {λ [$r :: PredTerm (RowOf klama)]
;                    (TanruAdmissible sutra klama $r)})
;     … (∧ (klama …) ($link …))}
; no governor dependencies in this reading. `na sutra klama` retrieves
; one intended admissible link at that occurrence's site and negates that claim;
; it does not quantify over every possible tanru link.
