; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: samples.md:372 fence 27; kind: specimen; sha1: 196e687aeb31437c27ec947e3a2c78c70c793d35
; lo mlatu poi blabi cu jbena — restrictive: inside the property
(Bind {$cat :: Referents Entity}
        (Refer (λ {$x :: Referents Entity}
          {(∧ (mlatu $x) (blabi $x))}))
  {(Assert (Close (jbena $cat)))})
