; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: samples.md:576 fence 39; kind: specimen; sha1: 0f27825bb7a77f05bab90ee9aad54691301c2830
; xu mi klama
(Ask (Polar (Close (klama Speaker))))

; ma klama
(Ask (OpenQ (λ {$x :: Referents Entity} {(Close (klama $x))})))

; ti mo — an open relation question
(Ask (OpenQ (λ {$r :: PredTerm ⟨x1:(Referents Entity)⟩}
  {(Close ($r This))})))

; klama fi'a ti — a place question           [spec §4.7]
(Ask (OpenQ (λ {$p :: CompatibleLabel klama (Referents Entity)}
  {(Close (At klama $p This))})))
; the computed-label domain is the compatible refinement (§4.7): the
; event place and any sort-incompatible place contribute no branch
