; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: samples.md:270 fence 20; kind: specimen; sha1: 497b9d18e12a253ce48800954ecf4499f46063b1
; lo mlatu na jbena — the referent scopes outside negation
(Bind {$cat :: Referents Entity}
        (Refer (λ {$x :: Referents Entity} {(mlatu $x)}))
  {(Assert
    (CloseClause (ClauseNot (DirectClause (jbena $cat)))))})
