; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: samples.md:1014 fence 59; kind: specimen; sha1: b0f1aa5a0a0b355c6c9e67397ee6399a5be8f6c6
; lo mlatu cu blabi .i ri jbena — effectful binding across a discourse
(Bind {$cat :: Referents Entity}
      (Refer (λ {$x :: Referents Entity} {(mlatu $x)}))
  {(Do (Assert (Close (blabi $cat)))
       (Assert (Close (jbena $cat))))})
