; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: samples.md:1192 fence 69; kind: specimen; sha1: 589adfc4e176dc6ab1035fd0a48e93ba2dbe6ef1
; origin: surface
; rules: L3.1 L11.7 L8.1
; lo mlatu cu blabi .i ri jbena — effectful binding across a discourse
{Bind [$cat :: Referents Entity]
      (Refer {λ [$x :: Referents Entity] (mlatu $x)})
  (Do (Assert (Close (blabi $cat)))
       (Assert (Close (jbena $cat))))}
