; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: samples.md:215 fence 16; kind: specimen; sha1: 33ea8bb4cdb9bbc90f7e759cd40eb0385ce8bef0
; origin: surface
; rules: L5.9 L5.8
; mi na klama — the negative State is the clause eventuality
(Assert
  (CloseClause
    (ActualClause
      (ClauseNot (DirectClause (klama Speaker))))))
