; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: samples.md:630 fence 42; kind: specimen; sha1: e26ccac68719e5502d1785ed81029b8f7ae4cd11
; la'e do'i — proposition reading of a salient performed assertion
(Bind {$u :: Referents UtteranceToken} (Context)
  {(Mention (Reify (RealizedContent $u)))})
