; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: samples.md:508 fence 34; kind: specimen; sha1: dc75fd1862f35daa19094d81680d127900274a05
; origin: surface
; rules: L3.14 L3.2 L3.9 L3.15
; lu'o le ci prenu — canonical aggregate of the selected people
{Let [$P :: EFn ((Referents Entity)) Content]
      {λ [$y :: Referents Entity] (prenu $y)}
  {Bind [$people :: Referents Entity]
        (Local (Refer {λ [$r :: Referents Entity]
          (∧ (SpeakerDescribes $r $P)
             (= (CardBasis $r {λ [$x :: Entity]
                   (SpeakerDescribes $x $P)}) 3))}))
    {Bind [$κ :: DecompositionBasis (Group Entity) Entity]
          (Context (GroupBasisConstraint lu'o Entity) deps…)
      {Bind [$aggregate :: Referents (Group Entity)] (Massify $κ $people)
        (Mention $aggregate)}}}}
; Sharing the property does not evaluate it.
