; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: samples.md:31 fence 1; kind: specimen; sha1: 82d318130152003287c099c7eefd701ce6868242
; mi klama
(Assert
  (Close (klama Speaker)))
; ≝ (Assert (CloseClause (ActualClause (DirectClause (klama Speaker)))))
; this specimen selects the actual missing-CAhA reading; Close names that
; core composition, not a default imposed on the surface.
