; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: samples.md:536 fence 37; kind: specimen; sha1: ccf68ce3fb78ffc5ac02f46b6273afaf35e01275
; origin: surface
; rules: L4.1
; lo mlatu poi blabi cu jbena — restrictive: inside the property
{Bind [$cat :: Referents Entity]
        (Refer {λ [$x :: Referents Entity]
          (∧ (mlatu $x) (blabi $x))})
  (Assert (Close (jbena $cat)))}
