; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: samples.md:648 fence 43; kind: specimen; sha1: 629721dd4329b3f20347e2ca349839363ca774fb
; mi djuno lo du'u ma kau klama      [pin P9]
(Assert
  (Close
    (djuno Speaker
      (Reify
        (Answer
          (OpenQ (λ {$x :: Referents Entity} {(Close (klama $x))}))
          ContextualAnswer)))))
