; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: samples.md:759 fence 50; kind: specimen; sha1: 84ab2c11e55a9d4f82413c6275f80daa2f41fedb
; mi djica tu'a lo cukta                      [pin P14]
(Bind {$book :: Referents Entity}
        (Refer (λ {$x :: Referents Entity} {(cukta $x)}))
  {(Bind {$a :: Referents Eventuality}          ; sort from djica's x2
          (Context (λ {$v :: Referents Eventuality}
            {(∧ (∃ (λ {$p :: Proposition}
                 {(CoRef $v (EventOfContent (Holds $p)))})) ; clause-event shape
               (Close (srana $v $book)))})
            $book)                               ; depends on this book
    {(Assert (Close (djica Speaker $a)))})})
