; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: samples.md:228 fence 17; kind: specimen; sha1: 14a885a17c62156d54c7ed3a78b6b3908ef59371
; origin: surface
; rules: L5.12 L5.8
; mi klama .ije do stali — joint State; one assertion
(Assert
  (CloseClause
    (ActualClause
      (ClauseAnd (DirectClause (klama Speaker))
                 (DirectClause (stali Audience))))))

; mi klama .ija do stali — branch-relative event; one assertion
(Assert
  (CloseClause
    (ActualClause
      (ClauseOr (DirectClause (klama Speaker))
                (DirectClause (stali Audience))))))
