; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: samples.md:666 fence 43; kind: specimen; sha1: 94d7c78c9ffa610e620b869e490dcead7e2f1e12
; xu mi klama
(Ask (Polar (Close (klama Speaker))))

; ma klama
(Ask (OpenQ {λ [$x :: Referents Entity] (Close (klama $x))}))

; ti mo — an open relation question
(Ask (OpenQ {λ [$r :: PredTerm (Row (1 (Referents Entity)))]
  (Close ($r This))}))

; klama fi'a ti — a place question           [spec §4.7]
(Ask (OpenQ {λ [$p :: CompatibleLabel (RowOf klama) (Referents Entity)]
  (Close (At klama $p This))}))
; the computed-label domain is the compatible refinement (§4.7): the
; event place and any sort-incompatible place contribute no branch
