; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: samples.md:354 fence 26; kind: specimen; sha1: d4aa723c38d70a1b4f5f272b4f3c680ecf95ce33
; origin: surface
; rules: L7.4 L5.8
; mi .e do jmaji — speaker gathers AND audience gathers [P40]
(Assert
  (CloseClause
    (ClauseAnd (DirectClause (jmaji Speaker))
               (DirectClause (jmaji Audience)))))
