; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: samples.md:114 fence 9; kind: specimen; sha1: 4021f0618fabf586468f89e6dd79a129bb675bb6
; mi klama ti sepi'o ti — an instrumental facet, same event
(Assert
  (CloseClause
    (ActualClause
      (λ {$e :: Referents Eventuality}
        {(∧ ((DirectClause (klama Speaker This)) $e)
           (Close (pilno :2 This :3 $e)))}))))
; the host event fills pilno x3 (purpose) — the tag row's licensed link
; per the official row: x1 uses x2 for purpose x3.
