; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: samples.md:510 fence 35; kind: specimen; sha1: ca720fac04381fe51bd067b1fdb1aafa76b5a0ae
; lo xo prenu cu jmaji — ... no — inner-no answer      [pin P22]
; the answer "no" is elliptical lo no prenu cu jmaji (guskant),
; which lowers through the zero-count special case, never Refer:
(Assert
  (No (λ {$x :: Entity} {(prenu $x)})
      (λ {$w :: Referents Entity} {(Close (jmaji $w))})))
; the nuclear scope is reference-typed (spec §12): "no people-witness
; gathers" — the collective reading a distributive quantifier could not
; state at all.
; answer substitution into the question's frame works; anaphora to
; the form is inaccessible (No exports nothing — nothing to refer to).
