; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: samples.md:405 fence 27; kind: specimen; sha1: 0053b0ad0158260b7a1f5c1863a3a60b7d695ead
; lei ci prenu du le kamni — fragment after resolving le kamni and κ
{λ [[$κ :: DecompositionBasis (Group Entity) Entity]
    [$committee :: Referents (Group Entity)]]
  {Bind [$people :: Referents Entity]
        (Local (SelectExactly 3 {λ [$x :: Entity]
          (Close (skicu Speaker $x Audience
            {λ [$y :: Referents Entity] (prenu $y)}))}))
    {Bind [$described :: Referents (Group Entity)]
          (Refer {λ [$g :: Group Entity]
                   (CompleteGunmaAt $κ $g $people)})
      (Assert (CoRef $described $committee))}}}
