; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: samples.md:301 fence 22; kind: specimen; sha1: 68fd3b480a697f1f7f5d93e6ad02cbfd92541bab
; origin: surface
; rules: L3.2
; le mlatu cu blabi              [pin P10]
{Bind [$it :: Referents Entity]
        (Refer {λ [$x :: Referents Entity]
          (Close (skicu Speaker $x Audience
            {λ [$y :: Referents Entity] (mlatu $y)}))})
  (Assert (Close (blabi $it)))}
