; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: samples.md:321 fence 23; kind: specimen; sha1: 51894d5541b6381e478bca7b33a039b6f96feab4
; origin: surface
; rules: L3.3
; la .alis. klama
{Bind [$alis :: Referents Entity]
        (Refer {λ [$x :: Referents Entity] (Named "alis" $x)})
  (Assert (Close (klama $alis)))}
