; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: samples.md:794 fence 52; kind: specimen; sha1: 18fc2d84c0815db802a7c4408fc3cb6c23716df0
; mi jai rinka lo nu do morsi — a typed bare-jai role site [spec §12]
{Bind [$death :: Referents Eventuality]
      (Refer {λ [$e :: Referents Eventuality]
        (Close (morsi :1 Audience :Eventuality $e))})
  {Bind [$role :: Fn ((Referents Entity) (Referents Eventuality)) Content]
        (Context
          {λ [$k :: Fn ((Referents Entity) (Referents Eventuality)) Content]
            (JaiRoleAdmissible rinka $k)})
    (Assert
      (Close ((JaiRaise rinka $role) :1 Speaker :2 $death)))}}
; T = Entity and A = Eventuality in this reading. The unfilled fai place
; retrieves the hidden cause event; the intended role relates Speaker to it.
