; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: samples.md:158 fence 12; kind: specimen; sha1: 862742d0f6b9951dea2544082774bb62e0998fe5
; ro datka cu flulimna — CLL 10.19's bare capability reading
(Assert
  (CloseClause
    (StateClause
      (Every (λ {$x :: Entity} {(datka $x)})
        (λ {$ducks :: Referents Entity}
          {(CloseClause
            (CapableClause (DirectClause (flulimna $ducks))))})))))
; Each nuclear capability clause closes locally; the outer State is the
; universal claim. No one event is shared by every duck.
