; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: samples.md:416 fence 31; kind: schema; sha1: a6b81beecc7005ac4cdc5349fd2bb0d9f812e9f1
; classification-note: descriptor lowering schema with an explicit dependency-profile metavariable
; loi gerku — κ is the occurrence's resolved group basis
{Bind [$base :: Referents Entity]
      (Local (Refer {λ [$x :: Entity] (gerku $x)}))
  {Bind [$κ :: GroupBasis Entity]
         (Context (GroupBasisConstraint loi Entity) deps…)
    {Bind [$groups :: Referents (Group Entity)]
           (Refer {λ [$g :: Group Entity]
             (CompleteGunmaAt $κ $g $base)})
      (Mention $groups)}}}
; the outer restrictor is member-level: by the §5.3 lift the reference is
; CoveredBy that property — each qualifying group qualifies individually
