; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: samples.md:329 fence 24; kind: specimen; sha1: 987b16e0e1ac2ffb237d3bb38239d2bdd43375ce
; mi'o remna — one member-level-compatible predication [P40]
(Assert (Close (remna (Combine Speaker Audience))))
