; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: samples.md:567 fence 40; kind: specimen; sha1: dac8ad12b46365a0c1d8f1960c64873de7205e78
; mi tavla le pendo goi ko'a — aliasing is shared binding
{Bind [$friend :: Referents Entity]
        (Refer {λ [$x :: Referents Entity]
          (Close (skicu Speaker $x Audience
            {λ [$y :: Referents Entity] (pendo $y)}))})
  (Assert (Close (tavla Speaker $friend)))}
; later ko'a occurrences consume the same binding.  [pin P16]
