; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: samples.md:158 fence 12; kind: specimen; sha1: 06d0d9d33529bc747322d3cdb405412e003be3ff
; ro datka cu flulimna — CLL 10.19's bare capability reading
(Assert
  (CloseClause
    (StateClause
      (Every {λ [$x :: Entity] (datka $x)}
        {λ [$ducks :: Referents Entity]
          (CloseClause
            (CapableClause (DirectClause (flulimna $ducks))))}))))
; Each nuclear capability clause closes locally; the outer State is the
; universal claim. No one event is shared by every duck.
