; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: samples.md:222 fence 17; kind: specimen; sha1: 23dffcd28bf78120428768ab5f66684f86ee46a9
; mi klama .ije do stali — joint State, one assertion
(Assert
  (CloseClause
    (ActualClause
      (ClauseAnd (DirectClause (klama Speaker))
                 (DirectClause (stali Audience))))))

; mi klama .ija do stali — branch-relative event, one assertion
(Assert
  (CloseClause
    (ActualClause
      (ClauseOr (DirectClause (klama Speaker))
                (DirectClause (stali Audience))))))
