; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: samples.md:339 fence 25; kind: schema; sha1: c77b076f41186db35732751e6fb7ecaae3c7471a
; classification-note: joi lowering schema with an explicit dependency-profile metavariable
; mi joi do bevri lo pipno — one constituted group carries
(Bind {$κ :: GroupBasis Entity}
      (Context GroupBasisConstraint[joi,Entity] deps…)
  {(Bind {$g :: Referents (Group Entity)}
         (JoiGroup $κ Speaker Audience)
    {(Bind {$p :: Referents Entity}
           (Refer (λ {$r :: Referents Entity} {(pipno $r)}))
      {(Close (bevri $g $p))})})})
