; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: samples.md:277 fence 20; kind: specimen; sha1: 902509e684aa12ecea4380471df65cef9293a457
; origin: core
; atomless bread reference — CoveredBy succeeds without atomic members [P39]
{λ [[$bread :: Referents Entity]
    [$breadUnit :: Fn (Entity) Content]]
  (∧ (CoveredBy $breadUnit $bread)
     (∀ {λ [$r :: Referents Entity]
       (→ (Among $r $bread)
          (∃ {λ [$s :: Referents Entity]
            (∧ (Among $s $r) (¬ (Among $r $s)))}))}))}
