; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: samples.md:923 fence 59; kind: specimen; sha1: d18b550e979e80e4ef5a9c15530e135e9dc7f869
; origin: surface
; rules: L5.11
; ta na'e melbi — scalar otherness            [spec §6.3]
{Bind [$d :: ContrastDomain (RowOf melbi)] (Context)
  (Assert (Close ((Scalar OtherThan $d melbi) That)))}
; contrast domain: visible Context site; any soritical boundary: Vague.
; DENIES beauty AND directly asserts membership in the complement of
; beauty's region in the recovered domain (CLL 15.4: selbri negation
; "remains an assertion of some specific truth"). No finer alternative is
; selected; to'e uses the domain's antipode; no'e its between-region.
