; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: samples.md:709 fence 44; kind: specimen; sha1: ce7d66da0f0de2e3dc692c23cc3d3b836c9789ba
; origin: surface
; rules: L5.1
; ro gerku cu blabi — non-importing individual universal [pin P2]
(Assert
  (IndividualEvery {λ [$x :: Entity] (gerku $x)}
         {λ [$x :: Entity] (Close (blabi $x))}))
; ≝ ∀ x:Entity. gerku(x) → Close(blabi(x)); no implicit dog reference,
; MaxRefer, existence presupposition or outward universal group.
