; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: samples.md:957 fence 61; kind: schema; sha1: a578eede93730cad7e283ea7f584fce5efd24d2a
; classification-note: side-by-side positive/negative intended-value schema
; positive                                  ; negative
{Bind [$v :: T] (Context P deps…)           {Bind [$v :: T] (Context P deps…)
  (C $v)}                                     (¬ (C $v))}
