; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: samples.md:735 fence 45; kind: specimen; sha1: 731ea98abcb88f842b7f760815976812fc9d6142
; origin: surface
; rules: L5.2
; me'i gerku cu blabi — bare me'i = not-all              [pin P44]
; A resolved pure individual nucleus, as in the preceding ro example.
(Assert
  (¬ (IndividualEvery {λ [$x :: Entity] (gerku $x)}
                      {λ [$x :: Entity] (Close (blabi $x))})))

; me'i pa gerku cu blabi — explicit fewer-than-one, finite pure profile
(Assert
  (¬ (≤ 1 (Card (SetOf {λ [$x :: Entity]
                 (∧ (gerku $x) (Close (blabi $x)))})))))
