; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: samples.md:1179 fence 70; kind: specimen; sha1: cee1f11c30a4f8541a7f8e567642de3453389bbb
; one act value; performed and then targeted by a display
{Let [$a :: Act Assertion] (Assert (Close (klama Speaker)))
  {Bind [$o :: ActOccurrence Assertion] (Perform Host $a)
    (Do (Perform AttachedDisplay
      (Express (Close (Happiness Speaker $o Moderate)))))}}
