; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: samples.md:308 fence 22; kind: specimen; sha1: 00fe2e7f046eae70ff325b29c40883a520b61c01
; origin: surface
; rules: L3.2
; le mlatu cu blabi              [pin P10]
{Bind [$it :: Referents Entity]
        (Refer {λ [$x :: Referents Entity]
          (SpeakerDescribes $x
            {λ [$y :: Referents Entity] (mlatu $y)})})
  (Assert (Close (blabi $it)))}
