; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: samples.md:1065 fence 65; kind: specimen; sha1: 82f4bd4c4f1e86823f95585520240cf5e1fa735a
; origin: surface
; rules: L9.6 L12.7
; lo nu ta du lo mi zdani — event abstraction over eventless identity
{Bind [$home :: Referents Entity]
      (Refer {λ [$x :: Referents Entity] (zdani $x Speaker)})
  {Bind [$state :: Referents Eventuality]
        (Refer (StateClause (CoRef That $home)))
    (Mention $state)}}
; StateClause is already the event property nu needs; no event place is
; added to CoRef/du and EventOfContent selects this same holding state.
