; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: samples.md:608 fence 41; kind: specimen; sha1: 65a34b9ec5168c21e7c4a2cf6f94067c0c6bd378
; one reusable package, two performance occurrences
(Let {$a :: Act Assertion} (Assert (Close (klama Speaker)))
  {(Do (Perform $a) (Perform $a))})
