; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: samples.md:278 fence 21; kind: specimen; sha1: 2e19ca24c2dfbffffd59c44eceb51ee42290646f
; le mlatu cu blabi              [pin P10]
(Bind {$it :: Referents Entity}
        (Refer (λ {$x :: Referents Entity}
          {(Close (skicu Speaker $x Audience
            (λ {$y :: Referents Entity} {(mlatu $y)})))}))
  {(Assert (Close (blabi $it)))})
