; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: samples.md:43 fence 2; kind: specimen; sha1: 4dafb267405c206fcd2cfc26056b51d6d3940054
; rules: L1.1 L1.2 L1.6 L6.1
; mi klama — Close expanded
(Assert
  {Bind [$to :: Referents Entity] (Context)
         [$from :: Referents Entity] (Context)
         [$via :: Referents Entity] (Context)
         [$by :: Referents Entity] (Context)
    (CloseClause
      {λ [$e :: Referents Eventuality]
        (∧ (klama Speaker $to $from $via $by :Eventuality $e)
           (fasnu $e))})})
