; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: samples.md:544 fence 38; kind: specimen; sha1: 5af448ae9b9bd7501e692d569c52f597fe7ee753
; origin: surface
; rules: L4.3
; le gerku voi blabi cu jbena — voi: non-veridical restriction  [pin P10]
{Bind [$dog :: Referents Entity]
        (Refer {λ [$x :: Referents Entity]
          (∧ (Close (skicu Speaker $x Audience            ; the le-head:
               {λ [$y :: Referents Entity] (gerku $y)})) ; "my dog"
             (Close ((DropPlace skicu 3) Speaker $x       ; the voi
               {λ [$y :: Referents Entity] (blabi $y)})))})   ; restriction
  (Assert (Close (jbena $dog)))}
; the voi conjunct's audience place is DELETED; not omitted — a voi
; description has no audience role; the le-head keeps its audience.
; Three-way contrast: poi (veridical restriction; in the property);
; noi (projective supplement; below); voi (non-veridical restriction
; through the describer).
