; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: samples.md:1312 fence 72; kind: specimen; sha1: 8a0b52f4154b7714316a8a653626e38ef8ba3102
; origin: core
{λ [[$dogs :: Fn ((Referents Entity)) Content]
    [$sleep :: Fn ((Referents Entity)) Content]
    [$red :: Fn ((Referents Entity)) Content]]
  {PerformSource Host [$x :: Referents Entity] (Refer $dogs)
    (Assert ($sleep $x))
    [$read :: RefComp (Referents Entity)]
    [$o1 :: ActOccurrence Assertion]
    (Do (Perform Host
      (Assert {Bind [$y :: Referents Entity] $read ($red $y)})))}}
