; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: samples.md:444 fence 32; kind: specimen; sha1: 30eecfcc9bafe403e11fb8e2cbbe5918e7c78c92
; ro prenu cu ponse ci gerku .i ri tatpi — dependent witness
; truth-conditional joint-locus artifact; the discourse keeps two Host acts
(Presuppose (∃ (λ {$x :: Entity} {(prenu $x)}))
  (∧
      ; sentence 1's own claim — the ownership, never erased:
      (∀ (λ {$p :: Entity}
        {(→ (prenu $p)
           (∃ (λ {$d :: Referents Entity}
             {(∧ (Distrib (λ {$x :: Entity} {(gerku $x)}) $d)
                (= (CardBasis $d (λ {$x :: Entity} {(gerku $x)})) 3)
                (Close (ponse $p $d)))})))}))
      ; the anaphoric continuation at the joint locus (strong reading):
      (∀ (λ {{$p :: Entity} {$d :: Referents Entity}}
        {(→ (∧ (prenu $p)
              (Distrib (λ {$x :: Entity} {(gerku $x)}) $d)
              (= (CardBasis $d (λ {$x :: Entity} {(gerku $x)})) 3)
              (Close (ponse $p $d)))
           (Close (tatpi $d)))}))))
