; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: samples.md:390 fence 29; kind: specimen; sha1: db966ef3fd616d400ccb12d4dae6f82c5beeff05
; origin: surface
; rules: L7.1 L11.7
; mi'a .i do'o .i ma'a — their complete reference values [P40]
(Do
  (Mention (Combine Speaker MiAOthers))
  (Mention (Combine Audience DoOOthers))
  (Mention (Combine (Combine Speaker Audience) MaAOthers)))
