; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: samples.md:258 fence 19; kind: specimen; sha1: f6306ca6a825812183f3a1dfd7a344a82161b721
; lo mlatu cu blabi              [pin P1]
(Bind {$cat :: Referents Entity}
        (Refer (λ {$x :: Referents Entity} {(mlatu $x)}))
  {(Assert (Close (blabi $cat)))})
