; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: samples.md:304 fence 23; kind: specimen; sha1: c5deba4b14c6d8bdc0cc2f9ab092492c7993c40f
; lo'i gerku — a set object via selcmi (xorxes' lujvo: place 2 = members) [P5]
{Bind [$base :: Referents Entity]
        (Local (Refer {λ [$x :: Entity] (gerku $x)})) ; ordinary base;
                                                        ; but not a surface DR
  {Bind [$sets :: Referents (Set Entity)]
          (Refer {λ [$s :: Set Entity]
            (Close (selcmi $s $base))})
    (Mention $sets)}}
