; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: samples.md:750 fence 50; kind: specimen; sha1: 0d257553df3ae17c8eb7ca27f65922ceadd33ba0
; origin: surface
; rules: L12.1
; mi cusku lu mi klama li'u — reported; not performed
(Assert
  (Close
    (cusku Speaker
      (StructuredQuote
        (Utterance {$u :: UtteranceToken}
          {(∧ (SpeakerOf $u Speaker)
          (Realizes $u (Assert (Close (klama Speaker)))))})))))
