; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: samples.md:1135 fence 67; kind: specimen; sha1: 4c817faeaf9ed5ad1f796c7a5b6d9cba8b973769
; origin: surface
; rules: L3.1 L3.9 L3.15 L4.2 L5.9 L5.2 L11.2 L11.6 L11.7
; lo ci gerku noi blabi cu na batci re prenu .i .uinai cai ri tatpi
; (episodic readings: each sentence's occasion is Context-anchored; P8)
{Bind [$dogs :: Referents Entity]
      (Refer {λ [$r :: Referents Entity]
        (∧ (gerku $r)
            (= (CardBasis $r {λ [$x :: Entity] (gerku $x)}) 3))})
  (Do
    {Bind [$occ1 :: Time] (Context)          ; the biting's occasion — bound
      {Let [$a1 :: Act Assertion]         ; OUTSIDE the negation; so na
            (Assert                       ; denies biting AT that occasion
              (Supplement $dogs (Close (blabi $dogs))
                (¬ (Exactly 2 {λ [$x :: Entity] (prenu $x)}
                     {λ [$ppl :: Referents Entity]
                       (CloseClause (ActualClause
                         {λ [$e :: Referents Eventuality]
                           (∧ ((DirectClause (batci $dogs $ppl)) $e)
                              (cabna $e $occ1))}))}))))
        (Perform $a1)}}
    {Bind [$occ2 :: Time] (Context)
      {Let [$a2 :: Act Assertion]
            (Assert
              (CloseClause (ActualClause
                {λ [$e :: Referents Eventuality]
                  (∧ (Close (tatpi $dogs :Eventuality $e)) ; the prior direct-event
                     (cabna $e $occ2))})))         ; fill is kept: tatpi's mode is #12's
        {Bind [$o2 :: ActOccurrence Assertion] (Perform Host $a2)
          (Do (Perform AttachedDisplay
            (Express (Close (Unhappiness Speaker $o2 Intense)))))}}})}
