; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: samples.md:195 fence 14; kind: schema; sha1: bf0cd5c00290030d92e0a7008345fca7288900f8
; classification-note: open physical-parameter fragment with declared metavariables
; fragment: a physical parameter has value $x now but not in a future state
; $alpha :: Referents Entity
; $valueOf :: Fn ((Referents Entity)) Number  (state-sensitive projection)
; $x :: Number
(CloseClause
  (ActualClause
    (ClauseAnd
      {λ [$s :: Referents Eventuality]
        (∧ ((StateClause (= ($valueOf $alpha) $x)) $s)
           (cabna $s Now))}
      {λ [$t :: Referents Eventuality]
        (∧ ((StateClause (¬ (= ($valueOf $alpha) $x))) $t)
           (balvi $t Now))})))
; The two applications of $valueOf are inside their StateClauses and may vary.
; Binding the resulting Number outside instead would give the rigid de re case.
