; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: samples.md:676 fence 42; kind: specimen; sha1: b8921f35fcc1f2b6c24277fff21d4d91ed70835f
; classification-note: P43 and samples §5 explicitly mark this as a plural/library comparison or excluded historical extension; retained as a checked core term, not a surface lowering (#20).
; durable-issue: #20
; origin: core
; historical excluded extension: ro prenu cu ponse ci gerku .i ri tatpi
; truth-conditional joint-locus artifact; the discourse keeps two Host acts
(Presuppose (∃ {λ [$x :: Entity] (prenu $x)})
  (∧
      ; sentence 1's own claim — the ownership; never erased:
      (∀ {λ [$p :: Entity]
        (→ (prenu $p)
           (∃ {λ [$d :: Referents Entity]
             (∧ (CoveredBy {λ [$x :: Entity] (gerku $x)} $d)
                (= (CardBasis $d {λ [$x :: Entity] (gerku $x)}) 3)
                (Close (ponse $p $d)))}))})
      ; the anaphoric continuation at the joint locus (strong reading):
      (∀ {λ [[$p :: Entity] [$d :: Referents Entity]]
        (→ (∧ (prenu $p)
              (CoveredBy {λ [$x :: Entity] (gerku $x)} $d)
              (= (CardBasis $d {λ [$x :: Entity] (gerku $x)}) 3)
              (Close (ponse $p $d)))
           (Close (tatpi $d)))})))
