; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: samples.md:687 fence 45; kind: specimen; sha1: 7549d4565ac0ab1e545914425fc678ca69065913
; origin: surface
; rules: L3.10
; lo no prenu cu jmaji — inner-no                       [pin P22]
; the answer "no" to the question lo xo prenu cu jmaji is elliptical
; for this sentence (guskant); the question itself is an OpenQ (L10.2)
; and records no answer; the answer lowers through the zero-count
; special case; never Refer:
(Assert
  (No {λ [$x :: Entity] (prenu $x)}
      {λ [$w :: Referents Entity] (Close (jmaji $w))}))
; the nuclear scope is reference-typed (spec §12): "no people-witness
; gathers" — the collective reading a distributive quantifier could not
; state at all.
; answer substitution into the question's frame works; anaphora to
; the form is inaccessible (No exports nothing — nothing to refer to).
