; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: samples.md:36 fence 1; kind: specimen; sha1: 738f3c4cc9a19d8708f73af84f65571286474905
; origin: surface
; rules: L1.1 L1.3 L1.6
; mi klama
(Assert
  (Close (klama Speaker)))
; ≝ (Assert (CloseClause (ActualClause (DirectClause (klama Speaker)))))
; this specimen selects the actual missing-CAhA reading; Close names that
; core composition; not a default imposed on the surface.
