; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: samples.md:171 fence 13; kind: specimen; sha1: 83b8a4dae2192d40b767754e3d1d86c0b2df22f1
; ta pu du lo mi zdani — tense on eventless identity [spec §4.6]
(Assert
  (CloseClause
    (ActualClause
      (λ {$s :: Referents Eventuality}
        {(∧ ((StateClause
               (Bind {$home :: Referents Entity}
                     (Refer (λ {$x :: Referents Entity}
                       {(zdani $x Speaker)}))
                 {(CoRef That $home)})) $s)
           (purci $s Now))}))))
; The home description is inside StateClause, so its property is evaluated in
; $s: That may have been the home then without being it now. Hoisting $home
; outside gives the rigid de re reading. du/CoRef itself retains ordinary arity.
