; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: samples.md:1124 fence 67; kind: specimen; sha1: 7863fadb45552896589e6a24f2afd4a481c9f7b5
; origin: surface
; rules: L3.1 L3.9 L3.15 L4.2 L5.9 L5.2 L11.2 L11.6 L11.7
; lo ci gerku noi blabi cu na batci re prenu .i .uinai cai ri tatpi
; (episodic readings: each sentence's occasion is Context-anchored; P8)
{Bind [$dogs :: Referents Entity]
      (Refer {λ [$r :: Referents Entity]
        (∧ (gerku $r)
            (= (CardBasis $r {λ [$x :: Entity] (gerku $x)}) 3))})
  (Do
    {Bind [$occ1 :: Time] (Context)          ; the biting's occasion — bound
      {Let [$a1 :: Act Assertion]         ; OUTSIDE the negation; so na
            (Assert                       ; denies biting AT that occasion
              (Supplement $dogs (Close (blabi $dogs))
                (¬ (Exactly 2 {λ [$x :: Entity] (prenu $x)}
                     {λ [$ppl :: Referents Entity]
                       (CloseClause (ActualClause
                         {λ [$e :: Referents Eventuality]
                           (∧ ((DirectClause (batci $dogs $ppl)) $e)
                              (cabna $e $occ1))}))}))))
        (Perform $a1)}}
    {Bind [$occ2 :: Time] (Context)
      {Let [$a2 :: Act Assertion]
            (Assert
              (CloseClause (ActualClause
                {λ [$e :: Referents Eventuality]
                  (∧ ((StateClause (tatpi $dogs)) $e) ; tatpi: eventless fixture row
                     (cabna $e $occ2))})))         ; so its holding state is the event
        {Bind [$o2 :: ActOccurrence Assertion] (Perform Host $a2)
          (Do (Perform AttachedDisplay
            (Express (Close (Unhappiness Speaker $o2 Intense)))))}}})}
