; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: samples.md:783 fence 51; kind: schema; sha1: 4c44c5948d5af87d72f06e12abfdb03cf9403454
; classification-note: side-by-side positive/negative intended-value schema
; positive                                  ; negative
(Bind {$v :: T} (Context P deps…)           (Bind {$v :: T} (Context P deps…)
  {C[$v]})                                    {(¬ C[$v])})
