; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: samples.md:1065 fence 64; kind: specimen; sha1: b53d5c6c6eafa47816dcb3dc8437b083cae3dd37
; origin: surface
; rules: L5.29
; ta barda — gradable predication: Context scale; Vague cutoff  [spec §6.4]
{Bind [$s :: Scale] (Context)                    ; which size-scale: recoverable
       [$reg :: Region Scale]
         (Vague {λ [$r :: Region Scale] (AdmissibleCutoff $s $r)})
  (Assert (Close ((Grade barda $s $reg) That)))}

; Reference-level threshold comparison: Vague threshold, Context purpose.
; Standard du'e gerku cu klama adaptation remains L5.28 work. [spec §6.4]
{Bind [$purpose :: Referents Entity] (Context)  ; too many FOR WHAT: recoverable
       [$n :: Natural]
         (Vague (AdmissibleThreshold TooManyK
                  {λ [$x :: Entity] (gerku $x)} $purpose))
  (Assert
    (MoreThan $n {λ [$x :: Entity] (gerku $x)}
                 {λ [$w :: Referents Entity] (Close (klama $w))}))}

; mi co'e do — elliptical selbri: Context; not Vague   [spec §6.1]
{Bind [$r :: PredTerm
              (Row (1 (Referents Entity)) (2 (Referents Entity)))]
        (Context)
  (Assert (Close ($r Speaker Audience)))}
