; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: samples.md:785 fence 48; kind: specimen; sha1: 6d990f968d4772b9ff1ae5699dbcd9f19889cc20
; classification-note: P43 and samples §5 explicitly mark this as a plural/library comparison or excluded historical extension; retained as a checked core term, not a surface lowering (#20).
; durable-issue: #20
; origin: core
; Explicit plural/core comparison — not standard ci jbopre quantification.
; A selected trio in pairwise mutual talk.                 [spec §12]
{Bind [$trio :: Referents Entity]
        (SelectExactly 3 {λ [$x :: Entity] (jbopre $x)})
  (Assert
    (Reciprocate $trio
      {λ [$a $b :: Referents Entity]
        (Close (tavla $a $b))}))}
; simxu's lexicon row consumes the library's Reciprocate schema:
; pairwise both ways among the witness.
