; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: samples.md:318 fence 24; kind: schema; sha1: 0f5c6074618341a240903a0682ba24fd8097a626
; classification-note: descriptor lowering schema with an explicit dependency-profile metavariable
; loi gerku — κ is the occurrence's resolved group basis
(Bind {$base :: Referents Entity}
      (Local (Refer (λ {$x :: Entity} {(gerku $x)})))
  {(Bind {$κ :: GroupBasis Entity}
         (Context GroupBasisConstraint[loi,Entity] deps…)
    {(Bind {$groups :: Referents (Group Entity)}
           (Refer (λ {$g :: Group Entity}
             {(CompleteGunmaAt $κ $g $base)}))
      {(Mention $groups)})})})
