; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: samples.md:405 fence 28; kind: specimen; sha1: 4d1569f29face71d85370c699b9c489d1585cb8f
; lu'a ri — fragment: components of the previously selected single group
{λ [[$κ :: DecompositionBasis (Group Entity) Entity]
    [$group :: Referents (Group Entity)]]
  (Mention (components_κ $κ $group))}
