; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: samples.md:242 fence 18; kind: schema; sha1: c0eddf6b865c5ad0a9c4d5e68ab73330faf8bf30
; classification-note: open JoiClause fragment parameterized by kappa
; κ :: DecompositionBasis<Eventuality;Eventuality>; recovered for this joi
(JoiClause $κ
  (DirectClause (sanga Speaker))
  (DirectClause (dansu Audience)))
