; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: samples.md:69 fence 4; kind: specimen; sha1: 6ee5b8e402e2c2f6585d7ade3e4911d3faef1a2a
; origin: surface
; rules: L1.5
; mi klama ti zi'o ti ti — the origin role removed; not omitted
(Assert (Close ((DropPlace klama 3) Speaker This This This)))
