; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: samples.md:845 fence 54; kind: schema; sha1: 5a1cd2b8b6822564b35b2fc42a92c19e7cc50fcd
; classification-note: side-by-side positive/negative intended-value schema
; positive                                  ; negative
(Bind {$v :: T} (Context P deps…)           {Bind [$v :: T] (Context P deps…)
  (C $v)}                                    {(¬ (C $v))})
