; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: samples.md:1145 fence 66; kind: specimen; sha1: 9aa3cabf2d2bd707631d5939b60ce11509bd99f3
; origin: surface
; rules: L9.6 L12.7
; lo nu ta du lo mi zdani — event abstraction over eventless identity
{Bind [$home :: Referents Entity]
      (Refer {λ [$x :: Referents Entity] (zdani $x Speaker)})
  {Bind [$state :: Referents Eventuality]
        (Refer (StateClause (CoRef That $home)))
    (Mention $state)}}
; StateClause is already the event property nu needs; no event place is
; added to CoRef/du and EventOfContent selects this same holding state.
; This displayed reading is de re: $home was bound outside StateClause.
