; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: samples.md:748 fence 49; kind: specimen; sha1: fadb46cf059ef282ee8df9d448995f4646e77051
; ta na'e melbi — scalar otherness            [spec §6.3]
(Bind {$d :: ContrastDomain ρ(melbi)} (Context)
  {(Assert (Close ((Scalar OtherThan $d melbi) That)))})
; contrast domain: visible Context site; any soritical boundary: Vague.
; DENIES beauty AND directly asserts membership in the complement of
; beauty's region in the recovered domain (CLL 15.4: selbri negation
; "remains an assertion of some specific truth"). No finer alternative is
; selected; to'e uses the domain's antipode, no'e its between-region.
