; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: samples.md:581 fence 40; kind: specimen; sha1: 31905249109a13167a5b4ae9dd36e8fb1445d03f
; origin: surface
; rules: L4.4
; mi tavla le pendo goi ko'a — aliasing is shared binding
{Bind [$friend :: Referents Entity]
        (Refer {λ [$x :: Referents Entity]
          (SpeakerDescribes $x
            {λ [$y :: Referents Entity] (Close (pendo $y))})})
  (Assert (Close (tavla Speaker $friend)))}
; the second place of pendo is omitted inside the description — one Context site (L1.6)
; later ko'a occurrences consume the same binding.  [pin P16]
