; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: samples.md:395 fence 30; kind: specimen; sha1: bb927fff8f0424bed33e08d63acaa232f3cca35c
; origin: surface
; rules: L3.5 L3.6
; lo'i gerku — a set object via selcmi (xorxes' lujvo: place 2 = members) [P5]
{Bind [$base :: Referents Entity]
        (Local (Refer {λ [$x :: Entity] (gerku $x)})) ; ordinary base via the
                                                        ; §5.3 member lift; not
                                                        ; a surface DR
  {Bind [$sets :: Referents (Set Entity)]
          (Refer {λ [$s :: Set Entity]
            (Close (selcmi $s $base))})
    (Mention $sets)}}
