; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: samples.md:824 fence 53; kind: specimen; sha1: 901e7498b95b442ff8bce8445419eee3ca88968e
; origin: surface
; rules: L10.3 L9.1
; mi djuno lo du'u ma kau klama      [pin P9]
(Assert
  (Close
    (djuno Speaker
      (Reify
        (Answer
          (OpenQ {λ [$x :: Referents Entity] (Close (klama $x))})
          ContextualAnswer)))))
