; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: samples.md:654 fence 44; kind: specimen; sha1: 546483572c8b82d02c31422e9f757152ce89b82b
; origin: surface
; rules: L5.1
; ro gerku cu blabi — importing universal   [pin P2]
(Assert
  (Presuppose
    (∃ {λ [$x :: Entity] (gerku $x)})
    (∀ {λ [$x :: Entity] (→ (gerku $x) (Close (blabi $x)))})))
