; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: samples.md:1022 fence 60; kind: specimen; sha1: 9d8bad3c3859775b7a27c761f110bd1083d8ecd4
; one act value, performed and then targeted by a display
(Let {$a :: Act Assertion} (Assert (Close (klama Speaker)))
  {(Bind {$o :: ActOccurrence Assertion} (Perform Host $a)
    {(Do (Perform AttachedDisplay
      (Express (Close (Happiness Speaker $o Moderate)))))})})
