; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: samples.md:92 fence 7; kind: specimen; sha1: 0c823943d9818415fe46cfbb6bf5f7f8a035be10
; mi pu citka
(Assert
  (CloseClause
    (ActualClause
      (λ {$e :: Referents Eventuality}
        {(∧ ((DirectClause (citka Speaker)) $e)
           (purci $e Now))}))))
