; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: samples.md:346 fence 25; kind: specimen; sha1: f738b63ed15fc9c6b5ffa9c84ba9a10f76abfb0c
; origin: surface
; rules: L7.1 L7.4
; mi'o jmaji ≡ mi jo'u do jmaji — one neutral plural predication [P40]
(Assert (Close (jmaji (Combine Speaker Audience))))
