; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: samples.md:665 fence 44; kind: specimen; sha1: 6a605399ce7d2f0f95202e9c42e526da81a914fa
; .ui do klama — pure emotion: host asserted, joy displayed
(Let {$a :: Act Assertion} (Assert (Close (klama Audience)))
  {(Bind {$o :: ActOccurrence Assertion} (Perform Host $a)
    {(Do (Perform AttachedDisplay
      (Express (Close (Happiness Speaker $o Moderate)))))})})

; .au mi sipna — propositional attitude: host subordinated  [spec §7.6]
(Express (Close (Desire Speaker (Reify (Close (sipna Speaker))))))
; no assertion of sleeping occurs — the host-force profile of .au.

; .uinai cai do klama — paired emotion, then degree   [spec §7.6]
(Let {$a :: Act Assertion} (Assert (Close (klama Audience)))
  {(Bind {$o :: ActOccurrence Assertion} (Perform Host $a)
    {(Do (Perform AttachedDisplay
      (Express (Close (Unhappiness Speaker $o Intense)))))})})
