; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: samples.md:1237 fence 72; kind: specimen; sha1: 9e9e7af59a1f4e4f5eef994dd1d2f230dbaf21e4
; origin: surface
; rules: L5.30 L5.1 L5.2
; ro gerku cu tavla su'o mlatu — two quantifiers: surface order is scope
; order; the cats may vary with the dog                         [pin P41]
(Assert
  (Every {λ [$x :: Entity] (gerku $x)}
         {λ [$dog :: Entity]
           (Some {λ [$y :: Entity] (mlatu $y)}
                 {λ [$w :: Referents Entity] (Close (tavla $dog $w))})}))
