; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: samples.md:780 fence 50; kind: specimen; sha1: c7922087c3c3985f9bf6e2f1b13cecf7fc8e5569
; mi djica tu'a lo cukta                      [pin P14]
{Bind [$book :: Referents Entity]
        (Refer {λ [$x :: Referents Entity] (cukta $x)})
  {Bind [$a :: Referents Eventuality]          ; sort from djica's place 2
          (Context {λ [$v :: Referents Eventuality]
            (∧ (∃ {λ [$p :: Proposition]
                 (CoRef $v (EventOfContent (Holds $p)))}) ; clause-event shape
               (Close (srana $v $book)))}
            $book)                               ; depends on this book
    (Assert (Close (djica Speaker $a)))}}
