; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: samples.md:1229 fence 71; kind: specimen; sha1: e5a3a20cbbc62b1cc8319b03e21c2980781391f5
; origin: surface
; rules: L5.30 L5.1 L3.1
; ro gerku cu tavla lo mlatu — the cats are one contextual plurality;
; every dog talks to them                                       [pin P41]
{Bind [$cats :: Referents Entity]
        (Refer {λ [$x :: Referents Entity] (mlatu $x)})
  (Assert
    (Every {λ [$x :: Entity] (gerku $x)}
           {λ [$dog :: Entity] (Close (tavla $dog $cats))}))}
