; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: samples.md:141 fence 11; kind: specimen; sha1: a114277901ea6efdfd2092ce68b2d76273153d48
; mi citka — the episodic reading: at the contextually relevant occasion
(Assert
  (Bind {$occ :: Time} (Context)
    {(CloseClause
      (λ {$e :: Referents Eventuality}
        {(∧ ((ActualClause (DirectClause (citka Speaker))) $e)
           (cabna $e $occ))}))}))
