; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: samples.md:487 fence 33; kind: specimen; sha1: ea7614d6f11e82b695ffd1171d2d6970a81bef28
; origin: surface
; rules: L3.12 L3.9 L3.15 L3.2 L12.7
; lei ci prenu du le kamni — fragment after resolving le kamni and κ
{λ [[$κ :: DecompositionBasis (Group Entity) Entity]
    [$committee :: Referents (Group Entity)]]
  {Let [$P :: EFn ((Referents Entity)) Content]
        {λ [$y :: Referents Entity] (prenu $y)}
    {Bind [$people :: Referents Entity]
          (Local (Refer {λ [$r :: Referents Entity]
            (∧ (SpeakerDescribes $r $P)
               (= (CardBasis $r {λ [$x :: Entity]
                     (SpeakerDescribes $x $P)}) 3))}))
      {Bind [$described :: Referents (Group Entity)]
            (Refer {λ [$g :: Group Entity]
                     (CompleteGunmaAt $κ $g $people)})
        (Assert (CoRef $described $committee))}}}}
; One formed description property is passed inertly at both uses.
