; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: samples.md:69 fence 4; kind: specimen; sha1: 14f7a042d294d075a0bad1978571a8a122200ac2
; mi klama ti zi'o ti ti — the origin role removed, not omitted
(Assert (Close ((DropPlace klama 3) Speaker This This This)))
