; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: samples.md:107 fence 8; kind: specimen; sha1: 45365bc7337e4453654b5e43103d859e34dbde60
; origin: surface
; rules: L6.3
; mi pu pu citka — a tense path: past of a past reference point
(Assert
  (CloseClause
    (ActualClause
      {λ [$e :: Referents Eventuality]
        (∃ {λ [$m :: Referents Eventuality]
          (∧ ((DirectClause (citka Speaker)) $e)
             (purci $m Now)
             (purci $e $m))})})))
