; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: samples.md:979 fence 57; kind: specimen; sha1: 4c9334364851c333d8d56bab7af0162ebfa6b174
; lo ci gerku noi blabi cu na batci re prenu .i .uinai cai ri tatpi
; (episodic readings: each sentence's occasion is Context-anchored; P8)
{Bind [$dogs :: Referents Entity]
      (Refer {λ [$r :: Referents Entity]
        (∧ (gerku $r)
            (= (CardBasis $r {λ [$x :: Entity] (gerku $x)}) 3))})
  (Do
    {Bind [$occ1 :: Time] (Context)          ; the biting's occasion — bound
      {Let [$a1 :: Act Assertion]         ; OUTSIDE the negation; so na
            (Assert                       ; denies biting AT that occasion
              (Supplement $dogs (Close (blabi $dogs))
                (¬ (Exactly 2 {λ [$x :: Entity] (prenu $x)}
                     {λ [$ppl :: Referents Entity]
                       (∃ {λ [$e :: Referents Eventuality]
                          (∧ (Close (batci $dogs $ppl :Eventuality $e))
                              (cabna $e $occ1))})}))))
        (Perform $a1)}}
    {Bind [$occ2 :: Time] (Context)
      {Let [$a2 :: Act Assertion]
            (Assert
              (∃ {λ [$e :: Referents Eventuality]
                (∧ (Close (tatpi $dogs :Eventuality $e))
                    (cabna $e $occ2))}))
        {Bind [$o2 :: ActOccurrence Assertion] (Perform Host $a2)
          (Do (Perform AttachedDisplay
            (Express (Close (Unhappiness Speaker $o2 Intense)))))}}})}
