; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: samples.md:114 fence 9; kind: specimen; sha1: f6c4583d56ec030ef369a55bc5233e8e0ed7c6e2
; mi klama ti sepi'o ti — an instrumental facet; same event
(Assert
  (CloseClause
    (ActualClause
      {λ [$e :: Referents Eventuality]
        (∧ ((DirectClause (klama Speaker This)) $e)
           (Close (pilno :2 This :3 $e)))})))
; the host event fills pilno place 3 (purpose) — the tag row's licensed link
; per the official row: place 1 uses place 2 for purpose place 3.
