; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: samples.md:1409 fence 77; kind: specimen; sha1: f504ad67c71bc8b8beec3c88b73547faa75fec58
; origin: surface
; rules: L5.2 L5.3
; su'o gerku ce'e su'o prenu cu nelci — pure joint individual locus
(Assert
  (∃ {λ [[$dog :: Entity] [$person :: Entity]]
    (∧ (gerku $dog) (prenu $person) (Close (nelci $dog $person)))}))
