; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: samples.md:258 fence 19; kind: specimen; sha1: 9e3967b0e16d7c22d263f5dd3e873c8babd43e84
; lo mlatu cu blabi              [pin P1]
{Bind [$cat :: Referents Entity]
        (Refer {λ [$x :: Referents Entity] (mlatu $x)})
  (Assert (Close (blabi $cat)))}
