; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: samples.md:396 fence 27; kind: specimen; sha1: 0e1eded10092060a254f714871debba0473a1902
; lu'o le ci prenu — canonical aggregate of the selected people
{Bind [$people :: Referents Entity]
      (Local (SelectExactly 3 {λ [$x :: Entity] (prenu $x)}))
  {Bind [$κ :: DecompositionBasis (Group Entity) Entity] (Context)
    {Bind [$aggregate :: Referents (Group Entity)] (Massify $κ $people)
      (Mention $aggregate)}}}
