; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: samples.md:1295 fence 72; kind: specimen; sha1: 4890c0005f7c7eca9bd4ea5fe9a8eaffc08c4b38
; origin: surface
; rules: L5.30 L5.1 L3.1
; ro gerku cu tavla lo mlatu — the cats are one contextual plurality;
; every dog talks to them                                       [pin P41]
{Bind [$cats :: Referents Entity]
        (Refer {λ [$x :: Referents Entity] (mlatu $x)})
  (Assert
    (IndividualEvery {λ [$x :: Entity] (gerku $x)}
           {λ [$dog :: Entity] (Close (tavla $dog $cats))}))}
