; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: samples.md:736 fence 48; kind: specimen; sha1: 7803f54fed3fbabeeb36b7fed9b4b6264bee058c
; origin: surface
; rules: L5.28
; so'i prenu cu klama — vague quantity    [spec §6.4]
{Bind [$n :: Natural]
        (Vague (AdmissibleThreshold ManyK {λ [$x :: Entity] (prenu $x)}))
  (Assert
    (AtLeast $n {λ [$x :: Entity] (prenu $x)}
                {λ [$w :: Referents Entity] (Close (klama $w))}))}
