; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: samples.md:825 fence 52; kind: specimen; sha1: 108047de2dcd7fda8512944d7f0ff361c5052b6f
; sutra klama — one intended link recovered at this occurrence [spec §6.2]
(Assert
  (Close ((Tanru sutra klama) Speaker)))
; ≗ (Bind {$link :: PredTerm (RowOf klama)}
;         (Context (λ {$r :: PredTerm (RowOf klama)}
;                    {(TanruAdmissible sutra klama $r)}))
;     {… (∧ (klama …) ($link …))})
; no governor dependencies in this reading. `na sutra klama` retrieves
; one intended admissible link at that occurrence's site and negates that claim;
; it does not quantify over every possible tanru link.
