; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: spec.md:752 fence 8; kind: schema; sha1: 5cc00428665b2b8278e155d6377b50228552bafc
; classification-note: finite computed-label case schema
(∨ (∧ (= $p ℓ₁) C[(At R ℓ₁ v)]) … (∧ (= $p ℓₙ) C[(At R ℓₙ v)]))
