; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: spec.md:756 fence 8; kind: schema; sha1: b1e9170c2d7fdd44d69baccb14a37ce987bcc65a
; classification-note: finite computed-label case schema
(∨ (∧ (= $p ℓ1) (C (At R ℓ1 v))) … (∧ (= $p ℓn) (C (At R ℓn v))))
