; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: spec.md:1246 fence 9; kind: specimen; sha1: 51db28bc844d630b0bc9e4d9619cf3fb36107cda
; origin: surface
; rules: L5.2 L0.1
; ci gerku cu bajra — standard finite individual exact count
{Bind [$surface :: Referents Entity] (Context)
      [$limbs :: Referents Entity] (Context)
      [$gait :: Referents Entity] (Context)
  (= (Card (SetOf {λ [$x :: Entity]
              (∧ (gerku $x) (Close (bajra $x $surface $limbs $gait)))})) 3)}
