; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: spec.md:1849 fence 12; kind: specimen; sha1: 3e35817cf46a4e9db74e9aba5f198cc3fd8d07e1
; origin: core
(∀ {λ [[$p :: Entity] [$d :: Entity]]
  (→ (∧ (prenu $p)
        (xasli $d)
        (Close (ponse $p $d)))
     (Close (ctigau $p $d)))})
