; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: spec.md:665 fence 6; kind: expansion; sha1: 2892852bfcc49d5773f580fdc8df8548d067e551
(DirectClause P) ≝
{λ [$e :: Referents Eventuality]
  (Bind {$v1 :: T1} (Context) … {$vk :: Tk} (Context)
    {(P :p1 $v1 … :pk $vk :Eventuality $e)})}
