; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: spec.md:1414 fence 11; kind: schema; sha1: efdf4c59513bd7ef0d3b4a3c8de66ba7d29a1ba6
; classification-note: lowering pattern with an ellipsis body
{Bind [$base :: Referents T] (Local (Refer P))
  {… construct and introduce the one surface group/set from $base …}}
