; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: spec.md:1528 fence 10; kind: schema; sha1: 64774649585218b06269d21a4b4a2d5a2f8724e1
; classification-note: lowering pattern with an ellipsis body
{Bind [$base :: Referents T] (Local (Refer P))
  … construct and introduce the one surface group/set from $base …}
