; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: spec.md:1561 fence 14; kind: specimen; sha1: f15e9d61dc795fdddb5721205a0d753dd2447384
(Presuppose (∃ (λ {$x :: Entity} {(∧ (prenu $x)
              (∃ (λ {$y :: Entity} {(∧ (xasli $y) (Close (ponse $x $y)))})))}))
  (∀ (λ {{$p :: Entity} {$d :: Referents Entity}}
    {(→ (∧ (prenu $p)
          (Distrib (λ {$z :: Entity} {(xasli $z)}) $d)
          (Close (ponse $p $d)))
       (Close (darxi $p $d)))})))
