; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: spec.md:1082 fence 9; kind: specimen; sha1: 25ece208c031e28df7d0e1c7b011cba8d3ffa645
; ci gerku cu bajra — the default (witness-set) reading
(Bind {$w :: Referents Entity}
        (SelectExactly 3 (λ {$x :: Entity} {(gerku $x)}))
  {(Close (bajra $w))})
