; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: spec.md:4099 fence 21; kind: expansion; sha1: 16c662212db5ad904d77249c4d23942e60514087
(JoiClause κ C D) ≝
  {λ [$j :: Referents Eventuality]
    (∃ {λ [$e1 :: Referents Eventuality]
      (∧ (C $e1)
          (∃ {λ [$e2 :: Referents Eventuality]
            (∧ (D $e2)
                (CompleteGunmaAt κ $j (Combine $e1 $e2))
                (fasnu $j))}))})}
