; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: spec.md:529 fence 2; kind: specimen; sha1: 621187d74d9d9df8953e2e731ea712bb08a6e111
; rules: L1.4
; klama fe ti tu        — place 2 = ti; place 3 = tu; place 1 unfilled
(klama :2 This Yonder)
