; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: spec.md:543 fence 3; kind: expansion; sha1: a590b34e23edf4d56ff5e0653ecbd4bf0f3747b0
(klama :2 This Yonder)
  ≝ (At (At klama x2 This) x3 Yonder)
(klama Speaker This)
  ≝ (At (At klama x1 Speaker) x2 This)
