; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: spec.md:1511 fence 13; kind: specimen; sha1: 1919bdf63d5cf55a15125508dab4031fd3c0c00a
; truth-condition artifact for the two Host occurrences
(Presuppose (∃ (λ {$x :: Entity} {(prenu $x)}))
  (∧
    ; sentence 1's claim, preserved:
    (∀ (λ {$p :: Entity}
      {(→ (prenu $p)
         (∃ (λ {$d :: Referents Entity}
           {(∧ (Distrib (λ {$x :: Entity} {(gerku $x)}) $d)
              (= (CardBasis $d (λ {$x :: Entity} {(gerku $x)})) 3)
              (Close (ponse $p $d)))})))}))
    ; the anaphoric continuation, at the joint locus (strong reading):
    (∀ (λ {{$p :: Entity} {$d :: Referents Entity}}
      {(→ (∧ (prenu $p)
            (Distrib (λ {$x :: Entity} {(gerku $x)}) $d)
            (= (CardBasis $d (λ {$x :: Entity} {(gerku $x)})) 3)
            (Close (ponse $p $d)))
         (Close (tatpi $d)))}))))
