; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: spec.md:3242 fence 19; kind: specimen; sha1: 46eff64a87691d0d08d1d9c434a625e0597e728f
; mi fa'u do tavla do fa'u mi
(ZipWith (λ {$s $l :: Referents Entity}
           {(Close (tavla $s $l))})
  (List Speaker Audience)
  (List Audience Speaker))
; ≡ (∧ (Close (tavla Speaker Audience))
;      (Close (tavla Audience Speaker)))
