; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: spec.md:2164 fence 17; kind: schema; sha1: d2a668ce7c6724c4aceb965f6d4e4db201337301
; classification-note: content-level indicator schema with free metavariables
(Let {$p :: Proposition} (Reify c)
  {(Supplement $p (Close (i-rel Speaker $p degree)) (Holds $p))})
