; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: spec.md:668 fence 6; kind: expansion; sha1: 7f9d9b1e5772edf5fad712b401812bf2e03ca6ee
(DirectClause P) ≝
{λ [$e :: Referents Eventuality]
  {Bind [$v1 :: T1] (Context) … [$vk :: Tk] (Context)
    (P :p1 $v1 … :pk $vk :Eventuality $e)}}
