; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: spec.md:1479 fence 12; kind: specimen; sha1: 0f9b6ab333c5867e5576d5c76cb5edf4255715d0
; ci gerku cu bajra .i ri tatpi
(Bind {$dogs :: Referents Entity}
        (SelectExactly 3 (λ {$x :: Entity} {(gerku $x)}))
  {(Do (Assert (Close (bajra $dogs)))
      (Assert (Close (tatpi $dogs))))})
