; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: spec.md:2262 fence 17; kind: schema; sha1: 075e8fcadecc1f89670409e8153df9b741c03c44
; classification-note: content-level indicator schema with free metavariables
{Let [$p :: Proposition] (Reify c)
  (Supplement $p (Close (i-rel Speaker $p degree)) (Holds $p))}
