; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: spec.md:549 fence 3; kind: expansion; sha1: bc4fa1b042bc8238d2dc1d8eab2354bc87acbe05
(klama :2 This Yonder)
  ≝ (At (At klama 2 This) 3 Yonder)
(klama Speaker This)
  ≝ (At (At klama 1 Speaker) 2 This)
