; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: spec.md:577 fence 4; kind: specimen; sha1: 6c0d8fabafa50b584e356584f7f3d825ebfab992
; se tavla, as a first-class binary relation
(λ {$new-x1 $new-x2 :: Referents Entity}
  {(tavla $new-x2 $new-x1)})
