; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: spec.md:2104 fence 16; kind: expansion; sha1: e23c95652100b56ceeb9e5c738d1eaf820569e8c
(Utterance {$u :: UtteranceToken} {fact…})
  ≝ {λ [$u :: Referents UtteranceToken] (∧ fact…)}
