; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: spec.md:633 fence 5; kind: schema; sha1: fe5bfbdec40ba0419b3761ff91931742e01196e2
; classification-note: schematic typed universal with an ellipsis body
(∀ {λ [$x $y :: Entity] …})
