; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: spec.md:2624 fence 18; kind: schema; sha1: b25e39c7036c3a300f47b25ab05dd5b2cf49022a
; classification-note: gunma lowering schema with dependency-profile metavariables
; gunma g Cs — deps selected by this resolved occurrence
(Bind {$κ :: GroupBasis T}
      (Context GroupBasisConstraint[gunma,T] deps…)
  {(GunmaAt $κ g Cs)})
