; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: spec.md:1835 fence 12; kind: specimen; sha1: 359a98c71303f56b83052b5c4ca6209662f43571
; origin: core
(∀ {λ [[$p :: Entity] [$d :: Entity]]
  (→ (∧ (prenu $p)
        (xasli $d)
        (Close (ponse $p $d)))
     (Close (darxi $p $d)))})
