; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: spec.md:582 fence 4; kind: specimen; sha1: 9d713f6c0194caa64dcf738c85bd1e2918b1b219
; origin: surface
; rules: L1.4
; se tavla as a first-class binary relation
{λ [$new1 $new2 :: Referents Entity]
  (tavla $new2 $new1)}
