; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: spec.md:1166 fence 10; kind: specimen; sha1: 30c6bd5c2676ca42a0ec03c53a93c7fdcf91b92d
; origin: surface
; rules: L5.2 L0.1
; ci gerku cu bajra — under the marked global reading
; the marked global strengthening (not the bare-PA default); bajra's
; surface/limbs/gait sites are hoisted outside the comprehension (L0.1)
{Bind [$surface :: Referents Entity] (Context)
      [$limbs :: Referents Entity] (Context)
      [$gait :: Referents Entity] (Context)
  (= (Card (SetOf {λ [$x :: Entity]
              (∧ (gerku $x) (Close (bajra $x $surface $limbs $gait)))})) 3)}
