; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: spec.md:2727 fence 18; kind: schema; sha1: 67aea6009c6201815520f5d8bc50a275690a14a4
; classification-note: gunma lowering schema with dependency-profile metavariables
; gunma g Cs — deps selected by this resolved occurrence
{Bind [$κ :: GroupBasis T]
      (Context (GroupBasisConstraint gunma T) deps…)
  (GunmaAt $κ g Cs)}
