; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: spec.md:1999 fence 13; kind: expansion; sha1: 860aec4e62adaf9863bcfc60e57482447a77fb11
((Tanru M H) fills…) ≝
{Bind [$link :: PredTerm (RowOf H)]
        (Context
          {λ [$r :: PredTerm (RowOf H)] (TanruAdmissible M H $r)}
          deps…)
  (∧ (H fills…) ($link fills…)) }
