; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: spec.md:663 fence 6; kind: expansion; sha1: 6be80bf36233d8ef8eb9d3f42fa805ffa51531b1
(DirectClause P) ≝
(λ {$e :: Referents Eventuality}
  {(Bind {$v1 :: T1} (Context) … {$vk :: Tk} (Context)
    {(P :p1 $v1 … :pk $vk :Eventuality $e)})})
