; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: spec.md:1830 fence 11; kind: specimen; sha1: 7a23a21f9446bb30dc1811a33f046f473b53c22f
; classification-note: Spec §5.6 explicitly marks this as a full-plural/library comparison with no baseline surface mapping; retained as a checked core term (#20).
; durable-issue: #20
; origin: core
; full-plural/library comparison only: ci gerku cu bajra .i ri tatpi
{Bind [$dogs :: Referents Entity]
        (SelectExactly 3 {λ [$x :: Entity] (gerku $x)})
  (Do (Assert (Close (bajra $dogs)))
      (Assert (Close (tatpi $dogs))))}
