; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: spec.md:628 fence 5; kind: schema; sha1: cb88a37f838407ab16037a3ec9f9d1e71d667826
; classification-note: schematic typed universal with an ellipsis body
(∀ (λ {$x $y :: Entity} {…}))
