; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: spec.md:3480 fence 20; kind: expansion; sha1: 088f873f9baadcb7a2c547adb7d6a6b08e8ac344
(NahiObjection t) ≝
  {Bind [$d :: DefectKind] (Context)
    (Express (Close (MetalinguisticallyDefective t $d)))}
