; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: spec.md:630 fence 5; kind: schema; sha1: ec12aedce7c517c0561463e3ce84640a9dbc6cbd
; classification-note: schematic typed universal with an ellipsis body
(∀ {λ [$x $y :: Entity] {…}})
