; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: spec.md:2032 fence 16; kind: expansion; sha1: dab522edf55f0c38c9afb4b6fa3f1000b57396c2
(Utterance {$u :: UtteranceToken} {fact…})
  ≝ (λ {$u :: Referents UtteranceToken} {(∧ fact…)})
