; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: spec.md:3396 fence 20; kind: expansion; sha1: 916298fc22f3806f19c9feb98b9bf460f29a859c
(NahiObjection t) ≝
  (Bind {$d :: DefectKind} (Context)
    {(Express (Close (MetalinguisticallyDefective t $d)))})
