; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: spec.md:1659 fence 14; kind: specimen; sha1: 54cca2029c04e08fb5a7fbe4a4e3646f60ff84d7
; origin: core
(Presuppose (∃ {λ [$x :: Entity] (∧ (prenu $x)
              (∃ {λ [$y :: Entity] (∧ (xasli $y) (Close (ponse $x $y)))}))})
  (∀ {λ [[$p :: Entity] [$d :: Referents Entity]]
    (→ (∧ (prenu $p)
          (Distrib {λ [$z :: Entity] (xasli $z)} $d)
          (Close (ponse $p $d)))
       (Close (darxi $p $d)))}))
