; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: spec.md:527 fence 2; kind: specimen; sha1: 7974b2da579099162cc037f3952c3de202434ae5
; klama fe ti tu        — x2 = ti, x3 = tu, x1 unfilled
(klama :2 This Yonder)
