; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: spec.md:1138 fence 10; kind: specimen; sha1: adf09e7b1524d4d7d299a629e334a159c4e1b33f
; the marked global strengthening (not the bare-PA default)
(= (Card (SetOf {λ [$x :: Entity] (∧ (gerku $x) (bajra $x))})) 3)
