; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: spec.md:3700 fence 21; kind: expansion; sha1: 3a75c4dd7394882ecd3293c678c3a6225317ce06
(JoiClause κ C D) ≝
  (λ {$j :: Referents Eventuality}
    {(∃ (λ {$e1 :: Referents Eventuality}
      {(∧ (C $e1)
          (∃ (λ {$e2 :: Referents Eventuality}
            {(∧ (D $e2)
                (CompleteGunmaAt κ $j (Combine $e1 $e2))
                (fasnu $j))})))}))})
