; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: spec.md:3609 fence 19; kind: specimen; sha1: a9c634f7bd73b38f2bdda307801f658a9257861d
; origin: surface
; rules: L5.21
; mi fa'u do tavla do fa'u mi
(ZipWith {λ [$s $l :: Referents Entity]
           (Close (tavla $s $l))}
  (List Speaker Audience)
  (List Audience Speaker))
; ≡ (∧ (Close (tavla Speaker Audience))
;      (Close (tavla Audience Speaker)))
