; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: spec.md:1685 fence 15; kind: expansion; sha1: 82601f947a97fb3a82f1f3e82149320b19b03a2d
((Tanru M H) fills…) ≝
(Bind {$link :: PredTerm ρ(H)}
        (Context
          (λ {$r :: PredTerm ρ(H)} {(TanruAdmissible M H $r)})
          deps…)
  {(∧ (H fills…) ($link fills…))})
