; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: spec.md:1146 fence 9; kind: specimen; sha1: 4da2df77645deee22f6ddfbb87b1418fa7bfecc5
; origin: surface
; rules: L5.2
; ci gerku cu bajra — the default (witness-set) reading
{Bind [$w :: Referents Entity]
        (SelectExactly 3 {λ [$x :: Entity] (gerku $x)})
  (Close (bajra $w))}
