; GENERATED by tools/smusni-redex/extract.rkt; do not edit.
; source: spec.md:522 fence 1; kind: specimen; sha1: e11b80722140960fac027e32c07ce60254e32614
; origin: surface
; rules: L1.1 L1.3
; mi klama ti
(klama Speaker This)
