-- Generated by build_m1_inventory.py from M1_CONSTRUCTOR_DISPOSITION.tsv.
-- Do not edit by hand.

namespace SmusniPilot

inductive Primitive where
  | application
  | index
  | lexicalPredication
  | natural
  | string
  | variable
  | add
  | lessThan
  | equal
  | actContent
  | admissibleCutoff
  | admissibleThreshold
  | aggregate
  | among
  | amountValue
  | answer
  | ask
  | assert
  | attachedAddress
  | attachedDisplay
  | audience
  | basisUnitAt
  | bind
  | card
  | closeClause
  | combine
  | context
  | contrast
  | contributesAt
  | currentToken
  | deictic
  | desire
  | do
  | doOOthers
  | dropPlace
  | during
  | enumerationOrdinal
  | eventOfContent
  | evidentialBasis
  | express
  | generic
  | happiness
  | hearsay
  | holds
  | host
  | inContext
  | innatelyCapable
  | intense
  | interpretAct
  | interpretContent
  | jaiRoleAdmissible
  | jeiRel
  | letteralSign
  | list
  | local
  | locutionOf
  | maAOthers
  | manyK
  | mention
  | metalinguisticallyDefective
  | miAOthers
  | mixAt
  | moderate
  | motionVector
  | named
  | nameSign
  | newTopic
  | niRel
  | now
  | observation
  | opaqueQuote
  | openQ
  | otherThan
  | peerUnitAt
  | perform
  | polar
  | presuppose
  | questionOf
  | realizedAct
  | realizedContent
  | realizedDiscourse
  | realizes
  | refer
  | reify
  | resume
  | scalar
  | selectAllBut
  | selectAtLeast
  | selectExactly
  | sentenceSign
  | set
  | setOf
  | shiftedGround
  | speaker
  | speakerOf
  | stateClause
  | structuredQuote
  | suhuRel
  | supplement
  | tanruAdmissible
  | teha
  | tooManyK
  | topicAdmissible
  | typical
  | unhappiness
  | vague
  | wordSign
  | not
  | multiply
  | divide
  | lambda
  | implies
  | iff
  | forall
  | exists
  | memberOf
  | subtract
  | and
  | or
  | lessOrEqual
  | xor
  deriving Repr, DecidableEq, BEq, Inhabited

def Primitive.name : Primitive → String
  | .application => "term:$application"
  | .index => "term:$index"
  | .lexicalPredication => "term:$lexical-predication"
  | .natural => "term:$natural"
  | .string => "term:$string"
  | .variable => "term:$variable"
  | .add => "term:+"
  | .lessThan => "term:<"
  | .equal => "term:="
  | .actContent => "term:ActContent"
  | .admissibleCutoff => "term:AdmissibleCutoff"
  | .admissibleThreshold => "term:AdmissibleThreshold"
  | .aggregate => "term:Aggregate"
  | .among => "term:Among"
  | .amountValue => "term:AmountValue"
  | .answer => "term:Answer"
  | .ask => "term:Ask"
  | .assert => "term:Assert"
  | .attachedAddress => "term:AttachedAddress"
  | .attachedDisplay => "term:AttachedDisplay"
  | .audience => "term:Audience"
  | .basisUnitAt => "term:BasisUnitAt"
  | .bind => "term:Bind"
  | .card => "term:Card"
  | .closeClause => "term:CloseClause"
  | .combine => "term:Combine"
  | .context => "term:Context"
  | .contrast => "term:Contrast"
  | .contributesAt => "term:ContributesAt"
  | .currentToken => "term:CurrentToken"
  | .deictic => "term:Deictic"
  | .desire => "term:Desire"
  | .do => "term:Do"
  | .doOOthers => "term:DoOOthers"
  | .dropPlace => "term:DropPlace"
  | .during => "term:During"
  | .enumerationOrdinal => "term:EnumerationOrdinal"
  | .eventOfContent => "term:EventOfContent"
  | .evidentialBasis => "term:EvidentialBasis"
  | .express => "term:Express"
  | .generic => "term:Generic"
  | .happiness => "term:Happiness"
  | .hearsay => "term:Hearsay"
  | .holds => "term:Holds"
  | .host => "term:Host"
  | .inContext => "term:InContext"
  | .innatelyCapable => "term:InnatelyCapable"
  | .intense => "term:Intense"
  | .interpretAct => "term:InterpretAct"
  | .interpretContent => "term:InterpretContent"
  | .jaiRoleAdmissible => "term:JaiRoleAdmissible"
  | .jeiRel => "term:JeiRel"
  | .letteralSign => "term:LetteralSign"
  | .list => "term:List"
  | .local => "term:Local"
  | .locutionOf => "term:LocutionOf"
  | .maAOthers => "term:MaAOthers"
  | .manyK => "term:ManyK"
  | .mention => "term:Mention"
  | .metalinguisticallyDefective => "term:MetalinguisticallyDefective"
  | .miAOthers => "term:MiAOthers"
  | .mixAt => "term:MixAt"
  | .moderate => "term:Moderate"
  | .motionVector => "term:MotionVector"
  | .named => "term:Named"
  | .nameSign => "term:NameSign"
  | .newTopic => "term:NewTopic"
  | .niRel => "term:NiRel"
  | .now => "term:Now"
  | .observation => "term:Observation"
  | .opaqueQuote => "term:OpaqueQuote"
  | .openQ => "term:OpenQ"
  | .otherThan => "term:OtherThan"
  | .peerUnitAt => "term:PeerUnitAt"
  | .perform => "term:Perform"
  | .polar => "term:Polar"
  | .presuppose => "term:Presuppose"
  | .questionOf => "term:QuestionOf"
  | .realizedAct => "term:RealizedAct"
  | .realizedContent => "term:RealizedContent"
  | .realizedDiscourse => "term:RealizedDiscourse"
  | .realizes => "term:Realizes"
  | .refer => "term:Refer"
  | .reify => "term:Reify"
  | .resume => "term:Resume"
  | .scalar => "term:Scalar"
  | .selectAllBut => "term:SelectAllBut"
  | .selectAtLeast => "term:SelectAtLeast"
  | .selectExactly => "term:SelectExactly"
  | .sentenceSign => "term:SentenceSign"
  | .set => "term:Set"
  | .setOf => "term:SetOf"
  | .shiftedGround => "term:ShiftedGround"
  | .speaker => "term:Speaker"
  | .speakerOf => "term:SpeakerOf"
  | .stateClause => "term:StateClause"
  | .structuredQuote => "term:StructuredQuote"
  | .suhuRel => "term:SuhuRel"
  | .supplement => "term:Supplement"
  | .tanruAdmissible => "term:TanruAdmissible"
  | .teha => "term:te'a"
  | .tooManyK => "term:TooManyK"
  | .topicAdmissible => "term:TopicAdmissible"
  | .typical => "term:Typical"
  | .unhappiness => "term:Unhappiness"
  | .vague => "term:Vague"
  | .wordSign => "term:WordSign"
  | .not => "term:¬"
  | .multiply => "term:×"
  | .divide => "term:÷"
  | .lambda => "term:λ"
  | .implies => "term:→"
  | .iff => "term:↔"
  | .forall => "term:∀"
  | .exists => "term:∃"
  | .memberOf => "term:∈"
  | .subtract => "term:−"
  | .and => "term:∧"
  | .or => "term:∨"
  | .lessOrEqual => "term:≤"
  | .xor => "term:⊕"

def Primitive.ofName : String → Option Primitive
  | "term:$application" => Option.some .application
  | "term:$index" => Option.some .index
  | "term:$lexical-predication" => Option.some .lexicalPredication
  | "term:$natural" => Option.some .natural
  | "term:$string" => Option.some .string
  | "term:$variable" => Option.some .variable
  | "term:+" => Option.some .add
  | "term:<" => Option.some .lessThan
  | "term:=" => Option.some .equal
  | "term:ActContent" => Option.some .actContent
  | "term:AdmissibleCutoff" => Option.some .admissibleCutoff
  | "term:AdmissibleThreshold" => Option.some .admissibleThreshold
  | "term:Aggregate" => Option.some .aggregate
  | "term:Among" => Option.some .among
  | "term:AmountValue" => Option.some .amountValue
  | "term:Answer" => Option.some .answer
  | "term:Ask" => Option.some .ask
  | "term:Assert" => Option.some .assert
  | "term:AttachedAddress" => Option.some .attachedAddress
  | "term:AttachedDisplay" => Option.some .attachedDisplay
  | "term:Audience" => Option.some .audience
  | "term:BasisUnitAt" => Option.some .basisUnitAt
  | "term:Bind" => Option.some .bind
  | "term:Card" => Option.some .card
  | "term:CloseClause" => Option.some .closeClause
  | "term:Combine" => Option.some .combine
  | "term:Context" => Option.some .context
  | "term:Contrast" => Option.some .contrast
  | "term:ContributesAt" => Option.some .contributesAt
  | "term:CurrentToken" => Option.some .currentToken
  | "term:Deictic" => Option.some .deictic
  | "term:Desire" => Option.some .desire
  | "term:Do" => Option.some .do
  | "term:DoOOthers" => Option.some .doOOthers
  | "term:DropPlace" => Option.some .dropPlace
  | "term:During" => Option.some .during
  | "term:EnumerationOrdinal" => Option.some .enumerationOrdinal
  | "term:EventOfContent" => Option.some .eventOfContent
  | "term:EvidentialBasis" => Option.some .evidentialBasis
  | "term:Express" => Option.some .express
  | "term:Generic" => Option.some .generic
  | "term:Happiness" => Option.some .happiness
  | "term:Hearsay" => Option.some .hearsay
  | "term:Holds" => Option.some .holds
  | "term:Host" => Option.some .host
  | "term:InContext" => Option.some .inContext
  | "term:InnatelyCapable" => Option.some .innatelyCapable
  | "term:Intense" => Option.some .intense
  | "term:InterpretAct" => Option.some .interpretAct
  | "term:InterpretContent" => Option.some .interpretContent
  | "term:JaiRoleAdmissible" => Option.some .jaiRoleAdmissible
  | "term:JeiRel" => Option.some .jeiRel
  | "term:LetteralSign" => Option.some .letteralSign
  | "term:List" => Option.some .list
  | "term:Local" => Option.some .local
  | "term:LocutionOf" => Option.some .locutionOf
  | "term:MaAOthers" => Option.some .maAOthers
  | "term:ManyK" => Option.some .manyK
  | "term:Mention" => Option.some .mention
  | "term:MetalinguisticallyDefective" => Option.some .metalinguisticallyDefective
  | "term:MiAOthers" => Option.some .miAOthers
  | "term:MixAt" => Option.some .mixAt
  | "term:Moderate" => Option.some .moderate
  | "term:MotionVector" => Option.some .motionVector
  | "term:Named" => Option.some .named
  | "term:NameSign" => Option.some .nameSign
  | "term:NewTopic" => Option.some .newTopic
  | "term:NiRel" => Option.some .niRel
  | "term:Now" => Option.some .now
  | "term:Observation" => Option.some .observation
  | "term:OpaqueQuote" => Option.some .opaqueQuote
  | "term:OpenQ" => Option.some .openQ
  | "term:OtherThan" => Option.some .otherThan
  | "term:PeerUnitAt" => Option.some .peerUnitAt
  | "term:Perform" => Option.some .perform
  | "term:Polar" => Option.some .polar
  | "term:Presuppose" => Option.some .presuppose
  | "term:QuestionOf" => Option.some .questionOf
  | "term:RealizedAct" => Option.some .realizedAct
  | "term:RealizedContent" => Option.some .realizedContent
  | "term:RealizedDiscourse" => Option.some .realizedDiscourse
  | "term:Realizes" => Option.some .realizes
  | "term:Refer" => Option.some .refer
  | "term:Reify" => Option.some .reify
  | "term:Resume" => Option.some .resume
  | "term:Scalar" => Option.some .scalar
  | "term:SelectAllBut" => Option.some .selectAllBut
  | "term:SelectAtLeast" => Option.some .selectAtLeast
  | "term:SelectExactly" => Option.some .selectExactly
  | "term:SentenceSign" => Option.some .sentenceSign
  | "term:Set" => Option.some .set
  | "term:SetOf" => Option.some .setOf
  | "term:ShiftedGround" => Option.some .shiftedGround
  | "term:Speaker" => Option.some .speaker
  | "term:SpeakerOf" => Option.some .speakerOf
  | "term:StateClause" => Option.some .stateClause
  | "term:StructuredQuote" => Option.some .structuredQuote
  | "term:SuhuRel" => Option.some .suhuRel
  | "term:Supplement" => Option.some .supplement
  | "term:TanruAdmissible" => Option.some .tanruAdmissible
  | "term:te'a" => Option.some .teha
  | "term:TooManyK" => Option.some .tooManyK
  | "term:TopicAdmissible" => Option.some .topicAdmissible
  | "term:Typical" => Option.some .typical
  | "term:Unhappiness" => Option.some .unhappiness
  | "term:Vague" => Option.some .vague
  | "term:WordSign" => Option.some .wordSign
  | "term:¬" => Option.some .not
  | "term:×" => Option.some .multiply
  | "term:÷" => Option.some .divide
  | "term:λ" => Option.some .lambda
  | "term:→" => Option.some .implies
  | "term:↔" => Option.some .iff
  | "term:∀" => Option.some .forall
  | "term:∃" => Option.some .exists
  | "term:∈" => Option.some .memberOf
  | "term:−" => Option.some .subtract
  | "term:∧" => Option.some .and
  | "term:∨" => Option.some .or
  | "term:≤" => Option.some .lessOrEqual
  | "term:⊕" => Option.some .xor
  | _ => Option.none

def Primitive.all : List Primitive := [
  .application,
  .index,
  .lexicalPredication,
  .natural,
  .string,
  .variable,
  .add,
  .lessThan,
  .equal,
  .actContent,
  .admissibleCutoff,
  .admissibleThreshold,
  .aggregate,
  .among,
  .amountValue,
  .answer,
  .ask,
  .assert,
  .attachedAddress,
  .attachedDisplay,
  .audience,
  .basisUnitAt,
  .bind,
  .card,
  .closeClause,
  .combine,
  .context,
  .contrast,
  .contributesAt,
  .currentToken,
  .deictic,
  .desire,
  .do,
  .doOOthers,
  .dropPlace,
  .during,
  .enumerationOrdinal,
  .eventOfContent,
  .evidentialBasis,
  .express,
  .generic,
  .happiness,
  .hearsay,
  .holds,
  .host,
  .inContext,
  .innatelyCapable,
  .intense,
  .interpretAct,
  .interpretContent,
  .jaiRoleAdmissible,
  .jeiRel,
  .letteralSign,
  .list,
  .local,
  .locutionOf,
  .maAOthers,
  .manyK,
  .mention,
  .metalinguisticallyDefective,
  .miAOthers,
  .mixAt,
  .moderate,
  .motionVector,
  .named,
  .nameSign,
  .newTopic,
  .niRel,
  .now,
  .observation,
  .opaqueQuote,
  .openQ,
  .otherThan,
  .peerUnitAt,
  .perform,
  .polar,
  .presuppose,
  .questionOf,
  .realizedAct,
  .realizedContent,
  .realizedDiscourse,
  .realizes,
  .refer,
  .reify,
  .resume,
  .scalar,
  .selectAllBut,
  .selectAtLeast,
  .selectExactly,
  .sentenceSign,
  .set,
  .setOf,
  .shiftedGround,
  .speaker,
  .speakerOf,
  .stateClause,
  .structuredQuote,
  .suhuRel,
  .supplement,
  .tanruAdmissible,
  .teha,
  .tooManyK,
  .topicAdmissible,
  .typical,
  .unhappiness,
  .vague,
  .wordSign,
  .not,
  .multiply,
  .divide,
  .lambda,
  .implies,
  .iff,
  .forall,
  .exists,
  .memberOf,
  .subtract,
  .and,
  .or,
  .lessOrEqual,
  .xor,
]

inductive SurfaceHead where
  | actualClause
  | additive
  | at
  | atLeast
  | atMost
  | canonicalAggregateAt
  | capableClause
  | cardBasis
  | clauseAnd
  | clauseIff
  | clauseImp
  | clauseNot
  | clauseOr
  | clauseXor
  | close
  | cOIExpress
  | completeGunmaAt
  | componentAt
  | componentsKappa
  | contextualAnswer
  | coRef
  | coveredBy
  | demonstratedClause
  | directClause
  | distrib
  | duhuRel
  | enough
  | every
  | exactly
  | few
  | fewerThan
  | gei
  | globalExactly
  | grade
  | groundedBy
  | gunmaAt
  | gunmaPredAt
  | interval
  | jaiPromote
  | jaiRaise
  | joiClause
  | joiEvent
  | joiGroup
  | joiPred
  | joiTanru
  | let
  | many
  | massify
  | maxRefer
  | meau0
  | meiRel
  | memberCover
  | mePred
  | metricBall
  | moreThan
  | most
  | nahiObjection
  | no
  | only
  | overlap
  | realized
  | reciprocate
  | regionComplement
  | roiClause
  | selectSome
  | sign
  | some
  | spanRegion
  | speakerDescribes
  | speakerDescribesUnaddressed
  | tanru
  | tanruLinkConnect
  | that
  | this
  | tooFew
  | tooMany
  | topic
  | unitSet
  | unrealizedClause
  | utterance
  | xi
  | yonder
  | zipWith
  | top
  deriving Repr, DecidableEq, BEq, Inhabited

def SurfaceHead.name : SurfaceHead → String
  | .actualClause => "term:ActualClause"
  | .additive => "term:Additive"
  | .at => "term:At"
  | .atLeast => "term:AtLeast"
  | .atMost => "term:AtMost"
  | .canonicalAggregateAt => "term:CanonicalAggregateAt"
  | .capableClause => "term:CapableClause"
  | .cardBasis => "term:CardBasis"
  | .clauseAnd => "term:ClauseAnd"
  | .clauseIff => "term:ClauseIff"
  | .clauseImp => "term:ClauseImp"
  | .clauseNot => "term:ClauseNot"
  | .clauseOr => "term:ClauseOr"
  | .clauseXor => "term:ClauseXor"
  | .close => "term:Close"
  | .cOIExpress => "term:COIExpress"
  | .completeGunmaAt => "term:CompleteGunmaAt"
  | .componentAt => "term:ComponentAt"
  | .componentsKappa => "term:components_κ"
  | .contextualAnswer => "term:ContextualAnswer"
  | .coRef => "term:CoRef"
  | .coveredBy => "term:CoveredBy"
  | .demonstratedClause => "term:DemonstratedClause"
  | .directClause => "term:DirectClause"
  | .distrib => "term:Distrib"
  | .duhuRel => "term:DuhuRel"
  | .enough => "term:Enough"
  | .every => "term:Every"
  | .exactly => "term:Exactly"
  | .few => "term:Few"
  | .fewerThan => "term:FewerThan"
  | .gei => "term:gei"
  | .globalExactly => "term:GlobalExactly"
  | .grade => "term:Grade"
  | .groundedBy => "term:GroundedBy"
  | .gunmaAt => "term:GunmaAt"
  | .gunmaPredAt => "term:GunmaPredAt"
  | .interval => "term:Interval"
  | .jaiPromote => "term:JaiPromote"
  | .jaiRaise => "term:JaiRaise"
  | .joiClause => "term:JoiClause"
  | .joiEvent => "term:JoiEvent"
  | .joiGroup => "term:JoiGroup"
  | .joiPred => "term:JoiPred"
  | .joiTanru => "term:JoiTanru"
  | .let => "term:Let"
  | .many => "term:Many"
  | .massify => "term:Massify"
  | .maxRefer => "term:MaxRefer"
  | .meau0 => "term:Meau0"
  | .meiRel => "term:MeiRel"
  | .memberCover => "term:MemberCover"
  | .mePred => "term:MePred"
  | .metricBall => "term:MetricBall"
  | .moreThan => "term:MoreThan"
  | .most => "term:Most"
  | .nahiObjection => "term:NahiObjection"
  | .no => "term:No"
  | .only => "term:Only"
  | .overlap => "term:Overlap"
  | .realized => "term:Realized"
  | .reciprocate => "term:Reciprocate"
  | .regionComplement => "term:RegionComplement"
  | .roiClause => "term:RoiClause"
  | .selectSome => "term:SelectSome"
  | .sign => "term:Sign"
  | .some => "term:Some"
  | .spanRegion => "term:SpanRegion"
  | .speakerDescribes => "term:SpeakerDescribes"
  | .speakerDescribesUnaddressed => "term:SpeakerDescribesUnaddressed"
  | .tanru => "term:Tanru"
  | .tanruLinkConnect => "term:TanruLinkConnect"
  | .that => "term:That"
  | .this => "term:This"
  | .tooFew => "term:TooFew"
  | .tooMany => "term:TooMany"
  | .topic => "term:Topic"
  | .unitSet => "term:UnitSet"
  | .unrealizedClause => "term:UnrealizedClause"
  | .utterance => "term:Utterance"
  | .xi => "term:xi"
  | .yonder => "term:Yonder"
  | .zipWith => "term:ZipWith"
  | .top => "term:⊤"

def SurfaceHead.ofName : String → Option SurfaceHead
  | "term:ActualClause" => Option.some .actualClause
  | "term:Additive" => Option.some .additive
  | "term:At" => Option.some .at
  | "term:AtLeast" => Option.some .atLeast
  | "term:AtMost" => Option.some .atMost
  | "term:CanonicalAggregateAt" => Option.some .canonicalAggregateAt
  | "term:CapableClause" => Option.some .capableClause
  | "term:CardBasis" => Option.some .cardBasis
  | "term:ClauseAnd" => Option.some .clauseAnd
  | "term:ClauseIff" => Option.some .clauseIff
  | "term:ClauseImp" => Option.some .clauseImp
  | "term:ClauseNot" => Option.some .clauseNot
  | "term:ClauseOr" => Option.some .clauseOr
  | "term:ClauseXor" => Option.some .clauseXor
  | "term:Close" => Option.some .close
  | "term:COIExpress" => Option.some .cOIExpress
  | "term:CompleteGunmaAt" => Option.some .completeGunmaAt
  | "term:ComponentAt" => Option.some .componentAt
  | "term:components_κ" => Option.some .componentsKappa
  | "term:ContextualAnswer" => Option.some .contextualAnswer
  | "term:CoRef" => Option.some .coRef
  | "term:CoveredBy" => Option.some .coveredBy
  | "term:DemonstratedClause" => Option.some .demonstratedClause
  | "term:DirectClause" => Option.some .directClause
  | "term:Distrib" => Option.some .distrib
  | "term:DuhuRel" => Option.some .duhuRel
  | "term:Enough" => Option.some .enough
  | "term:Every" => Option.some .every
  | "term:Exactly" => Option.some .exactly
  | "term:Few" => Option.some .few
  | "term:FewerThan" => Option.some .fewerThan
  | "term:gei" => Option.some .gei
  | "term:GlobalExactly" => Option.some .globalExactly
  | "term:Grade" => Option.some .grade
  | "term:GroundedBy" => Option.some .groundedBy
  | "term:GunmaAt" => Option.some .gunmaAt
  | "term:GunmaPredAt" => Option.some .gunmaPredAt
  | "term:Interval" => Option.some .interval
  | "term:JaiPromote" => Option.some .jaiPromote
  | "term:JaiRaise" => Option.some .jaiRaise
  | "term:JoiClause" => Option.some .joiClause
  | "term:JoiEvent" => Option.some .joiEvent
  | "term:JoiGroup" => Option.some .joiGroup
  | "term:JoiPred" => Option.some .joiPred
  | "term:JoiTanru" => Option.some .joiTanru
  | "term:Let" => Option.some .let
  | "term:Many" => Option.some .many
  | "term:Massify" => Option.some .massify
  | "term:MaxRefer" => Option.some .maxRefer
  | "term:Meau0" => Option.some .meau0
  | "term:MeiRel" => Option.some .meiRel
  | "term:MemberCover" => Option.some .memberCover
  | "term:MePred" => Option.some .mePred
  | "term:MetricBall" => Option.some .metricBall
  | "term:MoreThan" => Option.some .moreThan
  | "term:Most" => Option.some .most
  | "term:NahiObjection" => Option.some .nahiObjection
  | "term:No" => Option.some .no
  | "term:Only" => Option.some .only
  | "term:Overlap" => Option.some .overlap
  | "term:Realized" => Option.some .realized
  | "term:Reciprocate" => Option.some .reciprocate
  | "term:RegionComplement" => Option.some .regionComplement
  | "term:RoiClause" => Option.some .roiClause
  | "term:SelectSome" => Option.some .selectSome
  | "term:Sign" => Option.some .sign
  | "term:Some" => Option.some .some
  | "term:SpanRegion" => Option.some .spanRegion
  | "term:SpeakerDescribes" => Option.some .speakerDescribes
  | "term:SpeakerDescribesUnaddressed" => Option.some .speakerDescribesUnaddressed
  | "term:Tanru" => Option.some .tanru
  | "term:TanruLinkConnect" => Option.some .tanruLinkConnect
  | "term:That" => Option.some .that
  | "term:This" => Option.some .this
  | "term:TooFew" => Option.some .tooFew
  | "term:TooMany" => Option.some .tooMany
  | "term:Topic" => Option.some .topic
  | "term:UnitSet" => Option.some .unitSet
  | "term:UnrealizedClause" => Option.some .unrealizedClause
  | "term:Utterance" => Option.some .utterance
  | "term:xi" => Option.some .xi
  | "term:Yonder" => Option.some .yonder
  | "term:ZipWith" => Option.some .zipWith
  | "term:⊤" => Option.some .top
  | _ => Option.none

def SurfaceHead.all : List SurfaceHead := [
  .actualClause,
  .additive,
  .at,
  .atLeast,
  .atMost,
  .canonicalAggregateAt,
  .capableClause,
  .cardBasis,
  .clauseAnd,
  .clauseIff,
  .clauseImp,
  .clauseNot,
  .clauseOr,
  .clauseXor,
  .close,
  .cOIExpress,
  .completeGunmaAt,
  .componentAt,
  .componentsKappa,
  .contextualAnswer,
  .coRef,
  .coveredBy,
  .demonstratedClause,
  .directClause,
  .distrib,
  .duhuRel,
  .enough,
  .every,
  .exactly,
  .few,
  .fewerThan,
  .gei,
  .globalExactly,
  .grade,
  .groundedBy,
  .gunmaAt,
  .gunmaPredAt,
  .interval,
  .jaiPromote,
  .jaiRaise,
  .joiClause,
  .joiEvent,
  .joiGroup,
  .joiPred,
  .joiTanru,
  .let,
  .many,
  .massify,
  .maxRefer,
  .meau0,
  .meiRel,
  .memberCover,
  .mePred,
  .metricBall,
  .moreThan,
  .most,
  .nahiObjection,
  .no,
  .only,
  .overlap,
  .realized,
  .reciprocate,
  .regionComplement,
  .roiClause,
  .selectSome,
  .sign,
  .some,
  .spanRegion,
  .speakerDescribes,
  .speakerDescribesUnaddressed,
  .tanru,
  .tanruLinkConnect,
  .that,
  .this,
  .tooFew,
  .tooMany,
  .topic,
  .unitSet,
  .unrealizedClause,
  .utterance,
  .xi,
  .yonder,
  .zipWith,
  .top,
]

inductive TypeName where
  | sortAbstractNature
  | sortAchievement
  | sortActivity
  | sortAmount
  | sortBool
  | sortCardinal
  | sortConcept
  | sortEntity
  | sortEpistemology
  | sortEventuality
  | sortExperience
  | sortGround
  | sortLocation
  | sortLocution
  | sortNatural
  | sortNumber
  | sortProcess
  | sortProposition
  | sortQuestion
  | sortScale
  | sortSignToken
  | sortState
  | sortText
  | sortTime
  | sortTruthValue
  | sortUnit
  | sortUtteranceToken
  | groupBasisConstraint
  | typeFormAct
  | typeFormActOccurrence
  | typeFormCompatibleLabel
  | typeFormContrastDomain
  | typeFormContributionBasis
  | typeFormDecompositionBasis
  | typeFormEFn
  | typeFormFn
  | typeFormGroup
  | typeFormLabel
  | typeFormList
  | typeFormPerfComp
  | typeFormPredTerm
  | typeFormQuery
  | typeFormRecord
  | typeFormRefComp
  | typeFormReferents
  | typeFormRegion
  | typeFormRow
  | typeFormRowMinus
  | typeFormRowOf
  | typeFormSet
  | typeFormSign
  | typeFormSignToken
  | typeIndex
  | typeVariable
  | typeBasisKind
  | typeClauseContent
  | typeContent
  | typeDefectKind
  | typeDirection
  | typeDiscourse
  | typeEnumerationLevel
  | typeForce
  | typeGenericMode
  | typeIntensity
  | typeOccurrenceRole
  | typeProximity
  | typeScalarMode
  | typeTarget
  | typeThresholdKind
  | typeTopicResolution
  deriving Repr, DecidableEq, BEq, Inhabited

def TypeName.name : TypeName → String
  | .sortAbstractNature => "sort:AbstractNature"
  | .sortAchievement => "sort:Achievement"
  | .sortActivity => "sort:Activity"
  | .sortAmount => "sort:Amount"
  | .sortBool => "sort:Bool"
  | .sortCardinal => "sort:Cardinal"
  | .sortConcept => "sort:Concept"
  | .sortEntity => "sort:Entity"
  | .sortEpistemology => "sort:Epistemology"
  | .sortEventuality => "sort:Eventuality"
  | .sortExperience => "sort:Experience"
  | .sortGround => "sort:Ground"
  | .sortLocation => "sort:Location"
  | .sortLocution => "sort:Locution"
  | .sortNatural => "sort:Natural"
  | .sortNumber => "sort:Number"
  | .sortProcess => "sort:Process"
  | .sortProposition => "sort:Proposition"
  | .sortQuestion => "sort:Question"
  | .sortScale => "sort:Scale"
  | .sortSignToken => "sort:SignToken"
  | .sortState => "sort:State"
  | .sortText => "sort:Text"
  | .sortTime => "sort:Time"
  | .sortTruthValue => "sort:TruthValue"
  | .sortUnit => "sort:Unit"
  | .sortUtteranceToken => "sort:UtteranceToken"
  | .groupBasisConstraint => "term:GroupBasisConstraint"
  | .typeFormAct => "type-form:Act"
  | .typeFormActOccurrence => "type-form:ActOccurrence"
  | .typeFormCompatibleLabel => "type-form:CompatibleLabel"
  | .typeFormContrastDomain => "type-form:ContrastDomain"
  | .typeFormContributionBasis => "type-form:ContributionBasis"
  | .typeFormDecompositionBasis => "type-form:DecompositionBasis"
  | .typeFormEFn => "type-form:EFn"
  | .typeFormFn => "type-form:Fn"
  | .typeFormGroup => "type-form:Group"
  | .typeFormLabel => "type-form:Label"
  | .typeFormList => "type-form:List"
  | .typeFormPerfComp => "type-form:PerfComp"
  | .typeFormPredTerm => "type-form:PredTerm"
  | .typeFormQuery => "type-form:Query"
  | .typeFormRecord => "type-form:Record"
  | .typeFormRefComp => "type-form:RefComp"
  | .typeFormReferents => "type-form:Referents"
  | .typeFormRegion => "type-form:Region"
  | .typeFormRow => "type-form:Row"
  | .typeFormRowMinus => "type-form:RowMinus"
  | .typeFormRowOf => "type-form:RowOf"
  | .typeFormSet => "type-form:Set"
  | .typeFormSign => "type-form:Sign"
  | .typeFormSignToken => "type-form:SignToken"
  | .typeIndex => "type:$index"
  | .typeVariable => "type:$variable"
  | .typeBasisKind => "type:BasisKind"
  | .typeClauseContent => "type:ClauseContent"
  | .typeContent => "type:Content"
  | .typeDefectKind => "type:DefectKind"
  | .typeDirection => "type:Direction"
  | .typeDiscourse => "type:Discourse"
  | .typeEnumerationLevel => "type:EnumerationLevel"
  | .typeForce => "type:Force"
  | .typeGenericMode => "type:GenericMode"
  | .typeIntensity => "type:Intensity"
  | .typeOccurrenceRole => "type:OccurrenceRole"
  | .typeProximity => "type:Proximity"
  | .typeScalarMode => "type:ScalarMode"
  | .typeTarget => "type:Target"
  | .typeThresholdKind => "type:ThresholdKind"
  | .typeTopicResolution => "type:TopicResolution"

def TypeName.ofName : String → Option TypeName
  | "sort:AbstractNature" => Option.some .sortAbstractNature
  | "sort:Achievement" => Option.some .sortAchievement
  | "sort:Activity" => Option.some .sortActivity
  | "sort:Amount" => Option.some .sortAmount
  | "sort:Bool" => Option.some .sortBool
  | "sort:Cardinal" => Option.some .sortCardinal
  | "sort:Concept" => Option.some .sortConcept
  | "sort:Entity" => Option.some .sortEntity
  | "sort:Epistemology" => Option.some .sortEpistemology
  | "sort:Eventuality" => Option.some .sortEventuality
  | "sort:Experience" => Option.some .sortExperience
  | "sort:Ground" => Option.some .sortGround
  | "sort:Location" => Option.some .sortLocation
  | "sort:Locution" => Option.some .sortLocution
  | "sort:Natural" => Option.some .sortNatural
  | "sort:Number" => Option.some .sortNumber
  | "sort:Process" => Option.some .sortProcess
  | "sort:Proposition" => Option.some .sortProposition
  | "sort:Question" => Option.some .sortQuestion
  | "sort:Scale" => Option.some .sortScale
  | "sort:SignToken" => Option.some .sortSignToken
  | "sort:State" => Option.some .sortState
  | "sort:Text" => Option.some .sortText
  | "sort:Time" => Option.some .sortTime
  | "sort:TruthValue" => Option.some .sortTruthValue
  | "sort:Unit" => Option.some .sortUnit
  | "sort:UtteranceToken" => Option.some .sortUtteranceToken
  | "term:GroupBasisConstraint" => Option.some .groupBasisConstraint
  | "type-form:Act" => Option.some .typeFormAct
  | "type-form:ActOccurrence" => Option.some .typeFormActOccurrence
  | "type-form:CompatibleLabel" => Option.some .typeFormCompatibleLabel
  | "type-form:ContrastDomain" => Option.some .typeFormContrastDomain
  | "type-form:ContributionBasis" => Option.some .typeFormContributionBasis
  | "type-form:DecompositionBasis" => Option.some .typeFormDecompositionBasis
  | "type-form:EFn" => Option.some .typeFormEFn
  | "type-form:Fn" => Option.some .typeFormFn
  | "type-form:Group" => Option.some .typeFormGroup
  | "type-form:Label" => Option.some .typeFormLabel
  | "type-form:List" => Option.some .typeFormList
  | "type-form:PerfComp" => Option.some .typeFormPerfComp
  | "type-form:PredTerm" => Option.some .typeFormPredTerm
  | "type-form:Query" => Option.some .typeFormQuery
  | "type-form:Record" => Option.some .typeFormRecord
  | "type-form:RefComp" => Option.some .typeFormRefComp
  | "type-form:Referents" => Option.some .typeFormReferents
  | "type-form:Region" => Option.some .typeFormRegion
  | "type-form:Row" => Option.some .typeFormRow
  | "type-form:RowMinus" => Option.some .typeFormRowMinus
  | "type-form:RowOf" => Option.some .typeFormRowOf
  | "type-form:Set" => Option.some .typeFormSet
  | "type-form:Sign" => Option.some .typeFormSign
  | "type-form:SignToken" => Option.some .typeFormSignToken
  | "type:$index" => Option.some .typeIndex
  | "type:$variable" => Option.some .typeVariable
  | "type:BasisKind" => Option.some .typeBasisKind
  | "type:ClauseContent" => Option.some .typeClauseContent
  | "type:Content" => Option.some .typeContent
  | "type:DefectKind" => Option.some .typeDefectKind
  | "type:Direction" => Option.some .typeDirection
  | "type:Discourse" => Option.some .typeDiscourse
  | "type:EnumerationLevel" => Option.some .typeEnumerationLevel
  | "type:Force" => Option.some .typeForce
  | "type:GenericMode" => Option.some .typeGenericMode
  | "type:Intensity" => Option.some .typeIntensity
  | "type:OccurrenceRole" => Option.some .typeOccurrenceRole
  | "type:Proximity" => Option.some .typeProximity
  | "type:ScalarMode" => Option.some .typeScalarMode
  | "type:Target" => Option.some .typeTarget
  | "type:ThresholdKind" => Option.some .typeThresholdKind
  | "type:TopicResolution" => Option.some .typeTopicResolution
  | _ => Option.none

def TypeName.all : List TypeName := [
  .sortAbstractNature,
  .sortAchievement,
  .sortActivity,
  .sortAmount,
  .sortBool,
  .sortCardinal,
  .sortConcept,
  .sortEntity,
  .sortEpistemology,
  .sortEventuality,
  .sortExperience,
  .sortGround,
  .sortLocation,
  .sortLocution,
  .sortNatural,
  .sortNumber,
  .sortProcess,
  .sortProposition,
  .sortQuestion,
  .sortScale,
  .sortSignToken,
  .sortState,
  .sortText,
  .sortTime,
  .sortTruthValue,
  .sortUnit,
  .sortUtteranceToken,
  .groupBasisConstraint,
  .typeFormAct,
  .typeFormActOccurrence,
  .typeFormCompatibleLabel,
  .typeFormContrastDomain,
  .typeFormContributionBasis,
  .typeFormDecompositionBasis,
  .typeFormEFn,
  .typeFormFn,
  .typeFormGroup,
  .typeFormLabel,
  .typeFormList,
  .typeFormPerfComp,
  .typeFormPredTerm,
  .typeFormQuery,
  .typeFormRecord,
  .typeFormRefComp,
  .typeFormReferents,
  .typeFormRegion,
  .typeFormRow,
  .typeFormRowMinus,
  .typeFormRowOf,
  .typeFormSet,
  .typeFormSign,
  .typeFormSignToken,
  .typeIndex,
  .typeVariable,
  .typeBasisKind,
  .typeClauseContent,
  .typeContent,
  .typeDefectKind,
  .typeDirection,
  .typeDiscourse,
  .typeEnumerationLevel,
  .typeForce,
  .typeGenericMode,
  .typeIntensity,
  .typeOccurrenceRole,
  .typeProximity,
  .typeScalarMode,
  .typeTarget,
  .typeThresholdKind,
  .typeTopicResolution,
]

inductive GapHead where
  | familySelect
  | metatheoryBind
  | greaterThan
  | cOISchemasProse
  | klama
  | nahiObjectionProse
  deriving Repr, DecidableEq, BEq, Inhabited

def GapHead.name : GapHead → String
  | .familySelect => "family:Select"
  | .metatheoryBind => "metatheory:bind"
  | .greaterThan => "term:>"
  | .cOISchemasProse => "term:COI-schemas-prose"
  | .klama => "term:klama"
  | .nahiObjectionProse => "term:na'i-objection-prose"

def GapHead.ofName : String → Option GapHead
  | "family:Select" => Option.some .familySelect
  | "metatheory:bind" => Option.some .metatheoryBind
  | "term:>" => Option.some .greaterThan
  | "term:COI-schemas-prose" => Option.some .cOISchemasProse
  | "term:klama" => Option.some .klama
  | "term:na'i-objection-prose" => Option.some .nahiObjectionProse
  | _ => Option.none

def GapHead.all : List GapHead := [
  .familySelect,
  .metatheoryBind,
  .greaterThan,
  .cOISchemasProse,
  .klama,
  .nahiObjectionProse,
]

inductive ToolHead where
  | closeWith
  | quote
  | site
  | siteValue
  | syntax
  deriving Repr, DecidableEq, BEq, Inhabited

def ToolHead.name : ToolHead → String
  | .closeWith => "term:CloseWith"
  | .quote => "term:Quote"
  | .site => "term:Site"
  | .siteValue => "term:SiteValue"
  | .syntax => "term:Syntax"

def ToolHead.ofName : String → Option ToolHead
  | "term:CloseWith" => Option.some .closeWith
  | "term:Quote" => Option.some .quote
  | "term:Site" => Option.some .site
  | "term:SiteValue" => Option.some .siteValue
  | "term:Syntax" => Option.some .syntax
  | _ => Option.none

def ToolHead.all : List ToolHead := [
  .closeWith,
  .quote,
  .site,
  .siteValue,
  .syntax,
]

inductive HeadDisposition where
  | primitiveCore
  | definedSurface
  | typeIndexData
  | gapProseOnly
  | toolOnly
  deriving Repr, DecidableEq, BEq

def classifyHead (name : String) : Option HeadDisposition :=
  if (Primitive.ofName name).isSome then Option.some .primitiveCore
  else if (SurfaceHead.ofName name).isSome then Option.some .definedSurface
  else if (TypeName.ofName name).isSome then Option.some .typeIndexData
  else if (GapHead.ofName name).isSome then Option.some .gapProseOnly
  else if (ToolHead.ofName name).isSome then Option.some .toolOnly
  else Option.none

end SmusniPilot
