-- Generated by build_m2_inventory.py from the pinned M2 manifests.
-- Do not edit by hand.

namespace SmusniPilot

inductive M2DefinitionId where
  | d12ActualClause
  | d12AtLeast
  | d12AtMost
  | d12CanonicalAggregateAt
  | d12CoRef
  | d12Distrib
  | d12Every
  | d12Exactly
  | d12FewerThan
  | d12GlobalExactly
  | d12Grade
  | d12JaiRaise
  | d12Massify
  | d12MaxRefer
  | d12MoreThan
  | d12No
  | d12Overlap
  | d12Some
  | d12TooMany
  | d12ZipWith
  | d44Let
  | d46Close
  | d46DirectClause
  | d48CoveredBy
  | d49CompleteGunmaAt
  | d49GunmaAt
  | d53ReferMemberLift
  | d56SelectSome
  deriving Repr, DecidableEq, BEq

def M2DefinitionId.name : M2DefinitionId → String
  | .d12ActualClause => "D12.ActualClause"
  | .d12AtLeast => "D12.AtLeast"
  | .d12AtMost => "D12.AtMost"
  | .d12CanonicalAggregateAt => "D12.CanonicalAggregateAt"
  | .d12CoRef => "D12.CoRef"
  | .d12Distrib => "D12.Distrib"
  | .d12Every => "D12.Every"
  | .d12Exactly => "D12.Exactly"
  | .d12FewerThan => "D12.FewerThan"
  | .d12GlobalExactly => "D12.GlobalExactly"
  | .d12Grade => "D12.Grade"
  | .d12JaiRaise => "D12.JaiRaise"
  | .d12Massify => "D12.Massify"
  | .d12MaxRefer => "D12.MaxRefer"
  | .d12MoreThan => "D12.MoreThan"
  | .d12No => "D12.No"
  | .d12Overlap => "D12.Overlap"
  | .d12Some => "D12.Some"
  | .d12TooMany => "D12.TooMany"
  | .d12ZipWith => "D12.ZipWith"
  | .d44Let => "D4.4.Let"
  | .d46Close => "D4.6.Close"
  | .d46DirectClause => "D4.6.DirectClause"
  | .d48CoveredBy => "D4.8.CoveredBy"
  | .d49CompleteGunmaAt => "D4.9.CompleteGunmaAt"
  | .d49GunmaAt => "D4.9.GunmaAt"
  | .d53ReferMemberLift => "D5.3.Refer-member-lift"
  | .d56SelectSome => "D5.6.SelectSome"

def M2DefinitionId.all : List M2DefinitionId := [
  .d12ActualClause,
  .d12AtLeast,
  .d12AtMost,
  .d12CanonicalAggregateAt,
  .d12CoRef,
  .d12Distrib,
  .d12Every,
  .d12Exactly,
  .d12FewerThan,
  .d12GlobalExactly,
  .d12Grade,
  .d12JaiRaise,
  .d12Massify,
  .d12MaxRefer,
  .d12MoreThan,
  .d12No,
  .d12Overlap,
  .d12Some,
  .d12TooMany,
  .d12ZipWith,
  .d44Let,
  .d46Close,
  .d46DirectClause,
  .d48CoveredBy,
  .d49CompleteGunmaAt,
  .d49GunmaAt,
  .d53ReferMemberLift,
  .d56SelectSome,
]

inductive M2ClauseId where
  | d12ActualClauseActualEvent
  | d12AtLeastPositive
  | d12AtLeastZero
  | d12AtMostNegatedSuccessor
  | d12CanonicalAggregateAtAggregateAndCompleteGunma
  | d12CoRefMutualAmong
  | d12DistribUniversalMembers
  | d12EveryMaximalDistribution
  | d12ExactlyPositive
  | d12ExactlyZero
  | d12FewerThanNegatedAtLeast
  | d12GlobalExactlyComprehension
  | d12GradeRowDirected
  | d12JaiRaiseRaisedRole
  | d12JaiRaiseBareJaiMapping
  | d12MassifyCanonicalSelection
  | d12MaxReferInhabitedMaximalReference
  | d12MoreThanSuccessor
  | d12NoNegatedSome
  | d12OverlapCommonSubreference
  | d12SomeWitness
  | d12TooManyDependentThreshold
  | d12ZipWithEmpty
  | d12ZipWithPairedStep
  | d44LetBeta
  | d46CloseDirectEventExplicit
  | d46CloseDirectEventImplicit
  | d46CloseHoldingState
  | d46DirectClauseDefaultedEventProperty
  | d48CoveredByNoResidue
  | d49CompleteGunmaAtCompletePeerCover
  | d49GunmaAtBasisToPeerCover
  | d53ReferMemberLiftMemberLift
  | d56SelectSomeAtLeastOne
  deriving Repr, DecidableEq, BEq

def M2ClauseId.name : M2ClauseId → String
  | .d12ActualClauseActualEvent => "D12.ActualClause/actual-event"
  | .d12AtLeastPositive => "D12.AtLeast/positive"
  | .d12AtLeastZero => "D12.AtLeast/zero"
  | .d12AtMostNegatedSuccessor => "D12.AtMost/negated-successor"
  | .d12CanonicalAggregateAtAggregateAndCompleteGunma => "D12.CanonicalAggregateAt/aggregate-and-complete-gunma"
  | .d12CoRefMutualAmong => "D12.CoRef/mutual-among"
  | .d12DistribUniversalMembers => "D12.Distrib/universal-members"
  | .d12EveryMaximalDistribution => "D12.Every/maximal-distribution"
  | .d12ExactlyPositive => "D12.Exactly/positive"
  | .d12ExactlyZero => "D12.Exactly/zero"
  | .d12FewerThanNegatedAtLeast => "D12.FewerThan/negated-at-least"
  | .d12GlobalExactlyComprehension => "D12.GlobalExactly/comprehension"
  | .d12GradeRowDirected => "D12.Grade/row-directed"
  | .d12JaiRaiseRaisedRole => "D12.JaiRaise/raised-role"
  | .d12JaiRaiseBareJaiMapping => "D12.JaiRaise/bare-jai-mapping"
  | .d12MassifyCanonicalSelection => "D12.Massify/canonical-selection"
  | .d12MaxReferInhabitedMaximalReference => "D12.MaxRefer/inhabited-maximal-reference"
  | .d12MoreThanSuccessor => "D12.MoreThan/successor"
  | .d12NoNegatedSome => "D12.No/negated-some"
  | .d12OverlapCommonSubreference => "D12.Overlap/common-subreference"
  | .d12SomeWitness => "D12.Some/witness"
  | .d12TooManyDependentThreshold => "D12.TooMany/dependent-threshold"
  | .d12ZipWithEmpty => "D12.ZipWith/empty"
  | .d12ZipWithPairedStep => "D12.ZipWith/paired-step"
  | .d44LetBeta => "D4.4.Let/beta"
  | .d46CloseDirectEventExplicit => "D4.6.Close/direct-event-explicit"
  | .d46CloseDirectEventImplicit => "D4.6.Close/direct-event-implicit"
  | .d46CloseHoldingState => "D4.6.Close/holding-state"
  | .d46DirectClauseDefaultedEventProperty => "D4.6.DirectClause/defaulted-event-property"
  | .d48CoveredByNoResidue => "D4.8.CoveredBy/no-residue"
  | .d49CompleteGunmaAtCompletePeerCover => "D4.9.CompleteGunmaAt/complete-peer-cover"
  | .d49GunmaAtBasisToPeerCover => "D4.9.GunmaAt/basis-to-peer-cover"
  | .d53ReferMemberLiftMemberLift => "D5.3.Refer-member-lift/member-lift"
  | .d56SelectSomeAtLeastOne => "D5.6.SelectSome/at-least-one"

def M2ClauseId.all : List M2ClauseId := [
  .d12ActualClauseActualEvent,
  .d12AtLeastPositive,
  .d12AtLeastZero,
  .d12AtMostNegatedSuccessor,
  .d12CanonicalAggregateAtAggregateAndCompleteGunma,
  .d12CoRefMutualAmong,
  .d12DistribUniversalMembers,
  .d12EveryMaximalDistribution,
  .d12ExactlyPositive,
  .d12ExactlyZero,
  .d12FewerThanNegatedAtLeast,
  .d12GlobalExactlyComprehension,
  .d12GradeRowDirected,
  .d12JaiRaiseRaisedRole,
  .d12JaiRaiseBareJaiMapping,
  .d12MassifyCanonicalSelection,
  .d12MaxReferInhabitedMaximalReference,
  .d12MoreThanSuccessor,
  .d12NoNegatedSome,
  .d12OverlapCommonSubreference,
  .d12SomeWitness,
  .d12TooManyDependentThreshold,
  .d12ZipWithEmpty,
  .d12ZipWithPairedStep,
  .d44LetBeta,
  .d46CloseDirectEventExplicit,
  .d46CloseDirectEventImplicit,
  .d46CloseHoldingState,
  .d46DirectClauseDefaultedEventProperty,
  .d48CoveredByNoResidue,
  .d49CompleteGunmaAtCompletePeerCover,
  .d49GunmaAtBasisToPeerCover,
  .d53ReferMemberLiftMemberLift,
  .d56SelectSomeAtLeastOne,
]

inductive M2TypingRuleId where
  | a0Synth
  | a0Check
  | a0TNatural
  | a0TSpeaker
  | a0TAudience
  | a0TThresholdKind
  | a0TTop
  | a0TVariable
  | a0TLambdaPure
  | a0TLambdaEffectful
  | a0TLambdaMultiPure
  | a0TLambdaMultiEffectful
  | a0TLet
  | a0TBindNest
  | a0TBindReference
  | a0TBindPerformanceAct
  | a0TBindPerformanceComp
  | a0TBindPerformanceDiscourse
  | a0TCheckSynth
  | a0TContext
  | a0TVague
  | a0TReferReference
  | a0TReferMember
  | a0TSelectExactly
  | a0TSelectSome
  | a0TMassify
  | a0TPerform
  | a0TExactlyZero
  | a0TExactlyPositive
  | a0TNo
  | a0TMoreThan
  | a0TGlobalExactly
  | a0TTooMany
  | a0TAdmissibleThreshold
  | a0TCanonicalAggregateAt
  | a0TSetOf
  | a0TCard
  | a0TEquality
  | a0TAnd
  | a0TCoRef
  | a0TListCheck
  | a0TZipWithPure
  | a0TZipWithEmptyEffectful
  | a0TZipWithEffectful
  | a0TStateClause
  | a0TDirectClausePure
  | a0TDirectClauseEffectful
  | a0TActualClauseState
  | a0TActualClauseEventPure
  | a0TActualClauseEventEffectful
  | a0TCloseClause
  | a0TCloseWith
  | a0TApplyClauseContent
  | a0TApplyPure
  | a0TApplyEffectful
  | b1TSelectAtLeast
  | b1TSelectAllBut
  | b1TMaxRefer
  | b1TImplication
  | b1TNegation
  | b1TForall
  | b1TExists
  | b1TAmong
  | b1TPresupposeSynth
  | b1TPresupposeReference
  | b1TDistrib
  | b1TCoveredBy
  | b1TOverlap
  | b1TAddition
  | b1TAtLeastZero
  | b1TAtLeastPositive
  | b1TAtLeastSymbolic
  | b1TSome
  | b1TEvery
  | b1TAtMost
  | b1TFewerThanZero
  | b1TFewerThanPositive
  | b1TFewerThanSymbolic
  deriving Repr, DecidableEq, BEq

def M2TypingRuleId.name : M2TypingRuleId → String
  | .a0Synth => "A0-Synth"
  | .a0Check => "A0-Check"
  | .a0TNatural => "A0-T-Natural"
  | .a0TSpeaker => "A0-T-Speaker"
  | .a0TAudience => "A0-T-Audience"
  | .a0TThresholdKind => "A0-T-ThresholdKind"
  | .a0TTop => "A0-T-Top"
  | .a0TVariable => "A0-T-Variable"
  | .a0TLambdaPure => "A0-T-Lambda-Pure"
  | .a0TLambdaEffectful => "A0-T-Lambda-Effectful"
  | .a0TLambdaMultiPure => "A0-T-Lambda-Multi-Pure"
  | .a0TLambdaMultiEffectful => "A0-T-Lambda-Multi-Effectful"
  | .a0TLet => "A0-T-Let"
  | .a0TBindNest => "A0-T-Bind-Nest"
  | .a0TBindReference => "A0-T-Bind-Reference"
  | .a0TBindPerformanceAct => "A0-T-Bind-Performance-Act"
  | .a0TBindPerformanceComp => "A0-T-Bind-Performance-Comp"
  | .a0TBindPerformanceDiscourse => "A0-T-Bind-Performance-Discourse"
  | .a0TCheckSynth => "A0-T-Check-Synth"
  | .a0TContext => "A0-T-Context"
  | .a0TVague => "A0-T-Vague"
  | .a0TReferReference => "A0-T-Refer-Reference"
  | .a0TReferMember => "A0-T-Refer-Member"
  | .a0TSelectExactly => "A0-T-SelectExactly"
  | .a0TSelectSome => "A0-T-SelectSome"
  | .a0TMassify => "A0-T-Massify"
  | .a0TPerform => "A0-T-Perform"
  | .a0TExactlyZero => "A0-T-Exactly-Zero"
  | .a0TExactlyPositive => "A0-T-Exactly-Positive"
  | .a0TNo => "A0-T-No"
  | .a0TMoreThan => "A0-T-MoreThan"
  | .a0TGlobalExactly => "A0-T-GlobalExactly"
  | .a0TTooMany => "A0-T-TooMany"
  | .a0TAdmissibleThreshold => "A0-T-AdmissibleThreshold"
  | .a0TCanonicalAggregateAt => "A0-T-CanonicalAggregateAt"
  | .a0TSetOf => "A0-T-SetOf"
  | .a0TCard => "A0-T-Card"
  | .a0TEquality => "A0-T-Equality"
  | .a0TAnd => "A0-T-And"
  | .a0TCoRef => "A0-T-CoRef"
  | .a0TListCheck => "A0-T-List-Check"
  | .a0TZipWithPure => "A0-T-ZipWith-Pure"
  | .a0TZipWithEmptyEffectful => "A0-T-ZipWith-Empty-Effectful"
  | .a0TZipWithEffectful => "A0-T-ZipWith-Effectful"
  | .a0TStateClause => "A0-T-StateClause"
  | .a0TDirectClausePure => "A0-T-DirectClause-Pure"
  | .a0TDirectClauseEffectful => "A0-T-DirectClause-Effectful"
  | .a0TActualClauseState => "A0-T-ActualClause-State"
  | .a0TActualClauseEventPure => "A0-T-ActualClause-Event-Pure"
  | .a0TActualClauseEventEffectful => "A0-T-ActualClause-Event-Effectful"
  | .a0TCloseClause => "A0-T-CloseClause"
  | .a0TCloseWith => "A0-T-CloseWith"
  | .a0TApplyClauseContent => "A0-T-Apply-ClauseContent"
  | .a0TApplyPure => "A0-T-Apply-Pure"
  | .a0TApplyEffectful => "A0-T-Apply-Effectful"
  | .b1TSelectAtLeast => "B1-T-SelectAtLeast"
  | .b1TSelectAllBut => "B1-T-SelectAllBut"
  | .b1TMaxRefer => "B1-T-MaxRefer"
  | .b1TImplication => "B1-T-Implication"
  | .b1TNegation => "B1-T-Negation"
  | .b1TForall => "B1-T-Forall"
  | .b1TExists => "B1-T-Exists"
  | .b1TAmong => "B1-T-Among"
  | .b1TPresupposeSynth => "B1-T-Presuppose-Synth"
  | .b1TPresupposeReference => "B1-T-Presuppose-Reference"
  | .b1TDistrib => "B1-T-Distrib"
  | .b1TCoveredBy => "B1-T-CoveredBy"
  | .b1TOverlap => "B1-T-Overlap"
  | .b1TAddition => "B1-T-Addition"
  | .b1TAtLeastZero => "B1-T-AtLeast-Zero"
  | .b1TAtLeastPositive => "B1-T-AtLeast-Positive"
  | .b1TAtLeastSymbolic => "B1-T-AtLeast-Symbolic"
  | .b1TSome => "B1-T-Some"
  | .b1TEvery => "B1-T-Every"
  | .b1TAtMost => "B1-T-AtMost"
  | .b1TFewerThanZero => "B1-T-FewerThan-Zero"
  | .b1TFewerThanPositive => "B1-T-FewerThan-Positive"
  | .b1TFewerThanSymbolic => "B1-T-FewerThan-Symbolic"

def M2TypingRuleId.all : List M2TypingRuleId := [
  .a0Synth,
  .a0Check,
  .a0TNatural,
  .a0TSpeaker,
  .a0TAudience,
  .a0TThresholdKind,
  .a0TTop,
  .a0TVariable,
  .a0TLambdaPure,
  .a0TLambdaEffectful,
  .a0TLambdaMultiPure,
  .a0TLambdaMultiEffectful,
  .a0TLet,
  .a0TBindNest,
  .a0TBindReference,
  .a0TBindPerformanceAct,
  .a0TBindPerformanceComp,
  .a0TBindPerformanceDiscourse,
  .a0TCheckSynth,
  .a0TContext,
  .a0TVague,
  .a0TReferReference,
  .a0TReferMember,
  .a0TSelectExactly,
  .a0TSelectSome,
  .a0TMassify,
  .a0TPerform,
  .a0TExactlyZero,
  .a0TExactlyPositive,
  .a0TNo,
  .a0TMoreThan,
  .a0TGlobalExactly,
  .a0TTooMany,
  .a0TAdmissibleThreshold,
  .a0TCanonicalAggregateAt,
  .a0TSetOf,
  .a0TCard,
  .a0TEquality,
  .a0TAnd,
  .a0TCoRef,
  .a0TListCheck,
  .a0TZipWithPure,
  .a0TZipWithEmptyEffectful,
  .a0TZipWithEffectful,
  .a0TStateClause,
  .a0TDirectClausePure,
  .a0TDirectClauseEffectful,
  .a0TActualClauseState,
  .a0TActualClauseEventPure,
  .a0TActualClauseEventEffectful,
  .a0TCloseClause,
  .a0TCloseWith,
  .a0TApplyClauseContent,
  .a0TApplyPure,
  .a0TApplyEffectful,
  .b1TSelectAtLeast,
  .b1TSelectAllBut,
  .b1TMaxRefer,
  .b1TImplication,
  .b1TNegation,
  .b1TForall,
  .b1TExists,
  .b1TAmong,
  .b1TPresupposeSynth,
  .b1TPresupposeReference,
  .b1TDistrib,
  .b1TCoveredBy,
  .b1TOverlap,
  .b1TAddition,
  .b1TAtLeastZero,
  .b1TAtLeastPositive,
  .b1TAtLeastSymbolic,
  .b1TSome,
  .b1TEvery,
  .b1TAtMost,
  .b1TFewerThanZero,
  .b1TFewerThanPositive,
  .b1TFewerThanSymbolic,
]

inductive M2GrammarCategory where
  | type
  | direction
  | r
  | t
  | rowDeclaration
  | dep
  | role
  deriving Repr, DecidableEq, BEq

def M2GrammarCategory.name : M2GrammarCategory → String
  | .type => "τ"
  | .direction => "direction"
  | .r => "R"
  | .t => "t"
  | .rowDeclaration => "ρdecl"
  | .dep => "dep"
  | .role => "role"

def M2GrammarCategory.all : List M2GrammarCategory := [
  .type,
  .direction,
  .r,
  .t,
  .rowDeclaration,
  .dep,
  .role,
]

structure SourceRange where
  start : Nat
  stop : Nat
  deriving Repr, DecidableEq, BEq

inductive M2DefinitionSelection where
  | definitionPortState
  | planV2Extra
  | dependencyClosure
  deriving Repr, DecidableEq, BEq

structure M2DefinitionRecord where
  id : M2DefinitionId
  head : String
  selection : M2DefinitionSelection
  portState : String
  dependencies : List String
  clauses : List M2ClauseId
  selectedDomains : List String
  specRanges : List SourceRange
  equationRanges : List SourceRange
  specDigest : String
  equationDigest : String
  supplementKind : Option String
  deriving Repr, DecidableEq, BEq

def M2DefinitionId.record : M2DefinitionId → M2DefinitionRecord
  | .d12ActualClause => {
      id := .d12ActualClause
      head := "ActualClause"
      selection := .dependencyClosure
      portState := "none"
      dependencies := ["StateClause", "fasnu"]
      clauses := [.d12ActualClauseActualEvent]
      selectedDomains := []
      specRanges := [{ start := 3728, stop := 3741 }]
      equationRanges := [{ start := 3734, stop := 3735 }]
      specDigest := "114ba3296c3329ea84daa83d1a6ed0d8077cfb9514f2ed539b6d7651da8beef2"
      equationDigest := "01bc1f971b000f5b5b552524750498780991592d3e07059d24e3f62a22d48e1b"
      supplementKind := some "definition"
    }
  | .d12AtLeast => {
      id := .d12AtLeast
      head := "AtLeast"
      selection := .definitionPortState
      portState := "ported"
      dependencies := ["Bind", "SelectAtLeast"]
      clauses := [.d12AtLeastPositive, .d12AtLeastZero]
      selectedDomains := []
      specRanges := [{ start := 3405, stop := 3405 }, { start := 3422, stop := 3429 }]
      equationRanges := [{ start := 3405, stop := 3405 }, { start := 3429, stop := 3429 }]
      specDigest := "cad25d744a9f26b2788d2b5b352cf4a92f64ccff9df521654f415fd6b5418a44"
      equationDigest := "678a2e02001dc873fed97c71ce33ab6267dfe0c47cc3045d0b72d3978d67ce99"
      supplementKind := none
    }
  | .d12AtMost => {
      id := .d12AtMost
      head := "AtMost"
      selection := .definitionPortState
      portState := "ported"
      dependencies := ["¬", "AtLeast", "+"]
      clauses := [.d12AtMostNegatedSuccessor]
      selectedDomains := []
      specRanges := [{ start := 3413, stop := 3413 }]
      equationRanges := [{ start := 3413, stop := 3413 }]
      specDigest := "56d07487632f54b136f72dd54c6813031a74cb88b1213e323ded180face92404"
      equationDigest := "56d07487632f54b136f72dd54c6813031a74cb88b1213e323ded180face92404"
      supplementKind := none
    }
  | .d12CanonicalAggregateAt => {
      id := .d12CanonicalAggregateAt
      head := "CanonicalAggregateAt"
      selection := .dependencyClosure
      portState := "none"
      dependencies := ["Aggregate", "CompleteGunmaAt"]
      clauses := [.d12CanonicalAggregateAtAggregateAndCompleteGunma]
      selectedDomains := []
      specRanges := [{ start := 3558, stop := 3571 }]
      equationRanges := [{ start := 3562, stop := 3563 }]
      specDigest := "d5efb742b3289b80fd49de807eec104dc0fbeafa69ac6523f25e7bc03d835bf1"
      equationDigest := "15fda3225ab825817bea9675feece972c72157fc2cf80141d3b4e64a79cff21a"
      supplementKind := some "definition"
    }
  | .d12CoRef => {
      id := .d12CoRef
      head := "CoRef"
      selection := .dependencyClosure
      portState := "none"
      dependencies := ["Among"]
      clauses := [.d12CoRefMutualAmong]
      selectedDomains := []
      specRanges := [{ start := 3643, stop := 3650 }]
      equationRanges := [{ start := 3646, stop := 3646 }]
      specDigest := "28e8f0e85a1f67fb0feb12d656532547f4deb488199680f4d7989be9a83218ca"
      equationDigest := "c35affe506631c01fae26c01dfbf7b2424c64085548820de272201af682f5fa7"
      supplementKind := some "definition"
    }
  | .d12Distrib => {
      id := .d12Distrib
      head := "Distrib"
      selection := .definitionPortState
      portState := "ported"
      dependencies := ["∀", "λ", "→", "Among"]
      clauses := [.d12DistribUniversalMembers]
      selectedDomains := []
      specRanges := [{ start := 3417, stop := 3419 }]
      equationRanges := [{ start := 3417, stop := 3417 }]
      specDigest := "05fc1e6d340ee2201ea74c61bfbc97c4d0e7d33b6df12fdbf7a4ba2089e01506"
      equationDigest := "7fb9ae1f51b7db97f144fd37539d0987e732c31e0dfe0df9d83e7e316672a7d4"
      supplementKind := none
    }
  | .d12Every => {
      id := .d12Every
      head := "Every"
      selection := .definitionPortState
      portState := "ported"
      dependencies := ["Bind", "MaxRefer", "Distrib"]
      clauses := [.d12EveryMaximalDistribution]
      selectedDomains := []
      specRanges := [{ start := 3407, stop := 3411 }]
      equationRanges := [{ start := 3407, stop := 3408 }]
      specDigest := "2d405cfde7bc52a9e889716bfaf001e194a0cc8eb24aa35476dcfbb0de901e35"
      equationDigest := "3e2a76a2e6860795c27e59225d45bb585dc17dec291463e95fd4c3c8e4f2c78a"
      supplementKind := none
    }
  | .d12Exactly => {
      id := .d12Exactly
      head := "Exactly"
      selection := .definitionPortState
      portState := "a0"
      dependencies := ["Bind", "SelectExactly", "No"]
      clauses := [.d12ExactlyPositive, .d12ExactlyZero]
      selectedDomains := []
      specRanges := [{ start := 3404, stop := 3404 }, { start := 3422, stop := 3430 }]
      equationRanges := [{ start := 3404, stop := 3404 }, { start := 3430, stop := 3430 }]
      specDigest := "1230d6330f6a1ae3b93503aaf55ad590393e50cfdb717b9945d982fecd834c48"
      equationDigest := "0a6c858f8095b47b2683d608b94492814376d50822381f32f2ee8c43624e7613"
      supplementKind := none
    }
  | .d12FewerThan => {
      id := .d12FewerThan
      head := "FewerThan"
      selection := .definitionPortState
      portState := "ported"
      dependencies := ["¬", "AtLeast"]
      clauses := [.d12FewerThanNegatedAtLeast]
      selectedDomains := []
      specRanges := [{ start := 3415, stop := 3415 }]
      equationRanges := [{ start := 3415, stop := 3415 }]
      specDigest := "4e590662af30baeefec4c2f5369dd44fd0f38ac0f137a8f3dca4e3ed9eaabf8e"
      equationDigest := "4e590662af30baeefec4c2f5369dd44fd0f38ac0f137a8f3dca4e3ed9eaabf8e"
      supplementKind := none
    }
  | .d12GlobalExactly => {
      id := .d12GlobalExactly
      head := "GlobalExactly"
      selection := .definitionPortState
      portState := "a0"
      dependencies := ["=", "Card", "SetOf", "λ", "∧"]
      clauses := [.d12GlobalExactlyComprehension]
      selectedDomains := []
      specRanges := [{ start := 3416, stop := 3416 }]
      equationRanges := [{ start := 3416, stop := 3416 }]
      specDigest := "ca85dfdabba93858a3003958ac06565a244e5e5e666b36f53cd217e4c41649f4"
      equationDigest := "ca85dfdabba93858a3003958ac06565a244e5e5e666b36f53cd217e4c41649f4"
      supplementKind := none
    }
  | .d12Grade => {
      id := .d12Grade
      head := "Grade"
      selection := .planV2Extra
      portState := "none"
      dependencies := ["InRegion"]
      clauses := [.d12GradeRowDirected]
      selectedDomains := []
      specRanges := [{ start := 1901, stop := 1917 }, { start := 3488, stop := 3509 }]
      equationRanges := [{ start := 3504, stop := 3505 }]
      specDigest := "3cf2dcc1f2468b7c33a14905b818154402e2da4d0c692ba1d9b0b3a1767203de"
      equationDigest := "ba9e522eaf9f56cd6632f2137ba9398d29d00b1b8b023d0fbc7850daeef1635a"
      supplementKind := some "schema"
    }
  | .d12JaiRaise => {
      id := .d12JaiRaise
      head := "JaiRaise"
      selection := .planV2Extra
      portState := "none"
      dependencies := ["PredTerm", "JaiRoleAdmissible"]
      clauses := [.d12JaiRaiseRaisedRole, .d12JaiRaiseBareJaiMapping]
      selectedDomains := []
      specRanges := [{ start := 3316, stop := 3321 }, { start := 3769, stop := 3808 }]
      equationRanges := [{ start := 3785, stop := 3788 }, { start := 3795, stop := 3802 }]
      specDigest := "57f43c30afdac7265c66a455499629e382b5d2b3044c78f800174863d1268b76"
      equationDigest := "2330e0c3595d2a794df9d999a4cd5a40461f2a315a577874cd0e8bf108f1803f"
      supplementKind := some "schema-mapping"
    }
  | .d12Massify => {
      id := .d12Massify
      head := "Massify"
      selection := .definitionPortState
      portState := "a0"
      dependencies := ["SelectExactly", "λ", "CanonicalAggregateAt"]
      clauses := [.d12MassifyCanonicalSelection]
      selectedDomains := []
      specRanges := [{ start := 3565, stop := 3567 }]
      equationRanges := [{ start := 3565, stop := 3567 }]
      specDigest := "7d3a375f2b90878fde97d04b11e0585d2a78a7aa0a8486a1db9e3e88004b1b47"
      equationDigest := "7d3a375f2b90878fde97d04b11e0585d2a78a7aa0a8486a1db9e3e88004b1b47"
      supplementKind := none
    }
  | .d12MaxRefer => {
      id := .d12MaxRefer
      head := "MaxRefer"
      selection := .definitionPortState
      portState := "ported"
      dependencies := ["Presuppose", "∃", "Refer", "λ", "∧", "CoveredBy", "∀", "→", "Among"]
      clauses := [.d12MaxReferInhabitedMaximalReference]
      selectedDomains := []
      specRanges := [{ start := 3650, stop := 3661 }]
      equationRanges := [{ start := 3650, stop := 3654 }]
      specDigest := "a1dcc212677ff270f90b1f551996305450fff289faaccc631a0733f9dc4ba1df"
      equationDigest := "938b551803291b47dedba24085ba223d908f3d54d26ee7d5a1f7a473c6360713"
      supplementKind := none
    }
  | .d12MoreThan => {
      id := .d12MoreThan
      head := "MoreThan"
      selection := .definitionPortState
      portState := "ported"
      dependencies := ["AtLeast", "+"]
      clauses := [.d12MoreThanSuccessor]
      selectedDomains := []
      specRanges := [{ start := 3414, stop := 3414 }]
      equationRanges := [{ start := 3414, stop := 3414 }]
      specDigest := "3fb608e1fecd71d8cba57299d14d97ad9ba3a484364fc5c7cee4e8a1c0b0c4d8"
      equationDigest := "3fb608e1fecd71d8cba57299d14d97ad9ba3a484364fc5c7cee4e8a1c0b0c4d8"
      supplementKind := none
    }
  | .d12No => {
      id := .d12No
      head := "No"
      selection := .definitionPortState
      portState := "ported"
      dependencies := ["¬", "Some"]
      clauses := [.d12NoNegatedSome]
      selectedDomains := []
      specRanges := [{ start := 3412, stop := 3412 }]
      equationRanges := [{ start := 3412, stop := 3412 }]
      specDigest := "d5936bcde4883638b992c9fa92b81cb1bd278df971db4d3d29f9189ad951c59e"
      equationDigest := "d5936bcde4883638b992c9fa92b81cb1bd278df971db4d3d29f9189ad951c59e"
      supplementKind := none
    }
  | .d12Overlap => {
      id := .d12Overlap
      head := "Overlap"
      selection := .definitionPortState
      portState := "ported"
      dependencies := ["∃", "λ", "∧", "Among"]
      clauses := [.d12OverlapCommonSubreference]
      selectedDomains := []
      specRanges := [{ start := 3605, stop := 3605 }]
      equationRanges := [{ start := 3605, stop := 3605 }]
      specDigest := "98d11e3cc60624a2ed90c131d50912acb076abffbed198e77851f12e8cad0776"
      equationDigest := "98d11e3cc60624a2ed90c131d50912acb076abffbed198e77851f12e8cad0776"
      supplementKind := none
    }
  | .d12Some => {
      id := .d12Some
      head := "Some"
      selection := .definitionPortState
      portState := "ported"
      dependencies := ["Bind", "SelectSome"]
      clauses := [.d12SomeWitness]
      selectedDomains := []
      specRanges := [{ start := 3406, stop := 3406 }]
      equationRanges := [{ start := 3406, stop := 3406 }]
      specDigest := "010ec8c5f2e90a24a2bf52925ba31025ee254ae167df69061de32507598ef82e"
      equationDigest := "010ec8c5f2e90a24a2bf52925ba31025ee254ae167df69061de32507598ef82e"
      supplementKind := none
    }
  | .d12TooMany => {
      id := .d12TooMany
      head := "TooMany"
      selection := .definitionPortState
      portState := "a0"
      dependencies := ["Bind", "Context", "Vague", "AdmissibleThreshold", "MoreThan"]
      clauses := [.d12TooManyDependentThreshold]
      selectedDomains := []
      specRanges := [{ start := 3477, stop := 3479 }]
      equationRanges := [{ start := 3477, stop := 3479 }]
      specDigest := "a9b7601d7bf15bbe59540873990be50c62cea2144ccab7ec82ac51f8c46e63b5"
      equationDigest := "a9b7601d7bf15bbe59540873990be50c62cea2144ccab7ec82ac51f8c46e63b5"
      supplementKind := none
    }
  | .d12ZipWith => {
      id := .d12ZipWith
      head := "ZipWith"
      selection := .definitionPortState
      portState := "a0"
      dependencies := ["∧", "List"]
      clauses := [.d12ZipWithEmpty, .d12ZipWithPairedStep]
      selectedDomains := ["equal-length"]
      specRanges := [{ start := 3622, stop := 3628 }]
      equationRanges := [{ start := 3626, stop := 3628 }]
      specDigest := "2582167bdebae0b1a0da94a78d5ad356a9e74baa4da9ef5a3ab586f082360e28"
      equationDigest := "a5f3ab596f8a016c989b3015ae4da31c8f93253f2a192273b80fef204912c937"
      supplementKind := none
    }
  | .d44Let => {
      id := .d44Let
      head := "Let"
      selection := .definitionPortState
      portState := "a0"
      dependencies := ["λ"]
      clauses := [.d44LetBeta]
      selectedDomains := []
      specRanges := [{ start := 613, stop := 615 }]
      equationRanges := [{ start := 615, stop := 615 }]
      specDigest := "05ef09f9d3e14436471ebbfb26eb4d37d0bce8fe0ade7576b3bcd75082ee10a2"
      equationDigest := "1d05667b2a11b54d987a23c68a9a1fc4d757f0ae5ac6346e65f8e42966f5101d"
      supplementKind := none
    }
  | .d46Close => {
      id := .d46Close
      head := "Close"
      selection := .definitionPortState
      portState := "a0"
      dependencies := ["CloseClause", "ActualClause", "DirectClause"]
      clauses := [.d46CloseDirectEventExplicit, .d46CloseDirectEventImplicit, .d46CloseHoldingState]
      selectedDomains := []
      specRanges := [{ start := 699, stop := 713 }]
      equationRanges := [{ start := 703, stop := 704 }, { start := 706, stop := 709 }, { start := 711, stop := 712 }]
      specDigest := "925d6b638fe27aa1a1e06bff5bc2b75392c505a9596023bc8a17f77310d17476"
      equationDigest := "1a5024f1978bfc8fc6866a776468db34eb74ea609468759e204504b89c6fd9c6"
      supplementKind := some "definition"
    }
  | .d46DirectClause => {
      id := .d46DirectClause
      head := "DirectClause"
      selection := .dependencyClosure
      portState := "none"
      dependencies := ["Bind", "Context", "StateClause"]
      clauses := [.d46DirectClauseDefaultedEventProperty]
      selectedDomains := []
      specRanges := [{ start := 652, stop := 680 }]
      equationRanges := [{ start := 671, stop := 674 }]
      specDigest := "312ceb30e7f4816c14b9cb4af08ae1ca3c1c708891eada707e5fc64e64b541a7"
      equationDigest := "bdaa049d7b930b3957e0e435c38a481ba40c74953a820cdcb96ca6ee31148849"
      supplementKind := some "schema"
    }
  | .d48CoveredBy => {
      id := .d48CoveredBy
      head := "CoveredBy"
      selection := .definitionPortState
      portState := "ported"
      dependencies := ["∧", "Distrib", "∀", "λ", "→", "Among", "∃", "Overlap"]
      clauses := [.d48CoveredByNoResidue]
      selectedDomains := []
      specRanges := [{ start := 808, stop := 817 }]
      equationRanges := [{ start := 812, stop := 817 }]
      specDigest := "d274dd5d6df6cbe272866c81f5ff9552e648b52845f0902c55be66c9b10a5d86"
      equationDigest := "119fa557a7a1fa02505e4a4852ed971dc1c77647ecd8bb4db3316a319730a0ce"
      supplementKind := none
    }
  | .d49CompleteGunmaAt => {
      id := .d49CompleteGunmaAt
      head := "CompleteGunmaAt"
      selection := .dependencyClosure
      portState := "none"
      dependencies := ["GunmaAt", "PeerUnitAt", "BasisUnitAt"]
      clauses := [.d49CompleteGunmaAtCompletePeerCover]
      selectedDomains := []
      specRanges := [{ start := 963, stop := 977 }]
      equationRanges := [{ start := 972, stop := 974 }]
      specDigest := "9c0c9114c69d4ebb9cfbdb1716f0db4225b13259d4819aa1edd62bd06f57c6f3"
      equationDigest := "d44ad90034390d0f162e9167ab535d3cfc2188d3453410fc47ae994d611bd286"
      supplementKind := some "definition"
    }
  | .d49GunmaAt => {
      id := .d49GunmaAt
      head := "GunmaAt"
      selection := .dependencyClosure
      portState := "none"
      dependencies := ["PeerUnitAt", "BasisUnitAt", "CoRef"]
      clauses := [.d49GunmaAtBasisToPeerCover]
      selectedDomains := []
      specRanges := [{ start := 963, stop := 977 }]
      equationRanges := [{ start := 968, stop := 970 }]
      specDigest := "9c0c9114c69d4ebb9cfbdb1716f0db4225b13259d4819aa1edd62bd06f57c6f3"
      equationDigest := "0d719677199b2a74789f78ff32c7da32f265a1d9f443b059d03d956ced96fe2f"
      supplementKind := some "definition"
    }
  | .d53ReferMemberLift => {
      id := .d53ReferMemberLift
      head := "Refer"
      selection := .planV2Extra
      portState := "none"
      dependencies := ["CoveredBy"]
      clauses := [.d53ReferMemberLiftMemberLift]
      selectedDomains := []
      specRanges := [{ start := 1452, stop := 1466 }]
      equationRanges := [{ start := 1454, stop := 1455 }]
      specDigest := "9892b13a0fd9b39beaebcf098ad2ca6c45a124030c1f773ab50f8c057b28105f"
      equationDigest := "5e8deb7adaccc5cee07a08ca2c3f66ef728a9b3151091c051b3162224f7c8d76"
      supplementKind := some "domain-overload"
    }
  | .d56SelectSome => {
      id := .d56SelectSome
      head := "SelectSome"
      selection := .definitionPortState
      portState := "ported"
      dependencies := ["SelectAtLeast"]
      clauses := [.d56SelectSomeAtLeastOne]
      selectedDomains := []
      specRanges := [{ start := 1563, stop := 1566 }]
      equationRanges := [{ start := 1566, stop := 1566 }]
      specDigest := "9b1b8b5abe9405f056667e083929a3d2933d2f4d9bafdaa9cf27db2eba51456c"
      equationDigest := "5ed705e778744900b30a691d7ece68d344ed55fc318f9eb8ecd10f45cdbd7a21"
      supplementKind := none
    }

def m2DefinitionRecords : List M2DefinitionRecord :=
  M2DefinitionId.all.map M2DefinitionId.record

structure M2TypingRuleRecord where
  id : M2TypingRuleId
  anchor : String
  sourceRange : SourceRange
  sourceDigest : String
  conclusion : String
  deriving Repr, DecidableEq, BEq

def M2TypingRuleId.record : M2TypingRuleId → M2TypingRuleRecord
  | .a0Synth => {
      id := .a0Synth
      anchor := "spec §1.6, §3"
      sourceRange := { start := 1829, stop := 1831 }
      sourceDigest := "40dd4cf4e380a7ebca7e8bf68ca4e225469f25191320ca135c29602abf2bf339"
      conclusion := "(a0-synth Γ t R)"
    }
  | .a0Check => {
      id := .a0Check
      anchor := "spec §1.6, §3"
      sourceRange := { start := 1836, stop := 1838 }
      sourceDigest := "5453f547aade95407a7e888072570b78ce39d540acf34ac728b624b65d5aadad"
      conclusion := "(a0-check Γ t τ R)"
    }
  | .a0TNatural => {
      id := .a0TNatural
      anchor := "spec §3.1"
      sourceRange := { start := 1038, stop := 1039 }
      sourceDigest := "eb9c649cd91df43382bfe6f2ef5d2ed0b97c5b9fb9af8e021cd266e3b72e82ef"
      conclusion := "(a0-type synth Γ n (typing Natural () ()))"
    }
  | .a0TSpeaker => {
      id := .a0TSpeaker
      anchor := "spec §5.1"
      sourceRange := { start := 1041, stop := 1042 }
      sourceDigest := "333e4b25f92d3f0acc92adac8e4cc7c6d07e5d55fae1c7fdf1e0618ad2ec28fb"
      conclusion := "(a0-type synth Γ Speaker (typing (Referents Entity) () ()))"
    }
  | .a0TAudience => {
      id := .a0TAudience
      anchor := "spec §5.1"
      sourceRange := { start := 1044, stop := 1045 }
      sourceDigest := "217f5ae7506e5e038ba31a2d84f113873b7d1b3a27c465155505efe50f534942"
      conclusion := "(a0-type synth Γ Audience (typing (Referents Entity) () ()))"
    }
  | .a0TThresholdKind => {
      id := .a0TThresholdKind
      anchor := "spec §6.4"
      sourceRange := { start := 1047, stop := 1048 }
      sourceDigest := "d11c4ffd8f51adcc59c30dd222e8049b2801fb0d4957793d8ba359982dc2d682"
      conclusion := "(a0-type synth Γ TooManyK (typing ThresholdKind () ()))"
    }
  | .a0TTop => {
      id := .a0TTop
      anchor := "spec §4.5"
      sourceRange := { start := 1050, stop := 1051 }
      sourceDigest := "a7fd9bf1ff85bf3a88cae7e398996aa9afb580daa5f66afa00beabc6f432134b"
      conclusion := "(a0-type synth Γ ⊤ (typing Content () ()))"
    }
  | .a0TVariable => {
      id := .a0TVariable
      anchor := "spec §4.4"
      sourceRange := { start := 1053, stop := 1055 }
      sourceDigest := "faddd276342fb6076b794bd29bfee5f50e275c9800198527fa378d93b10c2b11"
      conclusion := "(a0-type synth Γ x (typing τ () ()))"
    }
  | .a0TLambdaPure => {
      id := .a0TLambdaPure
      anchor := "spec §3.3, §4.4"
      sourceRange := { start := 1057, stop := 1066 }
      sourceDigest := "6a1e314ac3cd6f2f0b90f447430ac8ccde818319425e6d7e777a76dfe9d5a459"
      conclusion := "(a0-type synth Γ (λ ((x τ)) t_body) (typing (Fn (τ) τ_body) () (obligation_scoped ...)))"
    }
  | .a0TLambdaEffectful => {
      id := .a0TLambdaEffectful
      anchor := "spec §3.3, §4.4"
      sourceRange := { start := 1068, stop := 1078 }
      sourceDigest := "262950e007af10f924d9c9cfe4bcbb3f96eb64a62ffe89cb339824ba3dd474cc"
      conclusion := "(a0-type synth Γ (λ ((x τ)) t_body) (typing (EFn (τ) τ_body) () (obligation_scoped ...)))"
    }
  | .a0TLambdaMultiPure => {
      id := .a0TLambdaMultiPure
      anchor := "spec §3.3, §4.4"
      sourceRange := { start := 1080, stop := 1093 }
      sourceDigest := "fa47ee1cd04923ec9e3c971b17088bbb8ccc9393e263cfd26a10dfd3378670f7"
      conclusion := "(a0-type synth Γ (λ ((x_0 τ_0) (x_1 τ_1) (x_rest τ_rest) ...) t_body) (typing (Fn (τ_0 τ_1 τ_rest ...) τ_body) () (obligation_scoped ...)))"
    }
  | .a0TLambdaMultiEffectful => {
      id := .a0TLambdaMultiEffectful
      anchor := "spec §3.3, §4.4"
      sourceRange := { start := 1095, stop := 1109 }
      sourceDigest := "1bf0b21824adf3b3f24f665cc88159ab6552f2e8d444d737272c35a3fa0a59bf"
      conclusion := "(a0-type synth Γ (λ ((x_0 τ_0) (x_1 τ_1) (x_rest τ_rest) ...) t_body) (typing (EFn (τ_0 τ_1 τ_rest ...) τ_body) () (obligation_scoped ...)))"
    }
  | .a0TLet => {
      id := .a0TLet
      anchor := "spec §4.4; §12 Let"
      sourceRange := { start := 1111, stop := 1125 }
      sourceDigest := "1d31494889ba5ecbe9251b5c6b8398c3cb94d09169072de493de24ea88c36c6b"
      conclusion := "(a0-type synth Γ (Let (x τ) t_value t_body) R_out)"
    }
  | .a0TBindNest => {
      id := .a0TBindNest
      anchor := "spec §4.4, §5.2"
      sourceRange := { start := 1127, stop := 1133 }
      sourceDigest := "81e5e177bba17525207fdff7d89f75aa7dec36a12b4e4aec8c198548d44242c6"
      conclusion := "(a0-type synth Γ (Bind (binding_0 binding_1 binding_rest ...) t_body) R_out)"
    }
  | .a0TBindReference => {
      id := .a0TBindReference
      anchor := "spec §5.2"
      sourceRange := { start := 1135, stop := 1143 }
      sourceDigest := "e9a73b4625aa95855f2b7f2d265dabbf34b41ae58b4003ba41c076d431fcbd5d"
      conclusion := "(a0-type synth Γ (Bind ((x τ t_comp)) t_body) R_out)"
    }
  | .a0TBindPerformanceAct => {
      id := .a0TBindPerformanceAct
      anchor := "spec §5.2, §7.1"
      sourceRange := { start := 1145, stop := 1159 }
      sourceDigest := "d9b39adf53c870e1af1d2433c5b4f54539dae3d10a4f71df01e2ce706e0a1204"
      conclusion := "(a0-type synth Γ (Bind ((x τ t_comp)) t_body) R_out)"
    }
  | .a0TBindPerformanceComp => {
      id := .a0TBindPerformanceComp
      anchor := "spec §5.2, §7.1"
      sourceRange := { start := 1161, stop := 1176 }
      sourceDigest := "a2d6a983ef825a61881fb83aca33d3487fc54f40a0fd2530968ed93ece313f7a"
      conclusion := "(a0-type synth Γ (Bind ((x τ t_comp)) t_body) R_out)"
    }
  | .a0TBindPerformanceDiscourse => {
      id := .a0TBindPerformanceDiscourse
      anchor := "spec §5.2, §7.1"
      sourceRange := { start := 1178, stop := 1192 }
      sourceDigest := "a018f94c9076ad5771415765802384ba10f35aa41bbb59e758e6607b1d9f9cfc"
      conclusion := "(a0-type synth Γ (Bind ((x τ t_comp)) t_body) R_out)"
    }
  | .a0TCheckSynth => {
      id := .a0TCheckSynth
      anchor := "spec §1.6, §3"
      sourceRange := { start := 1194, stop := 1199 }
      sourceDigest := "9f7d98af84d383378a10aa874506b96eb9ec98b274b99b9d4a1c19e24b7c64f5"
      conclusion := "(a0-type (check τ_expected) Γ t_actual R_actual)"
    }
  | .a0TContext => {
      id := .a0TContext
      anchor := "spec §5.3"
      sourceRange := { start := 1201, stop := 1205 }
      sourceDigest := "278ac9fb1bd918c57d29c31d0a3b8dd6b941ff52941acc0f869e8facc0e894ee"
      conclusion := "(a0-type (check (RefComp τ)) Γ (Context t_argument ...) R_out)"
    }
  | .a0TVague => {
      id := .a0TVague
      anchor := "spec §6.4–§6.5"
      sourceRange := { start := 1207, stop := 1211 }
      sourceDigest := "b166b8514c074d043567a8a5710f6878d757b44ca239fcbcb4eab32561a06a3a"
      conclusion := "(a0-type (check (RefComp τ)) Γ (Vague t_property) (typing (RefComp τ) (context) (obligation ...)))"
    }
  | .a0TReferReference => {
      id := .a0TReferReference
      anchor := "spec §5.3"
      sourceRange := { start := 1213, stop := 1223 }
      sourceDigest := "e0ae54cbc08b6c8f1ed6368c702f33606472718545338c2620654b59488c29e9"
      conclusion := "(a0-type (check (RefComp (Referents τ))) Γ (Refer t_property) R_out)"
    }
  | .a0TReferMember => {
      id := .a0TReferMember
      anchor := "spec §5.3"
      sourceRange := { start := 1225, stop := 1233 }
      sourceDigest := "89c802fd966e8c803a7663bb4ac5fbbf8418f72b17a7620a3d869a27c80446f5"
      conclusion := "(a0-type (check (RefComp (Referents τ))) Γ (Refer t_property) R_out)"
    }
  | .a0TSelectExactly => {
      id := .a0TSelectExactly
      anchor := "spec §5.6"
      sourceRange := { start := 1235, stop := 1246 }
      sourceDigest := "e66e7de1f92240a3531b1744463b057b681ed2d7e9c2890a494fa88baca22690"
      conclusion := "(a0-type (check (RefComp (Referents τ))) Γ (SelectExactly t_count t_property) R_out)"
    }
  | .a0TSelectSome => {
      id := .a0TSelectSome
      anchor := "spec §5.6"
      sourceRange := { start := 1248, stop := 1257 }
      sourceDigest := "30c30acd90b4351115534b56ea961a7a9d876685e355190a27c9e99d5f0414f3"
      conclusion := "(a0-type (check (RefComp (Referents τ))) Γ (SelectSome t_property) R_out)"
    }
  | .a0TMassify => {
      id := .a0TMassify
      anchor := "spec §4.8; §12 Massify"
      sourceRange := { start := 1295, stop := 1308 }
      sourceDigest := "07de5aaa5ffc21426a131f1fe046fe499c457f14f861b968bdd510e05044cd6b"
      conclusion := "(a0-type (check (RefComp (Referents (Group τ)))) Γ (Massify t_basis t_cover) R_out)"
    }
  | .a0TPerform => {
      id := .a0TPerform
      anchor := "spec §7.1"
      sourceRange := { start := 1310, stop := 1315 }
      sourceDigest := "6c1a5aeb46dc774d872a34402b46633e2ef45c0f411a0a48ebea3b3c7301ecf3"
      conclusion := "(a0-type synth Γ (Perform t_act) (typing (PerfComp (ActOccurrence force)) (performance) (obligation ...)))"
    }
  | .a0TExactlyZero => {
      id := .a0TExactlyZero
      anchor := "spec §4.10; §12 Exactly"
      sourceRange := { start := 1317, stop := 1326 }
      sourceDigest := "a5d433b531335c17b4f76a1bd2d7d1f9289dbbcce445f4c161c42319900edf36"
      conclusion := "(a0-type synth Γ (Exactly 0 v_P v_Q) R_out)"
    }
  | .a0TExactlyPositive => {
      id := .a0TExactlyPositive
      anchor := "spec §4.10; §12 Exactly"
      sourceRange := { start := 1328, stop := 1338 }
      sourceDigest := "e981ced3f1e762e285d4c52ea5b0613455504ee164afa2e92dabbada3ce525b6"
      conclusion := "(a0-type synth Γ (Exactly t_count v_P v_Q) R_out)"
    }
  | .a0TNo => {
      id := .a0TNo
      anchor := "spec §4.10; §12 No"
      sourceRange := { start := 1397, stop := 1404 }
      sourceDigest := "6be7e700b0b5c44478d15b6bce0f434111708835c37cf04a4f99a0c186b369ce"
      conclusion := "(a0-type synth Γ (No v_P v_Q) R_out)"
    }
  | .a0TMoreThan => {
      id := .a0TMoreThan
      anchor := "spec §4.10; §12 MoreThan"
      sourceRange := { start := 1417, stop := 1426 }
      sourceDigest := "8a1ebc75ca23ee3312187098a06375a54427f1a3ce9c6353198c5ff7b78b8d50"
      conclusion := "(a0-type synth Γ (MoreThan t_n v_P v_Q) R_out)"
    }
  | .a0TGlobalExactly => {
      id := .a0TGlobalExactly
      anchor := "spec §4.10; §12 GlobalExactly"
      sourceRange := { start := 1460, stop := 1468 }
      sourceDigest := "8a0a4f9878674ac9c077f34365139b53d2aaa91914d58f81f7f90578cb77f93f"
      conclusion := "(a0-type synth Γ (GlobalExactly t_n t_P t_Q) R_out)"
    }
  | .a0TTooMany => {
      id := .a0TTooMany
      anchor := "spec §6.4; §12 TooMany"
      sourceRange := { start := 1470, stop := 1479 }
      sourceDigest := "ada743b2d2adc9de2fceb69fa1d851424a1031cb517a5dd0a5c412a31f825468"
      conclusion := "(a0-type synth Γ (TooMany t_P t_Q) R_out)"
    }
  | .a0TAdmissibleThreshold => {
      id := .a0TAdmissibleThreshold
      anchor := "spec §6.4"
      sourceRange := { start := 1481, stop := 1490 }
      sourceDigest := "f3a4521aeea0f422fb6835981a70ad2558cea8e910e8f4603f9cd70a32881e1a"
      conclusion := "(a0-type synth Γ (AdmissibleThreshold t_kind t_P t_purpose) R_out)"
    }
  | .a0TCanonicalAggregateAt => {
      id := .a0TCanonicalAggregateAt
      anchor := "spec §4.8"
      sourceRange := { start := 1492, stop := 1500 }
      sourceDigest := "f02589979ee46a9d9d219e86fd3e9fc9459e223cb7e8ba66c26bbf52e0a8e141"
      conclusion := "(a0-type synth Γ (CanonicalAggregateAt t_basis t_group t_cover) R_out)"
    }
  | .a0TSetOf => {
      id := .a0TSetOf
      anchor := "spec §4.9"
      sourceRange := { start := 1502, stop := 1506 }
      sourceDigest := "73548af40a02b7dbdd37e9360d92ecbaf3aa832ab229152c6a9d8ecd63c6cadb"
      conclusion := "(a0-type synth Γ (SetOf t_P) R_out)"
    }
  | .a0TCard => {
      id := .a0TCard
      anchor := "spec §4.9"
      sourceRange := { start := 1508, stop := 1514 }
      sourceDigest := "89e3abe80ee4c11bc75f2f785925d8724b4e89230a5b64e246ba506effa68c85"
      conclusion := "(a0-type synth Γ (Card t_set) R_out)"
    }
  | .a0TEquality => {
      id := .a0TEquality
      anchor := "spec §4.5"
      sourceRange := { start := 1516, stop := 1528 }
      sourceDigest := "3991b0c7916a1c2c44409c003231096cb6c6e31c68323c16230f144beaa0b36a"
      conclusion := "(a0-type synth Γ (= t_left t_right) R_out)"
    }
  | .a0TAnd => {
      id := .a0TAnd
      anchor := "spec §4.5"
      sourceRange := { start := 1540, stop := 1544 }
      sourceDigest := "ebf5f4732973f26b370cbf106e1395e6839b0d91a73135d1da68b83bf91872de"
      conclusion := "(a0-type synth Γ (∧ t_left t_right) R_out)"
    }
  | .a0TCoRef => {
      id := .a0TCoRef
      anchor := "spec §4.5"
      sourceRange := { start := 1620, stop := 1624 }
      sourceDigest := "5f7ca35b31d07a0f65c5c54d9ac645b77790350d37c416aa9070bee654417c0d"
      conclusion := "(a0-type synth Γ (CoRef t_left t_right) R_out)"
    }
  | .a0TListCheck => {
      id := .a0TListCheck
      anchor := "spec §4.9"
      sourceRange := { start := 1664, stop := 1667 }
      sourceDigest := "5fb37a0a07d7fd8f11705a7053702b50432e23421cf22d243688c658319c5e53"
      conclusion := "(a0-type (check (List τ)) Γ (List t_item ...) R_out)"
    }
  | .a0TZipWithPure => {
      id := .a0TZipWithPure
      anchor := "spec §4.9; §12 ZipWith"
      sourceRange := { start := 1669, stop := 1681 }
      sourceDigest := "52d4e31ec1229236315294e3e8e431fa7b2d0e1faec3a680d1841bacf8818341"
      conclusion := "(a0-type synth Γ (ZipWith v_f t_left t_right) R_out)"
    }
  | .a0TZipWithEmptyEffectful => {
      id := .a0TZipWithEmptyEffectful
      anchor := "spec §4.9; §12 ZipWith empty"
      sourceRange := { start := 1683, stop := 1692 }
      sourceDigest := "516bbe2b4a35e85689f6b9772904cd87ac2e9643eb2b58736f5447f4cc34385c"
      conclusion := "(a0-type synth Γ (ZipWith v_f (List) (List)) R_out)"
    }
  | .a0TZipWithEffectful => {
      id := .a0TZipWithEffectful
      anchor := "spec §4.9; §12 ZipWith"
      sourceRange := { start := 1694, stop := 1709 }
      sourceDigest := "e451c9266808e1d928f1237ffbc4473e5a3d9348af91d113a5bbf7b3852cb27c"
      conclusion := "(a0-type synth Γ (ZipWith v_f t_left t_right) R_out)"
    }
  | .a0TStateClause => {
      id := .a0TStateClause
      anchor := "spec §4.6"
      sourceRange := { start := 1711, stop := 1714 }
      sourceDigest := "176d484b48bfa17875d7bd9cad5fe699da383a367c5260c1052f06c16da2308f"
      conclusion := "(a0-type synth Γ (StateClause t_content) R_out)"
    }
  | .a0TDirectClausePure => {
      id := .a0TDirectClausePure
      anchor := "spec §4.6"
      sourceRange := { start := 1716, stop := 1726 }
      sourceDigest := "de8c6d1726e995b8c6b092b826752e7f793b530f803e1e71d639d603030ffe92"
      conclusion := "(a0-type synth Γ (DirectClause t_property) R_out)"
    }
  | .a0TDirectClauseEffectful => {
      id := .a0TDirectClauseEffectful
      anchor := "spec §4.6"
      sourceRange := { start := 1728, stop := 1738 }
      sourceDigest := "5d2a99eadfa0e997b7c2527882fa6dfa67dc5bd84223ad0988f6576727666f79"
      conclusion := "(a0-type synth Γ (DirectClause t_property) R_out)"
    }
  | .a0TActualClauseState => {
      id := .a0TActualClauseState
      anchor := "spec §4.6"
      sourceRange := { start := 1740, stop := 1748 }
      sourceDigest := "c5da08f7037872b42e257b6edd0bd85c2642e3bffcaafa4b8ceadbb8d13ac11f"
      conclusion := "(a0-type synth Γ (ActualClause t_clause) R_out)"
    }
  | .a0TActualClauseEventPure => {
      id := .a0TActualClauseEventPure
      anchor := "spec §4.6"
      sourceRange := { start := 1750, stop := 1755 }
      sourceDigest := "a1280af17d3f68432c357c450ee10c058c1aa18efa9157ed9754b25b290cb562"
      conclusion := "(a0-type synth Γ (ActualClause t_property) R_out)"
    }
  | .a0TActualClauseEventEffectful => {
      id := .a0TActualClauseEventEffectful
      anchor := "spec §4.6"
      sourceRange := { start := 1757, stop := 1762 }
      sourceDigest := "cdd7b0dd8a2cddb668a2d2faad9a47b7d86e0467403fa0978afd395eba25f5ac"
      conclusion := "(a0-type synth Γ (ActualClause t_property) R_out)"
    }
  | .a0TCloseClause => {
      id := .a0TCloseClause
      anchor := "spec §4.6"
      sourceRange := { start := 1764, stop := 1767 }
      sourceDigest := "e511dbbc050ab0ec631ebe19450c2743471d1d9728c09870922c1cba769bf8f0"
      conclusion := "(a0-type synth Γ (CloseClause t_clause) R_out)"
    }
  | .a0TCloseWith => {
      id := .a0TCloseWith
      anchor := "spec §4.6"
      sourceRange := { start := 1769, stop := 1782 }
      sourceDigest := "6a414c74b72afba0e461081297f0e858d80c62f78fec4f9567307dcfc682b32a"
      conclusion := "(a0-type synth Γ (CloseWith (row x_predicate n event-mode (label ...)) fills) R_out)"
    }
  | .a0TApplyClauseContent => {
      id := .a0TApplyClauseContent
      anchor := "spec §3.4, §4.6"
      sourceRange := { start := 1784, stop := 1796 }
      sourceDigest := "de13250bfb83e59d2194452726b94f3b31403db058c26de28662be16f0e2e7bb"
      conclusion := "(a0-type synth Γ (t_function t_argument) R_out)"
    }
  | .a0TApplyPure => {
      id := .a0TApplyPure
      anchor := "spec §3.3, §4.4"
      sourceRange := { start := 1798, stop := 1810 }
      sourceDigest := "5f103df9cb0041abb31b4b44f7481da3136b20c957c539eb722dece6abed4560"
      conclusion := "(a0-type synth Γ (t_function t_argument ...) R_out)"
    }
  | .a0TApplyEffectful => {
      id := .a0TApplyEffectful
      anchor := "spec §3.3, §4.4"
      sourceRange := { start := 1812, stop := 1824 }
      sourceDigest := "5d6ccd91e24ce471c9dff9a68c0f87f2d87057baf3bda7c8302a5a336f0d010e"
      conclusion := "(a0-type synth Γ (t_function t_argument ...) R_out)"
    }
  | .b1TSelectAtLeast => {
      id := .b1TSelectAtLeast
      anchor := "spec §5.6; §12 selection floor"
      sourceRange := { start := 1259, stop := 1270 }
      sourceDigest := "8080c4ffc1cbbbbf25e37bee08b9c76eddb0553e8db36f6b787c372eea30e9d9"
      conclusion := "(a0-type (check (RefComp (Referents τ))) Γ (SelectAtLeast t_count t_property) R_out)"
    }
  | .b1TSelectAllBut => {
      id := .b1TSelectAllBut
      anchor := "spec §5.6; §12 SelectAllBut"
      sourceRange := { start := 1272, stop := 1282 }
      sourceDigest := "73b2a78bf588309d4aa99eaa1bc1a46dea949389d35430f282766e0896dab771"
      conclusion := "(a0-type (check (RefComp (Referents τ))) Γ (SelectAllBut t_count t_property) R_out)"
    }
  | .b1TMaxRefer => {
      id := .b1TMaxRefer
      anchor := "spec §5.3; §12 MaxRefer"
      sourceRange := { start := 1284, stop := 1293 }
      sourceDigest := "010982ba33e40f17badaae1e813ca56e0e6c2ab064cb6aab7aa8e0b069656a7e"
      conclusion := "(a0-type (check (RefComp (Referents τ))) Γ (MaxRefer v_P) R_out)"
    }
  | .b1TImplication => {
      id := .b1TImplication
      anchor := "spec §4.5"
      sourceRange := { start := 1546, stop := 1550 }
      sourceDigest := "2ff77c16bc789d5d7f35f169cddad194745ba4aa8c8050041d25e16d6f6477c0"
      conclusion := "(a0-type synth Γ (→ t_left t_right) R_out)"
    }
  | .b1TNegation => {
      id := .b1TNegation
      anchor := "spec §4.5, §5.4"
      sourceRange := { start := 1552, stop := 1555 }
      sourceDigest := "fab4f6bc61eb0bd0538b4ab63f2889f1e5efe90e858d13fbb89bd1e2a4588eb2"
      conclusion := "(a0-type synth Γ (¬ t_body) R_out)"
    }
  | .b1TForall => {
      id := .b1TForall
      anchor := "spec §4.5"
      sourceRange := { start := 1557, stop := 1572 }
      sourceDigest := "f8818c60aaa78a1aad8c509e8194628c68ec4c8c271723e01be65777535e8591"
      conclusion := "(a0-type synth Γ (∀ v_property) R_out)"
    }
  | .b1TExists => {
      id := .b1TExists
      anchor := "spec §4.5"
      sourceRange := { start := 1574, stop := 1589 }
      sourceDigest := "6e99e8921af6ab06d9c7304e533846d083eafaa49fc7483dcd98d0f1222a5026"
      conclusion := "(a0-type synth Γ (∃ v_property) R_out)"
    }
  | .b1TAmong => {
      id := .b1TAmong
      anchor := "spec §4.8"
      sourceRange := { start := 1591, stop := 1599 }
      sourceDigest := "f28f3c5727bced00c4c0d9d429ccc75ecb7a20c38188ed96df1b7fbe093ac260"
      conclusion := "(a0-type synth Γ (Among t_left t_right) R_out)"
    }
  | .b1TPresupposeSynth => {
      id := .b1TPresupposeSynth
      anchor := "spec §5.5"
      sourceRange := { start := 1601, stop := 1608 }
      sourceDigest := "9f0c0ddccbed4305bd0ddeffa2c1fa58260be8af18ef7de8df98bf73a4a7f9ee"
      conclusion := "(a0-type synth Γ (Presuppose t_condition t_body) R_out)"
    }
  | .b1TPresupposeReference => {
      id := .b1TPresupposeReference
      anchor := "spec §5.5"
      sourceRange := { start := 1610, stop := 1618 }
      sourceDigest := "76fc9f631f81ac6a387ed9964b0625ef1a18f0a28b221f196b3021d94eb579f8"
      conclusion := "(a0-type (check (RefComp τ)) Γ (Presuppose t_condition t_body) R_out)"
    }
  | .b1TDistrib => {
      id := .b1TDistrib
      anchor := "spec §4.8; §12 Distrib"
      sourceRange := { start := 1626, stop := 1640 }
      sourceDigest := "f7e4fc3091908743e8a722a9a5ccdb2f2fde59c647ad47a621eda7453b3caa11"
      conclusion := "(a0-type synth Γ (Distrib v_Q t_reference) R_out)"
    }
  | .b1TCoveredBy => {
      id := .b1TCoveredBy
      anchor := "spec §4.8"
      sourceRange := { start := 1642, stop := 1652 }
      sourceDigest := "8834ce5c15c546d6b61a239f5697d7e3e16755ed79d315c7fc175e887c1c677b"
      conclusion := "(a0-type synth Γ (CoveredBy v_P t_reference) R_out)"
    }
  | .b1TOverlap => {
      id := .b1TOverlap
      anchor := "spec §4.8; §12 Overlap"
      sourceRange := { start := 1654, stop := 1662 }
      sourceDigest := "8503cf7645c1a1c1725e92236baef13b9721ed512362f4f1f120830880699386"
      conclusion := "(a0-type synth Γ (Overlap t_left t_right) R_out)"
    }
  | .b1TAddition => {
      id := .b1TAddition
      anchor := "spec §4.9"
      sourceRange := { start := 1530, stop := 1538 }
      sourceDigest := "46e44db9225e7bd5340232ebc5dcb7873dac4ea307fd9a25cfe8c9d348decb54"
      conclusion := "(a0-type synth Γ (+ t_left t_right) R_out)"
    }
  | .b1TAtLeastZero => {
      id := .b1TAtLeastZero
      anchor := "spec §4.10; §12 AtLeast zero"
      sourceRange := { start := 1340, stop := 1343 }
      sourceDigest := "71b39a0487475847f92aca4e1b8b6d8cd8ec8bc7dba9cf8188b054e9a642e7e8"
      conclusion := "(a0-type synth Γ (AtLeast 0 v_P v_Q) (typing Content () ()))"
    }
  | .b1TAtLeastPositive => {
      id := .b1TAtLeastPositive
      anchor := "spec §4.10; §12 AtLeast"
      sourceRange := { start := 1345, stop := 1355 }
      sourceDigest := "2363af25663fef06948dd7f7808051eb5f836acee391d2e73167c59592558b1f"
      conclusion := "(a0-type synth Γ (AtLeast t_count v_P v_Q) R_out)"
    }
  | .b1TAtLeastSymbolic => {
      id := .b1TAtLeastSymbolic
      anchor := "spec §4.10; §12 AtLeast totality"
      sourceRange := { start := 1357, stop := 1370 }
      sourceDigest := "273e3153f6be5d403fd0e706bf1f04c26a49f6e8bfe710b86092bd06889bdbf2"
      conclusion := "(a0-type synth Γ (AtLeast t_count v_P v_Q) R_out)"
    }
  | .b1TSome => {
      id := .b1TSome
      anchor := "spec §4.10; §12 Some"
      sourceRange := { start := 1372, stop := 1379 }
      sourceDigest := "3466ecc262a2d68cc08997529b4b324fa1e0fdcabe4d09a0320bb69e8b8be81c"
      conclusion := "(a0-type synth Γ (Some v_P v_Q) R_out)"
    }
  | .b1TEvery => {
      id := .b1TEvery
      anchor := "spec §4.10; §12 Every"
      sourceRange := { start := 1381, stop := 1395 }
      sourceDigest := "5856412515792ea8e756d1819441dfe6501478f9d41cd77b3c8a256e5fd76a2c"
      conclusion := "(a0-type synth Γ (Every v_P v_Q) R_out)"
    }
  | .b1TAtMost => {
      id := .b1TAtMost
      anchor := "spec §4.10; §12 AtMost"
      sourceRange := { start := 1406, stop := 1415 }
      sourceDigest := "288f1acdf35df2258e1c10cd653456d1eabc911db9e3a8c60fea51d82dd37f46"
      conclusion := "(a0-type synth Γ (AtMost t_n v_P v_Q) R_out)"
    }
  | .b1TFewerThanZero => {
      id := .b1TFewerThanZero
      anchor := "spec §4.10; §12 FewerThan zero"
      sourceRange := { start := 1428, stop := 1431 }
      sourceDigest := "9de685c6611e560dd78e96aa26091eefddb81c9778181cea1fd9601328d2eddb"
      conclusion := "(a0-type synth Γ (FewerThan 0 v_P v_Q) (typing Content () ()))"
    }
  | .b1TFewerThanPositive => {
      id := .b1TFewerThanPositive
      anchor := "spec §4.10; §12 FewerThan"
      sourceRange := { start := 1433, stop := 1443 }
      sourceDigest := "c42276378bf7c0e1ff9c500b008c6941f10912175f5220020faf281209b0ff58"
      conclusion := "(a0-type synth Γ (FewerThan t_count v_P v_Q) R_out)"
    }
  | .b1TFewerThanSymbolic => {
      id := .b1TFewerThanSymbolic
      anchor := "spec §4.10; §12 FewerThan totality"
      sourceRange := { start := 1445, stop := 1458 }
      sourceDigest := "e9e529b42363d72baf525f99991766e56847bc9311a700aecffd1d2613596478"
      conclusion := "(a0-type synth Γ (FewerThan t_count v_P v_Q) R_out)"
    }

def m2TypingRuleRecords : List M2TypingRuleRecord :=
  M2TypingRuleId.all.map M2TypingRuleId.record

structure M2GrammarRecord where
  category : M2GrammarCategory
  sourceRange : SourceRange
  sourceDigest : String
  source : String
  deriving Repr, DecidableEq, BEq

def M2GrammarCategory.record : M2GrammarCategory → M2GrammarRecord
  | .type => {
      category := .type
      sourceRange := { start := 66, stop := 72 }
      sourceDigest := "ddd5841444bed59674aab9de564f4a346a674cb6f30365246adfee62ae445bbe"
      source := "[τ Entity Eventuality Number Natural Cardinal Content ClauseContent Discourse ThresholdKind (Referents τ) (Group τ) (List τ) (Set τ) (DecompositionBasis τ τ) (Act force) (ActOccurrence force) (Fn (τ ...) τ) (EFn (τ ...) τ) (RefComp τ) (PerfComp τ)]"
    }
  | .direction => {
      category := .direction
      sourceRange := { start := 73, stop := 73 }
      sourceDigest := "eb5ec310fab7e1459145cab7d8e95aa8fa6cfae2ce8982aa478725424f6dd55b"
      source := "[direction synth (check τ)]"
    }
  | .r => {
      category := .r
      sourceRange := { start := 75, stop := 75 }
      sourceDigest := "e9cc470d4fb06e2c0c6ec7ced8f6692ead4f0d4433c02abba7556104fa11af69"
      source := "[R (typing τ (effect ...) (obligation ...))]"
    }
  | .t => {
      category := .t
      sourceRange := { start := 81, stop := 133 }
      sourceDigest := "b98defc81b5bded0c2151eb52ec085ab1382d07337db2d5510659657fcaa06f1"
      source := "[t x n constant (λ ((x τ) ...) t) (Let (x τ) t t) (Bind ((x τ t) ...) t) (Context t ...) (Vague t) (Refer t) (SelectExactly t t) (SelectAtLeast t t) (SelectSome t) (SelectAllBut t t) (Exactly t t t) (AtLeast t t t) (Some t t) (Every t t) (No t t) (AtMost t t t) (GlobalExactly t t t) (TooMany t t) (MoreThan t t t) (FewerThan t t t) (Distrib t t) (MaxRefer t) (CoveredBy t t) (Overlap t t) (Among t t) (∀ t) (∃ t) (→ t t) (¬ t) (Presuppose t t) (Massify t t) (Perform t) (CanonicalAggregateAt t t t) (AdmissibleThreshold t t t) (SetOf t) (Card t) (= t t) (+ t t) (∧ t t) (List t ...) (ZipWith t t t) (CoRef t t) (CloseClause t) (ActualClause t) (DirectClause t) (StateClause t) (Quote t) (Syntax t) (CloseWith ρdecl fills) (Site variable-not-otherwise-mentioned) (SiteValue variable-not-otherwise-mentioned) (t t ...)]"
    }
  | .rowDeclaration => {
      category := .rowDeclaration
      sourceRange := { start := 134, stop := 134 }
      sourceDigest := "53368971f7f0abc60f5107f981b6cf1e92d82b6eec8e9fc2d86bb8cbe26b6ba8"
      source := "[ρdecl (row variable-not-otherwise-mentioned n event-mode (label ...))]"
    }
  | .dep => {
      category := .dep
      sourceRange := { start := 140, stop := 140 }
      sourceDigest := "2a1dac01c6d9a2d75f8fe1bfe837364b5b522f108db0f8246b89044f1153b5e9"
      source := "[dep (site site-id) (outer x τ) (member)]"
    }
  | .role => {
      category := .role
      sourceRange := { start := 141, stop := 141 }
      sourceDigest := "71783de21e76648de58b32e193eb0f3cccf54207846901559657fe2dd6de2367"
      source := "[role (context t ...) (vague t)]"
    }

def m2GrammarRecords : List M2GrammarRecord :=
  M2GrammarCategory.all.map M2GrammarCategory.record

def m2DefinitionManifestDigest : String :=
  "91b5d6a86e493db27968edb4e88bcc1ef15ca10c4892c3389fb0aad6f5c437dc"

def m2TypingManifestDigest : String :=
  "5966ff2403b4c37dd5b02ddffab33db15d2ded73f2cf0441602c2ac377d9534f"

end SmusniPilot
