(smusni-core-inventory 1
  (sort Entity "spec §3.1")
  (sort Eventuality "spec §3.1")
  (sort Achievement "spec §3.1")
  (sort Process "spec §3.1")
  (sort Activity "spec §3.1")
  (sort State "spec §3.1")
  (sort Experience "spec §3.1")
  (sort Locution "spec §3.1")
  (sort Location "spec §3.1")
  (sort Time "spec §3.1")
  (sort Amount "spec §3.1")
  (sort Scale "spec §3.1")
  (sort Epistemology "spec §3.1")
  (sort TruthValue "spec §3.1")
  (sort Concept "spec §3.1")
  (sort AbstractNature "spec §3.1")
  (sort Proposition "spec §3.1")
  (sort Question "spec §3.1")
  (sort Number "spec §3.1")
  (sort Natural "spec §3.1")
  (sort Cardinal "spec §3.1")
  (sort Text "spec §3.1")
  (sort SignToken "spec §3.1")
  (sort UtteranceToken "spec §3.1")
  (sort Ground "spec §3.1")
  (sort Bool "spec §3.1")
  (sort Unit "spec §3.4")

  (subsort Eventuality Entity "spec §3.1")
  (subsort Achievement Eventuality "spec §3.1")
  (subsort Process Eventuality "spec §3.1")
  (subsort Activity Eventuality "spec §3.1")
  (subsort State Eventuality "spec §3.1")
  (subsort Experience Eventuality "spec §3.1")
  (subsort Locution Eventuality "spec §3.1")
  (subsort Location Entity "spec §3.1")
  (subsort Time Entity "spec §3.1")
  (subsort Amount Entity "spec §3.1")
  (subsort Scale Entity "spec §3.1")
  (subsort Epistemology Entity "spec §3.1")
  (subsort TruthValue Entity "spec §3.1")
  (subsort Concept Entity "spec §3.1")
  (subsort AbstractNature Entity "spec §3.1")
  (subsort Proposition Entity "spec §3.1")
  (subsort Question Entity "spec §3.1")
  (subsort Number Entity "spec §3.1")
  (subsort Natural Number "spec §3.1")
  (subsort Cardinal Natural "spec §3.1")
  (subsort Text Entity "spec §3.1")
  (subsort UtteranceToken Entity "spec §3.1")
  (subsort Ground Entity "spec §3.1")

  (type-form Referents 1 "spec §3.2")
  (type-form Set 1 "spec §3.1, §4.9")
  (type-form Group 1 "spec §3.1, §4.9")
  (type-form List 1 "spec §3.1, §3.5")
  (type-form Act 1 "spec §3.4")
  (type-form ActOccurrence 1 "spec §3.4")
  (type-form RefComp 1 "spec §3.4")
  (type-form PerfComp 1 "spec §3.4")
  (type-form Query 1 "spec §3.4")
  (type-form Sign 1 "spec §3.1")
  (type-form SignToken 1 "spec §3.1")
  (type-form Record 1 "spec §3.3")
  (type-form PredTerm 1 "spec §3.3")
  (type-form Fn variadic "spec §2, §3.3")
  (type-form EFn variadic "spec §2, §3.3")
  (type-form DecompositionBasis 2 "spec §3.5, §4.9")
  (type-form ContributionBasis 1 "spec §3.5, §4.9")
  (type-form ContrastDomain 1 "spec §3.5, §6.3")
  (type-form Region 1 "spec §3.5, §6.4")
  (type-form Row variadic "spec §2, §3.3")
  (type-form RowOf 1 "spec §2, §3.3")
  (type-form RowMinus 2 "spec §2, §3.3")
  (type-form Label 1 "spec §2, §3.3")
  (type-form CompatibleLabel 2 "spec §2, §4.7")

  (constant Speaker (Referents Entity) "spec §5.1")
  (constant Audience (Referents Entity) "spec §5.1")
  (constant MiAOthers (Referents Entity) "spec §5.1, P40")
  (constant MaAOthers (Referents Entity) "spec §5.1, P40")
  (constant DoOOthers (Referents Entity) "spec §5.1, P40")
  (constant This (Referents Entity) "spec §5.1")
  (constant That (Referents Entity) "spec §5.1")
  (constant Yonder (Referents Entity) "spec §5.1")
  (constant Now (Referents Time) "spec §5.1")
  (constant CurrentToken (Referents UtteranceToken) "spec §5.1")
  (constant Host OccurrenceRole "spec §7.1")
  (constant AttachedDisplay OccurrenceRole "spec §7.1")
  (constant AttachedAddress OccurrenceRole "spec §7.1")
  (constant Typical GenericMode "spec §5.8")
  (constant OtherThan ScalarMode "spec §6.3")
  (constant Moderate Intensity "spec §7.6")
  (constant Intense Intensity "spec §7.6")
  (constant Observation Epistemology "spec §7.6")
  (constant Hearsay Epistemology "spec §7.6")
  (constant TooManyK ThresholdKind "spec §6.4")
  (constant ManyK ThresholdKind "spec §6.4")

  ;; `special` means types.rkt owns the polymorphic/type-directed rule.
  (form λ structural special M generic "spec §2, §4.4")
  (form Let structural special M generic "spec §2, §4.4")
  (form Bind structural special M generic "spec §2, §5.2")
  (form At defined special M generic "spec §4.2")
  (form DropPlace primitive special O surface "spec §4.3")
  (form Close defined special O generic "spec §4.6")
  (form DirectClause defined special O generic "spec §4.6")
  (form StateClause primitive special O generic "spec §9.3")
  (form ActualClause defined special O generic "spec §12")
  (form CapableClause defined special O generic "spec §12")
  (form CloseClause primitive special O generic "spec §9.3")
  (form ClauseNot defined special O generic "spec §9.3")
  (form ClauseAnd defined special O generic "spec §9.3")
  (form ClauseOr defined special O generic "spec §9.3")
  (form Refer primitive special O surface "spec §5.3")
  (form Local primitive special O lowering-only "spec §5.2")
  (form Context primitive special O surface "spec §5.3")
  (form Vague primitive special O surface "spec §5.3, §6.5")
  (form SelectExactly primitive special O surface "spec §5.6")
  (form SelectAtLeast primitive special O surface "spec §5.6")
  (form SelectSome defined special O generic "spec §12")
  (form SelectAllBut primitive special O surface "spec §12")
  (form Presuppose primitive special O surface "spec §5.5")
  (form Supplement primitive special O surface "spec §5.5")
  (form Assert primitive special O surface "spec §7.1")
  (form Ask primitive special O surface "spec §7.1")
  (form Express primitive special O surface "spec §7.1")
  (form Mention primitive special O surface "spec §7.1")
  (form Perform primitive special O surface "spec §7.1")
  (form Do primitive special O generic "spec §7.2")
  (form Polar primitive special O surface "spec §8.1")
  (form OpenQ primitive special O surface "spec §8.1")
  (form Answer primitive special O surface "spec §8.4")
  (form ContextualAnswer defined special O generic "spec §8.4")
  (form Reify primitive special O generic "spec §9.1")
  (form Holds primitive special O generic "spec §9.1")
  (form EventOfContent primitive special O generic "spec §9.3")
  (form Generic primitive special O surface "spec §5.8")
  (form Distrib defined special O generic "spec §12")
  (form CoveredBy defined special O generic "spec §4.8")
  (form Every defined special O surface "spec §12")
  (form No defined special O surface "spec §12")
  (form Exactly defined special O surface "spec §12")
  (form AtLeast defined special O surface "spec §12")
  (form Some defined special O surface "spec §12")
  (form AtMost defined special O surface "spec §12")
  (form MoreThan defined special O surface "spec §12")
  (form FewerThan defined special O surface "spec §12")
  (form GlobalExactly defined special O surface "spec §12")
  (form Most defined special O surface "spec §12")
  (form SetOf primitive special M generic "spec §4.9")
  (form Card primitive special M generic "spec §4.9")
  (form CardBasis defined special O generic "spec §12")
  (form List primitive special M generic "spec §3.5")
  (form Set primitive special M generic "spec §4.9")
  (form CoRef defined special P generic "spec §4.8")
  (form Among primitive special M generic "spec §4.8")
  (form Combine primitive special M generic "spec §4.8")
  (form Tanru defined special O surface "spec §6.2")
  (form TanruLinkConnect defined special O surface "spec §12")
  (form TanruAdmissible primitive special O generic "spec §6.2")
  (form Scalar primitive special O surface "spec §6.3")
  (form Grade defined special O surface "spec §6.4")
  (form Reciprocate defined special O surface "spec §12")
  (form ZipWith defined special O surface "spec §12")
  (form JaiRaise defined special O surface "spec §12")
  (form JaiRoleAdmissible primitive special O generic "spec §12")
  (form DuhuRel defined special O generic "spec §9.2")
  (form NiRel primitive special O surface "spec §9.2")
  (form SuhuRel primitive special O surface "spec §9.2")
  (form JeiRel primitive special O surface "spec §9.2")
  (form AmountValue primitive special O surface "spec §9.2")
  (form StructuredQuote primitive special O surface "spec §7.5")
  (form OpaqueQuote primitive special O surface "spec §7.5")
  (form NameSign primitive special O surface "spec §7.5")
  (form SentenceSign primitive special O surface "spec §7.5")
  (form LetteralSign primitive special O surface "spec §7.5")
  (form WordSign primitive special O surface "spec §7.5")
  (form Utterance defined special O generic "spec §7.4")
  (form Sign defined special O generic "spec §7.5")
  (form InterpretContent primitive special O surface "spec §7.5")
  (form RealizedContent primitive special O surface "spec §7.4")
  (form Realizes primitive special P generic "spec §7.4")
  (form Named primitive special P generic "spec §7.5")
  (form SpeakerOf primitive special P generic "spec §7.4")
  (form LocutionOf primitive special P generic "spec §7.4")
  (form SpeakerDescribes defined special O surface "spec §12")
  (form SpeakerDescribesUnaddressed defined special O surface "spec §12")
  (form EvidentialBasis primitive special P generic "spec §7.6")
  (form Happiness primitive special P generic "spec §7.6")
  (form Unhappiness primitive special P generic "spec §7.6")
  (form Desire primitive special P generic "spec §7.6")
  (form AdmissibleCutoff primitive special P generic "spec §6.4")
  (form AdmissibleThreshold primitive special P generic "spec §6.4")
  (form MetalinguisticallyDefective primitive special P generic "spec §7.3")
  (form NahiObjection defined special O surface "spec §12")
  (form Contrast primitive special P generic "spec §7.3")
  (form JoiPred defined special M surface "spec §12")
  (form JoiTanru defined special O surface "spec §12")
  (form JoiGroup defined special O surface "spec §12")
  (form JoiEvent defined special O surface "spec §12")
  (form JoiClause defined special O surface "spec §12")
  (form CompleteGunmaAt defined special M generic "spec §4.9")
  (form GunmaAt defined special M generic "spec §4.9")
  (form Aggregate primitive special M generic "spec §4.9")
  (form CanonicalAggregateAt defined special M generic "spec §12")
  (form Massify defined special O surface "spec §12")
  (form components_κ defined special M surface "spec §12")
  (form ComponentAt defined special M generic "spec §4.9")
  (form GunmaPredAt defined special M generic "spec §4.9")
  (form BasisUnitAt primitive special M generic "spec §4.9")
  (form PeerUnitAt primitive special M generic "spec §4.9")
  (form MixAt primitive special M generic "spec §4.9")
  (form ContributesAt primitive special M generic "spec §4.9")
  (form MeiRel defined special O surface "spec §12")
  (form GroupBasisConstraint structural special M generic "spec §4.9")
  (form + primitive special M generic "spec §4.9")
  (form − primitive special M generic "spec §4.9")
  (form |te'a| primitive special M surface "spec §12 MEX")
  (form = primitive special M generic "spec §4.5")
  (form ∈ primitive special M generic "spec §4.9")
  (form ¬ primitive special M generic "spec §4.5")
  (form ∧ primitive special M generic "spec §4.5")
  (form ∨ primitive special M generic "spec §4.5")
  (form ↔ primitive special M generic "spec §4.5")
  (form ⊕ primitive special M generic "spec §4.5")
  (form → primitive special M generic "spec §4.5")
  (form ∀ primitive special M generic "spec §4.5")
  (form ∃ primitive special M generic "spec §4.5"))
