(smusni-definition-ledger
 1
 (definition
  (id "D12.ActualClause")
  (head ActualClause)
  (section "12")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies StateClause fasnu)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason "Its executable family has not yet reached the Redex port."))
 (definition
  (id "D12.AtLeast")
  (head AtLeast)
  (section "12")
  (spec-source-sha1 "e6106373b845d82c57219dd1a9af58e46e64cef0")
  (spec-source-ranges (3964 3964) (4002 4002) (3993 3999))
  (equation-source-sha1 "0c881b9b350f2f6be753423c854f51e5d6708d95")
  (equation-ranges (3964 3964) (4002 4002))
  (status executable)
  (port-state ported)
  (dependencies Bind SelectAtLeast)
  (legacy-implementations)
  (implementations
   (metafunction
    "tools/smusni-redex/port-a0.rkt"
    b1-expand-at-least
    (cases zero positive)))
  (domains
   (domain
    symbolic-natural
    (status executable)
    (port-state none)
    (reason
     "Direct typing is total, but the two-equation metafunction cannot choose zero or positive before a symbolic Natural is instantiated.")))
  (reason
   "B1 ports the separate zero and provably-positive witness equations."))
 (definition
  (id "D12.AtMost")
  (head AtMost)
  (section "12")
  (spec-source-sha1 "b1cfefdfcf27369715b2a070da134d669b76e2aa")
  (spec-source-ranges (3972 3972))
  (equation-source-sha1 "b1cfefdfcf27369715b2a070da134d669b76e2aa")
  (equation-ranges (3972 3972))
  (status executable)
  (port-state ported)
  (dependencies ¬ AtLeast +)
  (legacy-implementations)
  (implementations
   (metafunction
    "tools/smusni-redex/port-a0.rkt"
    b1-expand-at-most
    (cases negated-successor)))
  (domains)
  (reason "B1 ports negated successor-strength AtLeast."))
 (definition
  (id "D12.COI-schemas-prose")
  (head COI-schemas-prose)
  (section "12")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status not-a-definition)
  (port-state none)
  (dependencies COIExpress)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason
   "This prose introducer points to the following COIExpress schema and is not a separate equation."))
 (definition
  (id "D12.COIExpress")
  (head COIExpress)
  (section "12")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies Express Close)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason
   "The lexicon-parameterized performative schema awaits its executable family."))
 (definition
  (id "D12.CanonicalAggregateAt")
  (head CanonicalAggregateAt)
  (section "12")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies Aggregate CompleteGunmaAt)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason "Its executable family has not yet reached the Redex port."))
 (definition
  (id "D12.CapableClause")
  (head CapableClause)
  (section "12")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies StateClause InnatelyCapable)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason "Its executable family has not yet reached the Redex port."))
 (definition
  (id "D12.CoRef")
  (head CoRef)
  (section "12")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies Among)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason "Its executable family has not yet reached the Redex port."))
 (definition
  (id "D12.DemonstratedClause")
  (head DemonstratedClause)
  (section "12")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies StateClause DemonstrablyRealized)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason "Its executable family has not yet reached the Redex port."))
 (definition
  (id "D12.Distrib")
  (head Distrib)
  (section "12")
  (spec-source-sha1 "20d91ddcaadac2a9546a25d9e8325a122dbc3f95")
  (spec-source-ranges (3976 3976))
  (equation-source-sha1 "20d91ddcaadac2a9546a25d9e8325a122dbc3f95")
  (equation-ranges (3976 3976))
  (status executable)
  (port-state ported)
  (dependencies ∀ λ → Among)
  (legacy-implementations)
  (implementations
   (metafunction
    "tools/smusni-redex/port-a0.rkt"
    b1-expand-distrib
    (cases universal-members)))
  (domains)
  (reason "B1 ports universal member distribution over a plural reference."))
 (definition
  (id "D12.Enough")
  (head Enough)
  (section "12")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies Bind Context Vague AdmissibleThreshold AtLeast)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason
   "Its effectful threshold family has not yet reached the Redex port."))
 (definition
  (id "D12.Every")
  (head Every)
  (section "12")
  (spec-source-sha1 "09e08cabf0d508a27f735d435f8e3ac6486a9d19")
  (spec-source-ranges (3966 3967))
  (equation-source-sha1 "09e08cabf0d508a27f735d435f8e3ac6486a9d19")
  (equation-ranges (3966 3967))
  (status executable)
  (port-state ported)
  (dependencies Bind MaxRefer Distrib)
  (legacy-implementations)
  (implementations
   (metafunction
    "tools/smusni-redex/port-a0.rkt"
    b1-expand-every
    (cases maximal-distribution)))
  (domains)
  (reason "B1 ports maximal witness import followed by member distribution."))
 (definition
  (id "D12.Exactly")
  (head Exactly)
  (section "12")
  (spec-source-sha1 "c44594d4c399528d66c71c67ee1dc20ab0ee5053")
  (spec-source-ranges (3963 3963) (4003 4003) (3993 3999))
  (equation-source-sha1 "0cde8c7b5e9488ca54dd38f99fed6ce70f428729")
  (equation-ranges (3963 3963) (4003 4003))
  (status executable)
  (port-state a0)
  (dependencies Bind SelectExactly No)
  (legacy-implementations)
  (implementations
   (metafunction
    "tools/smusni-redex/port-a0.rkt"
    a0-expand-exactly
    (cases zero positive)))
  (domains)
  (reason "A0 ports both the zero and positive witness-set equations."))
 (definition
  (id "D12.Few")
  (head Few)
  (section "12")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies Bind Vague AdmissibleThreshold FewerThan)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason
   "Its effectful threshold family has not yet reached the Redex port."))
 (definition
  (id "D12.FewerThan")
  (head FewerThan)
  (section "12")
  (spec-source-sha1 "9145eb1ccab3caa6e913530bcc23ea42cc0b4443")
  (spec-source-ranges (3974 3974))
  (equation-source-sha1 "9145eb1ccab3caa6e913530bcc23ea42cc0b4443")
  (equation-ranges (3974 3974))
  (status executable)
  (port-state ported)
  (dependencies ¬ AtLeast)
  (legacy-implementations)
  (implementations
   (metafunction
    "tools/smusni-redex/port-a0.rkt"
    b1-expand-fewer-than
    (cases negated-at-least)))
  (domains)
  (reason "B1 ports negated AtLeast, including the zero boundary."))
 (definition
  (id "D12.GlobalExactly")
  (head GlobalExactly)
  (section "12")
  (spec-source-sha1 "47fb0dfaf4d56b4da299841850d15d75760eb86b")
  (spec-source-ranges (3975 3975))
  (equation-source-sha1 "47fb0dfaf4d56b4da299841850d15d75760eb86b")
  (equation-ranges (3975 3975))
  (status executable)
  (port-state a0)
  (dependencies = Card SetOf λ ∧)
  (legacy-implementations
   (binding "tools/smusni-redex/lower.rkt" expand-global-exactly-datum)
   (binding "tools/smusni-redex/lower.rkt" global-exactly-definition))
  (implementations
   (metafunction
    "tools/smusni-redex/port-a0.rkt"
    a0-expand-global-exactly
    (cases comprehension)))
  (domains)
  (reason
   "A0 ports the pure comprehension equation alongside the retained legacy path."))
 (definition
  (id "D12.Grade")
  (head Grade)
  (section "12")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies InRegion)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason
   "Its row-polymorphic executable family has not yet reached the Redex port."))
 (definition
  (id "D12.GroundedBy")
  (head GroundedBy)
  (section "12")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies Bind Perform Do)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason "Its performance family has not yet reached the Redex port."))
 (definition
  (id "D12.Interval")
  (head Interval)
  (section "12")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies SetOf)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason
   "Its endpoint-kind parameterized family has not yet reached the Redex port."))
 (definition
  (id "D12.JaiPromote")
  (head JaiPromote)
  (section "12")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies PredTerm Record)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason "Its row-reconstruction schema has not yet reached the Redex port."))
 (definition
  (id "D12.JaiRaise")
  (head JaiRaise)
  (section "12")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies PredTerm JaiRoleAdmissible)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason "Its row-reconstruction schema has not yet reached the Redex port."))
 (definition
  (id "D12.JoiClause")
  (head JoiClause)
  (section "12")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies Bind Context Combine CloseClause)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason "Its event-construction family has not yet reached the Redex port."))
 (definition
  (id "D12.JoiEvent")
  (head JoiEvent)
  (section "12")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies Bind Combine CanonicalAggregateAt)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason "Its event-group family has not yet reached the Redex port."))
 (definition
  (id "D12.JoiGroup")
  (head JoiGroup)
  (section "12")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies Massify Combine)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason
   "Its expected-type-directed family has not yet reached the Redex port."))
 (definition
  (id "D12.JoiPred")
  (head JoiPred)
  (section "12")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies GunmaPredAt MixAt)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason "Its contribution-basis family has not yet reached the Redex port."))
 (definition
  (id "D12.JoiTanru")
  (head JoiTanru)
  (section "12")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies Bind Context JoiPred)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason
   "Its source-ordered link schema has not yet reached the Redex port."))
 (definition
  (id "D12.Many")
  (head Many)
  (section "12")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies Bind Vague AdmissibleThreshold AtLeast)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason
   "Its effectful threshold family has not yet reached the Redex port."))
 (definition
  (id "D12.Massify")
  (head Massify)
  (section "12")
  (spec-source-sha1 "f349c991313130c32515ac092f1f6472fbeb588a")
  (spec-source-ranges (4177 4180))
  (equation-source-sha1 "f349c991313130c32515ac092f1f6472fbeb588a")
  (equation-ranges (4177 4180))
  (status executable)
  (port-state a0)
  (dependencies Refer λ ∃ ∧ CanonicalAggregateAt CoRef)
  (legacy-implementations)
  (implementations
   (metafunction
    "tools/smusni-redex/port-a0.rkt"
    a0-expand-massify
    (cases canonical-reference)))
  (domains)
  (reason
   "E01 replaces cardinal selection by reference-level existential co-reference to one canonical aggregate, per current §12."))
 (definition
  (id "D12.MaxRefer")
  (head MaxRefer)
  (section "12")
  (spec-source-sha1 "49f3e4ed5e120525da98dbbdc54a963e370d7ddb")
  (spec-source-ranges (4268 4272))
  (equation-source-sha1 "49f3e4ed5e120525da98dbbdc54a963e370d7ddb")
  (equation-ranges (4268 4272))
  (status executable)
  (port-state ported)
  (dependencies Presuppose ∃ Refer λ ∧ CoveredBy ∀ → Among)
  (legacy-implementations)
  (implementations
   (metafunction
    "tools/smusni-redex/port-a0.rkt"
    b1-expand-max-refer
    (cases inhabited-maximal-reference)))
  (domains)
  (reason
   "B1 ports inhabited maximal reference construction with its projective obligation."))
 (definition
  (id "D12.MePred")
  (head MePred)
  (section "12")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies Among)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason
   "Its type-directed property expansion has not yet reached the Redex port."))
 (definition
  (id "D12.MemberCover")
  (head MemberCover)
  (section "12")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies Distrib Among Overlap)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason
   "Its positive-MEI helper expansion has not yet reached the Redex port."))
 (definition
  (id "D12.MetricBall")
  (head MetricBall)
  (section "12")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies SetOf)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason
   "Its endpoint-kind parameterized family has not yet reached the Redex port."))
 (definition
  (id "D12.MoreThan")
  (head MoreThan)
  (section "12")
  (spec-source-sha1 "e0b6c474cb50acb0908bcac77d4b997b02b5cdd3")
  (spec-source-ranges (3973 3973))
  (equation-source-sha1 "e0b6c474cb50acb0908bcac77d4b997b02b5cdd3")
  (equation-ranges (3973 3973))
  (status executable)
  (port-state ported)
  (dependencies AtLeast +)
  (legacy-implementations)
  (implementations
   (metafunction
    "tools/smusni-redex/port-a0.rkt"
    b1-expand-more-than
    (cases successor)))
  (domains)
  (reason "B1 ports successor-strength AtLeast over a general Natural term."))
 (definition
  (id "D12.Most")
  (head Most)
  (section "12")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status (blocked "#66"))
  (port-state none)
  (dependencies Card SetOf >)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason
   "Its definition needs the separately scoped greater-than operator in issue #66."))
 (definition
  (id "D12.NahiObjection")
  (head NahiObjection)
  (section "12")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies MetalinguisticallyDefective TargetContent)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason "Its act-occurrence family has not yet reached the Redex port."))
 (definition
  (id "D12.Named")
  (head Named)
  (section "12")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies Close cmene NameSign)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason "Its executable family has not yet reached the Redex port."))
 (definition
  (id "D12.No")
  (head No)
  (section "12")
  (spec-source-sha1 "b69f31c9cc18589805ac7a4ef3705d240ef2333f")
  (spec-source-ranges (3971 3971))
  (equation-source-sha1 "b69f31c9cc18589805ac7a4ef3705d240ef2333f")
  (equation-ranges (3971 3971))
  (status executable)
  (port-state ported)
  (dependencies ¬ Some)
  (legacy-implementations)
  (implementations
   (metafunction
    "tools/smusni-redex/port-a0.rkt"
    b1-expand-no
    (cases negated-some)))
  (domains)
  (reason "B1 ports generic negation of Some."))
 (definition
  (id "D12.Only")
  (head Only)
  (section "12")
  (spec-source-sha1 "7a994a5bfd9dec77a3cf27344d4b7ad733d750d9")
  (spec-source-ranges (4466 4474))
  (equation-source-sha1 "b58992d66c05b51af4d2b185bc1cf217f740aca8")
  (equation-ranges (4470 4474))
  (status executable)
  (port-state ported)
  (dependencies ∧ ∀ λ → Among)
  (legacy-implementations)
  (implementations
   (metafunction
    "tools/smusni-redex/port-a0.rkt"
    e01-expand-only
    (cases host-and-exclusion)))
  (domains)
  (reason
   "E01 ports the adopted pure host-and-exclusion formula. Effectful frames remain the §14 gap."))
 (definition
  (id "D12.Overlap")
  (head Overlap)
  (section "12")
  (spec-source-sha1 "7e5470addbab1e78a5399f30e90fa7613ca3f83b")
  (spec-source-ranges (4223 4223))
  (equation-source-sha1 "7e5470addbab1e78a5399f30e90fa7613ca3f83b")
  (equation-ranges (4223 4223))
  (status executable)
  (port-state ported)
  (dependencies ∃ λ ∧ Among)
  (legacy-implementations)
  (implementations
   (metafunction
    "tools/smusni-redex/port-a0.rkt"
    b1-expand-overlap
    (cases common-subreference)))
  (domains)
  (reason "B1 ports existential common-subreference overlap."))
 (definition
  (id "D12.Realized")
  (head Realized)
  (section "12")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies EventOfContent fasnu)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason "Its clause-event family has not yet reached the Redex port."))
 (definition
  (id "D12.Reciprocate")
  (head Reciprocate)
  (section "12")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies Among CoRef)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason "Its executable family has not yet reached the Redex port."))
 (definition
  (id "D12.RegionComplement")
  (head RegionComplement)
  (section "12")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies SetOf)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason "Its region family has not yet reached the Redex port."))
 (definition
  (id "D12.RoiClause")
  (head RoiClause)
  (section "12")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies Card SetOf During)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason "Its event-counting family has not yet reached the Redex port."))
 (definition
  (id "D12.Some")
  (head Some)
  (section "12")
  (spec-source-sha1 "e81639d24c55ea188c28e08d6ca69abb56a2aefb")
  (spec-source-ranges (3965 3965))
  (equation-source-sha1 "e81639d24c55ea188c28e08d6ca69abb56a2aefb")
  (equation-ranges (3965 3965))
  (status executable)
  (port-state ported)
  (dependencies Bind SelectSome)
  (legacy-implementations)
  (implementations
   (metafunction
    "tools/smusni-redex/port-a0.rkt"
    b1-expand-some
    (cases witness)))
  (domains)
  (reason "B1 ports witness selection and export through SelectSome."))
 (definition
  (id "D12.SpanRegion")
  (head SpanRegion)
  (section "12")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies SetOf)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason
   "Its endpoint-kind parameterized family has not yet reached the Redex port."))
 (definition
  (id "D12.SpeakerDescribes")
  (head SpeakerDescribes)
  (section "12")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies LocutionOf skicu)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason "Its executable family has not yet reached the Redex port."))
 (definition
  (id "D12.SpeakerDescribesUnaddressed")
  (head SpeakerDescribesUnaddressed)
  (section "12")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies LocutionOf skicu)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason "Its executable family has not yet reached the Redex port."))
 (definition
  (id "D12.TanruLinkConnect")
  (head TanruLinkConnect)
  (section "12")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies Bind Context)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason
   "Its source-ordered connective schema has not yet reached the Redex port."))
 (definition
  (id "D12.TooFew")
  (head TooFew)
  (section "12")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies Bind Context Vague AdmissibleThreshold FewerThan)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason
   "Its effectful threshold family has not yet reached the Redex port."))
 (definition
  (id "D12.TooMany")
  (head TooMany)
  (section "12")
  (spec-source-sha1 "2701973ef8253e5ed8036e230f8ee8612c267aeb")
  (spec-source-ranges (4055 4057))
  (equation-source-sha1 "2701973ef8253e5ed8036e230f8ee8612c267aeb")
  (equation-ranges (4055 4057))
  (status executable)
  (port-state a0)
  (dependencies Bind Context Vague AdmissibleThreshold MoreThan)
  (legacy-implementations)
  (implementations
   (metafunction
    "tools/smusni-redex/port-a0.rkt"
    a0-expand-too-many
    (cases dependent-threshold)))
  (domains)
  (reason "A0 ports the ordered purpose and dependent threshold expansion."))
 (definition
  (id "D12.UnrealizedClause")
  (head UnrealizedClause)
  (section "12")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies StateClause Realizable)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason "Its executable family has not yet reached the Redex port."))
 (definition
  (id "D12.ZipWith")
  (head ZipWith)
  (section "12")
  (spec-source-sha1 "5fca0a2d8d3050f438ac9d99c44afdb74f4bdd6c")
  (spec-source-ranges (4244 4246))
  (equation-source-sha1 "5fca0a2d8d3050f438ac9d99c44afdb74f4bdd6c")
  (equation-ranges (4244 4246))
  (status executable)
  (port-state a0)
  (dependencies ∧ List)
  (legacy-implementations)
  (implementations
   (metafunction
    "tools/smusni-redex/port-a0.rkt"
    a0-expand-zipwith
    (cases empty paired-step)))
  (domains
   (domain
    equal-length
    (status executable)
    (port-state a0)
    (reason "A0 ports the settled base and paired recursive equations."))
   (domain
    unequal-length
    (status (blocked "#41"))
    (port-state none)
    (reason
     "Unequal-list behavior is human-partner-open in issue #41 item 6.")))
  (reason
   "Its settled equal-length recursion awaits A0 while unequal length remains blocked."))
 (definition
  (id "D12.gei")
  (head gei)
  (section "12")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies |te'a|)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason "Its recursive MEX family has not yet reached the Redex port."))
 (definition
  (id "D12.na'i-objection-prose")
  (head |na'i-objection-prose|)
  (section "12")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status not-a-definition)
  (port-state none)
  (dependencies NahiObjection)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason
   "This prose lead-in announces the following NahiObjection equation and is not a separate definition."))
 (definition
  (id "D12.te'a")
  (head |te'a|)
  (section "12")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies Natural)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason "Its recursive MEX family has not yet reached the Redex port."))
 (definition
  (id "D12.xi")
  (head xi)
  (section "12")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies List)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason
   "Its recursive list-index family has not yet reached the Redex port."))
 (definition
  (id "D4.1.At")
  (head At)
  (section "4.1")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies RowMinus)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason "Its row-application family has not yet reached the Redex port."))
 (definition
  (id "D4.1.klama-fill-examples")
  (head klama)
  (section "4.1")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status mapping-schema)
  (port-state none)
  (dependencies At)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason
   "These two equations illustrate positional fill notation rather than define the klama lexical row."))
 (definition
  (id "D4.4.Let")
  (head Let)
  (section "4.4")
  (spec-source-sha1 "18496b62c492f3c258d47972a9495d5338af6a4b")
  (spec-source-ranges (623 623))
  (equation-source-sha1 "18496b62c492f3c258d47972a9495d5338af6a4b")
  (equation-ranges (623 623))
  (status executable)
  (port-state a0)
  (dependencies λ)
  (legacy-implementations)
  (implementations
   (metafunction "tools/smusni-redex/port-a0.rkt" a0-expand-let (cases beta)))
  (domains)
  (reason "A0 ports direct Let as immediate pure lambda application."))
 (definition
  (id "D4.6.ClauseAnd")
  (head ClauseAnd)
  (section "4.6")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies StateClause CloseClause)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason "Its clause-event family has not yet reached the Redex port."))
 (definition
  (id "D4.6.ClauseIff")
  (head ClauseIff)
  (section "4.6")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies StateClause CloseClause)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason "Its clause-event family has not yet reached the Redex port."))
 (definition
  (id "D4.6.ClauseImp")
  (head ClauseImp)
  (section "4.6")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies StateClause CloseClause)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason "Its clause-event family has not yet reached the Redex port."))
 (definition
  (id "D4.6.ClauseNot")
  (head ClauseNot)
  (section "4.6")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies StateClause CloseClause)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason "Its clause-event family has not yet reached the Redex port."))
 (definition
  (id "D4.6.ClauseOr")
  (head ClauseOr)
  (section "4.6")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies CloseClause)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason "Its clause-event family has not yet reached the Redex port."))
 (definition
  (id "D4.6.ClauseXor")
  (head ClauseXor)
  (section "4.6")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies StateClause CloseClause)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason "Its clause-event family has not yet reached the Redex port."))
 (definition
  (id "D4.6.Close")
  (head Close)
  (section "4.6")
  (spec-source-sha1 "7624d09ef6f342a6e52cc0ff4e9b02e0de0b4275")
  (spec-source-ranges (714 723))
  (status executable)
  (port-state a0)
  (dependencies CloseClause ActualClause DirectClause)
  (legacy-implementations
   (binding "tools/smusni-redex/lower.rkt" expand-close-datum)
   (binding "tools/smusni-redex/lower.rkt" close-out))
  (implementations
   (metafunction
    "tools/smusni-redex/port-a0.rkt"
    a0-expand-close
    (cases holding-state direct-event-implicit direct-event-explicit)))
  (domains)
  (reason
   "A0 ports all three Close equations over an explicit adapter-supplied row declaration."))
 (definition
  (id "D4.6.DirectClause")
  (head DirectClause)
  (section "4.6")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies Bind Context StateClause)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason
   "Its row-aware direct-event family has not yet reached the Redex port."))
 (definition
  (id "D4.8.CardBasis")
  (head CardBasis)
  (section "4.8")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies Card UnitSet)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason "Its executable family has not yet reached the Redex port."))
 (definition
  (id "D4.8.CoveredBy")
  (head CoveredBy)
  (section "4.8")
  (spec-source-sha1 "b6b93d282c50e93e7777d034643f3438b975b17a")
  (spec-source-ranges (830 840))
  (equation-source-sha1 "d88bff73fcbab94fef4fe445e536440aa0599535")
  (equation-ranges (834 840))
  (status executable)
  (port-state ported)
  (dependencies ∧ Distrib ∀ λ → Among ∃ Overlap)
  (legacy-implementations)
  (implementations
   (metafunction
    "tools/smusni-redex/port-a0.rkt"
    b1-expand-covered-by
    (cases no-residue)))
  (domains)
  (reason "B1 ports the no-residue plural coverage equation."))
 (definition
  (id "D4.9.greater-than")
  (head >)
  (section "4.9")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status (blocked "#66"))
  (port-state none)
  (dependencies <)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason
   "The greater-than derived comparison is separately scoped in issue #66."))
 (definition
  (id "D4.9.CompleteGunmaAt")
  (head CompleteGunmaAt)
  (section "4.9")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies GunmaAt PeerUnitAt BasisUnitAt)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason "Its constitution family has not yet reached the Redex port."))
 (definition
  (id "D4.9.ComponentAt")
  (head ComponentAt)
  (section "4.9")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies GunmaAt)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason "Its constitution family has not yet reached the Redex port."))
 (definition
  (id "D4.9.GunmaAt")
  (head GunmaAt)
  (section "4.9")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies PeerUnitAt BasisUnitAt CoRef)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason "Its constitution family has not yet reached the Redex port."))
 (definition
  (id "D4.9.GunmaPredAt")
  (head GunmaPredAt)
  (section "4.9")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies ContributionBasis GunmaAt)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason
   "Its compatible-predicate constitution family has not yet reached the Redex port."))
 (definition
  (id "D5.1.That")
  (head That)
  (section "5.1")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status metatheory-or-model-law)
  (port-state none)
  (dependencies Deictic)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason
   "This abbreviation projects the model context ground and is not a closed term rewrite."))
 (definition
  (id "D5.1.This")
  (head This)
  (section "5.1")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status metatheory-or-model-law)
  (port-state none)
  (dependencies Deictic)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason
   "This abbreviation projects the model context ground and is not a closed term rewrite."))
 (definition
  (id "D5.1.Yonder")
  (head Yonder)
  (section "5.1")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status metatheory-or-model-law)
  (port-state none)
  (dependencies Deictic)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason
   "This abbreviation projects the model context ground and is not a closed term rewrite."))
 (definition
  (id "D5.3.Refer-member-lift")
  (head Refer)
  (section "5.3")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies CoveredBy)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason "Its type-directed overload has not yet reached the Redex port."))
 (definition
  (id "D5.6.SelectSome")
  (head SelectSome)
  (section "5.6")
  (spec-source-sha1 "584162d656964354d08083ba428eeb2329207c24")
  (spec-source-ranges (1801 1801))
  (equation-source-sha1 "584162d656964354d08083ba428eeb2329207c24")
  (equation-ranges (1801 1801))
  (status executable)
  (port-state ported)
  (dependencies SelectAtLeast)
  (legacy-implementations)
  (implementations
   (metafunction
    "tools/smusni-redex/port-a0.rkt"
    b1-expand-select-some
    (cases at-least-one)))
  (domains)
  (reason "B1 ports SelectSome as SelectAtLeast one."))
 (definition
  (id "D6.2.Tanru")
  (head Tanru)
  (section "6.2")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies Bind Context)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason
   "Its fills-parameterized expansion is executable but has not yet reached the Redex port."))
 (definition
  (id "D7.4.Utterance-entry")
  (head Utterance)
  (section "7.4")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status mapping-schema)
  (port-state none)
  (dependencies UtteranceToken)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason
   "This equation defines compact entry notation rather than an ordinary term former."))
 (definition
  (id "D8.2.Answer-contextual")
  (head Answer)
  (section "8.2")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies Bind Context TupleAnswer PolarAnswer)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason
   "Its query-type-directed overload has not yet reached the Redex port."))
 (definition
  (id "D9.1.Meau0")
  (head Meau0)
  (section "9.1")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies Presuppose Holds Reify)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason "Its abstraction bridge family has not yet reached the Redex port."))
 (definition
  (id "D9.2.DuhuRel")
  (head DuhuRel)
  (section "9.2")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies CoRef Reify Distrib InterpretContent)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason
   "Its abstraction-relation family has not yet reached the Redex port."))
 (definition
  (id "D12.IndividualSome")
  (head IndividualSome)
  (section "12")
  (spec-source-sha1 "82c1491d7d633d55c090334a7f90cf1fbdbc1854")
  (spec-source-ranges (3927 3927) (3922 3924) (3934 3947))
  (equation-source-sha1 "71049b2359450a22a2a7f4929df6dbd8be73b37e")
  (equation-ranges (3927 3927))
  (status executable)
  (port-state ported)
  (dependencies ∃ λ ∧)
  (legacy-implementations)
  (implementations
   (metafunction
    "tools/smusni-redex/port-a0.rkt"
    e01-expand-individual-some
    (cases individual-exists)))
  (domains)
  (reason
   "E01 ports the adopted ordinary closure equation; no outward reference introduction."))
 (definition
  (id "D12.IndividualNo")
  (head IndividualNo)
  (section "12")
  (spec-source-sha1 "aa45169256596a92ae1ca4b8837cfec4b76cc02c")
  (spec-source-ranges (3928 3928) (3922 3924) (3934 3947))
  (equation-source-sha1 "1c308073c3f28ffc7ce2a4be59cdfd1412fc35b2")
  (equation-ranges (3928 3928))
  (status executable)
  (port-state ported)
  (dependencies ¬ IndividualSome)
  (legacy-implementations)
  (implementations
   (metafunction
    "tools/smusni-redex/port-a0.rkt"
    e01-expand-individual-no
    (cases negated-individual-exists)))
  (domains)
  (reason
   "E01 ports the adopted ordinary closure equation; no outward reference introduction."))
 (definition
  (id "D12.IndividualEvery")
  (head IndividualEvery)
  (section "12")
  (spec-source-sha1 "5d031a98d9d43f3bf445c58737c8b2e82604b478")
  (spec-source-ranges (3929 3929) (3922 3924) (3934 3947))
  (equation-source-sha1 "9f0293c2b70588603ba9eeb7ba6d746666c3aff0")
  (equation-ranges (3929 3929))
  (status executable)
  (port-state ported)
  (dependencies ∀ λ →)
  (legacy-implementations)
  (implementations
   (metafunction
    "tools/smusni-redex/port-a0.rkt"
    e01-expand-individual-every
    (cases individual-forall)))
  (domains)
  (reason
   "E01 ports the adopted ordinary closure equation; no outward reference introduction."))
 (definition
  (id "D12.PluralSome")
  (head PluralSome)
  (section "12")
  (spec-source-sha1 "22886cc4766cfeed287d6d181c14d3e829465e5a")
  (spec-source-ranges (3930 3930) (3922 3924) (3934 3947))
  (equation-source-sha1 "15fcbf0115d05eaad4916a7d972ee908f2277234")
  (equation-ranges (3930 3930))
  (status executable)
  (port-state ported)
  (dependencies ∃ λ ∧)
  (legacy-implementations)
  (implementations
   (metafunction
    "tools/smusni-redex/port-a0.rkt"
    e01-expand-plural-some
    (cases plural-exists)))
  (domains)
  (reason
   "E01 ports the adopted ordinary closure equation; no outward reference introduction."))
 (definition
  (id "D12.PluralNo")
  (head PluralNo)
  (section "12")
  (spec-source-sha1 "0fb217a1e625d56c957795e21fbf4b1b2c5b43ca")
  (spec-source-ranges (3931 3931) (3922 3924) (3934 3947))
  (equation-source-sha1 "f320d571d896dad8ffc4645fb8883581e2ad7fdf")
  (equation-ranges (3931 3931))
  (status executable)
  (port-state ported)
  (dependencies ¬ PluralSome)
  (legacy-implementations)
  (implementations
   (metafunction
    "tools/smusni-redex/port-a0.rkt"
    e01-expand-plural-no
    (cases negated-plural-exists)))
  (domains)
  (reason
   "E01 ports the adopted ordinary closure equation; no outward reference introduction.")))
