(smusni-definition-ledger
 1
 (definition
  (id "D12.ActualClause")
  (head ActualClause)
  (section "12")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies StateClause fasnu)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason "Its executable family has not yet reached the Redex port."))
 (definition
  (id "D12.AtLeast")
  (head AtLeast)
  (section "12")
  (spec-source-sha1 "76f7c0f017d60aad6103f05d5844caa47f41e4bc")
  (spec-source-ranges (3795 3795) (3833 3833) (3824 3830))
  (equation-source-sha1 "305d1d5a1d5d55369138269c4ba9077fec5c71b1")
  (equation-ranges (3795 3795) (3833 3833))
  (status executable)
  (port-state ported)
  (dependencies Bind SelectAtLeast)
  (legacy-implementations)
  (implementations
   (metafunction
    "tools/smusni-redex/port-a0.rkt"
    b1-expand-at-least
    (cases zero positive)))
  (domains
   (domain
    symbolic-natural
    (status executable)
    (port-state none)
    (reason
     "Direct typing is total, but the two-equation metafunction cannot choose zero or positive before a symbolic Natural is instantiated.")))
  (reason
   "B1 ports the separate zero and provably-positive witness equations."))
 (definition
  (id "D12.AtMost")
  (head AtMost)
  (section "12")
  (spec-source-sha1 "ba5ca37a04a679e13253f0dbda3b7017315903e7")
  (spec-source-ranges (3803 3803))
  (equation-source-sha1 "ba5ca37a04a679e13253f0dbda3b7017315903e7")
  (equation-ranges (3803 3803))
  (status executable)
  (port-state ported)
  (dependencies ¬ AtLeast +)
  (legacy-implementations)
  (implementations
   (metafunction
    "tools/smusni-redex/port-a0.rkt"
    b1-expand-at-most
    (cases negated-successor)))
  (domains)
  (reason "B1 ports negated successor-strength AtLeast."))
 (definition
  (id "D12.COI-schemas-prose")
  (head COI-schemas-prose)
  (section "12")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status not-a-definition)
  (port-state none)
  (dependencies COIExpress)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason
   "This prose introducer points to the following COIExpress schema and is not a separate equation."))
 (definition
  (id "D12.COIExpress")
  (head COIExpress)
  (section "12")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies Express Close)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason
   "The lexicon-parameterized performative schema awaits its executable family."))
 (definition
  (id "D12.CanonicalAggregateAt")
  (head CanonicalAggregateAt)
  (section "12")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies Aggregate CompleteGunmaAt)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason "Its executable family has not yet reached the Redex port."))
 (definition
  (id "D12.CapableClause")
  (head CapableClause)
  (section "12")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies StateClause InnatelyCapable)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason "Its executable family has not yet reached the Redex port."))
 (definition
  (id "D12.CoRef")
  (head CoRef)
  (section "12")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies Among)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason "Its executable family has not yet reached the Redex port."))
 (definition
  (id "D12.DemonstratedClause")
  (head DemonstratedClause)
  (section "12")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies StateClause DemonstrablyRealized)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason "Its executable family has not yet reached the Redex port."))
 (definition
  (id "D12.Distrib")
  (head Distrib)
  (section "12")
  (spec-source-sha1 "416c89d5b45496813a6720dbeec2b370fac3af1e")
  (spec-source-ranges (3807 3807))
  (equation-source-sha1 "416c89d5b45496813a6720dbeec2b370fac3af1e")
  (equation-ranges (3807 3807))
  (status executable)
  (port-state ported)
  (dependencies ∀ λ → Among)
  (legacy-implementations)
  (implementations
   (metafunction
    "tools/smusni-redex/port-a0.rkt"
    b1-expand-distrib
    (cases universal-members)))
  (domains)
  (reason "B1 ports universal member distribution over a plural reference."))
 (definition
  (id "D12.Enough")
  (head Enough)
  (section "12")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies Bind Context Vague AdmissibleThreshold AtLeast)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason
   "Its effectful threshold family has not yet reached the Redex port."))
 (definition
  (id "D12.Every")
  (head Every)
  (section "12")
  (spec-source-sha1 "43d91f202246b5d926c85ccd67c93c776e38dd4f")
  (spec-source-ranges (3797 3798))
  (equation-source-sha1 "43d91f202246b5d926c85ccd67c93c776e38dd4f")
  (equation-ranges (3797 3798))
  (status executable)
  (port-state ported)
  (dependencies Bind MaxRefer Distrib)
  (legacy-implementations)
  (implementations
   (metafunction
    "tools/smusni-redex/port-a0.rkt"
    b1-expand-every
    (cases maximal-distribution)))
  (domains)
  (reason "B1 ports maximal witness import followed by member distribution."))
 (definition
  (id "D12.Exactly")
  (head Exactly)
  (section "12")
  (spec-source-sha1 "96fead33c47b804cdf4362a33f7b63315dd4fee5")
  (spec-source-ranges (3794 3794) (3834 3834) (3824 3830))
  (equation-source-sha1 "1767c6672a9637c95f285dc62057f4983fa359b3")
  (equation-ranges (3794 3794) (3834 3834))
  (status executable)
  (port-state a0)
  (dependencies Bind SelectExactly No)
  (legacy-implementations)
  (implementations
   (metafunction
    "tools/smusni-redex/port-a0.rkt"
    a0-expand-exactly
    (cases zero positive)))
  (domains)
  (reason "A0 ports both the zero and positive witness-set equations."))
 (definition
  (id "D12.Few")
  (head Few)
  (section "12")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies Bind Vague AdmissibleThreshold FewerThan)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason
   "Its effectful threshold family has not yet reached the Redex port."))
 (definition
  (id "D12.FewerThan")
  (head FewerThan)
  (section "12")
  (spec-source-sha1 "f424215f418759ddd444f811ee1622d755cacd76")
  (spec-source-ranges (3805 3805))
  (equation-source-sha1 "f424215f418759ddd444f811ee1622d755cacd76")
  (equation-ranges (3805 3805))
  (status executable)
  (port-state ported)
  (dependencies ¬ AtLeast)
  (legacy-implementations)
  (implementations
   (metafunction
    "tools/smusni-redex/port-a0.rkt"
    b1-expand-fewer-than
    (cases negated-at-least)))
  (domains)
  (reason "B1 ports negated AtLeast, including the zero boundary."))
 (definition
  (id "D12.GlobalExactly")
  (head GlobalExactly)
  (section "12")
  (spec-source-sha1 "42e64c6d1fa200eb622e11e74465356ada50bc68")
  (spec-source-ranges (3806 3806))
  (equation-source-sha1 "42e64c6d1fa200eb622e11e74465356ada50bc68")
  (equation-ranges (3806 3806))
  (status executable)
  (port-state a0)
  (dependencies = Card SetOf λ ∧)
  (legacy-implementations
   (binding "tools/smusni-redex/lower.rkt" expand-global-exactly-datum)
   (binding "tools/smusni-redex/lower.rkt" global-exactly-definition))
  (implementations
   (metafunction
    "tools/smusni-redex/port-a0.rkt"
    a0-expand-global-exactly
    (cases comprehension)))
  (domains)
  (reason
   "A0 ports the pure comprehension equation alongside the retained legacy path."))
 (definition
  (id "D12.Grade")
  (head Grade)
  (section "12")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies InRegion)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason
   "Its row-polymorphic executable family has not yet reached the Redex port."))
 (definition
  (id "D12.GroundedBy")
  (head GroundedBy)
  (section "12")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies Bind Perform Do)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason "Its performance family has not yet reached the Redex port."))
 (definition
  (id "D12.Interval")
  (head Interval)
  (section "12")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies SetOf)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason
   "Its endpoint-kind parameterized family has not yet reached the Redex port."))
 (definition
  (id "D12.JaiPromote")
  (head JaiPromote)
  (section "12")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies PredTerm Record)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason "Its row-reconstruction schema has not yet reached the Redex port."))
 (definition
  (id "D12.JaiRaise")
  (head JaiRaise)
  (section "12")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies PredTerm JaiRoleAdmissible)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason "Its row-reconstruction schema has not yet reached the Redex port."))
 (definition
  (id "D12.JoiClause")
  (head JoiClause)
  (section "12")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies Bind Context Combine CloseClause)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason "Its event-construction family has not yet reached the Redex port."))
 (definition
  (id "D12.JoiEvent")
  (head JoiEvent)
  (section "12")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies Bind Combine CanonicalAggregateAt)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason "Its event-group family has not yet reached the Redex port."))
 (definition
  (id "D12.JoiGroup")
  (head JoiGroup)
  (section "12")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies Massify Combine)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason
   "Its expected-type-directed family has not yet reached the Redex port."))
 (definition
  (id "D12.JoiPred")
  (head JoiPred)
  (section "12")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies GunmaPredAt MixAt)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason "Its contribution-basis family has not yet reached the Redex port."))
 (definition
  (id "D12.JoiTanru")
  (head JoiTanru)
  (section "12")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies Bind Context JoiPred)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason
   "Its source-ordered link schema has not yet reached the Redex port."))
 (definition
  (id "D12.Many")
  (head Many)
  (section "12")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies Bind Vague AdmissibleThreshold AtLeast)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason
   "Its effectful threshold family has not yet reached the Redex port."))
 (definition
  (id "D12.Massify")
  (head Massify)
  (section "12")
  (spec-source-sha1 "0cceeea9a492994148d45e498f1c805e028ac67f")
  (spec-source-ranges (4004 4007))
  (equation-source-sha1 "0cceeea9a492994148d45e498f1c805e028ac67f")
  (equation-ranges (4004 4007))
  (status executable)
  (port-state a0)
  (dependencies Refer λ ∃ ∧ CanonicalAggregateAt CoRef)
  (legacy-implementations)
  (implementations
   (metafunction
    "tools/smusni-redex/port-a0.rkt"
    a0-expand-massify
    (cases canonical-reference)))
  (domains)
  (reason
   "E01 replaces cardinal selection by reference-level existential co-reference to one canonical aggregate, per current §12."))
 (definition
  (id "D12.MaxRefer")
  (head MaxRefer)
  (section "12")
  (spec-source-sha1 "c3954a9903f836b918d804428b4315318b51e8ad")
  (spec-source-ranges (4095 4099))
  (equation-source-sha1 "c3954a9903f836b918d804428b4315318b51e8ad")
  (equation-ranges (4095 4099))
  (status executable)
  (port-state ported)
  (dependencies Presuppose ∃ Refer λ ∧ CoveredBy ∀ → Among)
  (legacy-implementations)
  (implementations
   (metafunction
    "tools/smusni-redex/port-a0.rkt"
    b1-expand-max-refer
    (cases inhabited-maximal-reference)))
  (domains)
  (reason
   "B1 ports inhabited maximal reference construction with its projective obligation."))
 (definition
  (id "D12.MePred")
  (head MePred)
  (section "12")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies Among)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason
   "Its type-directed property expansion has not yet reached the Redex port."))
 (definition
  (id "D12.MemberCover")
  (head MemberCover)
  (section "12")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies Distrib Among Overlap)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason
   "Its positive-MEI helper expansion has not yet reached the Redex port."))
 (definition
  (id "D12.MetricBall")
  (head MetricBall)
  (section "12")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies SetOf)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason
   "Its endpoint-kind parameterized family has not yet reached the Redex port."))
 (definition
  (id "D12.MoreThan")
  (head MoreThan)
  (section "12")
  (spec-source-sha1 "8ea91779ec74102e06b1b5391c7a2fe328182aa3")
  (spec-source-ranges (3804 3804))
  (equation-source-sha1 "8ea91779ec74102e06b1b5391c7a2fe328182aa3")
  (equation-ranges (3804 3804))
  (status executable)
  (port-state ported)
  (dependencies AtLeast +)
  (legacy-implementations)
  (implementations
   (metafunction
    "tools/smusni-redex/port-a0.rkt"
    b1-expand-more-than
    (cases successor)))
  (domains)
  (reason "B1 ports successor-strength AtLeast over a general Natural term."))
 (definition
  (id "D12.Most")
  (head Most)
  (section "12")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status (blocked "#66"))
  (port-state none)
  (dependencies Card SetOf >)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason
   "Its definition needs the separately scoped greater-than operator in issue #66."))
 (definition
  (id "D12.NahiObjection")
  (head NahiObjection)
  (section "12")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies MetalinguisticallyDefective TargetContent)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason "Its act-occurrence family has not yet reached the Redex port."))
 (definition
  (id "D12.Named")
  (head Named)
  (section "12")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies Close cmene NameSign)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason "Its executable family has not yet reached the Redex port."))
 (definition
  (id "D12.No")
  (head No)
  (section "12")
  (spec-source-sha1 "da783bf2d4262abbfe69900a4ac21424efe4c0a4")
  (spec-source-ranges (3802 3802))
  (equation-source-sha1 "da783bf2d4262abbfe69900a4ac21424efe4c0a4")
  (equation-ranges (3802 3802))
  (status executable)
  (port-state ported)
  (dependencies ¬ Some)
  (legacy-implementations)
  (implementations
   (metafunction
    "tools/smusni-redex/port-a0.rkt"
    b1-expand-no
    (cases negated-some)))
  (domains)
  (reason "B1 ports generic negation of Some."))
 (definition
  (id "D12.Only")
  (head Only)
  (section "12")
  (spec-source-sha1 "775a738497f05cc03c34c47765fa5e65cca1d2c5")
  (spec-source-ranges (4293 4301))
  (equation-source-sha1 "4b44c98bbfc65815b02c26851476df4e68831dad")
  (equation-ranges (4297 4301))
  (status executable)
  (port-state ported)
  (dependencies ∧ ∀ λ → Among)
  (legacy-implementations)
  (implementations
   (metafunction
    "tools/smusni-redex/port-a0.rkt"
    e01-expand-only
    (cases host-and-exclusion)))
  (domains)
  (reason
   "E01 ports the adopted pure host-and-exclusion formula. Effectful frames remain the §14 gap."))
 (definition
  (id "D12.Overlap")
  (head Overlap)
  (section "12")
  (spec-source-sha1 "cf6f928614e72db6a923a0b4495ae6e18e4c1661")
  (spec-source-ranges (4050 4050))
  (equation-source-sha1 "cf6f928614e72db6a923a0b4495ae6e18e4c1661")
  (equation-ranges (4050 4050))
  (status executable)
  (port-state ported)
  (dependencies ∃ λ ∧ Among)
  (legacy-implementations)
  (implementations
   (metafunction
    "tools/smusni-redex/port-a0.rkt"
    b1-expand-overlap
    (cases common-subreference)))
  (domains)
  (reason "B1 ports existential common-subreference overlap."))
 (definition
  (id "D12.Realized")
  (head Realized)
  (section "12")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies EventOfContent fasnu)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason "Its clause-event family has not yet reached the Redex port."))
 (definition
  (id "D12.Reciprocate")
  (head Reciprocate)
  (section "12")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies Among CoRef)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason "Its executable family has not yet reached the Redex port."))
 (definition
  (id "D12.RegionComplement")
  (head RegionComplement)
  (section "12")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies SetOf)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason "Its region family has not yet reached the Redex port."))
 (definition
  (id "D12.RoiClause")
  (head RoiClause)
  (section "12")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies Card SetOf During)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason "Its event-counting family has not yet reached the Redex port."))
 (definition
  (id "D12.Some")
  (head Some)
  (section "12")
  (spec-source-sha1 "d1d434cfcde56955918cf761de91cedb6aa2f897")
  (spec-source-ranges (3796 3796))
  (equation-source-sha1 "d1d434cfcde56955918cf761de91cedb6aa2f897")
  (equation-ranges (3796 3796))
  (status executable)
  (port-state ported)
  (dependencies Bind SelectSome)
  (legacy-implementations)
  (implementations
   (metafunction
    "tools/smusni-redex/port-a0.rkt"
    b1-expand-some
    (cases witness)))
  (domains)
  (reason "B1 ports witness selection and export through SelectSome."))
 (definition
  (id "D12.SpanRegion")
  (head SpanRegion)
  (section "12")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies SetOf)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason
   "Its endpoint-kind parameterized family has not yet reached the Redex port."))
 (definition
  (id "D12.SpeakerDescribes")
  (head SpeakerDescribes)
  (section "12")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies LocutionOf skicu)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason "Its executable family has not yet reached the Redex port."))
 (definition
  (id "D12.SpeakerDescribesUnaddressed")
  (head SpeakerDescribesUnaddressed)
  (section "12")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies LocutionOf skicu)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason "Its executable family has not yet reached the Redex port."))
 (definition
  (id "D12.TanruLinkConnect")
  (head TanruLinkConnect)
  (section "12")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies Bind Context)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason
   "Its source-ordered connective schema has not yet reached the Redex port."))
 (definition
  (id "D12.TooFew")
  (head TooFew)
  (section "12")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies Bind Context Vague AdmissibleThreshold FewerThan)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason
   "Its effectful threshold family has not yet reached the Redex port."))
 (definition
  (id "D12.TooMany")
  (head TooMany)
  (section "12")
  (spec-source-sha1 "ae9799c54c5a6ab0c6d56e118668c97836bfe53b")
  (spec-source-ranges (3886 3888))
  (equation-source-sha1 "ae9799c54c5a6ab0c6d56e118668c97836bfe53b")
  (equation-ranges (3886 3888))
  (status executable)
  (port-state a0)
  (dependencies Bind Context Vague AdmissibleThreshold MoreThan)
  (legacy-implementations)
  (implementations
   (metafunction
    "tools/smusni-redex/port-a0.rkt"
    a0-expand-too-many
    (cases dependent-threshold)))
  (domains)
  (reason "A0 ports the ordered purpose and dependent threshold expansion."))
 (definition
  (id "D12.UnrealizedClause")
  (head UnrealizedClause)
  (section "12")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies StateClause Realizable)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason "Its executable family has not yet reached the Redex port."))
 (definition
  (id "D12.ZipWith")
  (head ZipWith)
  (section "12")
  (spec-source-sha1 "aa7369a4a7c643f0ebf15f0d1cc039aa8723e0d0")
  (spec-source-ranges (4071 4073))
  (equation-source-sha1 "aa7369a4a7c643f0ebf15f0d1cc039aa8723e0d0")
  (equation-ranges (4071 4073))
  (status executable)
  (port-state a0)
  (dependencies ∧ List)
  (legacy-implementations)
  (implementations
   (metafunction
    "tools/smusni-redex/port-a0.rkt"
    a0-expand-zipwith
    (cases empty paired-step)))
  (domains
   (domain
    equal-length
    (status executable)
    (port-state a0)
    (reason "A0 ports the settled base and paired recursive equations."))
   (domain
    unequal-length
    (status (blocked "#41"))
    (port-state none)
    (reason
     "Unequal-list behavior is human-partner-open in issue #41 item 6.")))
  (reason
   "Its settled equal-length recursion awaits A0 while unequal length remains blocked."))
 (definition
  (id "D12.gei")
  (head gei)
  (section "12")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies |te'a|)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason "Its recursive MEX family has not yet reached the Redex port."))
 (definition
  (id "D12.na'i-objection-prose")
  (head |na'i-objection-prose|)
  (section "12")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status not-a-definition)
  (port-state none)
  (dependencies NahiObjection)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason
   "This prose lead-in announces the following NahiObjection equation and is not a separate definition."))
 (definition
  (id "D12.te'a")
  (head |te'a|)
  (section "12")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies Natural)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason "Its recursive MEX family has not yet reached the Redex port."))
 (definition
  (id "D12.xi")
  (head xi)
  (section "12")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies List)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason
   "Its recursive list-index family has not yet reached the Redex port."))
 (definition
  (id "D4.1.At")
  (head At)
  (section "4.1")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies RowMinus)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason "Its row-application family has not yet reached the Redex port."))
 (definition
  (id "D4.1.klama-fill-examples")
  (head klama)
  (section "4.1")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status mapping-schema)
  (port-state none)
  (dependencies At)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason
   "These two equations illustrate positional fill notation rather than define the klama lexical row."))
 (definition
  (id "D4.4.Let")
  (head Let)
  (section "4.4")
  (spec-source-sha1 "359463a1dce292f5e25bae88b199fbdfa080f831")
  (spec-source-ranges (664 664))
  (equation-source-sha1 "359463a1dce292f5e25bae88b199fbdfa080f831")
  (equation-ranges (664 664))
  (status executable)
  (port-state a0)
  (dependencies λ)
  (legacy-implementations)
  (implementations
   (metafunction "tools/smusni-redex/port-a0.rkt" a0-expand-let (cases beta)))
  (domains)
  (reason "A0 ports direct Let as immediate pure lambda application."))
 (definition
  (id "D4.6.ClauseAnd")
  (head ClauseAnd)
  (section "4.6")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies StateClause CloseClause)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason "Its clause-event family has not yet reached the Redex port."))
 (definition
  (id "D4.6.ClauseIff")
  (head ClauseIff)
  (section "4.6")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies StateClause CloseClause)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason "Its clause-event family has not yet reached the Redex port."))
 (definition
  (id "D4.6.ClauseImp")
  (head ClauseImp)
  (section "4.6")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies StateClause CloseClause)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason "Its clause-event family has not yet reached the Redex port."))
 (definition
  (id "D4.6.ClauseNot")
  (head ClauseNot)
  (section "4.6")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies StateClause CloseClause)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason "Its clause-event family has not yet reached the Redex port."))
 (definition
  (id "D4.6.ClauseOr")
  (head ClauseOr)
  (section "4.6")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies CloseClause)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason "Its clause-event family has not yet reached the Redex port."))
 (definition
  (id "D4.6.ClauseXor")
  (head ClauseXor)
  (section "4.6")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies StateClause CloseClause)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason "Its clause-event family has not yet reached the Redex port."))
 (definition
  (id "D4.6.Close")
  (head Close)
  (section "4.6")
  (spec-source-sha1 "dbc57435b66b6bdb5a92fa5e466c3380b1df1f6b")
  (spec-source-ranges (752 761))
  (status executable)
  (port-state a0)
  (dependencies CloseClause ActualClause DirectClause)
  (legacy-implementations
   (binding "tools/smusni-redex/lower.rkt" expand-close-datum)
   (binding "tools/smusni-redex/lower.rkt" close-out))
  (implementations
   (metafunction
    "tools/smusni-redex/port-a0.rkt"
    a0-expand-close
    (cases holding-state direct-event-implicit direct-event-explicit)))
  (domains)
  (reason
   "A0 ports all three Close equations over an explicit adapter-supplied row declaration."))
 (definition
  (id "D4.6.DirectClause")
  (head DirectClause)
  (section "4.6")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies Bind Context StateClause)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason
   "Its row-aware direct-event family has not yet reached the Redex port."))
 (definition
  (id "D4.8.CardBasis")
  (head CardBasis)
  (section "4.8")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies Card UnitSet)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason "Its executable family has not yet reached the Redex port."))
 (definition
  (id "D4.8.CoveredBy")
  (head CoveredBy)
  (section "4.8")
  (spec-source-sha1 "13fbff848b7b8397e5f3bdf15315286b620252cc")
  (spec-source-ranges (868 878))
  (equation-source-sha1 "468e6769d94c4a3acc7999c2bad4ad8ca002ca9c")
  (equation-ranges (872 878))
  (status executable)
  (port-state ported)
  (dependencies ∧ Distrib ∀ λ → Among ∃ Overlap)
  (legacy-implementations)
  (implementations
   (metafunction
    "tools/smusni-redex/port-a0.rkt"
    b1-expand-covered-by
    (cases no-residue)))
  (domains)
  (reason "B1 ports the no-residue plural coverage equation."))
 (definition
  (id "D4.9.greater-than")
  (head >)
  (section "4.9")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status (blocked "#66"))
  (port-state none)
  (dependencies <)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason
   "The greater-than derived comparison is separately scoped in issue #66."))
 (definition
  (id "D4.9.CompleteGunmaAt")
  (head CompleteGunmaAt)
  (section "4.9")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies GunmaAt PeerUnitAt BasisUnitAt)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason "Its constitution family has not yet reached the Redex port."))
 (definition
  (id "D4.9.ComponentAt")
  (head ComponentAt)
  (section "4.9")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies GunmaAt)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason "Its constitution family has not yet reached the Redex port."))
 (definition
  (id "D4.9.GunmaAt")
  (head GunmaAt)
  (section "4.9")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies PeerUnitAt BasisUnitAt CoRef)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason "Its constitution family has not yet reached the Redex port."))
 (definition
  (id "D4.9.GunmaPredAt")
  (head GunmaPredAt)
  (section "4.9")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies ContributionBasis GunmaAt)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason
   "Its compatible-predicate constitution family has not yet reached the Redex port."))
 (definition
  (id "D5.1.That")
  (head That)
  (section "5.1")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status metatheory-or-model-law)
  (port-state none)
  (dependencies Deictic)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason
   "This abbreviation projects the model context ground and is not a closed term rewrite."))
 (definition
  (id "D5.1.This")
  (head This)
  (section "5.1")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status metatheory-or-model-law)
  (port-state none)
  (dependencies Deictic)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason
   "This abbreviation projects the model context ground and is not a closed term rewrite."))
 (definition
  (id "D5.1.Yonder")
  (head Yonder)
  (section "5.1")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status metatheory-or-model-law)
  (port-state none)
  (dependencies Deictic)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason
   "This abbreviation projects the model context ground and is not a closed term rewrite."))
 (definition
  (id "D5.3.Refer-member-lift")
  (head Refer)
  (section "5.3")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies CoveredBy)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason "Its type-directed overload has not yet reached the Redex port."))
 (definition
  (id "D5.6.SelectSome")
  (head SelectSome)
  (section "5.6")
  (spec-source-sha1 "d987c2b372b1d3e1140ddb9a384e7129a71e7f9d")
  (spec-source-ranges (1798 1798))
  (equation-source-sha1 "d987c2b372b1d3e1140ddb9a384e7129a71e7f9d")
  (equation-ranges (1798 1798))
  (status executable)
  (port-state ported)
  (dependencies SelectAtLeast)
  (legacy-implementations)
  (implementations
   (metafunction
    "tools/smusni-redex/port-a0.rkt"
    b1-expand-select-some
    (cases at-least-one)))
  (domains)
  (reason "B1 ports SelectSome as SelectAtLeast one."))
 (definition
  (id "D6.2.Tanru")
  (head Tanru)
  (section "6.2")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies Bind Context)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason
   "Its fills-parameterized expansion is executable but has not yet reached the Redex port."))
 (definition
  (id "D7.4.Utterance-entry")
  (head Utterance)
  (section "7.4")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status mapping-schema)
  (port-state none)
  (dependencies UtteranceToken)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason
   "This equation defines compact entry notation rather than an ordinary term former."))
 (definition
  (id "D8.2.Answer-contextual")
  (head Answer)
  (section "8.2")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies Bind Context TupleAnswer PolarAnswer)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason
   "Its query-type-directed overload has not yet reached the Redex port."))
 (definition
  (id "D9.1.Meau0")
  (head Meau0)
  (section "9.1")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies Presuppose Holds Reify)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason "Its abstraction bridge family has not yet reached the Redex port."))
 (definition
  (id "D9.2.DuhuRel")
  (head DuhuRel)
  (section "9.2")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies CoRef Reify Distrib InterpretContent)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason
   "Its abstraction-relation family has not yet reached the Redex port."))
 (definition
  (id "D12.IndividualSome")
  (head IndividualSome)
  (section "12")
  (spec-source-sha1 "2f1c53a6a08bfe95ae5e03bfa3001d27507fda61")
  (spec-source-ranges (3758 3758) (3753 3755) (3765 3778))
  (equation-source-sha1 "380f30e9e22cbadcdfd7b3ee6ef452408055cbbc")
  (equation-ranges (3758 3758))
  (status executable)
  (port-state ported)
  (dependencies ∃ λ ∧)
  (legacy-implementations)
  (implementations
   (metafunction
    "tools/smusni-redex/port-a0.rkt"
    e01-expand-individual-some
    (cases individual-exists)))
  (domains)
  (reason
   "E01 ports the adopted ordinary closure equation; no outward reference introduction."))
 (definition
  (id "D12.IndividualNo")
  (head IndividualNo)
  (section "12")
  (spec-source-sha1 "2c170d8212203de3c848618a631e8da2c97af718")
  (spec-source-ranges (3759 3759) (3753 3755) (3765 3778))
  (equation-source-sha1 "f3aee89491f15d5a7cd8b1c310cf68a4e32f97b7")
  (equation-ranges (3759 3759))
  (status executable)
  (port-state ported)
  (dependencies ¬ IndividualSome)
  (legacy-implementations)
  (implementations
   (metafunction
    "tools/smusni-redex/port-a0.rkt"
    e01-expand-individual-no
    (cases negated-individual-exists)))
  (domains)
  (reason
   "E01 ports the adopted ordinary closure equation; no outward reference introduction."))
 (definition
  (id "D12.IndividualEvery")
  (head IndividualEvery)
  (section "12")
  (spec-source-sha1 "1fb177fb72174fb305dce52f7e89d079aa6f2663")
  (spec-source-ranges (3760 3760) (3753 3755) (3765 3778))
  (equation-source-sha1 "06a8a28bfc6a21a6b23e719fb540053d2456e584")
  (equation-ranges (3760 3760))
  (status executable)
  (port-state ported)
  (dependencies ∀ λ →)
  (legacy-implementations)
  (implementations
   (metafunction
    "tools/smusni-redex/port-a0.rkt"
    e01-expand-individual-every
    (cases individual-forall)))
  (domains)
  (reason
   "E01 ports the adopted ordinary closure equation; no outward reference introduction."))
 (definition
  (id "D12.PluralSome")
  (head PluralSome)
  (section "12")
  (spec-source-sha1 "498d641d7515b62847abb352e3733ac884d0d5e2")
  (spec-source-ranges (3761 3761) (3753 3755) (3765 3778))
  (equation-source-sha1 "6a89a08abbcdfc70b6d43142d57d0147f7210b17")
  (equation-ranges (3761 3761))
  (status executable)
  (port-state ported)
  (dependencies ∃ λ ∧)
  (legacy-implementations)
  (implementations
   (metafunction
    "tools/smusni-redex/port-a0.rkt"
    e01-expand-plural-some
    (cases plural-exists)))
  (domains)
  (reason
   "E01 ports the adopted ordinary closure equation; no outward reference introduction."))
 (definition
  (id "D12.PluralNo")
  (head PluralNo)
  (section "12")
  (spec-source-sha1 "286c5ff2b5d449676ce0d027a173478d030c1d1d")
  (spec-source-ranges (3762 3762) (3753 3755) (3765 3778))
  (equation-source-sha1 "5407b64792d8073634e89fb17da43255b4e0d0f9")
  (equation-ranges (3762 3762))
  (status executable)
  (port-state ported)
  (dependencies ¬ PluralSome)
  (legacy-implementations)
  (implementations
   (metafunction
    "tools/smusni-redex/port-a0.rkt"
    e01-expand-plural-no
    (cases negated-plural-exists)))
  (domains)
  (reason
   "E01 ports the adopted ordinary closure equation; no outward reference introduction.")))
