(smusni-definition-ledger
 1
 (definition
  (id "D12.ActualClause")
  (head ActualClause)
  (section "12")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies StateClause fasnu)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason "Its executable family has not yet reached the Redex port."))
 (definition
  (id "D12.AtLeast")
  (head AtLeast)
  (section "12")
  (spec-source-sha1 "4026c00fa18334539654e1cbde90ffc13f1db4de")
  (spec-source-ranges (3988 3988) (4026 4026) (4017 4023))
  (equation-source-sha1 "2099695721689e3e88273cec1a6918a5e2aafcaa")
  (equation-ranges (3988 3988) (4026 4026))
  (status executable)
  (port-state ported)
  (dependencies Bind SelectAtLeast)
  (legacy-implementations)
  (implementations
   (metafunction
    "tools/smusni-redex/port-a0.rkt"
    b1-expand-at-least
    (cases zero positive)))
  (domains
   (domain
    symbolic-natural
    (status executable)
    (port-state none)
    (reason
     "Direct typing is total, but the two-equation metafunction cannot choose zero or positive before a symbolic Natural is instantiated.")))
  (reason
   "B1 ports the separate zero and provably-positive witness equations."))
 (definition
  (id "D12.AtMost")
  (head AtMost)
  (section "12")
  (spec-source-sha1 "395259cc7f0b9a527920cc654389dc40a0e8cdc9")
  (spec-source-ranges (3996 3996))
  (equation-source-sha1 "395259cc7f0b9a527920cc654389dc40a0e8cdc9")
  (equation-ranges (3996 3996))
  (status executable)
  (port-state ported)
  (dependencies ¬ AtLeast +)
  (legacy-implementations)
  (implementations
   (metafunction
    "tools/smusni-redex/port-a0.rkt"
    b1-expand-at-most
    (cases negated-successor)))
  (domains)
  (reason "B1 ports negated successor-strength AtLeast."))
 (definition
  (id "D12.COI-schemas-prose")
  (head COI-schemas-prose)
  (section "12")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status not-a-definition)
  (port-state none)
  (dependencies COIExpress)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason
   "This prose introducer points to the following COIExpress schema and is not a separate equation."))
 (definition
  (id "D12.COIExpress")
  (head COIExpress)
  (section "12")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies Express Close)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason
   "The lexicon-parameterized performative schema awaits its executable family."))
 (definition
  (id "D12.CanonicalAggregateAt")
  (head CanonicalAggregateAt)
  (section "12")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies Aggregate CompleteGunmaAt)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason "Its executable family has not yet reached the Redex port."))
 (definition
  (id "D12.CapableClause")
  (head CapableClause)
  (section "12")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies StateClause InnatelyCapable)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason "Its executable family has not yet reached the Redex port."))
 (definition
  (id "D12.CoRef")
  (head CoRef)
  (section "12")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies Among)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason "Its executable family has not yet reached the Redex port."))
 (definition
  (id "D12.DemonstratedClause")
  (head DemonstratedClause)
  (section "12")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies StateClause DemonstrablyRealized)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason "Its executable family has not yet reached the Redex port."))
 (definition
  (id "D12.Distrib")
  (head Distrib)
  (section "12")
  (spec-source-sha1 "ad77f4330fbaaab045e3532dc58f26b9d13ff8da")
  (spec-source-ranges (4000 4000))
  (equation-source-sha1 "ad77f4330fbaaab045e3532dc58f26b9d13ff8da")
  (equation-ranges (4000 4000))
  (status executable)
  (port-state ported)
  (dependencies ∀ λ → Among)
  (legacy-implementations)
  (implementations
   (metafunction
    "tools/smusni-redex/port-a0.rkt"
    b1-expand-distrib
    (cases universal-members)))
  (domains)
  (reason "B1 ports universal member distribution over a plural reference."))
 (definition
  (id "D12.Enough")
  (head Enough)
  (section "12")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies Bind Context Vague AdmissibleThreshold AtLeast)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason
   "Its effectful threshold family has not yet reached the Redex port."))
 (definition
  (id "D12.Every")
  (head Every)
  (section "12")
  (spec-source-sha1 "5ec682630f66f59cb473f55d512fdeb89b7ba13c")
  (spec-source-ranges (3990 3991))
  (equation-source-sha1 "5ec682630f66f59cb473f55d512fdeb89b7ba13c")
  (equation-ranges (3990 3991))
  (status executable)
  (port-state ported)
  (dependencies Bind MaxRefer Distrib)
  (legacy-implementations)
  (implementations
   (metafunction
    "tools/smusni-redex/port-a0.rkt"
    b1-expand-every
    (cases maximal-distribution)))
  (domains)
  (reason "B1 ports maximal witness import followed by member distribution."))
 (definition
  (id "D12.Exactly")
  (head Exactly)
  (section "12")
  (spec-source-sha1 "2b097cd43a3cf09b150a309ec9eba914c1f1f626")
  (spec-source-ranges (3987 3987) (4027 4027) (4017 4023))
  (equation-source-sha1 "38dae2b443c0cc1d00043aaf996a84f020e624aa")
  (equation-ranges (3987 3987) (4027 4027))
  (status executable)
  (port-state a0)
  (dependencies Bind SelectExactly No)
  (legacy-implementations)
  (implementations
   (metafunction
    "tools/smusni-redex/port-a0.rkt"
    a0-expand-exactly
    (cases zero positive)))
  (domains)
  (reason "A0 ports both the zero and positive witness-set equations."))
 (definition
  (id "D12.Few")
  (head Few)
  (section "12")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies Bind Vague AdmissibleThreshold FewerThan)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason
   "Its effectful threshold family has not yet reached the Redex port."))
 (definition
  (id "D12.FewerThan")
  (head FewerThan)
  (section "12")
  (spec-source-sha1 "8fbc4c45c21360a7a5ab96582af161a5f4c4af92")
  (spec-source-ranges (3998 3998))
  (equation-source-sha1 "8fbc4c45c21360a7a5ab96582af161a5f4c4af92")
  (equation-ranges (3998 3998))
  (status executable)
  (port-state ported)
  (dependencies ¬ AtLeast)
  (legacy-implementations)
  (implementations
   (metafunction
    "tools/smusni-redex/port-a0.rkt"
    b1-expand-fewer-than
    (cases negated-at-least)))
  (domains)
  (reason "B1 ports negated AtLeast, including the zero boundary."))
 (definition
  (id "D12.GlobalExactly")
  (head GlobalExactly)
  (section "12")
  (spec-source-sha1 "c4ae9a48d10eb4b3bb0847e07684c6b5ff7ecdb2")
  (spec-source-ranges (3999 3999))
  (equation-source-sha1 "c4ae9a48d10eb4b3bb0847e07684c6b5ff7ecdb2")
  (equation-ranges (3999 3999))
  (status executable)
  (port-state a0)
  (dependencies = Card SetOf λ ∧)
  (legacy-implementations
   (binding "tools/smusni-redex/lower.rkt" expand-global-exactly-datum)
   (binding "tools/smusni-redex/lower.rkt" global-exactly-definition))
  (implementations
   (metafunction
    "tools/smusni-redex/port-a0.rkt"
    a0-expand-global-exactly
    (cases comprehension)))
  (domains)
  (reason
   "A0 ports the pure comprehension equation alongside the retained legacy path."))
 (definition
  (id "D12.Grade")
  (head Grade)
  (section "12")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies InRegion)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason
   "Its row-polymorphic executable family has not yet reached the Redex port."))
 (definition
  (id "D12.GroundedBy")
  (head GroundedBy)
  (section "12")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies Bind Perform Do)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason "Its performance family has not yet reached the Redex port."))
 (definition
  (id "D12.Interval")
  (head Interval)
  (section "12")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies SetOf)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason
   "Its endpoint-kind parameterized family has not yet reached the Redex port."))
 (definition
  (id "D12.JaiPromote")
  (head JaiPromote)
  (section "12")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies PredTerm Record)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason "Its row-reconstruction schema has not yet reached the Redex port."))
 (definition
  (id "D12.JaiRaise")
  (head JaiRaise)
  (section "12")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies PredTerm JaiRoleAdmissible)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason "Its row-reconstruction schema has not yet reached the Redex port."))
 (definition
  (id "D12.JoiClause")
  (head JoiClause)
  (section "12")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies Bind Context Combine CloseClause)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason "Its event-construction family has not yet reached the Redex port."))
 (definition
  (id "D12.JoiEvent")
  (head JoiEvent)
  (section "12")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies Bind Combine CanonicalAggregateAt)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason "Its event-group family has not yet reached the Redex port."))
 (definition
  (id "D12.JoiGroup")
  (head JoiGroup)
  (section "12")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies Massify Combine)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason
   "Its expected-type-directed family has not yet reached the Redex port."))
 (definition
  (id "D12.JoiPred")
  (head JoiPred)
  (section "12")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies GunmaPredAt MixAt)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason "Its contribution-basis family has not yet reached the Redex port."))
 (definition
  (id "D12.JoiTanru")
  (head JoiTanru)
  (section "12")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies Bind Context JoiPred)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason
   "Its source-ordered link schema has not yet reached the Redex port."))
 (definition
  (id "D12.Many")
  (head Many)
  (section "12")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies Bind Vague AdmissibleThreshold AtLeast)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason
   "Its effectful threshold family has not yet reached the Redex port."))
 (definition
  (id "D12.Massify")
  (head Massify)
  (section "12")
  (spec-source-sha1 "aefa779891a5d6cd2146a54b1ee993dcb7364665")
  (spec-source-ranges (4197 4200))
  (equation-source-sha1 "aefa779891a5d6cd2146a54b1ee993dcb7364665")
  (equation-ranges (4197 4200))
  (status executable)
  (port-state a0)
  (dependencies Refer λ ∃ ∧ CanonicalAggregateAt CoRef)
  (legacy-implementations)
  (implementations
   (metafunction
    "tools/smusni-redex/port-a0.rkt"
    a0-expand-massify
    (cases canonical-reference)))
  (domains)
  (reason
   "E01 replaces cardinal selection by reference-level existential co-reference to one canonical aggregate, per current §12."))
 (definition
  (id "D12.MaxRefer")
  (head MaxRefer)
  (section "12")
  (spec-source-sha1 "9eaac47b3da74a76ff3da59c42fd66566bb96593")
  (spec-source-ranges (4288 4292))
  (equation-source-sha1 "9eaac47b3da74a76ff3da59c42fd66566bb96593")
  (equation-ranges (4288 4292))
  (status executable)
  (port-state ported)
  (dependencies Presuppose ∃ Refer λ ∧ CoveredBy ∀ → Among)
  (legacy-implementations)
  (implementations
   (metafunction
    "tools/smusni-redex/port-a0.rkt"
    b1-expand-max-refer
    (cases inhabited-maximal-reference)))
  (domains)
  (reason
   "B1 ports inhabited maximal reference construction with its projective obligation."))
 (definition
  (id "D12.MePred")
  (head MePred)
  (section "12")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies Among)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason
   "Its type-directed property expansion has not yet reached the Redex port."))
 (definition
  (id "D12.MemberCover")
  (head MemberCover)
  (section "12")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies Distrib Among Overlap)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason
   "Its positive-MEI helper expansion has not yet reached the Redex port."))
 (definition
  (id "D12.MetricBall")
  (head MetricBall)
  (section "12")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies SetOf)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason
   "Its endpoint-kind parameterized family has not yet reached the Redex port."))
 (definition
  (id "D12.MoreThan")
  (head MoreThan)
  (section "12")
  (spec-source-sha1 "9fe1dcc8d2c3d9fedc8938a1e537e178541ae5dd")
  (spec-source-ranges (3997 3997))
  (equation-source-sha1 "9fe1dcc8d2c3d9fedc8938a1e537e178541ae5dd")
  (equation-ranges (3997 3997))
  (status executable)
  (port-state ported)
  (dependencies AtLeast +)
  (legacy-implementations)
  (implementations
   (metafunction
    "tools/smusni-redex/port-a0.rkt"
    b1-expand-more-than
    (cases successor)))
  (domains)
  (reason "B1 ports successor-strength AtLeast over a general Natural term."))
 (definition
  (id "D12.Most")
  (head Most)
  (section "12")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status (blocked "#66"))
  (port-state none)
  (dependencies Card SetOf >)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason
   "Its definition needs the separately scoped greater-than operator in issue #66."))
 (definition
  (id "D12.NahiObjection")
  (head NahiObjection)
  (section "12")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies MetalinguisticallyDefective TargetContent)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason "Its act-occurrence family has not yet reached the Redex port."))
 (definition
  (id "D12.Named")
  (head Named)
  (section "12")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies Close cmene NameSign)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason "Its executable family has not yet reached the Redex port."))
 (definition
  (id "D12.No")
  (head No)
  (section "12")
  (spec-source-sha1 "e193fac451d35a116a77ddfc601a688f788c105b")
  (spec-source-ranges (3995 3995))
  (equation-source-sha1 "e193fac451d35a116a77ddfc601a688f788c105b")
  (equation-ranges (3995 3995))
  (status executable)
  (port-state ported)
  (dependencies ¬ Some)
  (legacy-implementations)
  (implementations
   (metafunction
    "tools/smusni-redex/port-a0.rkt"
    b1-expand-no
    (cases negated-some)))
  (domains)
  (reason "B1 ports generic negation of Some."))
 (definition
  (id "D12.Only")
  (head Only)
  (section "12")
  (spec-source-sha1 "25b04eaf92b1b04cdcff925f645cf70c4144c2ca")
  (spec-source-ranges (4486 4494))
  (equation-source-sha1 "453bf82e12578057649c455504e9b418a4f39ca7")
  (equation-ranges (4490 4494))
  (status executable)
  (port-state ported)
  (dependencies ∧ ∀ λ → Among)
  (legacy-implementations)
  (implementations
   (metafunction
    "tools/smusni-redex/port-a0.rkt"
    e01-expand-only
    (cases host-and-exclusion)))
  (domains)
  (reason
   "E01 ports the adopted pure host-and-exclusion formula. Effectful frames remain the §14 gap."))
 (definition
  (id "D12.Overlap")
  (head Overlap)
  (section "12")
  (spec-source-sha1 "4a52180d9ffd1ee0a50f1bf421faba9856d38bbe")
  (spec-source-ranges (4243 4243))
  (equation-source-sha1 "4a52180d9ffd1ee0a50f1bf421faba9856d38bbe")
  (equation-ranges (4243 4243))
  (status executable)
  (port-state ported)
  (dependencies ∃ λ ∧ Among)
  (legacy-implementations)
  (implementations
   (metafunction
    "tools/smusni-redex/port-a0.rkt"
    b1-expand-overlap
    (cases common-subreference)))
  (domains)
  (reason "B1 ports existential common-subreference overlap."))
 (definition
  (id "D12.Realized")
  (head Realized)
  (section "12")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies EventOfContent fasnu)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason "Its clause-event family has not yet reached the Redex port."))
 (definition
  (id "D12.Reciprocate")
  (head Reciprocate)
  (section "12")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies Among CoRef)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason "Its executable family has not yet reached the Redex port."))
 (definition
  (id "D12.RegionComplement")
  (head RegionComplement)
  (section "12")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies SetOf)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason "Its region family has not yet reached the Redex port."))
 (definition
  (id "D12.RoiClause")
  (head RoiClause)
  (section "12")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies Card SetOf During)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason "Its event-counting family has not yet reached the Redex port."))
 (definition
  (id "D12.Some")
  (head Some)
  (section "12")
  (spec-source-sha1 "b23591d67116e34bcc5ec141faf44fc9fd470299")
  (spec-source-ranges (3989 3989))
  (equation-source-sha1 "b23591d67116e34bcc5ec141faf44fc9fd470299")
  (equation-ranges (3989 3989))
  (status executable)
  (port-state ported)
  (dependencies Bind SelectSome)
  (legacy-implementations)
  (implementations
   (metafunction
    "tools/smusni-redex/port-a0.rkt"
    b1-expand-some
    (cases witness)))
  (domains)
  (reason "B1 ports witness selection and export through SelectSome."))
 (definition
  (id "D12.SpanRegion")
  (head SpanRegion)
  (section "12")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies SetOf)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason
   "Its endpoint-kind parameterized family has not yet reached the Redex port."))
 (definition
  (id "D12.SpeakerDescribes")
  (head SpeakerDescribes)
  (section "12")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies LocutionOf skicu)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason "Its executable family has not yet reached the Redex port."))
 (definition
  (id "D12.SpeakerDescribesUnaddressed")
  (head SpeakerDescribesUnaddressed)
  (section "12")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies LocutionOf skicu)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason "Its executable family has not yet reached the Redex port."))
 (definition
  (id "D12.TanruLinkConnect")
  (head TanruLinkConnect)
  (section "12")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies Bind Context)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason
   "Its source-ordered connective schema has not yet reached the Redex port."))
 (definition
  (id "D12.TooFew")
  (head TooFew)
  (section "12")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies Bind Context Vague AdmissibleThreshold FewerThan)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason
   "Its effectful threshold family has not yet reached the Redex port."))
 (definition
  (id "D12.TooMany")
  (head TooMany)
  (section "12")
  (spec-source-sha1 "2f3d2b455613201536c597382bb6871479fd958e")
  (spec-source-ranges (4079 4081))
  (equation-source-sha1 "2f3d2b455613201536c597382bb6871479fd958e")
  (equation-ranges (4079 4081))
  (status executable)
  (port-state a0)
  (dependencies Bind Context Vague AdmissibleThreshold MoreThan)
  (legacy-implementations)
  (implementations
   (metafunction
    "tools/smusni-redex/port-a0.rkt"
    a0-expand-too-many
    (cases dependent-threshold)))
  (domains)
  (reason "A0 ports the ordered purpose and dependent threshold expansion."))
 (definition
  (id "D12.UnrealizedClause")
  (head UnrealizedClause)
  (section "12")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies StateClause Realizable)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason "Its executable family has not yet reached the Redex port."))
 (definition
  (id "D12.ZipWith")
  (head ZipWith)
  (section "12")
  (spec-source-sha1 "46a0b234c63ca75b7b903f1d4b24201ee86ba901")
  (spec-source-ranges (4264 4266))
  (equation-source-sha1 "46a0b234c63ca75b7b903f1d4b24201ee86ba901")
  (equation-ranges (4264 4266))
  (status executable)
  (port-state a0)
  (dependencies ∧ List)
  (legacy-implementations)
  (implementations
   (metafunction
    "tools/smusni-redex/port-a0.rkt"
    a0-expand-zipwith
    (cases empty paired-step)))
  (domains
   (domain
    equal-length
    (status executable)
    (port-state a0)
    (reason "A0 ports the settled base and paired recursive equations."))
   (domain
    unequal-length
    (status (blocked "#41"))
    (port-state none)
    (reason
     "Unequal-list behavior is human-partner-open in issue #41 item 6.")))
  (reason
   "Its settled equal-length recursion awaits A0 while unequal length remains blocked."))
 (definition
  (id "D12.gei")
  (head gei)
  (section "12")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies |te'a|)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason "Its recursive MEX family has not yet reached the Redex port."))
 (definition
  (id "D12.na'i-objection-prose")
  (head |na'i-objection-prose|)
  (section "12")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status not-a-definition)
  (port-state none)
  (dependencies NahiObjection)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason
   "This prose lead-in announces the following NahiObjection equation and is not a separate definition."))
 (definition
  (id "D12.te'a")
  (head |te'a|)
  (section "12")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies Natural)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason "Its recursive MEX family has not yet reached the Redex port."))
 (definition
  (id "D12.xi")
  (head xi)
  (section "12")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies List)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason
   "Its recursive list-index family has not yet reached the Redex port."))
 (definition
  (id "D4.1.At")
  (head At)
  (section "4.1")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies RowMinus)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason "Its row-application family has not yet reached the Redex port."))
 (definition
  (id "D4.1.klama-fill-examples")
  (head klama)
  (section "4.1")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status mapping-schema)
  (port-state none)
  (dependencies At)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason
   "These two equations illustrate positional fill notation rather than define the klama lexical row."))
 (definition
  (id "D4.4.Let")
  (head Let)
  (section "4.4")
  (spec-source-sha1 "6cda88c48e68c7b2e04b1ffdfd5dca90ede0bc45")
  (spec-source-ranges (670 670))
  (equation-source-sha1 "6cda88c48e68c7b2e04b1ffdfd5dca90ede0bc45")
  (equation-ranges (670 670))
  (status executable)
  (port-state a0)
  (dependencies λ)
  (legacy-implementations)
  (implementations
   (metafunction "tools/smusni-redex/port-a0.rkt" a0-expand-let (cases beta)))
  (domains)
  (reason "A0 ports direct Let as immediate pure lambda application."))
 (definition
  (id "D4.6.ClauseAnd")
  (head ClauseAnd)
  (section "4.6")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies StateClause CloseClause)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason "Its clause-event family has not yet reached the Redex port."))
 (definition
  (id "D4.6.ClauseIff")
  (head ClauseIff)
  (section "4.6")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies StateClause CloseClause)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason "Its clause-event family has not yet reached the Redex port."))
 (definition
  (id "D4.6.ClauseImp")
  (head ClauseImp)
  (section "4.6")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies StateClause CloseClause)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason "Its clause-event family has not yet reached the Redex port."))
 (definition
  (id "D4.6.ClauseNot")
  (head ClauseNot)
  (section "4.6")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies StateClause CloseClause)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason "Its clause-event family has not yet reached the Redex port."))
 (definition
  (id "D4.6.ClauseOr")
  (head ClauseOr)
  (section "4.6")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies CloseClause)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason "Its clause-event family has not yet reached the Redex port."))
 (definition
  (id "D4.6.ClauseXor")
  (head ClauseXor)
  (section "4.6")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies StateClause CloseClause)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason "Its clause-event family has not yet reached the Redex port."))
 (definition
  (id "D4.6.Close")
  (head Close)
  (section "4.6")
  (spec-source-sha1 "8615fe59057c0aa23214649715854f981416c7b7")
  (spec-source-ranges (758 767))
  (status executable)
  (port-state a0)
  (dependencies CloseClause ActualClause DirectClause)
  (legacy-implementations
   (binding "tools/smusni-redex/lower.rkt" expand-close-datum)
   (binding "tools/smusni-redex/lower.rkt" close-out))
  (implementations
   (metafunction
    "tools/smusni-redex/port-a0.rkt"
    a0-expand-close
    (cases holding-state direct-event-implicit direct-event-explicit)))
  (domains)
  (reason
   "A0 ports all three Close equations over an explicit adapter-supplied row declaration."))
 (definition
  (id "D4.6.DirectClause")
  (head DirectClause)
  (section "4.6")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies Bind Context StateClause)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason
   "Its row-aware direct-event family has not yet reached the Redex port."))
 (definition
  (id "D4.8.CardBasis")
  (head CardBasis)
  (section "4.8")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies Card UnitSet)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason "Its executable family has not yet reached the Redex port."))
 (definition
  (id "D4.8.CoveredBy")
  (head CoveredBy)
  (section "4.8")
  (spec-source-sha1 "4c110e0635ef993cfe19421ad803215af782b555")
  (spec-source-ranges (874 884))
  (equation-source-sha1 "074c78f6d1d8649827d399ccf6dbc0a582ef70c0")
  (equation-ranges (878 884))
  (status executable)
  (port-state ported)
  (dependencies ∧ Distrib ∀ λ → Among ∃ Overlap)
  (legacy-implementations)
  (implementations
   (metafunction
    "tools/smusni-redex/port-a0.rkt"
    b1-expand-covered-by
    (cases no-residue)))
  (domains)
  (reason "B1 ports the no-residue plural coverage equation."))
 (definition
  (id "D4.9.greater-than")
  (head >)
  (section "4.9")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status (blocked "#66"))
  (port-state none)
  (dependencies <)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason
   "The greater-than derived comparison is separately scoped in issue #66."))
 (definition
  (id "D4.9.CompleteGunmaAt")
  (head CompleteGunmaAt)
  (section "4.9")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies GunmaAt PeerUnitAt BasisUnitAt)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason "Its constitution family has not yet reached the Redex port."))
 (definition
  (id "D4.9.ComponentAt")
  (head ComponentAt)
  (section "4.9")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies GunmaAt)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason "Its constitution family has not yet reached the Redex port."))
 (definition
  (id "D4.9.GunmaAt")
  (head GunmaAt)
  (section "4.9")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies PeerUnitAt BasisUnitAt CoRef)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason "Its constitution family has not yet reached the Redex port."))
 (definition
  (id "D4.9.GunmaPredAt")
  (head GunmaPredAt)
  (section "4.9")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies ContributionBasis GunmaAt)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason
   "Its compatible-predicate constitution family has not yet reached the Redex port."))
 (definition
  (id "D5.1.That")
  (head That)
  (section "5.1")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status metatheory-or-model-law)
  (port-state none)
  (dependencies Deictic)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason
   "This abbreviation projects the model context ground and is not a closed term rewrite."))
 (definition
  (id "D5.1.This")
  (head This)
  (section "5.1")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status metatheory-or-model-law)
  (port-state none)
  (dependencies Deictic)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason
   "This abbreviation projects the model context ground and is not a closed term rewrite."))
 (definition
  (id "D5.1.Yonder")
  (head Yonder)
  (section "5.1")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status metatheory-or-model-law)
  (port-state none)
  (dependencies Deictic)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason
   "This abbreviation projects the model context ground and is not a closed term rewrite."))
 (definition
  (id "D5.3.Refer-member-lift")
  (head Refer)
  (section "5.3")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies CoveredBy)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason "Its type-directed overload has not yet reached the Redex port."))
 (definition
  (id "D5.6.SelectSome")
  (head SelectSome)
  (section "5.6")
  (spec-source-sha1 "2b7ddcae052b39cd3146a361657eb64914baebe6")
  (spec-source-ranges (1816 1816))
  (equation-source-sha1 "2b7ddcae052b39cd3146a361657eb64914baebe6")
  (equation-ranges (1816 1816))
  (status executable)
  (port-state ported)
  (dependencies SelectAtLeast)
  (legacy-implementations)
  (implementations
   (metafunction
    "tools/smusni-redex/port-a0.rkt"
    b1-expand-select-some
    (cases at-least-one)))
  (domains)
  (reason "B1 ports SelectSome as SelectAtLeast one."))
 (definition
  (id "D6.2.Tanru")
  (head Tanru)
  (section "6.2")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies Bind Context)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason
   "Its fills-parameterized expansion is executable but has not yet reached the Redex port."))
 (definition
  (id "D7.4.Utterance-entry")
  (head Utterance)
  (section "7.4")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status mapping-schema)
  (port-state none)
  (dependencies UtteranceToken)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason
   "This equation defines compact entry notation rather than an ordinary term former."))
 (definition
  (id "D8.2.Answer-contextual")
  (head Answer)
  (section "8.2")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies Bind Context TupleAnswer PolarAnswer)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason
   "Its query-type-directed overload has not yet reached the Redex port."))
 (definition
  (id "D9.1.Meau0")
  (head Meau0)
  (section "9.1")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies Presuppose Holds Reify)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason "Its abstraction bridge family has not yet reached the Redex port."))
 (definition
  (id "D9.2.DuhuRel")
  (head DuhuRel)
  (section "9.2")
  (spec-source-sha1 none)
  (spec-source-ranges)
  (status executable)
  (port-state none)
  (dependencies CoRef Reify Distrib InterpretContent)
  (legacy-implementations)
  (implementations)
  (domains)
  (reason
   "Its abstraction-relation family has not yet reached the Redex port."))
 (definition
  (id "D12.IndividualSome")
  (head IndividualSome)
  (section "12")
  (spec-source-sha1 "ecb2bb2c6ba30dbdc9361197b2da00355c29f265")
  (spec-source-ranges (3951 3951) (3946 3948) (3958 3971))
  (equation-source-sha1 "fed9782d0d57104ad16c24b229ffc8075a03d446")
  (equation-ranges (3951 3951))
  (status executable)
  (port-state ported)
  (dependencies ∃ λ ∧)
  (legacy-implementations)
  (implementations
   (metafunction
    "tools/smusni-redex/port-a0.rkt"
    e01-expand-individual-some
    (cases individual-exists)))
  (domains)
  (reason
   "E01 ports the adopted ordinary closure equation; no outward reference introduction."))
 (definition
  (id "D12.IndividualNo")
  (head IndividualNo)
  (section "12")
  (spec-source-sha1 "6eed32a75a5e5639cc0f6fd56d1df7419b2e88a2")
  (spec-source-ranges (3952 3952) (3946 3948) (3958 3971))
  (equation-source-sha1 "c4ac008845e7e4eab1e6b953a3b29a36f7401623")
  (equation-ranges (3952 3952))
  (status executable)
  (port-state ported)
  (dependencies ¬ IndividualSome)
  (legacy-implementations)
  (implementations
   (metafunction
    "tools/smusni-redex/port-a0.rkt"
    e01-expand-individual-no
    (cases negated-individual-exists)))
  (domains)
  (reason
   "E01 ports the adopted ordinary closure equation; no outward reference introduction."))
 (definition
  (id "D12.IndividualEvery")
  (head IndividualEvery)
  (section "12")
  (spec-source-sha1 "ef9b40002b6b6a59c40e3be0137ae341ce8a9c7a")
  (spec-source-ranges (3953 3953) (3946 3948) (3958 3971))
  (equation-source-sha1 "c6a5e28025f3a88d400966ccd468936dd4d104ba")
  (equation-ranges (3953 3953))
  (status executable)
  (port-state ported)
  (dependencies ∀ λ →)
  (legacy-implementations)
  (implementations
   (metafunction
    "tools/smusni-redex/port-a0.rkt"
    e01-expand-individual-every
    (cases individual-forall)))
  (domains)
  (reason
   "E01 ports the adopted ordinary closure equation; no outward reference introduction."))
 (definition
  (id "D12.PluralSome")
  (head PluralSome)
  (section "12")
  (spec-source-sha1 "fa5bc6f854d7ec630a3f16b7e2662e4bd722f333")
  (spec-source-ranges (3954 3954) (3946 3948) (3958 3971))
  (equation-source-sha1 "6c83c7726e6da5dac68e2c2fea80a8c692dfe653")
  (equation-ranges (3954 3954))
  (status executable)
  (port-state ported)
  (dependencies ∃ λ ∧)
  (legacy-implementations)
  (implementations
   (metafunction
    "tools/smusni-redex/port-a0.rkt"
    e01-expand-plural-some
    (cases plural-exists)))
  (domains)
  (reason
   "E01 ports the adopted ordinary closure equation; no outward reference introduction."))
 (definition
  (id "D12.PluralNo")
  (head PluralNo)
  (section "12")
  (spec-source-sha1 "0fa601ba7bb7f1b20a574bef55cd3a3ffe79b8f2")
  (spec-source-ranges (3955 3955) (3946 3948) (3958 3971))
  (equation-source-sha1 "edbe2348fe139c405b3a2ecdc5a44a747891294d")
  (equation-ranges (3955 3955))
  (status executable)
  (port-state ported)
  (dependencies ¬ PluralSome)
  (legacy-implementations)
  (implementations
   (metafunction
    "tools/smusni-redex/port-a0.rkt"
    e01-expand-plural-no
    (cases negated-plural-exists)))
  (domains)
  (reason
   "E01 ports the adopted ordinary closure equation; no outward reference introduction.")))
