(smusni-lexical-fixtures 1
  ;; These rows are non-normative scaffolding until issue #12 supplies the
  ;; adjudicated lexical resource. The numeral is the complete ordinary-place
  ;; count used by this bounded checker; an application with fewer fills stays
  ;; an open PredTerm and must be closed explicitly.
  (row bajra 5 direct-event "fixture; official row pending #12")
  (row balvi 2 holding-state "fixture binary tense-facet projection; pending #12")
  (row barda 2 holding-state "fixture; official row pending #12")
  (row batci 3 direct-event "fixture; official row pending #12")
  (row bevri 4 direct-event "fixture; official row pending #12")
  (row blabi 1 holding-state "fixture; official row pending #12")
  (row cabna 2 holding-state "fixture binary tense-facet projection; pending #12")
  (row cadzu 4 direct-event "fixture; official row pending #12")
  (row cinri 2 holding-state "fixture; official row pending #12")
  (row citka 3 direct-event "fixture; official row pending #12")
  (row cukta 1 holding-state "fixture unary description-head projection; pending #12")
  (row cusku 4 direct-event "fixture; official row pending #12")
  (row darxi 3 direct-event "fixture; official row pending #12")
  (row datka 1 holding-state "fixture; official row pending #12")
  (row djica 3 holding-state "fixture; official row pending #12")
  (row dansu 3 direct-event "fixture; official row pending #12")
  (row djuno 4 holding-state "fixture; official row pending #12")
  (row fasnu 1 holding-state "fixture; official row pending #12")
  (row flulimna 1 direct-event "fixture; official row pending #12")
  (row gerku 1 holding-state "fixture; official row pending #12")
  (row jbena 3 direct-event "fixture; official row pending #12")
  (row jbopre 1 holding-state "fixture; official row pending #12")
  (row jinvi 4 holding-state "fixture; official row pending #12")
  (row jmaji 1 direct-event "fixture; official row pending #12")
  (row klama 5 direct-event "fixture; official row pending #12")
  (row melbi 2 direct-event "fixture; official row pending #12")
  (row mlatu 1 holding-state "fixture; official row pending #12")
  (row morsi 1 direct-event "fixture; official row pending #12")
  (row nelci 2 holding-state "fixture; official row pending #12")
  (row pendo 2 holding-state "fixture; official row pending #12")
  (row pilno 3 holding-state "fixture; official row pending #12")
  (row pipno 1 holding-state "fixture; official row pending #12")
  (row ponse 2 holding-state "fixture; official row pending #12")
  (row prami 2 holding-state "fixture; official row pending #12")
  (row prenu 1 holding-state "fixture; official row pending #12")
  (row purci 2 holding-state "fixture; official row pending #12")
  (row rinka 3 holding-state "fixture; official row pending #12")
  (row sanga 3 direct-event "fixture; official row pending #12")
  (row selcmi 2 holding-state "fixture; official row pending #12")
  (row sipna 1 direct-event "fixture; official row pending #12")
  (row skicu 4 direct-event "fixture; official row pending #12")
  (row srana 2 holding-state "fixture; official row pending #12")
  (row stali 1 direct-event "fixture; official row pending #12")
  (row sutra 1 holding-state "fixture; official row pending #12")
  (row tatpi 1 holding-state "fixture; official row pending #12")
  (row tavla 3 direct-event "fixture; official row pending #12")
  (row valsi 2 holding-state "fixture; official row pending #12")
  (row xasli 1 holding-state "fixture; official row pending #12")
  (row zdani 2 holding-state "fixture; official row pending #12"))
