(smusni-m2-redex-oracle
 2
 (count 195)
 (cases
  (case (id "001387765e509fe487e7c355464631bb66e96719")
    (status unavailable)
    (category context-unsupported)
    (stage context)
    (reason "no independent context rule for Assert within whole-source"))
  (case (id "010a22f419f0e4714289ac20673998b765002c77")
    (status unavailable)
    (category unclassified-non-admission)
    (stage source)
    (reason
     "source has 0 admitted A0 typings: '(SetOf (λ (($z Entity)) (Every (λ (($x Entity)) (gerku $x)) (λ (($x Entity)) (CloseWith (row jmaji 1 direct-event (1)) ((1 $x)))))))"))
  (case (id "012afd6c32c46dcee1603d23f36997b574ef46fd")
    (status unavailable)
    (category context-unsupported)
    (stage context)
    (reason "no independent context rule for Mention within whole-source"))
  (case (id "056127c40eba32ecf0c586256bd9292d40f756c1")
    (status available)
    (context whole-a0)
    (source-type (Set Entity))
    (source-typing (typing (Set Entity) () ()))
    (target-typing (typing (Set Entity) () ()))
    (term
     (SetOf
      (λ (($z :: Entity))
        (¬
         (Bind
          ($w1 :: (Referents Entity))
          (SelectAtLeast (+ 1 1) (λ (($x :: Entity)) (gerku $x)))
          ((λ (($w :: (Referents Entity)))
             (CloseClause
              (λ (($actual_event :: (Referents Eventuality)))
                (∧ ((λ (($event :: (Referents Eventuality))) (jmaji $w $event)) $actual_event) (fasnu $actual_event)))))
           $w1)))))))
  (case (id "059ad6f2adf9d4a2cf81693ee14b6f3b5ea49562")
    (status unavailable)
    (category unclassified-non-admission)
    (stage source)
    (reason
     "source has 0 admitted A0 typings: '(SetOf (λ (($z Entity)) (Some (λ (($x Entity)) (gerku $x)) (λ (($w (Referents Entity))) (CloseWith (row jmaji 1 direct-event (1)) ((1 $w)))))))"))
  (case (id "05b101808826fe671ef1e2155db3629a01cc099d")
    (status available)
    (context whole-a0)
    (source-type Content)
    (source-typing (typing Content () ()))
    (target-typing (typing Content () ()))
    (term (¬ (∃ (λ (($r1 :: (Referents Number))) (∧ ($x $r1) ($r $r1)))))))
  (case (id "05bb8ad1ae173cc81f1f84b69b295fff82b9c9f2")
    (status available)
    (context whole-a0)
    (source-type Content)
    (source-typing (typing Content (effectful-call) ()))
    (target-typing (typing Content (effectful-call) ()))
    (term
     (∧
      ((λ (($s :: (Referents Entity)) ($l :: (Referents Entity)))
         (CloseClause
          (λ (($actual_event :: (Referents Eventuality)))
            (∧
             ((λ (($event :: (Referents Eventuality)))
                (Bind ($ctx3 :: (Referents Entity)) (Context) (tavla $s $l $ctx3 $event)))
              $actual_event)
             (fasnu $actual_event)))))
       Speaker
       Audience)
      (∧
       ((λ (($s :: (Referents Entity)) ($l :: (Referents Entity)))
          (CloseClause
           (λ (($actual_event :: (Referents Eventuality)))
             (∧
              ((λ (($event :: (Referents Eventuality)))
                 (Bind ($ctx3 :: (Referents Entity)) (Context) (tavla $s $l $ctx3 $event)))
               $actual_event)
              (fasnu $actual_event)))))
        Audience
        Speaker)
       (∧)))))
  (case (id "0632c0c9bdc1807f6fd0b03fa1168ad4cf78e860")
    (status unavailable)
    (category context-unsupported)
    (stage context)
    (reason "no independent context rule for Assert within whole-source"))
  (case (id "081d6e7115deb76869d85bb5dedd5334a78f62d2")
    (status unavailable)
    (category context-unsupported)
    (stage context)
    (reason "no independent context rule for Assert within whole-source"))
  (case (id "09f0948ce98ba5c5c10172f02e84d769c77fc947")
    (status unavailable)
    (category unclassified-non-admission)
    (stage source)
    (reason
     "source has 0 admitted A0 typings: '(SetOf (λ (($z Entity)) (Exactly 1 (λ (($x Entity)) (gerku $x)) (λ (($w (Referents Entity))) (CloseWith (row jmaji 1 direct-event (1)) ((1 $w)))))))"))
  (case (id "0a33e1a1815fb2640ffa77469a9a835d9c0a21e8")
    (status available)
    (context assert-bridge)
    (source-type (Act Assertion))
    (source-typing (typing (Act Assertion) () ()))
    (target-typing (typing (Act Assertion) () ()))
    (payload-source-typing (typing Content (effectful-call) ()))
    (payload-target-typing (typing Content (effectful-call) ()))
    (term
     (Assert
      (¬
       (∃
        (λ (($r1 :: (Referents Entity)))
          (∧
           ((λ (($r :: (Referents Entity))) (gerku $r)) $r1)
           ((λ (($w :: (Referents Entity)))
              (CloseClause
               (λ (($actual_event :: (Referents Eventuality)))
                 (∧
                  ((λ (($event :: (Referents Eventuality)))
                     (Bind ($ctx3 :: (Referents Entity)) (Context) (tavla $w Speaker $ctx3 $event)))
                   $actual_event)
                  (fasnu $actual_event)))))
            $r1))))))))
  (case (id "0bf331ccff8f436775a1a65f87d2e1848278fe82")
    (status unavailable)
    (category context-unsupported)
    (stage context)
    (reason "no independent context rule for Assert within whole-source"))
  (case (id "0d3d9d3ab4d065e4e09924149cb6db5c3151a2d0")
    (status available)
    (context assert-bridge)
    (source-type (Act Assertion))
    (source-typing (typing (Act Assertion) () ()))
    (target-typing (typing (Act Assertion) () ()))
    (payload-source-typing (typing Content (effectful-call) ()))
    (payload-target-typing (typing Content (effectful-call) ()))
    (term
     (Assert
      (∃
       (λ (($x1 :: Entity))
         (∧
          ((λ (($x :: Entity)) (gerku $x)) $x1)
          ((λ (($w :: Entity))
             (CloseClause
              (λ (($actual_event :: (Referents Eventuality)))
                (∧
                 ((λ (($event :: (Referents Eventuality)))
                    (Bind ($ctx3 :: (Referents Entity)) (Context) (tavla Speaker $w $ctx3 $event)))
                  $actual_event)
                 (fasnu $actual_event)))))
           $x1)))))))
  (case (id "0e13ef5fccb371aaf16273ca7d827a1702bf19cd")
    (status unavailable)
    (category unclassified-non-admission)
    (stage target)
    (reason "expanded target has 0 A0 typings at source type 'Content"))
  (case (id "101b2a2783517ee43d13d1b6f3896db9daecbc0f")
    (status available)
    (context whole-a0)
    (source-type Content)
    (source-typing (typing Content (context projective) (finite-set-cardinality-defined)))
    (target-typing (typing Content (context projective) (finite-set-cardinality-defined)))
    (term
     (Bind
      ($restrictor_klama_2 :: (Referents Entity))
      (Context)
      ($restrictor_klama_3 :: (Referents Entity))
      (Context)
      ($restrictor_klama_4 :: (Referents Entity))
      (Context)
      ($restrictor_klama_5 :: (Referents Entity))
      (Context)
      ($nuclear_bajra_2 :: (Referents Entity))
      (Context)
      ($nuclear_bajra_3 :: (Referents Entity))
      (Context)
      ($nuclear_bajra_4 :: (Referents Entity))
      (Context)
      (=
       (Card
        (SetOf
         (λ (($global_member :: Entity))
           (∧
            ((λ (($restrictor_member :: Entity))
               (CloseClause
                (λ (($actual_event :: (Referents Eventuality)))
                  (∧
                   ((λ (($event :: (Referents Eventuality)))
                      (klama
                       $restrictor_member
                       $restrictor_klama_2
                       $restrictor_klama_3
                       $restrictor_klama_4
                       $restrictor_klama_5
                       $event))
                    $actual_event)
                   (fasnu $actual_event)))))
             $global_member)
            ((λ (($nuclear_member :: Entity))
               (CloseClause
                (λ (($actual_event :: (Referents Eventuality)))
                  (∧
                   ((λ (($event :: (Referents Eventuality)))
                      (bajra $nuclear_member $nuclear_bajra_2 $nuclear_bajra_3 $nuclear_bajra_4 $event))
                    $actual_event)
                   (fasnu $actual_event)))))
             $global_member)))))
       3))))
  (case (id "1118b5772e65cdec9dfa2d52bad043bdb8a79e87")
    (status available)
    (context whole-a0)
    (source-type Content)
    (source-typing (typing Content () ()))
    (target-typing (typing Content () ()))
    (term (∃ (λ (($r1 :: (Referents Entity))) (∧ ($x $r1) ($r $r1))))))
  (case (id "1138ed0548a554660ae38acc0d17953c10674590")
    (status unavailable)
    (category context-unsupported)
    (stage context)
    (reason "no independent context rule for Assert within whole-source"))
  (case (id "115612e112a0b295df8d9d81027b7f2084b551e7")
    (status available)
    (context assert-bridge)
    (source-type (Act Assertion))
    (source-typing (typing (Act Assertion) () ()))
    (target-typing (typing (Act Assertion) () ()))
    (payload-source-typing (typing Content (effectful-call) ()))
    (payload-target-typing (typing Content (effectful-call) ()))
    (term
     (Assert
      (∀
       (λ (($x1 :: Entity))
         (→
          ((λ (($x :: Entity)) (gerku $x)) $x1)
          ((λ (($x :: Entity))
             (CloseClause
              (λ (($actual_event :: (Referents Eventuality)))
                (∧
                 ((λ (($event :: (Referents Eventuality)))
                    (Bind ($ctx3 :: (Referents Entity)) (Context) (tavla Speaker $x $ctx3 $event)))
                  $actual_event)
                 (fasnu $actual_event)))))
           $x1)))))))
  (case (id "11d95e9a19ce22e7a2da5e864740ad69981705ec")
    (status unavailable)
    (category context-unsupported)
    (stage context)
    (reason "no independent context rule for Assert within whole-source"))
  (case (id "13ef338566a4c549539b0f110831c08de69f2f9f")
    (status available)
    (context assert-bridge)
    (source-type (Act Assertion))
    (source-typing (typing (Act Assertion) () ()))
    (target-typing (typing (Act Assertion) () ()))
    (payload-source-typing (typing Content () ()))
    (payload-target-typing (typing Content (effectful-call) ()))
    (term
     (Assert
      (¬
       (∀
        (λ (($x1 :: Entity))
          (→
           ((λ (($x :: Entity)) (gerku $x)) $x1)
           ((λ (($x :: Entity))
              (CloseClause
               (λ (($actual_event :: (Referents Eventuality)))
                 (∧ ((StateClause (blabi $x)) $actual_event) (fasnu $actual_event)))))
            $x1))))))))
  (case (id "14dc45f6fcb104cae08ce81c7d9ff9a0efe9dede")
    (status available)
    (context whole-a0)
    (source-type Content)
    (source-typing (typing Content () ()))
    (target-typing (typing Content () ()))
    (term (¬ (∃ (λ (($x1 :: Entity)) (∧ ($x $x1) ($r $x1)))))))
  (case (id "1867f772a83bedef278eb16628b29786241f5704")
    (status unavailable)
    (category grammar-unsupported)
    (stage source)
    (reason
     "outside frozen A0 payload grammar: '(AtLeast 1 (λ (($x Entity)) (Bind (($s Scale (Context))) (gerku $x))) (λ (($w (Referents Entity))) (CloseWith (row jmaji 1 direct-event (1)) ((1 $w)))))"))
  (case (id "195dbd61b277d0041b57830565980e9d335f7456")
    (status available)
    (context whole-a0)
    (source-type Content)
    (source-typing (typing Content (effectful-call) ()))
    (target-typing (typing Content (effectful-call) ()))
    (term
     (∃
      (λ (($x1 :: Entity))
        (∧
         ((λ (($x :: Entity)) (gerku $x)) $x1)
         ((λ (($w :: Entity))
            (CloseClause
             (λ (($actual_event :: (Referents Eventuality)))
               (∧
                ((λ (($event :: (Referents Eventuality)))
                   (Bind ($ctx3 :: (Referents Entity)) (Context) (tavla $w Speaker $ctx3 $event)))
                 $actual_event)
                (fasnu $actual_event)))))
          $x1))))))
  (case (id "1d0f6a701fee3d78f3253fab11fe08d880a958eb")
    (status available)
    (context whole-a0)
    (source-type Content)
    (source-typing (typing Content (effectful-call) ()))
    (target-typing (typing Content (effectful-call) ()))
    (term (¬ (∃ (λ (($r1 :: (Referents Entity))) (∧ ($x $r1) ($r $r1)))))))
  (case (id "1e28492206cbc7c52192f9dc12976d9c59978dec")
    (status available)
    (context whole-a0)
    (source-type Content)
    (source-typing (typing Content (effectful-call) ()))
    (target-typing (typing Content (effectful-call) ()))
    (term (∃ (λ (($x1 :: Eventuality)) (∧ ($x $x1) ($r $x1))))))
  (case (id "1f588b7da2a44d6342b0cfbe0c063edc29b07d9b")
    (status unavailable)
    (category grammar-unsupported)
    (stage source)
    (reason
     "outside frozen A0 payload grammar: '(Generic Typical (λ (($x Entity)) (Bind (($s Scale (Context))) (gerku $x))) (λ (($x Entity)) (CloseWith (row jmaji 1 direct-event (1)) ((1 $x)))))"))
  (case (id "214203ae1c9fc4028fbd556ac7047d703e7082ee")
    (status unavailable)
    (category context-unsupported)
    (stage context)
    (reason "no independent context rule for Assert within whole-source"))
  (case (id "2350ec46a860b191ed7dfc8805106543d00813c7")
    (status unavailable)
    (category unclassified-non-admission)
    (stage source)
    (reason
     "source has 0 admitted A0 typings: '(SetOf (λ (($x Entity)) (Bind (($r (Referents Entity) (SelectSome (λ (($y Entity)) (gerku $y))))) (gerku $x))))"))
  (case (id "26f1c944a99b33a700914e37542483394829d333")
    (status unavailable)
    (category grammar-unsupported)
    (stage source)
    (reason
     "outside frozen A0 payload grammar: '(GlobalExactly 1 (λ (($x Entity)) (gerku $x)) (λ (($x Entity)) (Bind (($s Scale (Context))) (CloseWith (row jmaji 1 direct-event (1)) ((1 $x))))))"))
  (case (id "277c687168048661b7487b29e65cfe1d261affd8")
    (status available)
    (context whole-a0)
    (source-type Content)
    (source-typing (typing Content (refer) ()))
    (target-typing (typing Content (refer) ()))
    (term
     (Bind
      ($w1 :: (Referents Entity))
      (SelectAtLeast 1 (λ (($x :: Entity)) (gerku $x)))
      ((λ (($w :: (Referents Entity)))
         (CloseClause
          (λ (($actual_event :: (Referents Eventuality)))
            (∧ ((λ (($event :: (Referents Eventuality))) (jmaji $w $event)) $actual_event) (fasnu $actual_event)))))
       $w1))))
  (case (id "29bf44bac72a5633b69d8eb81dc6702a6e17bbbb")
    (status unavailable)
    (category context-unsupported)
    (stage context)
    (reason "no independent context rule for Assert within whole-source"))
  (case (id "2a00f8ca5df0ba140dbe29fa18c0acda9b274913")
    (status unavailable)
    (category unclassified-non-admission)
    (stage source)
    (reason
     "source has 0 admitted A0 typings: '(λ (($p (EFn (Entity) Content)) ($r (Referents Entity))) (CoveredBy $p $r))"))
  (case (id "2b338049c10e9453426315140e2d00875af639d9")
    (status unavailable)
    (category unclassified-non-admission)
    (stage source)
    (reason
     "source has 0 admitted A0 typings: '(SetOf (λ (($z Entity)) (MoreThan 0 (λ (($x Entity)) (gerku $x)) (λ (($w (Referents Entity))) (CloseWith (row jmaji 1 direct-event (1)) ((1 $w)))))))"))
  (case (id "2ba4f999ea724091045ddc204cbf6851ca7b2d35")
    (status unavailable)
    (category grammar-unsupported)
    (stage source)
    (reason
     "outside frozen A0 payload grammar: '(GlobalExactly 1 (λ (($x Entity)) (Bind (($s Scale (Context))) (gerku $x))) (λ (($x Entity)) (CloseWith (row jmaji 1 direct-event (1)) ((1 $x)))))"))
  (case (id "304422c80d6314f63fa20beed0d3e9823577a6f9")
    (status available)
    (context assert-bridge)
    (source-type (Act Assertion))
    (source-typing (typing (Act Assertion) () ()))
    (target-typing (typing (Act Assertion) () ()))
    (payload-source-typing (typing Content (effectful-call) ()))
    (payload-target-typing (typing Content (effectful-call) ()))
    (term
     (Assert
      (∃
       (λ (($x1 :: Entity))
         (∧
          ((λ (($x :: Entity)) (gerku $x)) $x1)
          ((λ (($w :: Entity))
             (CloseClause
              (λ (($actual_event :: (Referents Eventuality)))
                (∧
                 ((λ (($event :: (Referents Eventuality)))
                    (Bind ($ctx3 :: (Referents Entity)) (Context) (tavla $w Speaker $ctx3 $event)))
                  $actual_event)
                 (fasnu $actual_event)))))
           $x1)))))))
  (case (id "33cb8f8dd15af7286c07ceff96c9c45613658e95")
    (status unavailable)
    (category context-unsupported)
    (stage context)
    (reason "no independent context rule for Assert within whole-source"))
  (case (id "352a489bb8b6a76622a78e09991c14af379cb0a7")
    (status available)
    (context assert-bridge)
    (source-type (Act Assertion))
    (source-typing (typing (Act Assertion) () ()))
    (target-typing (typing (Act Assertion) () ()))
    (payload-source-typing (typing Content () ()))
    (payload-target-typing (typing Content (effectful-call) ()))
    (term
     (Assert
      (∃
       (λ (($x1 :: Entity))
         (∧
          ((λ (($x :: Entity)) (gerku $x)) $x1)
          ((λ (($w :: Entity))
             (CloseClause
              (λ (($actual_event :: (Referents Eventuality)))
                (∧ ((StateClause (blabi $w)) $actual_event) (fasnu $actual_event)))))
           $x1)))))))
  (case (id "356837155ec5d15971bf168c66836f7b664728f7")
    (status unavailable)
    (category grammar-unsupported)
    (stage source)
    (reason
     "outside frozen A0 payload grammar: '(SetOf (λ (($z Entity)) (AtLeast 0 (λ (($x Entity)) (gerku $x)) (λ (($w (Referents Entity))) (Bind (($s Scale (Context))) (CloseWith (row jmaji 1 direct-event (1)) ((1 $w))))))))"))
  (case (id "361a294c5db62cdbd2b35d436af41c0197631032")
    (status available)
    (context assert-bridge)
    (source-type (Act Assertion))
    (source-typing (typing (Act Assertion) () ()))
    (target-typing (typing (Act Assertion) () ()))
    (payload-source-typing (typing Content () ()))
    (payload-target-typing (typing Content () ()))
    (term
     (Assert
      (¬
       (∃
        (λ (($r1 :: (Referents Entity)))
          (∧
           ((λ (($r :: (Referents Entity))) (prenu $r)) $r1)
           ((λ (($w :: (Referents Entity)))
              (CloseClause
               (λ (($actual_event :: (Referents Eventuality)))
                 (∧
                  ((λ (($event :: (Referents Eventuality))) (jmaji $w $event)) $actual_event)
                  (fasnu $actual_event)))))
            $r1))))))))
  (case (id "387dfd07a6ebc6a3d19b054f498cff4f379330cf")
    (status unavailable)
    (category context-unsupported)
    (stage context)
    (reason "no independent context rule for SentenceSign within whole-source"))
  (case (id "3a3cadb49384c27db6a6a21decdc1a9fdd9d176c")
    (status available)
    (context whole-a0)
    (source-type Content)
    (source-typing (typing Content (effectful-call) ()))
    (target-typing (typing Content (effectful-call) ()))
    (term (∃ (λ (($r1 :: (Referents Number))) (∧ ($x $r1) ($r $r1))))))
  (case (id "3ae1d25ae39772469efc3b8caa937241917cb06b")
    (status unavailable)
    (category grammar-unsupported)
    (stage source)
    (reason
     "outside frozen A0 payload grammar: '(Exactly 1 (λ (($x Entity)) (Bind (($s Scale (Context))) (gerku $x))) (λ (($w (Referents Entity))) (CloseWith (row jmaji 1 direct-event (1)) ((1 $w)))))"))
  (case (id "3d34cb0f4f289a63dace2aedc2a86e684759baee")
    (status unavailable)
    (category grammar-unsupported)
    (stage source)
    (reason
     "outside frozen A0 payload grammar: '(No (λ (($x Entity)) (gerku $x)) (λ (($w (Referents Entity))) (Bind (($s Scale (Context))) (CloseWith (row jmaji 1 direct-event (1)) ((1 $w))))))"))
  (case (id "3e20c1451de1e24477c2c9c376eafbd7a8be2150")
    (status unavailable)
    (category context-unsupported)
    (stage context)
    (reason "no independent context rule for Mention within whole-source"))
  (case (id "3e2bc26981287529b8d7ddc426dc8fba4458fb06")
    (status available)
    (context whole-a0)
    (source-type Content)
    (source-typing (typing Content () ()))
    (target-typing (typing Content () ()))
    (term (∀ (λ (($x1 :: Number)) (→ ($x $x1) ($r $x1))))))
  (case (id "3f832f695b663a6fa5d39a2336404b96c4854603")
    (status unavailable)
    (category context-unsupported)
    (stage context)
    (reason "no independent context rule for Mention within whole-source"))
  (case (id "41354da416e736280e6ae37f353604dad4b680be")
    (status available)
    (context whole-a0)
    (source-type Content)
    (source-typing (typing Content (effectful-call) ()))
    (target-typing (typing Content (effectful-call) ()))
    (term (∀ (λ (($x1 :: Number)) (→ ($x $x1) ($r $x1))))))
  (case (id "42171935390224ab5042ee63543b3d03e33f6009")
    (status available)
    (context whole-a0)
    (source-type Content)
    (source-typing (typing Content (effectful-call refer) ()))
    (target-typing (typing Content (effectful-call refer) ()))
    (term
     (Bind
      ($r :: (Referents Entity))
      (Refer (λ (($unit :: (Referents Entity))) (gerku $unit)))
      (CloseClause
       (λ (($actual_event :: (Referents Eventuality)))
         (∧
          ((λ (($event :: (Referents Eventuality)))
             (Bind ($ctx3 :: (Referents Entity)) (Context) (tavla Speaker $r $ctx3 $event)))
           $actual_event)
          (fasnu $actual_event)))))))
  (case (id "42c9d9ff87974e6c60bfdade0803e1d4e9b31e30")
    (status available)
    (context assert-bridge)
    (source-type (Act Assertion))
    (source-typing (typing (Act Assertion) () ()))
    (target-typing (typing (Act Assertion) () ()))
    (payload-source-typing (typing Content () ()))
    (payload-target-typing (typing Content (effectful-call) ()))
    (term
     (Assert
      (¬
       (∀
        (λ (($x :: Entity))
          (→
           ((λ (($restrictor_member :: Entity)) (gerku $restrictor_member)) $x)
           ((λ (($nuclear_member :: Entity))
              (CloseClause
               (λ (($actual_event :: (Referents Eventuality)))
                 (∧ ((StateClause (blabi $nuclear_member)) $actual_event) (fasnu $actual_event)))))
            $x))))))))
  (case (id "4601e0fc1cd98dda4396bef40b0909f12e3e35b0")
    (status unavailable)
    (category malformed-input)
    (stage environment)
    (reason "missing declaration for free variable $x"))
  (case (id "461e7d7ad9466fa7f5ace614d71b37fa8e8d0df1")
    (status unavailable)
    (category context-unsupported)
    (stage context)
    (reason "no independent context rule for Assert within whole-source"))
  (case (id "46aa50ddf4c3dfe8ae551fe795b739337bf72d66")
    (status available)
    (context whole-a0)
    (source-type Content)
    (source-typing (typing Content (context projective) (finite-set-cardinality-defined)))
    (target-typing (typing Content (context projective) (finite-set-cardinality-defined)))
    (term
     (Bind
      ($nuclear_bajra_2 :: (Referents Entity))
      (Context)
      ($nuclear_bajra_3 :: (Referents Entity))
      (Context)
      ($nuclear_bajra_4 :: (Referents Entity))
      (Context)
      (=
       (Card
        (SetOf
         (λ (($global_member :: Entity))
           (∧
            ((λ (($restrictor_member :: Entity)) (gerku $restrictor_member)) $global_member)
            ((λ (($nuclear_member :: Entity))
               (CloseClause
                (λ (($actual_event :: (Referents Eventuality)))
                  (∧
                   ((λ (($event :: (Referents Eventuality)))
                      (bajra $nuclear_member $nuclear_bajra_2 $nuclear_bajra_3 $nuclear_bajra_4 $event))
                    $actual_event)
                   (fasnu $actual_event)))))
             $global_member)))))
       3))))
  (case (id "474d678ccb329b5010fd93cb2483fc170ba04644")
    (status unavailable)
    (category context-unsupported)
    (stage context)
    (reason "no independent context rule for Assert within whole-source"))
  (case (id "47c74d3e5cc04fb221ad5be388eab58b4cc90600")
    (status unavailable)
    (category context-unsupported)
    (stage context)
    (reason "no independent context rule for Assert within whole-source"))
  (case (id "48f8ddd3eed7e9f370f83decd47ee8253b5dd8df")
    (status available)
    (context whole-a0)
    (source-type Content)
    (source-typing (typing Content (effectful-call) ()))
    (target-typing (typing Content (effectful-call) ()))
    (term (∃ (λ (($x1 :: Number)) (∧ ($x $x1) ($r $x1))))))
  (case (id "49fdcd451a4d10a0253b25faf9b8589f92911cc4")
    (status available)
    (context whole-a0)
    (source-type Content)
    (source-typing (typing Content (context projective) (finite-set-cardinality-defined)))
    (target-typing (typing Content (context projective) (finite-set-cardinality-defined)))
    (term
     (Bind
      ($surface :: (Referents Entity))
      (Context)
      ($limbs :: (Referents Entity))
      (Context)
      ($gait :: (Referents Entity))
      (Context)
      (=
       (Card
        (SetOf
         (λ (($x :: Entity))
           (∧
            (gerku $x)
            (CloseClause
             (λ (($actual_event :: (Referents Eventuality)))
               (∧
                ((λ (($event :: (Referents Eventuality))) (bajra $x $surface $limbs $gait $event)) $actual_event)
                (fasnu $actual_event))))))))
       3))))
  (case (id "4d227a1aeabe5caf0ec07097143646d55611ab35")
    (status available)
    (context whole-a0)
    (source-type Content)
    (source-typing (typing Content () ()))
    (target-typing (typing Content () ()))
    (term (∃ (λ (($x1 :: Number)) (∧ ($x $x1) ($r $x1))))))
  (case (id "4d482e180986050b07345abfbe7a787a7cc17b5f")
    (status unavailable)
    (category grammar-unsupported)
    (stage source)
    (reason "outside frozen A0 payload grammar: '(λ (($p (PredTerm (RowOf zzzz)))) (Close $p))"))
  (case (id "4d9423ca0957656f9622e3e40d2e8d2164ae9f73")
    (status unavailable)
    (category grammar-unsupported)
    (stage source)
    (reason
     "outside frozen A0 payload grammar: '(Some (λ (($x Entity)) (gerku $x)) (λ (($w (Referents Entity))) (Bind (($s Scale (Context))) (CloseWith (row jmaji 1 direct-event (1)) ((1 $w))))))"))
  (case (id "4ddba40634e2b11950d9614d88d55401df7bb472")
    (status unavailable)
    (category context-unsupported)
    (stage context)
    (reason "no independent context rule for Mention within whole-source"))
  (case (id "4e5fd5ea85ec36e00cc8028b583b491ca32f444f")
    (status unavailable)
    (category unclassified-non-admission)
    (stage source)
    (reason
     "source has 0 admitted A0 typings: '(Combine Speaker (CloseWith (row gerku 1 holding-state (1)) ((1 Speaker))))"))
  (case (id "515d77014d591e60474fd4ba23f716adc54c1d54")
    (status unavailable)
    (category context-unsupported)
    (stage context)
    (reason "no independent context rule for Assert within whole-source"))
  (case (id "5216f757d47aaf3edde74d99cd37204869308eca")
    (status unavailable)
    (category grammar-unsupported)
    (stage source)
    (reason
     "outside frozen A0 payload grammar: '(∀ (λ (($p Entity) ($d Entity)) (→ (∧ (prenu $p) (xasli $d) (CloseWith (row ponse 2 holding-state (1 2)) ((1 $p) (2 $d)))) (CloseWith (row darxi 3 direct-event (1 2 3)) ((1 $p) (2 $d))))))"))
  (case (id "521ea6a0036941b13eb668102d0cd8b4bec6a43e")
    (status unavailable)
    (category grammar-unsupported)
    (stage source)
    (reason
     "outside frozen A0 payload grammar: '(FewerThan 1 (λ (($x Entity)) (Bind (($s Scale (Context))) (gerku $x))) (λ (($w (Referents Entity))) (CloseWith (row jmaji 1 direct-event (1)) ((1 $w)))))"))
  (case (id "53630773f8538fd688f7404388201a709de9d070")
    (status unavailable)
    (category context-unsupported)
    (stage context)
    (reason "no independent context rule for Assert within whole-source"))
  (case (id "56e48659ffe3a0f86bfe26991cbd947cccb0cd1e")
    (status available)
    (context assert-bridge)
    (source-type (Act Assertion))
    (source-typing (typing (Act Assertion) () ()))
    (target-typing (typing (Act Assertion) () ()))
    (payload-source-typing (typing Content () ()))
    (payload-target-typing (typing Content (effectful-call) ()))
    (term
     (Assert
      (¬
       (∃
        (λ (($x1 :: Entity))
          (∧
           ((λ (($x :: Entity)) (gerku $x)) $x1)
           ((λ (($w :: Entity))
              (CloseClause
               (λ (($actual_event :: (Referents Eventuality)))
                 (∧ ((StateClause (blabi $w)) $actual_event) (fasnu $actual_event)))))
            $x1))))))))
  (case (id "588862c224b66667eb8bc4056d58a732be2051a8")
    (status available)
    (context whole-a0)
    (source-type (Set Entity))
    (source-typing (typing (Set Entity) () ()))
    (target-typing (typing (Set Entity) () ()))
    (term
     (SetOf
      (λ (($z :: Entity))
        (¬
         (Bind
          ($w1 :: (Referents Entity))
          (SelectAtLeast 1 (λ (($x :: Entity)) (gerku $x)))
          ((λ (($w :: (Referents Entity)))
             (CloseClause
              (λ (($actual_event :: (Referents Eventuality)))
                (∧ ((λ (($event :: (Referents Eventuality))) (jmaji $w $event)) $actual_event) (fasnu $actual_event)))))
           $w1)))))))
  (case (id "5fc4cb3d66cfc99d2326c91c02477ace9fd6873d")
    (status unavailable)
    (category context-unsupported)
    (stage context)
    (reason "no independent context rule for Assert within whole-source"))
  (case (id "5ff051197263d7f1448751e14ff74ada2789534f")
    (status unavailable)
    (category context-unsupported)
    (stage context)
    (reason "no independent context rule for Mention within whole-source"))
  (case (id "60fc87759bed60e4d6ddaa460b108229363b260f")
    (status available)
    (context whole-a0)
    (source-type Content)
    (source-typing (typing Content (effectful-call) ()))
    (target-typing (typing Content (effectful-call) ()))
    (term (¬ (∃ (λ (($x1 :: Eventuality)) (∧ ($x $x1) ($r $x1)))))))
  (case (id "61cf1593994da5db92de0016c1e60bea615086b5")
    (status unavailable)
    (category context-unsupported)
    (stage context)
    (reason "no independent context rule for Assert within whole-source"))
  (case (id "62ef9d2abb3071b0cc188c169d027c46b0ce41fd")
    (status available)
    (context whole-a0)
    (source-type Content)
    (source-typing (typing Content (effectful-call) ()))
    (target-typing (typing Content (effectful-call) ()))
    (term
     (∧
      ((λ (($left :: (Referents Entity)) ($right :: (Referents Entity)))
         (CloseClause
          (λ (($actual_event :: (Referents Eventuality)))
            (∧
             ((λ (($event :: (Referents Eventuality)))
                (Bind ($ctx3 :: (Referents Entity)) (Context) (tavla $left $right $ctx3 $event)))
              $actual_event)
             (fasnu $actual_event)))))
       Speaker
       Audience)
      (∧
       ((λ (($left :: (Referents Entity)) ($right :: (Referents Entity)))
          (CloseClause
           (λ (($actual_event :: (Referents Eventuality)))
             (∧
              ((λ (($event :: (Referents Eventuality)))
                 (Bind ($ctx3 :: (Referents Entity)) (Context) (tavla $left $right $ctx3 $event)))
               $actual_event)
              (fasnu $actual_event)))))
        Audience
        Speaker)
       (∧)))))
  (case (id "637a4cc637a83276ab5c18e850d2c647064f47c8")
    (status unavailable)
    (category context-unsupported)
    (stage context)
    (reason "no independent context rule for Mention within whole-source"))
  (case (id "64dff58ebc8029173fd6c37d9e453f3cf0b91e31")
    (status available)
    (context whole-a0)
    (source-type Content)
    (source-typing (typing Content (effectful-call) ()))
    (target-typing (typing Content (effectful-call) ()))
    (term (¬ (∃ (λ (($r1 :: (Referents Number))) (∧ ($x $r1) ($r $r1)))))))
  (case (id "6535d8b6add07035ebe6d764114833ff161e828c")
    (status unavailable)
    (category context-unsupported)
    (stage context)
    (reason "no independent context rule for SentenceSign within whole-source"))
  (case (id "6630372bac3c65a1d2efd1ebe62e5f48f285f61a")
    (status available)
    (context whole-a0)
    (source-type (Set Entity))
    (source-typing (typing (Set Entity) () ()))
    (target-typing (typing (Set Entity) () ()))
    (term
     (SetOf
      (λ (($z :: Entity))
        (¬
         (Bind
          ($w1 :: (Referents Entity))
          (SelectAtLeast 1 (λ (($x :: Entity)) (gerku $x)))
          ((λ (($w :: (Referents Entity)))
             (CloseClause
              (λ (($actual_event :: (Referents Eventuality)))
                (∧ ((λ (($event :: (Referents Eventuality))) (jmaji $w $event)) $actual_event) (fasnu $actual_event)))))
           $w1)))))))
  (case (id "665e54d5ae4c63ea62677e01ca6a42d6f25fac78")
    (status unavailable)
    (category context-unsupported)
    (stage context)
    (reason "no independent context rule for Mention within whole-source"))
  (case (id "66d020121167148ef905c438f17b9e08279c8c41")
    (status available)
    (context whole-a0)
    (source-type Content)
    (source-typing (typing Content (context projective) (finite-set-cardinality-defined)))
    (target-typing (typing Content (context projective) (finite-set-cardinality-defined)))
    (term
     (Bind
      ($nuclear_bajra_2 :: (Referents Entity))
      (Context)
      ($nuclear_bajra_3 :: (Referents Entity))
      (Context $nuclear_bajra_2)
      ($nuclear_bajra_4 :: (Referents Entity))
      (Context)
      (=
       (Card
        (SetOf
         (λ (($global_member :: Entity))
           (∧
            ((λ (($restrictor_member :: Entity)) (gerku $restrictor_member)) $global_member)
            ((λ (($nuclear_member :: Entity))
               (CloseClause
                (λ (($actual_event :: (Referents Eventuality)))
                  (∧
                   ((λ (($event :: (Referents Eventuality)))
                      (bajra $nuclear_member $nuclear_bajra_2 $nuclear_bajra_3 $nuclear_bajra_4 $event))
                    $actual_event)
                   (fasnu $actual_event)))))
             $global_member)))))
       3))))
  (case (id "679a6c30ff1a50022b0318f997405b963275d5ec")
    (status unavailable)
    (category malformed-input)
    (stage environment)
    (reason "missing declaration for free variable $x"))
  (case (id "686b8a01e259b902a68c4bf25a21c829e47c5f2b")
    (status available)
    (context assert-bridge)
    (source-type (Act Assertion))
    (source-typing (typing (Act Assertion) () ()))
    (target-typing (typing (Act Assertion) () ()))
    (payload-source-typing (typing Content (effectful-call) ()))
    (payload-target-typing (typing Content (effectful-call) ()))
    (term
     (Assert
      (¬
       (∃
        (λ (($r1 :: (Referents Entity)))
          (∧
           ((λ (($r :: (Referents Entity))) (gerku $r)) $r1)
           ((λ (($w :: (Referents Entity)))
              (CloseClause
               (λ (($actual_event :: (Referents Eventuality)))
                 (∧
                  ((λ (($event :: (Referents Eventuality)))
                     (Bind ($ctx3 :: (Referents Entity)) (Context) (tavla Speaker $w $ctx3 $event)))
                   $actual_event)
                  (fasnu $actual_event)))))
            $r1))))))))
  (case (id "695621c9fd6768ad692d49c8fe908e1dffe0e552")
    (status unavailable)
    (category context-unsupported)
    (stage context)
    (reason "no independent context rule for Assert within whole-source"))
  (case (id "6964e1d3ba0bef78d774d795a84a8dd7c8343a77")
    (status available)
    (context whole-a0)
    (source-type (Set Entity))
    (source-typing (typing (Set Entity) () ()))
    (target-typing (typing (Set Entity) () ()))
    (term
     (SetOf
      (λ (($z :: Entity))
        (¬
         (Bind
          ($w1 :: (Referents Entity))
          (SelectAtLeast 1 (λ (($x :: Entity)) (gerku $x)))
          ((λ (($w :: (Referents Entity)))
             (CloseClause
              (λ (($actual_event :: (Referents Eventuality)))
                (∧ ((λ (($event :: (Referents Eventuality))) (jmaji $w $event)) $actual_event) (fasnu $actual_event)))))
           $w1)))))))
  (case (id "6bb9a9d112af8c788db60a146139be5bdf24ed50")
    (status available)
    (context whole-a0)
    (source-type (EFn ((Fn (Eventuality) Content) ClauseContent) Content))
    (source-typing (typing (EFn ((Fn (Eventuality) Content) ClauseContent) Content) () ()))
    (target-typing (typing (EFn ((Fn (Eventuality) Content) ClauseContent) Content) () ()))
    (term
     (λ (($p :: (Fn (Eventuality) Content)) ($c :: ClauseContent))
       (Bind ($w :: (Referents Eventuality)) (SelectExactly 1 $p) ($c $w)))))
  (case (id "6d99ce06d21108698d3e07c185def4ad7282819a")
    (status unavailable)
    (category grammar-unsupported)
    (stage source)
    (reason
     "outside frozen A0 payload grammar: '(MoreThan 1 (λ (($x Entity)) (gerku $x)) (λ (($w (Referents Entity))) (Bind (($s Scale (Context))) (CloseWith (row jmaji 1 direct-event (1)) ((1 $w))))))"))
  (case (id "7018932048d70db90a00f9517739c57b1d12bd59")
    (status unavailable)
    (category context-unsupported)
    (stage context)
    (reason "no independent context rule for Assert within whole-source"))
  (case (id "7111ccf3ee66a9a8da066e83054410be8605a6d7")
    (status unavailable)
    (category context-unsupported)
    (stage context)
    (reason "no independent context rule for Mention within whole-source"))
  (case (id "73990142c280664ee4318f19c642fea7ed0cf18b")
    (status available)
    (context whole-a0)
    (source-type Content)
    (source-typing (typing Content () ()))
    (target-typing (typing Content () ()))
    (term (¬ (∃ (λ (($r1 :: (Referents Eventuality))) (∧ ($x $r1) ($r $r1)))))))
  (case (id "74d0212bae121f9f6f818fd874766bf175e0fc4b")
    (status unavailable)
    (category unclassified-non-admission)
    (stage source)
    (reason
     "source has 0 admitted A0 typings: '(λ (($p (Fn (Eventuality) Content)) ($r (Referents Entity))) (CoveredBy $p $r))"))
  (case (id "7611cc8cb7ce1a802c515748fb22e9c3be81fe04")
    (status available)
    (context whole-a0)
    (source-type Content)
    (source-typing (typing Content (effectful-call) ()))
    (target-typing (typing Content (effectful-call) ()))
    (term
     (∃
      (λ (($x1 :: Entity))
        (∧
         ((λ (($x :: Entity)) (gerku $x)) $x1)
         ((λ (($w :: Entity))
            (CloseClause
             (λ (($actual_event :: (Referents Eventuality)))
               (∧
                ((λ (($event :: (Referents Eventuality)))
                   (Bind ($ctx3 :: (Referents Entity)) (Context) (tavla Speaker $w $ctx3 $event)))
                 $actual_event)
                (fasnu $actual_event)))))
          $x1))))))
  (case (id "78838d7257dd8fbb6ed52d74abd09a02b651f2e6")
    (status available)
    (context assert-bridge)
    (source-type (Act Assertion))
    (source-typing (typing (Act Assertion) () ()))
    (target-typing (typing (Act Assertion) () ()))
    (payload-source-typing (typing Content () ()))
    (payload-target-typing (typing Content (effectful-call) ()))
    (term
     (Assert
      (∀
       (λ (($x :: Entity))
         (→
          ((λ (($person :: Entity))
             (∧
              (prenu $person)
              (∃
               (λ (($x :: Entity))
                 (∧
                  ((λ (($dog :: Entity)) (gerku $dog)) $x)
                  ((λ (($dog :: Entity))
                     (CloseClause
                      (λ (($actual_event :: (Referents Eventuality)))
                        (∧ ((StateClause (ponse $person $dog)) $actual_event) (fasnu $actual_event)))))
                   $x))))))
           $x)
          ((λ (($person :: Entity))
             (CloseClause
              (λ (($actual_event :: (Referents Eventuality)))
                (∧ ((StateClause (blabi $person)) $actual_event) (fasnu $actual_event)))))
           $x)))))))
  (case (id "78eb28d388df392801eebdb6b05b520d78dd8683")
    (status available)
    (context assert-bridge)
    (source-type (Act Assertion))
    (source-typing (typing (Act Assertion) () ()))
    (target-typing (typing (Act Assertion) () ()))
    (payload-source-typing (typing Content (effectful-call) ()))
    (payload-target-typing (typing Content (effectful-call) ()))
    (term
     (Assert
      (∀
       (λ (($x1 :: Entity))
         (→
          ((λ (($x :: Entity)) (gerku $x)) $x1)
          ((λ (($dog :: Entity))
             (Bind
              ($cats :: (Referents Entity))
              (Refer (λ (($r :: (Referents Entity))) (mlatu $r)))
              (CloseClause
               (λ (($actual_event :: (Referents Eventuality)))
                 (∧
                  ((λ (($event :: (Referents Eventuality)))
                     (Bind ($ctx3 :: (Referents Entity)) (Context) (tavla $dog $cats $ctx3 $event)))
                   $actual_event)
                  (fasnu $actual_event))))))
           $x1)))))))
  (case (id "7a9252b6a87cfaf94507e361e0df3f7cf72e97a3")
    (status unavailable)
    (category context-unsupported)
    (stage context)
    (reason "no independent context rule for Assert within whole-source"))
  (case (id "7bcd8dc2f4961a8b551b2d2258b1c8e26d59a3bc")
    (status unavailable)
    (category unclassified-non-admission)
    (stage source)
    (reason
     "source has 0 admitted A0 typings: '(Every (λ (($x Entity)) (gerku $x)) (λ (($w (Referents Entity))) (CloseWith (row jmaji 1 direct-event (1)) ((1 $w)))))"))
  (case (id "7c191d9763138b3416250ae6f5bf49521055400f")
    (status unavailable)
    (category grammar-unsupported)
    (stage source)
    (reason
     "outside frozen A0 payload grammar: '(AtMost 1 (λ (($x Entity)) (gerku $x)) (λ (($w (Referents Entity))) (Bind (($s Scale (Context))) (CloseWith (row jmaji 1 direct-event (1)) ((1 $w))))))"))
  (case (id "7ca8ef9d963163fbd4cd8b8a33d7b1c3934c30af")
    (status unavailable)
    (category context-unsupported)
    (stage context)
    (reason "no independent context rule for Assert within whole-source"))
  (case (id "7d4d458a9d04dd3ba6bae430d4816057d4c3d3cd")
    (status available)
    (context assert-bridge)
    (source-type (Act Assertion))
    (source-typing (typing (Act Assertion) () ()))
    (target-typing (typing (Act Assertion) () ()))
    (payload-source-typing (typing Content () ()))
    (payload-target-typing (typing Content (effectful-call) ()))
    (term
     (Assert
      (∀
       (λ (($x1 :: Entity))
         (→
          ((λ (($x :: Entity)) (gerku $x)) $x1)
          ((λ (($x :: Entity))
             (CloseClause
              (λ (($actual_event :: (Referents Eventuality)))
                (∧ ((StateClause (blabi $x)) $actual_event) (fasnu $actual_event)))))
           $x1)))))))
  (case (id "7f780f0566da970a43f8e1eed8160f12bdf06c0e")
    (status available)
    (context assert-bridge)
    (source-type (Act Assertion))
    (source-typing (typing (Act Assertion) () ()))
    (target-typing (typing (Act Assertion) () ()))
    (payload-source-typing (typing Content (effectful-call) ()))
    (payload-target-typing (typing Content (effectful-call) ()))
    (term
     (Assert
      (∀
       (λ (($x1 :: Entity))
         (→
          ((λ (($x :: Entity)) (gerku $x)) $x1)
          ((λ (($x :: Entity))
             (∃
              (λ (($x1 :: Entity))
                (∧
                 ((λ (($x :: Entity)) (mlatu $x)) $x1)
                 ((λ (($w :: Entity))
                    (CloseClause
                     (λ (($actual_event :: (Referents Eventuality)))
                       (∧
                        ((λ (($event :: (Referents Eventuality)))
                           (Bind ($ctx3 :: (Referents Entity)) (Context) (tavla $x $w $ctx3 $event)))
                         $actual_event)
                        (fasnu $actual_event)))))
                  $x1)))))
           $x1)))))))
  (case (id "7f96a0ab593a3601eeeb783cd16bf0ab90df986e")
    (status unavailable)
    (category context-unsupported)
    (stage context)
    (reason "no independent context rule for Assert within whole-source"))
  (case (id "8106a9b54255c646e0c8751116d4d886509934b9")
    (status unavailable)
    (category context-unsupported)
    (stage context)
    (reason "no independent context rule for Do within whole-source"))
  (case (id "8163cfa0e248843355957879bd8cbcc51dd7e65f")
    (status unavailable)
    (category context-unsupported)
    (stage context)
    (reason "no independent context rule for Assert within whole-source"))
  (case (id "81f9b07efa324d80f1c0bae6616345355a483493")
    (status unavailable)
    (category grammar-unsupported)
    (stage source)
    (reason
     "outside frozen A0 payload grammar: '(AtLeast 1 (λ (($x Entity)) (gerku $x)) (λ (($w (Referents Entity))) (Bind (($s Scale (Context))) (CloseWith (row jmaji 1 direct-event (1)) ((1 $w))))))"))
  (case (id "823f81460a1611321ed58295e69bf0ff3fa830e8")
    (status available)
    (context whole-a0)
    (source-type Content)
    (source-typing (typing Content () ()))
    (target-typing (typing Content () ()))
    (term (∀ (λ (($x1 :: Eventuality)) (→ ($x $x1) ($r $x1))))))
  (case (id "85ea9b541f5e6e09092dcbdec5f36229a2d2706f")
    (status unavailable)
    (category context-unsupported)
    (stage context)
    (reason "no independent context rule for Mention within whole-source"))
  (case (id "86b1cb84a2388cd620c361462da252c3750359df")
    (status unavailable)
    (category grammar-unsupported)
    (stage source)
    (reason
     "outside frozen A0 payload grammar: '(Exactly 1 (λ (($x Entity)) (gerku $x)) (λ (($w (Referents Entity))) (Bind (($s Scale (Context))) (CloseWith (row jmaji 1 direct-event (1)) ((1 $w))))))"))
  (case (id "87c2718ed127f4ec8251d80779f405dabeb6b1fb")
    (status unavailable)
    (category context-unsupported)
    (stage context)
    (reason "no independent context rule for Assert within whole-source"))
  (case (id "8844fb5c7eb3a5a6ce9d3e52df6875fe170e5dd4")
    (status available)
    (context whole-a0)
    (source-type Content)
    (source-typing (typing Content () ()))
    (target-typing (typing Content () ()))
    (term (∀ (λ (($x1 :: Entity)) (→ ($x $x1) ($r $x1))))))
  (case (id "892fd70ba536901bcce73f4fe1df29035b464860")
    (status unavailable)
    (category grammar-unsupported)
    (stage source)
    (reason
     "outside frozen A0 payload grammar: '(SetOf (λ (($z Entity)) (Exactly 0 (λ (($x Entity)) (gerku $x)) (λ (($w (Referents Entity))) (Bind (($s Scale (Context))) (CloseWith (row jmaji 1 direct-event (1)) ((1 $w))))))))"))
  (case (id "89b40210a2103ac2c256a69ee20dd6401ebe2aae")
    (status unavailable)
    (category context-unsupported)
    (stage context)
    (reason "no independent context rule for Ask within whole-source"))
  (case (id "8cb7eee7664a04dab103d7c12b5ac81b779495eb")
    (status unavailable)
    (category context-unsupported)
    (stage context)
    (reason "no independent context rule for Assert within whole-source"))
  (case (id "8da7d02eafb4d49c334c666a6bda1022651cb4b3")
    (status available)
    (context whole-a0)
    (source-type Content)
    (source-typing (typing Content (effectful-call) ()))
    (target-typing (typing Content (effectful-call) ()))
    (term (∀ (λ (($x1 :: Eventuality)) (→ ($x $x1) ($r $x1))))))
  (case (id "8e251e2449e938fab084751d0a47b168a35f09c0")
    (status unavailable)
    (category context-unsupported)
    (stage context)
    (reason "no independent context rule for Assert within whole-source"))
  (case (id "8ee772ea90969da159b32de133af285ee54b3b08")
    (status unavailable)
    (category grammar-unsupported)
    (stage source)
    (reason
     "outside frozen A0 payload grammar: '(MoreThan 1 (λ (($x Entity)) (Bind (($s Scale (Context))) (gerku $x))) (λ (($w (Referents Entity))) (CloseWith (row jmaji 1 direct-event (1)) ((1 $w)))))"))
  (case (id "8f1c82306360b91dcf555dd1bdd22fa812ceafc3")
    (status unavailable)
    (category context-unsupported)
    (stage context)
    (reason "no independent context rule for Assert within whole-source"))
  (case (id "8f45e6958948fa1f1c5e9390d489e7a8bc3c091c")
    (status unavailable)
    (category context-unsupported)
    (stage context)
    (reason "no independent context rule for Mention within whole-source"))
  (case (id "9100ac2ba8c22f1d3f21a197cf4cc25f62afb978")
    (status unavailable)
    (category context-unsupported)
    (stage context)
    (reason "no independent context rule for Assert within whole-source"))
  (case (id "91e734c8cc712b20008b7270ed9241dd870bd83f")
    (status available)
    (context whole-a0)
    (source-type (Fn ((Fn (Entity) Content) (Referents Entity)) Content))
    (source-typing (typing (Fn ((Fn (Entity) Content) (Referents Entity)) Content) () ()))
    (target-typing (typing (Fn ((Fn (Entity) Content) (Referents Entity)) Content) () ()))
    (term
     (λ (($p :: (Fn (Entity) Content)) ($r :: (Referents Entity)))
       (∧
        (∀ (λ (($member :: Entity)) (→ (Among $member $r) ($p $member))))
        (∀
         (λ (($subreference :: (Referents Entity)))
           (→
            (Among $subreference $r)
            (∃
             (λ (($member :: Entity))
               (∧
                ($p $member)
                (∃
                 (λ (($common :: (Referents Entity)))
                   (∧ (Among $common $member) (Among $common $subreference))))))))))))))
  (case (id "925b1a64ed5237b2d6dc1312849292e8ac28b41b")
    (status available)
    (context whole-a0)
    (source-type Content)
    (source-typing (typing Content () ()))
    (target-typing (typing Content () ()))
    (term (∃ (λ (($x1 :: Entity)) (∧ ($x $x1) ($r $x1))))))
  (case (id "9321744e93f7036a53463bf36d4072cc74f2b8fb")
    (status unavailable)
    (category grammar-unsupported)
    (stage source)
    (reason
     "outside frozen A0 payload grammar: '(∀ (λ (($p Entity) ($d Entity)) (→ (∧ (prenu $p) (xasli $d) (CloseWith (row ponse 2 holding-state (1 2)) ((1 $p) (2 $d)))) (CloseWith (row darxi 3 direct-event (1 2 3)) ((1 $p) (2 $d))))))"))
  (case (id "933ed459ec2709af28c10938d6d15c37d6780e60")
    (status available)
    (context whole-a0)
    (source-type Content)
    (source-typing (typing Content () ()))
    (target-typing (typing Content () ()))
    (term (¬ (∃ (λ (($x1 :: Eventuality)) (∧ ($x $x1) ($r $x1)))))))
  (case (id "93f412d4c8e70f45ef7f289f6c554ad2a0a70387")
    (status unavailable)
    (category context-unsupported)
    (stage context)
    (reason "no independent context rule for Assert within whole-source"))
  (case (id "9441e9406a7fb5c08427c9958b5813ae110c9064")
    (status unavailable)
    (category unclassified-non-admission)
    (stage target)
    (reason "expanded target has 0 A0 typings at source type 'Content"))
  (case (id "96e93d97016dd645070b670068a4827536451100")
    (status unavailable)
    (category context-unsupported)
    (stage context)
    (reason "no independent context rule for Assert within whole-source"))
  (case (id "97437724c3bee94e6b423f9c73c31b239417dc45")
    (status unavailable)
    (category unclassified-non-admission)
    (stage target)
    (reason "expanded target has 0 A0 typings at source type 'Content"))
  (case (id "9a3d9b551c3ac1553da45cfd95cb258a6cb36a13")
    (status unavailable)
    (category unclassified-non-admission)
    (stage source)
    (reason
     "source has 0 admitted A0 typings: '(Generic Typical (λ (($x Entity)) (mlatu $x)) (λ (($x Entity)) (CloseWith (row cinri 2 holding-state (1 2)) ((1 $x)))))"))
  (case (id "9a7acc1a00231c256073bb1164e60dcc65e2fccc")
    (status unavailable)
    (category context-unsupported)
    (stage context)
    (reason "no independent context rule for Mention within whole-source"))
  (case (id "9c2755813fa230bef2c71056e5b45f497e27ef2c")
    (status unavailable)
    (category context-unsupported)
    (stage context)
    (reason "no independent context rule for Mention within whole-source"))
  (case (id "9e410285ceb918074344ad528bcd79e037212ee8")
    (status unavailable)
    (category unclassified-non-admission)
    (stage source)
    (reason
     "source has 0 admitted A0 typings: '(CloseWith (row remna 1 holding-state (1)) ((1 (Combine Speaker Audience))))"))
  (case (id "a3c0c4aaec7ccef15f25fae0a9a840cef1cab8fc")
    (status available)
    (context assert-bridge)
    (source-type (Act Assertion))
    (source-typing (typing (Act Assertion) () ()))
    (target-typing (typing (Act Assertion) () ()))
    (payload-source-typing (typing Content (effectful-call) ()))
    (payload-target-typing (typing Content (effectful-call) ()))
    (term
     (Assert
      (∀
       (λ (($x1 :: Entity))
         (→
          ((λ (($x :: Entity)) (gerku $x)) $x1)
          ((λ (($dog :: Entity))
             (∃
              (λ (($x :: Entity))
                (∧
                 ((λ (($y :: Entity)) (mlatu $y)) $x)
                 ((λ (($cat :: Entity))
                    (CloseClause
                     (λ (($actual_event :: (Referents Eventuality)))
                       (∧
                        ((λ (($event :: (Referents Eventuality)))
                           (Bind ($ctx3 :: (Referents Entity)) (Context) (tavla $dog $cat $ctx3 $event)))
                         $actual_event)
                        (fasnu $actual_event)))))
                  $x)))))
           $x1)))))))
  (case (id "a3c12cc87e39c2d0aaa2675dafcd4d8009fdf513")
    (status available)
    (context assert-bridge)
    (source-type (Act Assertion))
    (source-typing (typing (Act Assertion) () (finite-set-cardinality-defined)))
    (target-typing (typing (Act Assertion) () (finite-set-cardinality-defined)))
    (payload-source-typing (typing Content (effectful-call) (finite-set-cardinality-defined)))
    (payload-target-typing (typing Content (effectful-call) (finite-set-cardinality-defined)))
    (term
     (Assert
      (∀
       (λ (($x1 :: Entity))
         (→
          ((λ (($x :: Entity)) (gerku $x)) $x1)
          ((λ (($x :: Entity))
             (Bind
              ($nuclear_tavla_3 :: (Referents Entity))
              (Context)
              (=
               (Card
                (SetOf
                 (λ (($global_member :: Entity))
                   (∧
                    ((λ (($restrictor_member :: Entity)) (mlatu $restrictor_member)) $global_member)
                    ((λ (($nuclear_member :: Entity))
                       (CloseClause
                        (λ (($actual_event :: (Referents Eventuality)))
                          (∧
                           ((λ (($event :: (Referents Eventuality))) (tavla $x $nuclear_member $nuclear_tavla_3 $event))
                            $actual_event)
                           (fasnu $actual_event)))))
                     $global_member)))))
               3)))
           $x1)))))))
  (case (id "a420add01889181f8bacb04f9f9c30f61b41dcae")
    (status available)
    (context whole-a0)
    (source-type Content)
    (source-typing (typing Content (context projective) (finite-set-cardinality-defined)))
    (target-typing (typing Content (context projective) (finite-set-cardinality-defined)))
    (term
     (Bind
      ($restrictor_klama_2 :: (Referents Entity))
      (Context)
      ($restrictor_klama_3 :: (Referents Entity))
      (Context)
      ($restrictor_klama_4 :: (Referents Entity))
      (Context)
      ($restrictor_klama_5 :: (Referents Entity))
      (Context)
      ($nuclear_klama_2 :: (Referents Entity))
      (Context)
      ($nuclear_klama_3 :: (Referents Entity))
      (Context)
      ($nuclear_klama_4 :: (Referents Entity))
      (Context)
      ($nuclear_klama_5 :: (Referents Entity))
      (Context)
      (=
       (Card
        (SetOf
         (λ (($global_member :: Entity))
           (∧
            ((λ (($restrictor_member :: Entity))
               (CloseClause
                (λ (($actual_event :: (Referents Eventuality)))
                  (∧
                   ((λ (($event :: (Referents Eventuality)))
                      (klama
                       $restrictor_member
                       $restrictor_klama_2
                       $restrictor_klama_3
                       $restrictor_klama_4
                       $restrictor_klama_5
                       $event))
                    $actual_event)
                   (fasnu $actual_event)))))
             $global_member)
            ((λ (($nuclear_member :: Entity))
               (CloseClause
                (λ (($actual_event :: (Referents Eventuality)))
                  (∧
                   ((λ (($event :: (Referents Eventuality)))
                      (klama
                       $nuclear_member
                       $nuclear_klama_2
                       $nuclear_klama_3
                       $nuclear_klama_4
                       $nuclear_klama_5
                       $event))
                    $actual_event)
                   (fasnu $actual_event)))))
             $global_member)))))
       3))))
  (case (id "a6b67772465a0276af377d33d98d102d7e3bddff")
    (status unavailable)
    (category context-unsupported)
    (stage context)
    (reason "no independent context rule for Assert within whole-source"))
  (case (id "a7dc745e8ebce5f8e1e04767521823f6cdbdbc7c")
    (status unavailable)
    (category unclassified-non-admission)
    (stage source)
    (reason
     "source has 0 admitted A0 typings: '(SetOf (λ (($z Entity)) (GlobalExactly 1 (λ (($x Entity)) (gerku $x)) (λ (($x Entity)) (CloseWith (row jmaji 1 direct-event (1)) ((1 $x)))))))"))
  (case (id "a90859565ec0462fd34ba74cea3fb0f69ee30977")
    (status available)
    (context whole-a0)
    (source-type Content)
    (source-typing (typing Content () ()))
    (target-typing (typing Content () ()))
    (term (¬ (∃ (λ (($r1 :: (Referents Entity))) (∧ ($x $r1) ($r $r1)))))))
  (case (id "a99847a240454c1a50605422e0369038b77f03a3")
    (status unavailable)
    (category context-unsupported)
    (stage context)
    (reason "no independent context rule for Ask within whole-source"))
  (case (id "aef2d7cb00a5866e752137b3a5717ef6bb3a025d")
    (status unavailable)
    (category grammar-unsupported)
    (stage source)
    (reason
     "outside frozen A0 payload grammar: '(Some (λ (($x Entity)) (Bind (($s Scale (Context))) (gerku $x))) (λ (($w (Referents Entity))) (CloseWith (row jmaji 1 direct-event (1)) ((1 $w)))))"))
  (case (id "b40eea04da4fdffdbce331b1814fcaf0d259cba4")
    (status unavailable)
    (category context-unsupported)
    (stage context)
    (reason "no independent context rule for Do within whole-source"))
  (case (id "b45f5f1e3c64a0ae5b25571470837b2fa287771f")
    (status unavailable)
    (category context-unsupported)
    (stage context)
    (reason "no independent context rule for Mention within whole-source"))
  (case (id "b48cd52864e981629d5094f9f34a257d7c5c9113")
    (status available)
    (context whole-a0)
    (source-type Content)
    (source-typing (typing Content () ()))
    (target-typing (typing Content () ()))
    (term (∃ (λ (($r1 :: (Referents Eventuality))) (∧ ($x $r1) ($r $r1))))))
  (case (id "b6fdf53c940c0fbfddd3982d10ccb1b9444ce6ae")
    (status unavailable)
    (category context-unsupported)
    (stage context)
    (reason "no independent context rule for Assert within whole-source"))
  (case (id "b7243031b806f2fb8895ebd30e470e492903db57")
    (status available)
    (context whole-a0)
    (source-type Content)
    (source-typing (typing Content () ()))
    (target-typing (typing Content () ()))
    (term (∃ (λ (($x1 :: Eventuality)) (∧ ($x $x1) ($r $x1))))))
  (case (id "b7c361bf3ce652c761d68c33ce87b7f5169e4eb7")
    (status available)
    (context whole-a0)
    (source-type Content)
    (source-typing (typing Content (effectful-call) ()))
    (target-typing (typing Content (effectful-call) ()))
    (term (∃ (λ (($r1 :: (Referents Entity))) (∧ ($x $r1) ($r $r1))))))
  (case (id "b8c355f86a0a95f9fa205ca74b6fe21167143e31")
    (status available)
    (context whole-a0)
    (source-type Content)
    (source-typing (typing Content (effectful-call) ()))
    (target-typing (typing Content (effectful-call) ()))
    (term (¬ (∃ (λ (($x1 :: Entity)) (∧ ($x $x1) ($r $x1)))))))
  (case (id "bb5a31420e23dca522099a310f5e5940c7c4d646")
    (status unavailable)
    (category unclassified-non-admission)
    (stage target)
    (reason "expanded target has 0 A0 typings at source type 'Content"))
  (case (id "bc919c6ebc40037be37a33bc6e082f3746325b7b")
    (status unavailable)
    (category grammar-unsupported)
    (stage source)
    (reason
     "outside frozen A0 payload grammar: '(∃ (λ (($dog Entity) ($person Entity)) (∧ (gerku $dog) (prenu $person) (CloseWith (row nelci 2 holding-state (1 2)) ((1 $dog) (2 $person))))))"))
  (case (id "c0e41a9613b287bfe9fa8a063c7d8efc19655cd0")
    (status available)
    (context whole-a0)
    (source-type (Fn ((Referents Entity) (Fn (Entity) Content)) Content))
    (source-typing (typing (Fn ((Referents Entity) (Fn (Entity) Content)) Content) () ()))
    (target-typing (typing (Fn ((Referents Entity) (Fn (Entity) Content)) Content) () ()))
    (term
     (λ (($bread :: (Referents Entity)) ($breadUnit :: (Fn (Entity) Content)))
       (∧
        (∧
         (∀ (λ (($member :: Entity)) (→ (Among $member $bread) ($breadUnit $member))))
         (∀
          (λ (($subreference :: (Referents Entity)))
            (→
             (Among $subreference $bread)
             (∃
              (λ (($member :: Entity))
                (∧
                 ($breadUnit $member)
                 (∃
                  (λ (($common :: (Referents Entity)))
                    (∧ (Among $common $member) (Among $common $subreference)))))))))))
        (∀
         (λ (($r :: (Referents Entity)))
           (→ (Among $r $bread) (∃ (λ (($s :: (Referents Entity))) (∧ (Among $s $r) (¬ (Among $r $s))))))))))))
  (case (id "c2b13aeac1d028b6008fcaa99d4139867212c0df")
    (status available)
    (context whole-a0)
    (source-type Content)
    (source-typing (typing Content (projective) (finite-set-cardinality-defined)))
    (target-typing (typing Content (projective) (finite-set-cardinality-defined)))
    (term
     (=
      (Card
       (SetOf
        (λ (($global_member :: Entity))
          (∧ ((λ (($p :: Entity)) (prenu $p)) $global_member) ((λ (($q :: Entity)) (blabi $q)) $global_member)))))
      2)))
  (case (id "c7387efbff0854a92d3ebeadbb69dc704affe9f6")
    (status unavailable)
    (category context-unsupported)
    (stage context)
    (reason "no independent context rule for Assert within whole-source"))
  (case (id "c7d4919b24c88919dda77d438875a3f6f53b453c")
    (status unavailable)
    (category context-unsupported)
    (stage context)
    (reason "no independent context rule for Mention within whole-source"))
  (case (id "c92bfd5d1f2d869b13d6aa49b9a5989472a7fec1")
    (status available)
    (context whole-a0)
    (source-type Content)
    (source-typing (typing Content (effectful-call) ()))
    (target-typing (typing Content (effectful-call) ()))
    (term (∃ (λ (($r1 :: (Referents Eventuality))) (∧ ($x $r1) ($r $r1))))))
  (case (id "c95543d005238c8dabd2975103cda6cfb1cde15b")
    (status available)
    (context whole-a0)
    (source-type Content)
    (source-typing (typing Content (effectful-call) ()))
    (target-typing (typing Content (effectful-call) ()))
    (term (¬ (∃ (λ (($x1 :: Number)) (∧ ($x $x1) ($r $x1)))))))
  (case (id "cb9ec898c0ebd3ce8c2c1fb4ac7eb701cf81a772")
    (status unavailable)
    (category context-unsupported)
    (stage context)
    (reason "no independent context rule for Mention within whole-source"))
  (case (id "cbeb7069823bd300b05864e10b2322bee39b8eb8")
    (status unavailable)
    (category context-unsupported)
    (stage context)
    (reason "no independent context rule for Assert within whole-source"))
  (case (id "cd741d0aaeffd4cb3f43c7acc40813ca13768fc1")
    (status unavailable)
    (category unclassified-non-admission)
    (stage target)
    (reason "expanded target has 0 A0 typings at source type 'Content"))
  (case (id "cdbed9ae8889cb9857ce42ffdc440282aab47518")
    (status unavailable)
    (category grammar-unsupported)
    (stage source)
    (reason
     "outside frozen A0 payload grammar: '(FewerThan 1 (λ (($x Entity)) (gerku $x)) (λ (($w (Referents Entity))) (Bind (($s Scale (Context))) (CloseWith (row jmaji 1 direct-event (1)) ((1 $w))))))"))
  (case (id "ce45bfa25171aa37e87244fa29f6af160fb4f9a3")
    (status unavailable)
    (category context-unsupported)
    (stage context)
    (reason "no independent context rule for Mention within whole-source"))
  (case (id "ce5f54409233f87a06f40fa7162207b7719ed949")
    (status unavailable)
    (category grammar-unsupported)
    (stage source)
    (reason
     "outside frozen A0 payload grammar: '(Every (λ (($x Entity)) (Bind (($s Scale (Context))) (gerku $x))) (λ (($x Entity)) (CloseWith (row jmaji 1 direct-event (1)) ((1 $x)))))"))
  (case (id "cf406a6137e6d29f89dcd8771e3315a2f8370045")
    (status unavailable)
    (category context-unsupported)
    (stage context)
    (reason "no independent context rule for Assert within whole-source"))
  (case (id "cf4d92656bda690acd276e9203d0f63d15050c58")
    (status unavailable)
    (category context-unsupported)
    (stage context)
    (reason "no independent context rule for WordSign within Assert"))
  (case (id "d41a79a05eaa9b893290fceedc31bc3777e695b6")
    (status unavailable)
    (category grammar-unsupported)
    (stage source)
    (reason
     "outside frozen A0 payload grammar: '(AtMost 1 (λ (($x Entity)) (Bind (($s Scale (Context))) (gerku $x))) (λ (($w (Referents Entity))) (CloseWith (row jmaji 1 direct-event (1)) ((1 $w)))))"))
  (case (id "d4b74f424d70945396466ff26553ae4d8104277c")
    (status unavailable)
    (category context-unsupported)
    (stage context)
    (reason "no independent context rule for Assert within whole-source"))
  (case (id "d4c465b8692516568de2970f2551fd42d645bf65")
    (status unavailable)
    (category context-unsupported)
    (stage context)
    (reason "no independent context rule for Do within whole-source"))
  (case (id "dae7a1015747372b9d2a5e5cb0430b250a2c6199")
    (status unavailable)
    (category context-unsupported)
    (stage context)
    (reason "no independent context rule for Assert within whole-source"))
  (case (id "dc6b2ae3a00c5ff575c7e9880e0dc03bc4c54e83")
    (status available)
    (context assert-bridge)
    (source-type (Act Assertion))
    (source-typing (typing (Act Assertion) () ()))
    (target-typing (typing (Act Assertion) () ()))
    (payload-source-typing (typing Content () ()))
    (payload-target-typing (typing Content () ()))
    (term
     (Assert
      (¬
       (∃
        (λ (($r :: (Referents Entity)))
          (∧
           ((λ (($x :: (Referents Entity))) (prenu $x)) $r)
           ((λ (($w :: (Referents Entity)))
              (CloseClause
               (λ (($actual_event :: (Referents Eventuality)))
                 (∧
                  ((λ (($event :: (Referents Eventuality))) (jmaji $w $event)) $actual_event)
                  (fasnu $actual_event)))))
            $r))))))))
  (case (id "dd60726d8e42d9d819aef5b9e98b0cde8a55d3eb")
    (status available)
    (context whole-a0)
    (source-type Content)
    (source-typing (typing Content () ()))
    (target-typing (typing Content () ()))
    (term (¬ (∃ (λ (($x1 :: Number)) (∧ ($x $x1) ($r $x1)))))))
  (case (id "ddfcec347f67b854dcdbc59b01ea61e976c0f311")
    (status unavailable)
    (category grammar-unsupported)
    (stage source)
    (reason
     "outside frozen A0 payload grammar: '(Generic Typical (λ (($x Entity)) (gerku $x)) (λ (($x Entity)) (Bind (($s Scale (Context))) (CloseWith (row jmaji 1 direct-event (1)) ((1 $x))))))"))
  (case (id "dea28886c2b9a331b99bd06cbdbf0f84f8a18d7a")
    (status unavailable)
    (category unclassified-non-admission)
    (stage source)
    (reason
     "source has 0 admitted A0 typings: '(SetOf (λ (($z Entity)) (AtLeast 1 (λ (($x Entity)) (gerku $x)) (λ (($w (Referents Entity))) (CloseWith (row jmaji 1 direct-event (1)) ((1 $w)))))))"))
  (case (id "e015326497484cfe14f0ccf0d90e044c2f7cee1f")
    (status available)
    (context assert-bridge)
    (source-type (Act Assertion))
    (source-typing (typing (Act Assertion) () ()))
    (target-typing (typing (Act Assertion) () ()))
    (payload-source-typing (typing Content () ()))
    (payload-target-typing (typing Content (effectful-call) ()))
    (term
     (Assert
      (¬
       (∃
        (λ (($r1 :: (Referents Entity)))
          (∧
           ((λ (($r :: (Referents Entity))) (mlatu $r)) $r1)
           ((λ (($w :: (Referents Entity)))
              (CloseClause
               (λ (($actual_event :: (Referents Eventuality)))
                 (∧ ((StateClause (blabi $w)) $actual_event) (fasnu $actual_event)))))
            $r1))))))))
  (case (id "e194c86c0027f59a5b2e08633b91eeb9d4905dde")
    (status unavailable)
    (category context-unsupported)
    (stage context)
    (reason "no independent context rule for Assert within whole-source"))
  (case (id "e2d793fbfb39dff9a96fadd7712f2782748b2307")
    (status unavailable)
    (category unclassified-non-admission)
    (stage target)
    (reason "expanded target has 0 A0 typings at source type 'Content"))
  (case (id "e308057746367a87f89a460965019412eb9b513f")
    (status unavailable)
    (category unclassified-non-admission)
    (stage target)
    (reason "expanded target has 0 A0 typings at source type 'Content"))
  (case (id "e319c178b99588bd94b79a0ad69a0f691679f1c3")
    (status unavailable)
    (category context-unsupported)
    (stage context)
    (reason "no independent context rule for Mention within whole-source"))
  (case (id "e364bb91b4106910ac77758a99ec2401f16fa7a1")
    (status available)
    (context assert-bridge)
    (source-type (Act Assertion))
    (source-typing (typing (Act Assertion) () ()))
    (target-typing (typing (Act Assertion) () ()))
    (payload-source-typing (typing Content (effectful-call) ()))
    (payload-target-typing (typing Content (effectful-call) ()))
    (term
     (Assert
      (CloseClause
       (λ (($actual_event :: (Referents Eventuality)))
         (∧
          ((λ (($event :: (Referents Eventuality)))
             (Bind
              ($ctx2 :: (Referents Entity))
              (Context)
              ($ctx3 :: (Referents Entity))
              (Context)
              ($ctx4 :: (Referents Entity))
              (Context)
              ($ctx5 :: (Referents Entity))
              (Context)
              (klama Speaker $ctx2 $ctx3 $ctx4 $ctx5 $event)))
           $actual_event)
          (fasnu $actual_event)))))))
  (case (id "e3cc58ea58d18b15852ecce37d7b52f277312ef6")
    (status available)
    (context whole-a0)
    (source-type (EFn ((Referents Entity)) Content))
    (source-typing (typing (EFn ((Referents Entity)) Content) () ()))
    (target-typing (typing (EFn ((Referents Entity)) Content) () ()))
    (term
     (λ (($x :: (Referents Entity)))
       (CloseClause
        (λ (($actual_event :: (Referents Eventuality)))
          (∧
           ((λ (($event :: (Referents Eventuality)))
              (Bind
               ($ctx1 :: (Referents Entity))
               (Context)
               ($ctx3 :: (Referents Entity))
               (Context)
               ($ctx4 :: (Referents Entity))
               (Context)
               ($ctx5 :: (Referents Entity))
               (Context)
               (klama $ctx1 $x $ctx3 $ctx4 $ctx5 $event)))
            $actual_event)
           (fasnu $actual_event)))))))
  (case (id "e588d35763d895a68934c732a8ff3c3e78edb5b6")
    (status unavailable)
    (category context-unsupported)
    (stage context)
    (reason "no independent context rule for Assert within whole-source"))
  (case (id "e58c78854c138024e50609666b91b4f15df00d8a")
    (status available)
    (context whole-a0)
    (source-type Content)
    (source-typing (typing Content (effectful-call) ()))
    (target-typing (typing Content (effectful-call) ()))
    (term (¬ (∃ (λ (($r1 :: (Referents Eventuality))) (∧ ($x $r1) ($r $r1)))))))
  (case (id "e9d786c6eeb92a0f74a7853885f198e91d1abf23")
    (status available)
    (context whole-a0)
    (source-type Content)
    (source-typing (typing Content (projective) (finite-set-cardinality-defined)))
    (target-typing (typing Content (projective) (finite-set-cardinality-defined)))
    (term
     (=
      (Card
       (SetOf
        (λ (($global_member :: Entity))
          (∧
           ((λ (($x :: Entity)) (gerku $x)) $global_member)
           ((λ (($x :: Entity))
              (CloseClause
               (λ (($actual_event :: (Referents Eventuality)))
                 (∧
                  ((λ (($event :: (Referents Eventuality))) (jmaji $x $event)) $actual_event)
                  (fasnu $actual_event)))))
            $global_member)))))
      1)))
  (case (id "eb25b474d04d551d558e517f0248943c27c6712e")
    (status unavailable)
    (category malformed-input)
    (stage environment)
    (reason "missing declaration for free variable $x"))
  (case (id "ed9b04034814200f58fddbdec548f99a038bc428")
    (status available)
    (context whole-a0)
    (source-type Content)
    (source-typing (typing Content (effectful-call) ()))
    (target-typing (typing Content (effectful-call) ()))
    (term (∃ (λ (($x1 :: Entity)) (∧ ($x $x1) ($r $x1))))))
  (case (id "eecc4625fc5ffae42cb3bb60deb92d444a28cf62")
    (status available)
    (context whole-a0)
    (source-type (EFn ((Referents Eventuality)) Content))
    (source-typing (typing (EFn ((Referents Eventuality)) Content) () ()))
    (target-typing (typing (EFn ((Referents Eventuality)) Content) () ()))
    (term
     (λ (($e :: (Referents Eventuality)))
       (CloseClause
        (λ (($clause_event :: (Referents Eventuality)))
          (∧
           (∧ (Among $clause_event $e) (Among $e $clause_event))
           ((λ (($actual_event :: (Referents Eventuality)))
              (∧
               ((λ (($lexical_event :: (Referents Eventuality)))
                  (Bind
                   ($ctx2 :: (Referents Entity))
                   (Context)
                   ($ctx3 :: (Referents Entity))
                   (Context)
                   ($ctx4 :: (Referents Entity))
                   (Context)
                   ($ctx5 :: (Referents Entity))
                   (Context)
                   (klama Speaker $ctx2 $ctx3 $ctx4 $ctx5 $lexical_event)))
                $actual_event)
               (fasnu $actual_event)))
            $e)))))))
  (case (id "f05f4d8d6f8900dcf9f2bbc1ff278a93023e2e11")
    (status available)
    (context whole-a0)
    (source-type Content)
    (source-typing (typing Content (context projective) (finite-set-cardinality-defined)))
    (target-typing (typing Content (context projective) (finite-set-cardinality-defined)))
    (term
     (Bind
      ($nuclear_klama_2 :: (Referents Entity))
      (Context)
      ($nuclear_klama_3 :: (Referents Entity))
      (Context)
      ($nuclear_klama_4 :: (Referents Entity))
      (Context)
      ($nuclear_klama_5 :: (Referents Entity))
      (Context)
      (=
       (Card
        (SetOf
         (λ (($global_member :: Entity))
           (∧
            ((λ (($restrictor_member :: Entity)) (prenu $restrictor_member)) $global_member)
            ((λ (($nuclear_member :: Entity))
               (CloseClause
                (λ (($actual_event :: (Referents Eventuality)))
                  (∧
                   ((λ (($event :: (Referents Eventuality)))
                      (klama
                       $nuclear_member
                       $nuclear_klama_2
                       $nuclear_klama_3
                       $nuclear_klama_4
                       $nuclear_klama_5
                       $event))
                    $actual_event)
                   (fasnu $actual_event)))))
             $global_member)))))
       2))))
  (case (id "f0b03ab446bef9c36ea48ddf799f5e935ab0d235")
    (status unavailable)
    (category context-unsupported)
    (stage context)
    (reason "no independent context rule for Assert within whole-source"))
  (case (id "f1beb4ef6a10acf370224865716485f80c21195f")
    (status available)
    (context whole-a0)
    (source-type Content)
    (source-typing (typing Content () ()))
    (target-typing (typing Content () ()))
    (term (∃ (λ (($r1 :: (Referents Number))) (∧ ($x $r1) ($r $r1))))))
  (case (id "f1fc1d56a889c979e74bb8a6482d05ec43eca7ca")
    (status unavailable)
    (category context-unsupported)
    (stage context)
    (reason "no independent context rule for Assert within whole-source"))
  (case (id "f5c36a172141b3fb8059c45bbce69ea115f5ea70")
    (status available)
    (context whole-a0)
    (source-type Content)
    (source-typing (typing Content (effectful-call) ()))
    (target-typing (typing Content (effectful-call) ()))
    (term (∀ (λ (($x1 :: Entity)) (→ ($x $x1) ($r $x1))))))
  (case (id "f81721a81e71a0cdd44c85ca033688999c619143")
    (status available)
    (context whole-a0)
    (source-type (Set Entity))
    (source-typing (typing (Set Entity) () ()))
    (target-typing (typing (Set Entity) () ()))
    (term (SetOf (λ (($z :: Entity)) (∧)))))
  (case (id "f936005a958fa8d65abcdae0294b1a92329fef37")
    (status unavailable)
    (category context-unsupported)
    (stage context)
    (reason "no independent context rule for Assert within whole-source"))
  (case (id "f981106111772906ed7d014fef60df1a3705b00b")
    (status unavailable)
    (category context-unsupported)
    (stage context)
    (reason "no independent context rule for Mention within whole-source"))
  (case (id "fa6884c0879ec08bcff75b679deb65edac523a4f")
    (status available)
    (context assert-bridge)
    (source-type (Act Assertion))
    (source-typing (typing (Act Assertion) () ()))
    (target-typing (typing (Act Assertion) () ()))
    (payload-source-typing (typing Content (effectful-call) ()))
    (payload-target-typing (typing Content (effectful-call) ()))
    (term
     (Assert
      (CloseClause
       (λ (($actual_event :: (Referents Eventuality)))
         (∧
          ((λ (($event :: (Referents Eventuality)))
             (Bind
              ($ctx2 :: (Referents Entity))
              (Context)
              ($ctx3 :: (Referents Entity))
              (Context)
              (tavla Speaker $ctx2 $ctx3 $event)))
           $actual_event)
          (fasnu $actual_event)))))))
  (case (id "fb2133f70e88f14bfbe2a052739d1ed5c5f3c859")
    (status unavailable)
    (category context-unsupported)
    (stage context)
    (reason "no independent context rule for Assert within whole-source"))
  (case (id "fbbb637dc453cc3d364bd7f5627a2beb516c760d")
    (status unavailable)
    (category context-unsupported)
    (stage context)
    (reason "no independent context rule for Reify within Assert"))
  (case (id "fcfec738ee302d719f6254efbc77ccde936c7721")
    (status unavailable)
    (category context-unsupported)
    (stage context)
    (reason "no independent context rule for Express within whole-source"))
  (case (id "fd31e7bdcbe48333bfd275db7175d0574cc58dce")
    (status unavailable)
    (category context-unsupported)
    (stage context)
    (reason "no independent context rule for Assert within whole-source"))
  (case (id "fd8b93e752f590a5d2be231e39afeb3cbcfa85a1")
    (status unavailable)
    (category grammar-unsupported)
    (stage source)
    (reason
     "outside frozen A0 payload grammar: '(No (λ (($x Entity)) (Bind (($s Scale (Context))) (gerku $x))) (λ (($w (Referents Entity))) (CloseWith (row jmaji 1 direct-event (1)) ((1 $w)))))"))
  (case (id "fdf6a466b6ff4021955160318d9bfaf8c6b42f44")
    (status unavailable)
    (category unclassified-non-admission)
    (stage source)
    (reason
     "source has 0 admitted A0 typings: '(CloseWith (row jmaji 1 direct-event (1)) ((1 (Combine Speaker Audience))))"))
  (case (id "ff7e9c879bf10b8f0decbc44815aaebc5f02807b")
    (status unavailable)
    (category unclassified-non-admission)
    (stage target)
    (reason "expanded target has 0 A0 typings at source type 'Content"))))
